### ISSUE TITLE
compatibility between turicreate and swift greyscale images

### ISSUE THREAD

**Issue by johnyquest7** [apple/turicreate#1009]
I have used - `tc.image_analysis.resize` to resize my training images to fit the size requirement for the model and to convert them to greyscale using the following command. 
`turicreate.image_analysis.resize(image, width, height,channels=1)`

Then I tried to deploy it as an iOS app. But the results I get on my unbuntu and iphone are close but different. I think this has to do with how I am converting the image to greyscale in my app. 
I have tried CIPhotoEffectMono  and CIPhotoEffectNoir to convert to greyscale. Both of them did not yield the result  I was getting from my ubuntu runs on the same images. 

Is there an equivalent greyscale converter in swift  to match the one used in `tc.image_analysis.resize(channel=1)`?

**Comment by TobyRoseman** [comment]
There is no equivalent grayscale converter in Swift. There are certainly ways to convert images to grayscale in Swift, but these will likely give slightly different answers than the Turi create methods.

**Comment by johnyquest7** [comment]
How does Turicreate convert an image to greyscale? I could create a function based on this.

**Comment by nickjong** [comment]
I think this call to `resize` boils down to a usage of the [Boost Generic Image Library](https://www.boost.org/doc/libs/1_68_0/libs/gil/doc/html/index.html). Take a look at their [sample code](https://www.boost.org/doc/libs/1_68_0/libs/gil/doc/html/design_guide.html#sample-code), under "Using Image Views", for an example of converting a JPEG from RGB to grayscale (and then transforming it some more).

FWIW, our code (that calls into Boost GIL) is under src/image/image_util_impl.cpp, but most of that stuff handles non-color-related transformations: resampling, etc.

**Comment by johnyquest7** [comment]
@nickjong thanks for pointing me in the right direction.
