### ISSUE TITLE
Style Transfer GPU

### ISSUE THREAD

**Issue by rainhut** [apple/turicreate#1029]
I'm unable to get style transfer training to work with GPU with release version 5.0

**Comment by shantanuchhabra** [comment]
Hi @rainhut , we unfortunately do not have support for Style Transfer on GPU yet. We have GPU support for the following toolkits on the following macOS versions:
- Image Classification (macOS 10.13+)
- Image Similarity (macOS 10.13+)
- Object Detection (macOS 10.14+)
- Activity Classification (macOS 10.14+)

We are tracking GPU support for Style Transfer as a feature request in [#635](https://github.com/apple/turicreate/issues/635).
