### ISSUE TITLE
SFrame head method is returning [n+1] rather than [n] rows

### ISSUE THREAD

**Issue by AFathi** [apple/turicreate#103]
I'm currently using the `SFrame` object to load data from a **csv** file and it's working perfectly fine.

However, when I call the `head(n)` method to retrieve the first **n** rows (as mentioned in the API docs), the result is always n+1.

I forked this project and edited the `unity_sframe::head(size_t nrows)` method in the `src/unity/lib/unity_sframe.cpp` file, by subtracting 1 from `nrows` in the for loop. 

But it seem to be not working properly. So I wanted to ask if this is the correct file that handles the head method in the Python package?

Great work by the way! 
I'm very excited to create new CoreML models using this amazing tool :)

**Comment by srikris** [comment]
Can you provide repro steps? I don't quite see this behavior

```
import turicreate
sf = turicreate.SFrame({'a': range(100)})
sf.head(10)
```

returns 

```
Columns:
	a	int

Rows: 10

Data:
+---+
| a |
+---+
| 0 |
| 1 |
| 2 |
| 3 |
| 4 |
| 5 |
| 6 |
| 7 |
| 8 |
| 9 |
+---+
[10 rows x 1 columns]
```

**Comment by AFathi** [comment]
@srikris, I see where the problem is coming from now! 

The data in the sample **csv** file I'm using doesn't have the 'a' column and starts right away from the actual data. So when I was counting, I included the 'a' column.

Here's how it looks like:
<img width="1099" alt="screen shot 2017-12-14 at 8 58 23 pm" src="https://user-images.githubusercontent.com/4106695/34023224-a4071392-e111-11e7-952c-502fb5b5f318.png">

_`dataBuffer` is the `SFrame` object_

**Comment by srikris** [comment]
The row in bold is the "header" row. I think your call to `read_csv` automatically assumed the first row is the header which it should not be. When you use `read_csv`, you can use the `header = False` option that will prevent that from happening.

**Comment by AFathi** [comment]
Perfect, thank you.
