### ISSUE TITLE
Parameters of query fucntion in c++, v2::ml_data class

### ISSUE THREAD

**Issue by gitturi** [apple/turicreate#1048]
In the function uri::nearest_neighbors::lsh_neighbors::query, the first parameter, mld_query, is of data type v2::ml_data. I was unable to find any documentation about v2::ml_data class. A class called turi::v2 exists, also turi::ml_data, but the compiler (clang++) insists it should be const v2::ml_data. How do I construct it for a query?

**Comment by TobyRoseman** [comment]
You can find the header file for `turi::v2::ml_data`, along with plenty of documentation, in  `src/unity/toolkits/ml_data_2/ml_data.hpp`.

It would probably also be helpful for you to take a look at [the c++ unit tests for nearest neighbors](https://github.com/apple/turicreate/blob/master/test/unity/toolkits/nearest_neighbors.cxx).
