### ISSUE TITLE
SArray.show() is not working in Jupyter Notebook

### ISSUE THREAD

**Issue by The-Code-Killer** [apple/turicreate#1053]
Here is my code in Jupyter Notebook
`import turicreate as tc`

`products = tc.SFrame('amazon_baby.gl')`
`products['name'].show()`

Above code shows nothing but a string ''Materializing SArray''

`products.show()` is working fine.

**Comment by TobyRoseman** [comment]
Thanks @The-Code-Killer for reporting this. I was able to reproduce the issue. 

Here is a more minimalistic way to reproduce the issue:
```
import turicreate as tc

sa = tc.SArray(["&quot;Firsts&quot;"])
sa.show()
```
We'll look in to it.

**Comment by The-Code-Killer** [comment]
Thanks. I am waiting for it @TobyRoseman.

**Comment by abhishekpratapa** [comment]
Hey @The-Code-Killer looks like we have a potential fix for it. Try it out and let us know if that works for you!
