### ISSUE TITLE
VisionFeaturePrint - Screen or Scene? 

### ISSUE THREAD

**Issue by hipwelljo** [apple/turicreate#1056]
Everywhere in the Create ML documentation, the feature extractor is termed the **scene** print feature extractor, but everywhere in the Turi Create documentation it is termed **screen** print. Is this interchangeable, is one of them incorrect, or are they actually different extractor types?

[Create ML](https://developer.apple.com/documentation/createml/mlimageclassifier/featureextractortype/sceneprint_revision)
[Turi Create](https://apple.github.io/turicreate/docs/userguide/image_classifier/how-it-works.html)

**Comment by srikris** [comment]
This is a typo. It should be scene. We will fix it in the next release along with all the documentation.
