### ISSUE TITLE
Image.save not working in Python 3.6 

### ISSUE THREAD

**Issue by jasminWills** [apple/turicreate#1060]
<img width="780" alt="messages image 148071017" src="https://user-images.githubusercontent.com/37459745/45062802-7ff5d880-b05f-11e8-8c07-1128ae8fd76d.png">

Image.save() doesn't seem to be working properly on python 3.6 . Same lines of code with same SFrame work properly in 2.7.13 but not in 3.6

**Comment by nickjong** [comment]
I was able to repro this issue with turicreate 4.3.2, but not with turicreate 5.0 (which we released a week or so ago). If you are on turicreate 4.3.2, try upgrading to turicreate 5.0!

If you still see this issue on turicreate 5.0, please reopen, as something more interesting is going on!

**Comment by jasminWills** [comment]
Thanks!!

I no longer see this issue with Turi create 5.0
