### ISSUE TITLE
Mongo 'ObjectId' handled issue

### ISSUE THREAD

**Issue by chrinide** [apple/turicreate#1062]
When import/convert python object like dict or Pandas dataframe which contains **'_id': ObjectId('5b2291044a6eeb27435da734')** (MongoDB related data) into Sframe.

It will return below error:

_TypeError: Cannot convert type 'ObjectId' into flexible type._

or 

TypeError: object of type 'ObjectId' has no len()

It is possible to fix?

For example:

I have some data like below:

tt = [{'_id': ObjectId('5b8c0900d3154e6d01431f82'),
  'user_id': 361422,
  'unionid': 'ofxUkwb1XAcwY2shIpRsKIt4bhQ8',
  'time': 1535904000,
  'date': 20180903,
  'ip': '171.111.5.70',
  'device': 'android',},
 {'_id': ObjectId('5b8c0901975fa12f7a14c9df'),
  'user_id': 329770,
  'unionid': 'ofxUkwYqT4z93S_jVZx2psSPnero',
  'time': 1535904001,
  'date': 20180903,
  'ip': '112.38.49.158',
  'device': 'android',}]

if I run:

tc.Sframe(tt)

it will get below error:

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> ~/miniconda3/lib/python3.6/site-packages/turicreate/data_structures/sarray.py in __init__(self, data, dtype, ignore_cast_failure, _proxy)
>     419                 with cython_context():
> --> 420                     self.__proxy__.load_from_iterable(data, dtype, ignore_cast_failure)
>     421             else:
> 
> turicreate/cython/cy_sarray.pyx in turicreate.cython.cy_sarray.UnitySArrayProxy.load_from_iterable()
> 
> turicreate/cython/cy_sarray.pyx in turicreate.cython.cy_sarray.UnitySArrayProxy.load_from_iterable()
> 
> turicreate/cython/cy_flexible_type.pyx in turicreate.cython.cy_flexible_type.flex_list_from_typed_iterable()
> 
> turicreate/cython/cy_flexible_type.pyx in turicreate.cython.cy_flexible_type.fill_typed_list()
> 
> turicreate/cython/cy_flexible_type.pyx in turicreate.cython.cy_flexible_type._fill_typed_sequence()
> 
> turicreate/cython/cy_flexible_type.pyx in turicreate.cython.cy_flexible_type._ft_translate()
> 
> turicreate/cython/cy_flexible_type.pyx in turicreate.cython.cy_flexible_type.tr_dict_to_ft()
> 
> turicreate/cython/cy_flexible_type.pyx in turicreate.cython.cy_flexible_type.flexible_type_from_pyobject()
> 
> turicreate/cython/cy_flexible_type.pyx in turicreate.cython.cy_flexible_type._ft_translate()
> 
> TypeError: Cannot convert type 'ObjectId' into flexible type.
> 
> During handling of the above exception, another exception occurred:
> 
> TypeError                                 Traceback (most recent call last)
> ~/miniconda3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in __init__(self, data, format, _proxy)
>     783                         else:
> --> 784                             self.__proxy__.add_column(SArray(data).__proxy__, '')
>     785                 elif (_format == 'dict'):
> 
> ~/miniconda3/lib/python3.6/site-packages/turicreate/data_structures/sarray.py in __init__(self, data, dtype, ignore_cast_failure, _proxy)
>     419                 with cython_context():
> --> 420                     self.__proxy__.load_from_iterable(data, dtype, ignore_cast_failure)
>     421             else:
> 
> ~/miniconda3/lib/python3.6/site-packages/turicreate/cython/context.py in __exit__(self, exc_type, exc_value, traceback)
>      48                 # To hide cython trace, we re-raise from here
> ---> 49                 raise exc_type(exc_value)
>      50             else:
> 
> TypeError: Cannot convert type 'ObjectId' into flexible type.
> 
> During handling of the above exception, another exception occurred:
> 
> TypeError                                 Traceback (most recent call last)
> <ipython-input-40-0df7c5f121cb> in <module>()
> ----> 1 tc.SFrame(tt)
> 
> ~/miniconda3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in __init__(self, data, format, _proxy)
>     809                     pass
>     810                 else:
> --> 811                     raise ValueError('Unknown input type: ' + format)
>     812 
>     813     @staticmethod
> 
> ~/miniconda3/lib/python3.6/site-packages/turicreate/cython/context.py in __exit__(self, exc_type, exc_value, traceback)
>      47             if not self.show_cython_trace:
>      48                 # To hide cython trace, we re-raise from here
> ---> 49                 raise exc_type(exc_value)
>      50             else:
>      51                 # To show the full trace, we do nothing and let exception propagate
> 
> TypeError: Cannot convert type 'ObjectId' into flexible type.

If I delete 'ObjectId' like below:

tt_ = [{
  'user_id': 361422,
  'unionid': 'ofxUkwb1XAcwY2shIpRsKIt4bhQ8',
  'time': 1535904000,
  'date': 20180903,
  'ip': '171.111.5.70',
  'device': 'android',},
 {
  'user_id': 329770,
  'unionid': 'ofxUkwYqT4z93S_jVZx2psSPnero',
  'time': 1535904001,
  'date': 20180903,
  'ip': '112.38.49.158',
  'device': 'android',}]

then i run:

tc.SFrame(tt_).unpack('X1'), get:

X1.date | X1.device | X1.ip | X1.time | X1.unionid | X1.user_id
-- | -- | -- | -- | -- | --
20180903 | android | 171.111.5.70 | 1535904000 | ofxUkwb1XAcwY2shIpRsKIt4bhQ8 ... | 361422
20180903 | android | 112.38.49.158 | 1535904001 | ofxUkwYqT4z93S_jVZx2psSPnero ... | 329770

I can get the dateframe which I want, just like pd.DataFrame(tt) and pd.DataFrame(tt_) 

  | _id | date | device | ip | time | unionid | user_id
-- | -- | -- | -- | -- | -- | -- | --
5b8c0900d3154e6d01431f82 | 20180903 | android | 171.111.5.70 | 1535904000 | ofxUkwb1XAcwY2shIpRsKIt4bhQ8 | 361422
5b8c0901975fa12f7a14c9df | 20180903 | android | 112.38.49.158 | 1535904001 | ofxUkwYqT4z93S_jVZx2psSPnero | 329770

So Pandas can handle the 'ObjectId', however, Sframe can not.

**Comment by srikris** [comment]
Can you share the code that resulted in this error? I'm sure there is a work around for this.

**Comment by chrinide** [comment]
@srikris I have updated the detail code and error.

**Comment by chrinide** [comment]
@srikris Any suggestion?

**Comment by chrinide** [comment]
@srikris It  works, Thanks a lot.

**Comment by TobyRoseman** [comment]
I'm going to close this issue.

@chrinide - if you want, feel free to open up a feature request issue for storing arbitrary objects in an SFrame.
