### ISSUE TITLE
Unintuitive Behaviour in SArray dtype specification

### ISSUE THREAD

**Issue by Shayne13** [apple/turicreate#1070]
The following creates an SFrame with type `array` in its singular column:
```
x = tc.SFrame({'a': [[1,2], None, [3,4], None]})
```
In an attempt to change the column type, using the following code throws no error, and does not succeed:
```
x['a'] = tc.SArray(x['a'], list)
```
This behaviour is unintuitive.

**Comment by TobyRoseman** [comment]
This is an issue in both Python 2 and Python 3.
