### ISSUE TITLE
CoreML model - Get class name

### ISSUE THREAD

**Issue by dhgokul** [apple/turicreate#1084]
How to get class name from turicreate coreML in iOS app ?  As of now i can able to get index value and confidence value

**Comment by TobyRoseman** [comment]
This could be done by using the [coremltools package](https://github.com/apple/coremltools) to add meta data to your mlmodel. 

Something like the following should work:
```python
import coremltools

turicreate_model.export_coreml('my_model.mlmodel')
core_ml_model = coremltools.models.MLModel('my_model.mlmodel')
core_ml_model.user_defined_metadata['class name'] = type(turicreate_model)
core_ml_model.save('my_model.mlmodel')
```

In your iOS app, you can then use the [metadata property](https://developer.apple.com/documentation/coreml/mlmodeldescription/2879386-metadata?language=objc) of the [MLModelDescription](https://developer.apple.com/documentation/coreml/mlmodeldescription?language=objc) class to get the value for `class name`.

**Comment by dhgokul** [comment]
Thanks Toby. Will check and update you.

**Comment by dhgokul** [comment]
@TobyRoseman coremltools is python package for trained model to convert MLmode.
 If there any way to get labels name from trained turicreate coreML model in xcode ?
(iOS code)

Sample  sframe JSON format used for training : 
[{'coordinates': {'y': 280.0, 'width': 127, 'x': 536.0, 'height': 277}, 'label': 'test'}]
[{'coordinates': {'y': 280.0, 'width': 127, 'x': 536.0, 'height': 277}, 'label': 'test1'}]
[{'coordinates': {'y': 280.0, 'width': 127, 'x': 536.0, 'height': 277}, 'label': 'test2'}]

I need to get label name from coreML model in xcode by accessing coreML import in ios code

**Comment by srikris** [comment]
@dhgokul The code for getting the labs name in Xcode is provided in the links on @TobyRoseman's previous response. I'm closing this. Feel free to open it if you feel like its still unresolved.

**Comment by dhgokul** [comment]
@srikris I don't find coremltools library available for iOS code. When import trained coreML model in xcode, can able to access index and confidence parameters only

Based on toby comment, i can see coremltools python package, if there is any option to save label name when export coreML model in training phase (python script)

Code snippet : 
modelname = model.name()
model.save('Turicreate' + modelname + '.model')
scores = model.evaluate(data)
print('Mean Average Precision(mAP): {:.1%}'.format(scores['mean_average_precision']))
#Print a summary of the model
model.summary()
# Export for use in CoreML
model.export_coreml('Turicreate' + modelname + '.mlmodel')

Please correct me ,if i am wrong

**Comment by dhgokul** [comment]
@srikris I need to get label name as we trained dataset from sframe in output parameter 

Sample sframe format  :  [{'coordinates': {'y': 280.0, 'width': 127, 'x': 536.0, 'height': 277}, 'label': 'test'}]

I am not able to get label parameter Model Evaluation Parameters - Output - PFA

![image](https://user-images.githubusercontent.com/5689804/45738589-8b740280-bc0e-11e8-80a9-9d47f5ca74f2.png)

is there is any changes need to be done while training and save turicreate model ?

**Comment by dhgokul** [comment]
@srikris Thanks , it's worked !
