### ISSUE TITLE
Better Error Message when nvidia-smi Fails

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#1085]
During [automatic GPU detection](https://github.com/apple/turicreate/blob/a7810cbcdc5eeb551853185db14fad16c4c75599/src/unity/python/turicreate/util/__init__.py#L728) a system command is make to `nvidia-smi`. If an exception other than `OSError` is raised, the program crashes but no helpful information is displayed. We should output a helpful error message, that should probably include the output of the system command.

**Comment by znation** [comment]
@TobyRoseman Any consistent way we can repro this? (Possibly by messing with the system, installing a wrong version of `nvidia-smi`, etc.?)

**Comment by TobyRoseman** [comment]
@znation - I think just not having `nvidia-smi` installed should repo the issue.

**Comment by TobyRoseman** [comment]
This was fixed by #1406.
