### ISSUE TITLE
object detector presenting errors

### ISSUE THREAD

**Issue by yousifKashef** [apple/turicreate#1086]
Hi guys, I've been getting this error when I run my training script after updating. The code hasn't changed at all. The only thing that's different is the update to Turi create.

here's the error that I got:
 File "train.py", line 16, in <module>
    model = tc.object_detector.create(train_data, feature='image', annotations='annotations', max_iterations=3500, batch_size=12)
  File "/Users/yousif/venv/lib/python2.7/site-packages/turicreate/toolkits/object_detector/object_detector.py", line 389, in create
    ref_model.available_parameters_subset(net_params).load(ref_model.model_path, ctx)
  File "/Users/yousif/venv/lib/python2.7/site-packages/mxnet/gluon/parameter.py", line 664, in load
    for k, v in ndarray.load(filename).items()]
  File "/Users/yousif/venv/lib/python2.7/site-packages/mxnet/ndarray/utils.py", line 175, in load
    ctypes.byref(names)))
  File "/Users/yousif/venv/lib/python2.7/site-packages/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [19:33:59] src/ndarray/ndarray.cc:1114: Check failed: fi->Read(data) Invalid NDArray file format

Stack trace returned 7 entries:
[bt] (0) 0   libmxnet.so                         0x0000000116e127cf libmxnet.so + 59343
[bt] (1) 1   libmxnet.so                         0x0000000116e1256f libmxnet.so + 58735
[bt] (2) 2   libmxnet.so                         0x0000000116e11e79 libmxnet.so + 56953
[bt] (3) 3   libmxnet.so                         0x0000000117ef78e7 MXNDListFree + 1330215
[bt] (4) 4   libmxnet.so                         0x0000000117d83201 MXNDArrayLoad + 241
[bt] (5) 5   _ctypes.so                          0x000000010f61b5c7 ffi_call_unix64 + 79
[bt] (6) 6   ???                                 0x00007ffee0f07c80 0x0 + 140732672277632

I looked at the documentation and I noticed the train_data property wasn't anywhere in the create method for the object detector. Did you guys deprecate it in 5.0?

Thanks

**Comment by srikris** [comment]
train_data is an SFrame. Its part of your data.  Can you share the MXNet version that you have?

**Comment by yousifKashef** [comment]
I have MXNet 1.0.1

I get this error message every time I try to clean install Turi Create:

mxnet 1.1.0.post0 has requirement numpy<1.15.0,>=1.8.2, but you'll have numpy 1.15.1 which is incompatible.
mxnet 1.1.0.post0 has requirement requests<2.19.0,>=2.18.4, but you'll have requests 2.19.1 which is incompatible.

**Comment by yousifKashef** [comment]
Is there a workaround? thanks

**Comment by znation** [comment]
@yousifKashef We no longer support MXNet 1.0.1 with Turi Create 5.0. As of 5.0, you'll need `mxnet >= 1.1.0, < 1.2.0`. See https://github.com/apple/turicreate/blob/master/src/unity/python/setup.py#L181. Please reopen this issue if you are able to repro with an MXNet version in that range. Note that the warnings you're getting about required/compatible versions of numpy and requests can probably be safely ignored; both Turi Create and MXNet are likely to still work in that case.

**Comment by yousifKashef** [comment]
@znation it's happening again with mxnet==1.1.0.post0

**Comment by znation** [comment]
Reopening as this now seems to repro with a supported mxnet version.

**Comment by nickjong** [comment]
Are you still encountering this error? It looks like it might be a corrupted MXNet params file. By now, the locally downloaded copy of the pre-trained model has probably been deleted, but if necessary we can clear it out to force a fresh download

**Comment by TobyRoseman** [comment]
This is ultimately an MXNet issue. Since we no longer use MXNet, I'm going to close this issue.
