### ISSUE TITLE
Tuples get parsed as arrays which are unhashable

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#1096]
Right now, even if I have an SArray of dictionaries with tuple keys, displaying it doesn't work because tuples automatically get interpreted as arrays. This is calamitous because arrays are not a hashable type. Furthermore, if I try to save/create/explore this SArray/SFrame, I don't get any errors but the data structure is pretty unusable. 

I think the true solution to this would be to support tuple types in Turi Create. 

Minimal Repro:

```
d = {(0,0):"lol"}  
arr = [d]
sa = tc.SArray(arr) # works
sa.save("no_error.sarray") # works
sa.explore() # works
print(sa[0]) # uh oh
print(sa) # uh oh
```

**Comment by hoytak** [comment]
Tuple types are supported; the C++ types don't match up one-to-one to the python types, so the main solution to this seems to be to have the translation from C++ into python depend somewhat on the context.

**Comment by hoytak** [comment]
Fixed in https://github.com/apple/turicreate/pull/1106
