### ISSUE TITLE
How can I use PNG's of the object to create an Object detection model as opposed to annotating boxes

### ISSUE THREAD

**Issue by pshaburov** [apple/turicreate#1110]
Here is an example of a photo:
![img_0208](https://user-images.githubusercontent.com/30537516/46281131-771cf780-c576-11e8-9bb5-31e76e3f637a.png)

**Comment by TobyRoseman** [comment]
In order to use the object detector, you will need bounding boxes. 

If you're not interested in the location of an object in an image, but only if the object is present, take a look at the [image classifier](https://apple.github.io/turicreate/docs/userguide/image_classifier/). It learn labels for images.

**Comment by pshaburov** [comment]
Yes, I understand, but in the documentation for object detection under data preparation it listed two ways to do it, one where you use an annotator and another where you use a "mask." I wanted to use PNG's for more "accurate" bounding boxes

**Comment by TobyRoseman** [comment]
I assume you are referring to [this page](https://apple.github.io/turicreate/docs/userguide/object_detection/data-preparation.html). It's not really listing two ways to do it, rather it's showing how to covert masked images into bounding boxes. 

Do you have masked images (i.e. images where everything but the object is blacked out)? Or is your question how to generate masked images?

**Comment by pshaburov** [comment]
I thought the way to do it to have the original photo and a PNG of where it is, but in a nutshell yes

**Comment by TobyRoseman** [comment]
Turi Create does not support generating masked images from PNG files (or any other image format). I believe masked images are generally created only by manual annotation.
