### ISSUE TITLE
object_detector.create freezes when using multiple GPUs

### ISSUE THREAD

**Issue by SoroushKadineh** [apple/turicreate#1115]
My specs are:
Turi Create: 5.0b3
CUDA: release 9.0, V9.0.176
mxnet: mxnet==1.1.0     mxnet-cu90==1.1.0
GPU: Nvidia Tesla K80 (8 of them)

How I reproduce the issue:
```
import turicreate as tc
mySframe = tc.load_sframe(filename='/mySframeFile/')
sampleModel = tc.object_detector.create(dataset=mySframe, feature='image', annotations='annotations', max_iterations=1, batch_size=512)
```

> Downloading https://docs-assets.developer.apple.com/turicreate/models/darknet.params
> Download completed: /var/tmp/model_cache/darknet.params
> Setting 'batch_size' to 512
> Using 8 GPUs to create model (CUDA)

I have also tried setting `batch_size=0` which has the same result.

Update: using only 1 GPU made things work!

**Comment by shantanuchhabra** [comment]
Hi @SoroushKadineh we are working on this but haven't been able to reproduce this on a toy dataset. 1. Are you able to reproduce this on a toy or programmatically created dataset?
2. If not, is the dataset that you face this issue with, publicly available?

Looking forward to hearing back from you!

**Comment by shantanuchhabra** [comment]
Alright, thanks for the update! Feel free to post if you run into any other issues!
