### ISSUE TITLE
Instructions don't work. Cant create CoreML model, crashes

### ISSUE THREAD

**Issue by amayers** [apple/turicreate#112]
So I'm trying to make my first model. First the installation instructions are incorrect, if you follow them to the T, they fail with a non useful error on `pip install -U turicreate`. Turns out this project requires you to downgrade to an ancient Python version. How about the installation instructions include that detail, or better yet, make it work with the current version that ships on all Macs.

Ok, so I worked around that, and started on replicating https://apple.github.io/turicreate/docs/userguide/image_classifier/introduction.html to make sure everything is working properly before I go through the work of gathering real training data.

I downloaded the following images into a `images` folder, with a subfolder for `dogs` and `tractor`
[dog_urls.txt](https://github.com/apple/turicreate/files/1565743/dog_urls.txt)
[tractor_urls.txt](https://github.com/apple/turicreate/files/1565744/tractor_urls.txt)

I copy/pasted the sample code into a new python file and just change the paths.
```
import turicreate as tc

# Load images
sf = tc.image_analysis.load_images('images', with_path=True)

# From the path-name, create a label column
data['label'] = data['path'].apply(lambda path: 'dog' if 'dogs' in path else 'tractor')

# Save the data for future use
data.save('dogs-tractors.sframe')

# Explore interatively
data.explore()
```

Then go to run it `python <file_just_created>.py` and it fails because `sf = tc.image_analysis.load_images('train', with_path=True)` writes to `sf` but the rest of the file expects it to be `data`. Another incorrect doc, but easy enough to fix. Changed `sf` to `data` and it runs, and I can see that the SFrame matches what I'd expect. Now I copy & paste the next code snippet from the guide, just changing the file names.

```import turicreate as tc

# Load the data
data =  tc.SFrame('dogs-tractors.sframe')

# Make a train-test split
train_data, test_data = data.random_split(0.8)

# Automatically picks the right model based on your data.
model = tc.image_classifier.create(train_data, target='label')

# Save predictions to an SArray
predictions = model.predict(test_data)

# Evaluate the model and save the results into a dictionary
metrics = model.evaluate(test_data)
print(metrics['accuracy'])

# Save the model for later use in Turi Create
model.save('mymodel.model')

# Export for use in Core ML
model.export_coreml('MyCustomImageClassifier.mlmodel')
```

It goes off and processes for a few minutes as expected, then fails in the export to CoreML step:
```
python export.py 
[09:35:58] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[09:35:58] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
Resizing images...
Performing feature extraction on resized images...
Completed 340/340
PROGRESS: Creating a validation set from 5 percent of training data. This may take a while.
          You can set ``validation_set=None`` to disable validation tracking.

WARNING: The number of feature dimensions in this problem is very large in comparison with the number of examples. Unless an appropriate regularization value is set, this model may not provide accurate predictions for a validation/test set.
WARNING: Detected extremely low variance for feature(s) '__image_features__' because all entries are nearly the same.
Proceeding with model training using all features. If the model does not provide results of adequate quality, exclude the above mentioned feature(s) from the input dataset.
Logistic regression:
--------------------------------------------------------
Number of examples          : 324
Number of classes           : 2
Number of feature columns   : 1
Number of unpacked features : 2048
Number of coefficients    : 2049
Starting L-BFGS
--------------------------------------------------------
+-----------+----------+-----------+--------------+-------------------+---------------------+
| Iteration | Passes   | Step size | Elapsed Time | Training-accuracy | Validation-accuracy |
+-----------+----------+-----------+--------------+-------------------+---------------------+
| 1         | 7        | 0.000046  | 1.121025     | 0.672840          | 0.625000            |
| 2         | 9        | 1.000000  | 1.173264     | 0.944444          | 0.937500            |
| 3         | 10       | 1.000000  | 1.210695     | 0.996914          | 1.000000            |
| 4         | 11       | 1.000000  | 1.242987     | 0.996914          | 1.000000            |
| 5         | 12       | 1.000000  | 1.277638     | 0.990741          | 1.000000            |
| 6         | 14       | 1.000000  | 1.323503     | 0.996914          | 1.000000            |
+-----------+----------+-----------+--------------+-------------------+---------------------+
TERMINATED: Iteration limit reached.
This model may not be optimal. To improve it, consider increasing `max_iterations`.
0.987654320988
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```

I know its getting past the `model.save('mymodel.model')` line fine as I can see that file being created, and have even been able to open it in another python script successfully.

How do you actually get this thing to export the CoreML file?

**Comment by amayers** [comment]
Yes I am on Python installed by homebrew. How do I install a version of python that works with this project since it seems like it's so picky about the version & install method???

**Comment by igiloh** [comment]
Hi @amayers , thank you for taking interest in Turi Create!

The documentation issues have already been fixed, as you can see [here](https://github.com/apple/turicreate/blob/master/userguide/image_classifier/introduction.md).

As @srikris have mentioned - the CoreML team is aware of the problem with Homebrew.
There are several recommended ways to install python on macOS:
1. Using [Anaconda](https://www.anaconda.com/what-is-anaconda/) - my personal favorite.
2. Downloading directly from [python.org](https://www.python.org/downloads/mac-osx/).
3. Use the native python version that comes with macOS, which is located in `/usr/bin/python`.

All of which have been tested and work well with both turicreate and coremltools.
If you have any further problems with installing or using turicreate - please feel free to ask.

**Comment by amayers** [comment]
Hi @igiloh I would have loved to use the native python version that ships with macOS, however Turi Create isn't even found when you try to use `pip install -U turicreate` on it. It wasn't until I installed 2.7.14 from Homebrew that Turi Create could be pip installed.

**Comment by igiloh** [comment]
Hi @amayers, thanks again for the further input.

I've just re-tested on a clean macOS10.12 and 10.13 machines - and on both I was able to successfully perform
```
pip install --upgrade pip
pip install -U turicreate
```
I was also able to create a model and export it to Core ML.

Which macOS version are you running?
Can you please print out the current `pip` version you're using, and the error you're gertting?

**Comment by amayers** [comment]
I just uninstalled python from homebrew leaving just the system python installed. 
```
python --version
Python 3.6.3 :: Anaconda, Inc.
```

Then I recreated the virtual environment:
```
virtualenv egg_environment
Using base prefix '/anaconda3'
New python executable in /Users/amayers/Code/Side_Projects/egg_environment/bin/python
Installing setuptools, pip, wheel...done.
Andrews-13-MacBook-Pro:Side_Projects amayers$ source egg_environment/bin/activate
(egg_environment) Andrews-13-MacBook-Pro:Side_Projects amayers$ pip install -U turicreate
Collecting turicreate
  Could not find a version that satisfies the requirement turicreate (from versions: )
No matching distribution found for turicreate
```

I also tried again adding the `pip install --upgrade pip` line that wasn't in the instructions. It gave the output `Requirement already up-to-date: pip in ./egg_environment/lib/python3.6/site-packages`, and didn't fix the install error.

I'm running macOS 10.13.2 (17C88), and pip:
```

**Comment by igiloh** [comment]
As mentioned in the [documentation](https://github.com/apple/turicreate#system-requirements), turicreate only supports python 2.7 at the moment. Any python 2 version from 2.7.8 and up to the latest 2.7.14 (released 9/2017) should work.
Python 3 support is still an ongoing process, as you can see here: https://github.com/apple/turicreate/issues/2

macOS 10.13 comes natively with python 2.7.10, and should support the turicreate package out of the box.
If you do choose to install Anaconda (which again, I personally really enjoy) - please make sure to install the python 2.7 version, which is available [here](https://www.anaconda.com/download/#macos).

**Comment by srikris** [comment]
For the macOS native python, it should look like this

```
$ python --version
Python 2.7.10
$ which python
/usr/bin/python
```
If you see `/usr/local/bin/python` for your python location then you probably have a mismatched version of Python and pip. 

As @igiloh mentioned, your Python seems to be 3.6 which isn't yet supported (we will be fixing that soon). So Python 2.7 should work.

**Comment by amayers** [comment]
After I installed Anaconda 2.7 it now works. But this is the first time I've done any python on this machine, and it had 3.6 on it. I guess some 3rd party app updated it?
