### ISSUE TITLE
Model Checkpoints / Save Progress on Large Project

### ISSUE THREAD

**Issue by philimanjaro** [apple/turicreate#1120]
Great work with Turi. I've loved the fixes and features and ease-of-use that has been added throughout version 5beta and now to the official release, well done!

***This might be a feature request, as I am not sure how to implement this in my current Object Detector project***

I have a large project that is running on an 18-core Intel 7980XE CPU and 5 GTX 1080Ti GPUs. While training, I made it through 20k+ iterations over the course of several weeks. The power at my house flickered and I lost everything and realized that I hadn't set up checkpoints of any kind like what is done automatically with Tensorflow.

I set up another training process using the "model_checkpoint_interval=10" and "model_checkpoint_path='/tmp/model_checkpoints'", but that doesn't seem to save any checkpoints and per the documentation -- doesn't actually seem like the object_detector supports checkpoints. (but checkpoints seem to be supported by other APIs in Turi)

Is there something that I can do to ensure my progress gets saved so that I do not waste my resources if a process crashes or the power goes out after weeks of processing time?

As a bonus question -- if I set my max_iterations to 20,000, but decide to call it off earlier than that and save the results that I have up until this point, is there a way to interrupt the training without killing the entire Python script?

Thanks everyone.

**Comment by gustavla** [comment]
@philimanjaro Thanks for the feedback! We are definitely aware of this problem and the feature request is tracked by #574. Currently, there is no work-around to this problem, unfortunately.

I'm going to quote your feedback on issue #574 and then close this issue as a duplicate. Feel free to add more follow-ups over there (consolidating all the feedback for this feature request into one issue will help build the case for it). Thanks again!
