### ISSUE TITLE
Object detection fails with: Unable to encode object of type '<class 'turicreate.data_structures.image.Image'>' as variant type.

### ISSUE THREAD

**Issue by pshaburov** [apple/turicreate#1123]
I just created a new Ig02.sframe that is significantly bigger than what I normally use. Turi-create works for me when I run my old sframes but fails on the bigger version. 

Here is the console:

 
> Victors-MacBook-Air:~ petershaburov$ python /Users/petershaburov/Desktop/TuriCreate/convert.py 
> Using 'image' as feature column
> Using 'annotations' as annotations column
> Traceback (most recent call last):
>   File "/Users/petershaburov/Desktop/TuriCreate/convert.py", line 10, in <module>
>     model = tc.object_detector.create(train_data, max_iterations= 4)
>   File "/usr/local/lib/python2.7/site-packages/turicreate/toolkits/object_detector/object_detector.py", line 336, in create
>     for batch in loader:
>   File "/usr/local/lib/python2.7/site-packages/turicreate/toolkits/object_detector/_sframe_loader.py", line 123, in next
>     return self._next()
>   File "/usr/local/lib/python2.7/site-packages/turicreate/toolkits/object_detector/_sframe_loader.py", line 146, in _next
>     orig_image = _mx.nd.array(row[_TMP_COL_RAW_IMAGE].pixel_data)
>   File "/usr/local/lib/python2.7/site-packages/turicreate/data_structures/image.py", line 174, in pixel_data
>     _extensions.image_load_to_numpy(self, data.ctypes.data, data.strides)
>   File "/usr/local/lib/python2.7/site-packages/turicreate/extensions.py", line 173, in <lambda>
>     return lambda *args, **kwargs: _run_toolkit_function(fn, arguments, args, kwargs)
>   File "/usr/local/lib/python2.7/site-packages/turicreate/extensions.py", line 158, in _run_toolkit_function
>     ret = _get_unity().run_toolkit(fnname, argument_dict)
>   File "/usr/local/lib/python2.7/site-packages/turicreate/cython/context.py", line 49, in __exit__
>     raise exc_type(exc_value)
> TypeError: Unable to encode object of type '<class 'turicreate.data_structures.image.Image'>' as variant type.

**Comment by TobyRoseman** [comment]
Please give us some more information. Since you mentioned `Ig02.sframe` I'm guessing you are following [these instructions](https://apple.github.io/turicreate/docs/userguide/object_detection/data-preparation.html). Is that correct? Are you following them exactly or are you changing something, like using your own data?

**Comment by pshaburov** [comment]
[training.py.zip](https://github.com/apple/turicreate/files/2447772/training.py.zip)
Here is the script I use (with my own data)

**Comment by TobyRoseman** [comment]
I can't reproduce this issue in TuriCreate 6.4
