### ISSUE TITLE
Object detection - multiple classes for an object with the same label

### ISSUE THREAD

**Issue by AndrGolubkov** [apple/turicreate#1125]
I create an object detector and am confronted with such a question. On one image there are several objects with the same label (similar to the example with the balls on the page https://apple.github.io/turicreate/docs/userguide/object_detection/). As a result, I received that for each example I created my own class in the model. Is this a bug or a feature?

**Comment by srikris** [comment]
I'm not sure I understand. Could you clarify more?

**Comment by AndrGolubkov** [comment]
Sure. An annotation, which is given for example: [{label: “Hand”, ...},{label: “Hand”, ...},{label: “Hand”, ...}]. In model sh

**Comment by AndrGolubkov** [comment]
The model shows 3 classes, although it seems to be one

**Comment by nickjong** [comment]
What do you mean by "the model shows 3 classes, although it seems to be one?" Precisely what output are you seeing and in what way is it not what you expect?

**Comment by AndrGolubkov** [comment]
Ok, that was just an example. It really looks like this.
In the annotation the following string: [{'type': 'rectangle', 'coordinates': {}, 'label': 'Hand'},{'type': 'rectangle', 'coordinates': {}, 'label': 'finger'},{'type': 'rectangle', 'coordinates': {}, 'label': 'finger_4'},{'type': 'rectangle', 'coordinates': {}, 'label': 'finger'},{'type': 'rectangle', 'coordinates': {}, 'label': 'finger_3'},{'type': 'rectangle', 'coordinates': {}, 'label': 'finger'},{'type': 'rectangle', 'coordinates': {}, 'label': 'finger_2'},{'type': 'rectangle', 'coordinates': {}, 'label': 'finger'},{'type': 'rectangle', 'coordinates': {}, 'label': 'finger_1'},{'type': 'rectangle', 'coordinates': {}, 'label': 'finger'},{'type': 'rectangle', 'coordinates': {}, 'label': 'finger_0'}].
In addition to these tags, there are 2 more types of tags.
Summary: Hand + finger + finger_4 + finger_3 + finger_2 + finger_1 + finger_0 + 2 other classes. Total - 9 classes.
I generated the model and uploaded to the project in Xcode. 
![image](https://user-images.githubusercontent.com/9430110/47135936-ca06e680-d2ba-11e8-89e4-3982eede47fd.png)
I see that in model 13 instead of 9 classes. It turns out that for each tag there is a separate class finger. Is this a bug or a feature?

**Comment by srikris** [comment]
We infer the number of classes from a union of labels given in the annotation. Can you run the following. 

```
model.classes
```
That should give you all the labels inferred from the dataset.

Assuming 'annotation' is the name of the column with annotations. You can also run the following command
```
labels = data['annotation'].apply(lambda x: [a['label'] for a in x]).stack('labels')
print labels['labels'].unique()
```

That should give you all the unique labels in your annotation. There might be a typo that's causing 4 extra classes.

**Comment by AndrGolubkov** [comment]
Thank you, I will try.
