### ISSUE TITLE
'module' object has no attribute 'text_classifier'

### ISSUE THREAD

**Issue by carlosdelamora** [apple/turicreate#1130]
I am getting the following error when I am trying to train a text_classifier model. 
    'module' object has no attribute 'text_classifier'
   
     import turicreate as tc 
     from turicreate import SFrame
     import pandas as pd
    
     model = tc.text_classifier.create(train, 'label')

**Comment by TobyRoseman** [comment]
@carlosdelamora - your code works for me. Please make sure you are using the most up to date version, by running `pip install -U turicreate`.
