### ISSUE TITLE
Model not working on iOS12

### ISSUE THREAD

**Issue by Vicapps** [apple/turicreate#1132]
The same model works perfect on iOS11 but it doesn't work on iOS12, it returns nan for all predictions.

**Comment by TobyRoseman** [comment]
@Vicapps - this sounds like a Core ML issue, not a Turi Create issue. I suspect it's the same as [this issue](https://github.com/apple/coremltools/issues/257) already created in the Core ML Tools Repository. If that is not the same issue, please create a new issue in the Core ML Tools Repository.

**Comment by Vicapps** [comment]
Thank you so much Toby!, it worked forcing CPU only.
