### ISSUE TITLE
Export to tensor-flow model

### ISSUE THREAD

**Issue by zoecarver** [apple/turicreate#1141]
Instead of exporting to an mlmodel, I would like to export to a tensor flow model so I can use the model on Android and other platforms. Is this possible?

**Comment by TobyRoseman** [comment]
This is not supported by Turi Create. 

You could try exporting your model to Core ML, then converting it to ONNX using [onnxmltools](https://github.com/onnx/onnxmltools) and finally converting the ONNX model to tensor flow using [onnx-tf](https://github.com/onnx/onnx-tensorflow#use-cli).

**Comment by zoecarver** [comment]
@TobyRoseman thanks for the suggestion.

**Comment by dhgokul** [comment]
@zoecarver Can able to convert coreml to onnx, but when convert from onnx to onnx-tf , i got issue

Any help appreciated !

**Comment by mkhizeryounas** [comment]
Any luck in converting onnx to tensorflow?
