### ISSUE TITLE
Activity Classification Code Needs Updating for Python 3

### ISSUE THREAD

**Issue by Digital-Rabbit** [apple/turicreate#1159]
In
https://apple.github.io/turicreate/docs/userguide/activity_classifier/data-preparation.html
data = data.filter_by(target_map.keys(), 'activity_id')
Need to be updated to:
data = data.filter_by(list(target_map.keys()), 'activity_id')
Since in Python 3, dict.keys() no longer returns a list.

**Comment by nickjong** [comment]
Close as a dupe of #1140
