### ISSUE TITLE
This custom model requires an implementation named 'TCRecommender' which was not found in the gloabl namespace

### ISSUE THREAD

**Issue by dogahe** [apple/turicreate#1160]
I get this error even though I have imported libRecommender.dylib and inluded in the proper locations within the Xcode project. 

Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=com.apple.CoreML Code=5 "This custom model requires an implementation named 'TCRecommender' which was not found in the gloabl namespace" UserInfo={NSLocalizedDescription=This custom model requires an implementation named 'TCRecommender' which was not found in the gloabl namespace}

On this line of the generated Swift class for the Turi Create Recommender model:
    convenience init() {
        try! self.init(contentsOf: type(of:self).urlOfModelInThisBundle)
    }

**Comment by TobyRoseman** [comment]
@dogahe are you following the instructions [here](https://apple.github.io/turicreate/docs/userguide/recommender/coreml-deployment.html)?

**Comment by dogahe** [comment]
@TobyRoseman Yes, I am.

**Comment by znation** [comment]
@dogahe What version of libRecommender.dylib are you using? And can you verify that the libRecommender.dylib (for arm64, if you are deploying to iOS) is present in all 3 of the following places in your Xcode project settings?

* Copy Bundle Resources
* Embedded Binaries
* Linked Frameworks and Libraries

Note that the file needs to be named `libRecommender.dylib` - in 5.0b1 this file was distributed under different names for x86_64 and arm64, and needed to be renamed; starting with 5.0b3 it has been distributed as libRecommender.dylib.

**Comment by dogahe** [comment]
@znation I was missing adding it to **Linked Frameworks and Libraries**. Now the problem is resolved for running on the actual device, thanks. However, it still does not work on the Simulator.

On the simulator I get the following error:
dyld: Library not loaded: @rpath/libRecommender.dylib
  Referenced from: /Users/...
  Reason: no suitable image found.  Did find:
	/Users/.../libRecommender.dylib: mach-o, but not built for iOS simulator

Or   Reason: no suitable image found.  Did find:
	/Users/.../libRecommender.dylib: mach-o, but wrong architecture

I am using the version under https://github.com/apple/turicreate/releases/tag/5.1 so the name was already `libRecommender.dylib`

But neither arm64 version nor x86_64 version work on the Simulator. My understanding is that I have to use x86_64 for the Simulator.

**Comment by znation** [comment]
Thanks @dogahe - it does appear running on Simulator is broken, and is tracked by #822. I'll close this issue and please add any additional notes there - we'll look into it.

**Comment by YogeshBhattGWL** [comment]
Hi, I am still facing the same issue on my **M1 MacBook** while using my iPhone and I have **followed all 3 processes** for `.libRecommender.dylib`.

Please let me know if any other info is needed.
Thanks

**Comment by YogeshBhattGWL** [comment]
I have fixed issue just by taking dragging `.libRecommender.dylib` in Project by reference from the Turi create folder.
