### ISSUE TITLE
Exclusion Sframe Error

### ISSUE THREAD

**Issue by Cyash** [apple/turicreate#1161]
Hi I'm trying to exclude some recommendations using 'exclude' in `recommend()` function but it shows this weird error   `Exclusion SFrame must have both user and item columns.: ToolkitError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 53, in lambda_handler
recommendations = model.recommend(user_id, k = int(size), exclude = exclude_pairs)
File "/var/task/turicreate/toolkits/recommender/util.py", line 1315, in recommend
response = _turicreate.extensions._recsys.recommend(opt)
File "/var/task/turicreate/extensions.py", line 170, in <lambda>
return lambda *args, **kwargs: _run_toolkit_function(fn, arguments, args, kwargs)
File "/var/task/turicreate/extensions.py", line 159, in _run_toolkit_function
raise _ToolkitError(ret[1])
ToolkitError: Exclusion SFrame must have both user and item columns.
`
so I tried to print the contents of sframe and it showed `| item_id | user_id | +---------+-------------------------------+ | 17866 | 0ceefa422cb7df66e22643d211... |` I'm assuming the sframe has all the contents, is there anything I'm missing ?

**Comment by TobyRoseman** [comment]
The exclude SFrame needs to contain two column, one for the id of the items and one for the id of the user. These columns must be named the same as those columns in your training data. 

That should get you past the error, but in trying to give you a toy example I think I found a bug, see #1164

**Comment by Cyash** [comment]
Ahh I see, I didn't use the same column name as my training data!

**Comment by Cyash** [comment]
@TobyRoseman also help me understand if it is possible to  do something like `{'item_id': ['c', 'b'], 'user_id': [1]}` i.e. excluding multiple items or do I've to pass another dictionary to SFrame ?

**Comment by TobyRoseman** [comment]
If all of the rows in the exclude SFrame should have the same value for `user_id` you could do the following:
```python
exclude = tc.SFrame({'item_id': ['c', 'b']})
exclude['user_id'] = 1
```
