### ISSUE TITLE
Image Preprocessing for Image Similarity Model

### ISSUE THREAD

**Issue by mark-bragg** [apple/turicreate#1162]
I created an image similarity model and used the reference data images to test it out. I tested the turicreate model, and I got back zero distances for reference data images, and the same came back when using this code with the coreml model:
`image = tc.image_analysis.resize(reference_data[0]['image'], *reversed(model.input_image_shape))`
`image = PIL.Image.fromarray(image.pixel_data)`
`mlmodel.predict({'image':image})`
However, when using the model in iOS as a VNCoreMLModel, no reference image test came back with a zero distance, and most of them weren't even the shortest distance, i.e. reference image 0 had a shortest distance to reference id 78. 
Since the coreml model works in python, I figured it was a preprocessing issue, so I preprocessed the image myself before passing it to the CoreMLModel. Doing this gave me a consistent output of the reference ids matching the reference images for the shortest distance--yay. The distance still isn't zero, so I have attempted to do whatever I can think of to affect the image to get some difference, but I can't get it any lower than I have already.
Any help is appreciated.

**Comment by mark-bragg** [comment]
@nickjong, any update on this?

**Comment by nickjong** [comment]
Sorry, no, we haven't had time to investigate this more closely. Although I wonder if it's going to end up being the same underlying cause as #1016, where object detectors deploying using the Vision framework are producing unexpected results as well.

Just to confirm, your integration into iOS is along the lines of the sample code in https://github.com/apple/turicreate/blob/master/userguide/image_similarity/export-coreml.md ? When you get the correct shortest distances (although still nonzero), how are you preprocessing the image yourself?

@TobyRoseman, have you seen anything like this in your work on this toolkit?

**Comment by TobyRoseman** [comment]
I don't think I've seen any thing like this before, but I'm having a difficult time understanding the exact problem.

@mark-bragg - Your Core ML model gives correct results on macOS but gives difference results on iOS, Is that correct?

**Comment by mark-bragg** [comment]
@nickjong, here is my preprocessing code:
```
+ (CVPixelBufferRef)pixelBufferForImage:(UIImage *)image sideLength:(CGFloat)sideLength {
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(sideLength, sideLength), YES, image.scale);
    [image drawInRect:CGRectMake(0, 0, sideLength, sideLength)];
    UIImage *resizedImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    CFStringRef keys[2] = {kCVPixelBufferCGImageCompatibilityKey, kCVPixelBufferCGBitmapContextCompatibilityKey};
    CFBooleanRef values[2] = {kCFBooleanTrue, kCFBooleanTrue};
    CFDictionaryRef attrs = CFDictionaryCreate(kCFAllocatorDefault, (const void **)keys, (const void **)values, 2, &kCFTypeDictionaryKeyCallBacks, &kCFTypeDictionaryValueCallBacks);
    CVPixelBufferRef buffer;
    CFDictionaryRef realAttrs;
    
    CFMutableArrayRef attrsArray = CFArrayCreateMutable(NULL, 0, NULL);
    CFArrayAppendValue(attrsArray, attrs);
    
    CVPixelBufferCreateResolvedAttributesDictionary(NULL, attrsArray, &realAttrs);
    
    int status = CVPixelBufferCreate(kCFAllocatorDefault, (int)(sideLength), (int)(sideLength), kCVPixelFormatType_32ARGB, realAttrs, &buffer);
    if (status != kCVReturnSuccess) {
        return nil;
    }
    
    CGColorSpaceRef colorSpace = CGColorSpaceCreateWithName(kCGColorSpaceSRGB);
    size_t numComps = CGColorSpaceGetNumberOfComponents(colorSpace);
    size_t bytesPerRow = CVPixelBufferGetBytesPerRow(buffer);
    size_t bitsPerComponent = (8 * (bytesPerRow/sideLength) - 7) / numComps;
    
    CVPixelBufferLockBaseAddress(buffer, kCVPixelBufferLock_ReadOnly);
    void *data = CVPixelBufferGetBaseAddress(buffer);
    
    CGContextRef context = CGBitmapContextCreate(data, sideLength, sideLength, bitsPerComponent, bytesPerRow, colorSpace, kCGImageAlphaNoneSkipFirst);
    
    CGContextTranslateCTM(context, 0, sideLength);
    CGContextScaleCTM(context, 1.0, -1.0);
    
    UIGraphicsPushContext(context);
    [resizedImage drawInRect:CGRectMake(0, 0, sideLength, sideLength)];
    UIGraphicsPopContext();
    CVPixelBufferUnlockBaseAddress(buffer, kCVPixelBufferLock_ReadOnly);
    return buffer;
}
```
and yes I followed the Turi export to CoreML instructions.
Side note: I am also using an Object Detection model for what I am developing, and the confidences come back much lower using a video feed in comparison to a single image, I followed this example in implementation: https://developer.apple.com/documentation/vision/recognizing_objects_in_live_capture?language=objc.

@TobyRoseman, that is correct.

**Comment by TobyRoseman** [comment]
Can you try passing in an image of all zeros and see if you get the same results on both macOS and iOS? If that's the case then there is probably an issue with your preprocessing code.

**Comment by srikris** [comment]
@mark-bragg Any update on this? Did you get a chance to try out the all zeros image on macOS and iOS?

**Comment by mark-bragg** [comment]
@srikris, I have not. The project I am working on has shifted a few times, but I am still using the image similarity model, so I will investigate and have an update by the end of the week.
