### ISSUE TITLE
Error:  AttributeError: 'Model' object has no attribute 'nonMaximumSuppression'

### ISSUE THREAD

**Issue by yungdai** [apple/turicreate#1165]
I got this odd error that I've never come across before while trying to save my model.  I can't seem to find any reference to this error as well. I'm using Turicreate 5.1 with a MacPro using with an ATi FirePro D300 for GPU acceleration. 

Any ideas why this happens?

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-b99168165bae> in <module>()
     18 
     19 # Export for use in Core ML
---> 20 model.export_coreml('CIBCCardObjects.mlmodel')

~/anaconda3/envs/turienv/lib/python3.6/site-packages/turicreate/toolkits/object_detector/object_detector.py in export_coreml(self, filename, include_non_maximum_suppression, iou_threshold, confidence_threshold)
   1451             model.pipeline.models[0].neuralNetwork.ParseFromString(b'')
   1452             model.pipeline.models.add()
-> 1453             model.pipeline.models[1].nonMaximumSuppression.ParseFromString(b'')
   1454             # begin: Neural network  model
   1455             nn_model = model.pipeline.models[0]

AttributeError: 'Model' object has no attribute 'nonMaximumSuppression'

**Comment by yungdai** [comment]
The print out of my model has the following information:

Class                                    : ObjectDetector

Schema
------
Model                                    : darknet-yolo
Number of classes                        : 2
Non-maximum suppression threshold        : 0.45
Input image shape                        : (3, 416, 416)

Training summary
----------------
Training time                            : 3h 25m 28s
Training epochs                          : 426
Training iterations                      : 10000
Number of examples (images)              : 375
Number of bounding boxes (instances)     : 375
Final loss (specific to model)           : 0.6738

**Comment by nickjong** [comment]
Can you double-check what version of coremltools you have installed? (`pip show coremltools`)

The error message implies that we're using an older version of the MLModel protocol buffer

**Comment by yungdai** [comment]
Name: coremltools
Version: 2.0b1
Summary: Community Tools for CoreML
Home-page: UNKNOWN
Author: Apple Inc.
Author-email: coremltools@apple.com
License: BSD
Location: /Users/yungdai/anaconda3/lib/python3.6/site-packages
Requires: protobuf, numpy, six
Required-by: turicreate

**Comment by yungdai** [comment]
got it working, thanks!

**Comment by gyao852** [comment]
Sorry, I think I'm having a similar issue. Yungdai did you just update coremltools to the latest version?
