### ISSUE TITLE
Which Mac supports GPU?

### ISSUE THREAD

**Issue by nuthinking** [apple/turicreate#1168]
Training a model for transfer style on my 2015 MBP and it's doing it in the CPU (taking ages). Which Macs do support GPU, let's say for all types of models?

**Comment by nuthinking** [comment]
I get style transfer on Mac is still not GPU accelerated: https://github.com/apple/turicreate/issues/635

**Comment by TobyRoseman** [comment]
Not all of our models support using GPUs, on any version of macOS. For details on which models are supported by which versions of macOS, see the [GPU Support](https://github.com/apple/turicreate#gpu-support) of our README.
