### ISSUE TITLE
Image Similarity README syntax highlight for saving model

### ISSUE THREAD

**Issue by denisenepraunig** [apple/turicreate#1172]
Hello.

In the Image Similarity README there is the section "**Saving the model**" and the following code is not highlighted.

Current status:
```
model.save('./myModel.model')
loaded_model = turicreate.load_model('./myModel.model')
```

Prefered syntax highlighting:
```python
model.save('./myModel.model')
loaded_model = turicreate.load_model('./myModel.model')
```

I'll prepare a pull request for that.

BR, Denise

**Comment by shantanuchhabra** [comment]
Great, thanks @denisenepraunig ! Happy to review it!
