### ISSUE TITLE
Item_content_recommender predicition score formula

### ISSUE THREAD

**Issue by thanasisDr** [apple/turicreate#1181]
I would like your help on how the item content recommender generates the recommendations. What is the formula used to produce the prediction score? 

I would like to make clear how the neighborhood size affects the prediction score.  It is totally not clear in the documentation.  I see that many times the prediction score is 0 and I would like to understand why that happens. Does it use for every candidate item similar items that the user has rated or similar items in general? If we have the second case it makes sense to have often prediction score equal to 0. 

The formula used to compute the prediction score would make clear the situation. Could anyone give help me with that issue?

Thank you in advance.

**Comment by TobyRoseman** [comment]
Hi @thanasisDr -

Please take a look at [the section in our User Guide about the Item Content Recommender](https://apple.github.io/turicreate/docs/userguide/recommender/choosing-a-model.html#item-content-data).

From that document: `The ItemContentRecommender builds a model similar to the item similarity model, but uses similarities between item content to actually build the model. ` [The Item Similarity API docs](https://apple.github.io/turicreate/docs/api/generated/turicreate.recommender.item_similarity_recommender.ItemSimilarityRecommender.html#turicreate.recommender.item_similarity_recommender.ItemSimilarityRecommender) does contain formulas.

I'm going to close this issue, but let us know if you have suggestions about how to make this clearer, or send us a pull request. Also let us know if you have additional questions.

**Comment by thanasisDr** [comment]
Hi Toby,

Thank you for your prompt reply. Unfortunately the documentation doesn't reply to my question. The formulas in API do not include anywhere the informatin about the max item neighboorhood. The documentation and the formulas mentioned in it say that for each candidate item the system uses the similarities between that items and all the items the user has rated. If that is the case could you tell me where the max_item_neighborhood_size parameter is used and why it affects the accuracy of the system? I believe that the formula is not correct and a correction or clarification is needed. The parameter I mention is included only in the item content similarity and not in the item similarity recommender. 

I am looking forward to your response. It is very important to know if the system considers all the rated items or some of them defined by the neighboorhood parameter.

Thank you in advance

**Comment by hoytak** [comment]
Hello @thanasisDr,

After all the similarities have been computed, a sparse item-to-item lookup table is built that holds, for each item, a list of the most similar items as determined by overlapping content.  All the items are considered, but only the top max_item_neighborhood_size are actually saved and used for prediction.  However, all are considered when building the model.

Note also that by default, the item content recommender doesn't include user access patterns in its recommendations, only the content provided with the items.  To add in user interaction patterns, add a column containing a sparse dictionary of the users interacting with each item as an item feature.   (There are several ways to get the data in for this; e.g. use groupby + concat if you have a table of user-item interactions).

**Comment by thanasisDr** [comment]
Hi @hoytak.  

Thank you for your reply. What you say confirms what I thought. Could you please answer to one more question I have? In the case that the prediction score is the same for two items how is the ranking in the recommendation list determined? Are the items selected randomly or there is another way that breaks ties like popularity?

Thank you in advance.

**Comment by hoytak** [comment]
Hi @thanasisDr, 

In that case, the items are selected deterministically based on the indexing of the items, which is fixed at train time; however, due to parallelism that indexing is essentially random.  In other words, the only guarantee is that subsequent calls to predict have the same ordering.  

If you want it to be random between calls, try playing with a small but non-zero value of the diversity parameter; this invokes sampling of the recommendations based on a a balance of diversity (trying to not recommend two items that are nearly identical) with recommendation accuracy, and a small value of the diversity parameter means that recommendation accuracy is pretty much all that's used there.
