### ISSUE TITLE
Recommender Sframe Error "All column should be of the same length"

### ISSUE THREAD

**Issue by Cyash** [apple/turicreate#1183]
I'm trying to exclude a array of items from recommender so I've used `exclude_pairs = tc.SFrame({'userID': user_id, 'articleID': exclude_items})` where userid is ['0ceefa422cb7df66e22643d2115ab2e9'] and exclude_items are [17866, 17800, 17869], I'm getting this weird error as 
`All column should be of the same length: RuntimeError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 55, in lambda_handler
exclude_pairs = tc.SFrame({'userID': user_id, 'articleID': exclude_items})
File "/var/task/turicreate/data_structures/sframe.py", line 811, in __init__
raise ValueError('Unknown input type: ' + format)
File "/var/task/turicreate/cython/context.py", line 49, in __exit__
raise exc_type(exc_value)
RuntimeError: All column should be of the same length`
not sure what this means as it worked very well before and all of sudden it started raising this error

**Comment by Cyash** [comment]
so I tried to change my a little bit like this `exclude = tc.SFrame({'articleID': exclude_items})
exclude['userID'] = user_id` now I think I found that userID column is what causing this error it says 
`All column should be of the same length: RuntimeError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 55, in lambda_handler
exclude_pairs = tc.SFrame({'userID': user_id, 'articleID': exclude_items})
File "/var/task/turicreate/data_structures/sframe.py", line 811, in __init__
raise ValueError('Unknown input type: ' + format)
File "/var/task/turicreate/cython/context.py", line 49, in __exit__
raise exc_type(exc_value)
RuntimeError: All column should be of the same length`
I still can't understand what size it is referring to

**Comment by TobyRoseman** [comment]
The code:
`tc.SFrame({'userID': user_id, 'articleID': exclude_items})`
will create an SFrame with two columns, one column called "userID" and the other column called "articleID". 

All columns in a SFrame must be of the same length. So `user_id` and `exclude_items` must have the same length. This error message is saying they are not of the same length.

Feel free to send us a pull request with and better [error message](https://github.com/apple/turicreate/blob/2e8b922db18ad6ed65b9f6b4ecc2a54240de57fe/src/unity/python/turicreate/data_structures/sframe.py#L791).
