### ISSUE TITLE
Could not find a version that satisfies the requirement mxnet==0.11

### ISSUE THREAD

**Issue by codedphoenix** [apple/turicreate#121]
I followed the installation instruction, but ended up with an error when running command pip install -U turicreate. 
The error: Could not find a version that satisfies the requirement mxnet==0.11
Any help would be very much appreciated.

Python 2.7.13
OS: Windows 10

**Comment by gustavla** [comment]
Hi @codedphoenix, thanks for giving Turi Create a go. Let's see if we can figure out what's going on. Can you first confirm that you are...
* running this with [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux)?
* on a x86_64 system?

**Comment by codedphoenix** [comment]
Oh that's where the problem is. I haven't enabled WSL. Thanks
