### ISSUE TITLE
module compiled against API version 0xc but this version of numpy is 0xb for using GPU

### ISSUE THREAD

**Issue by Quinn-0511** [apple/turicreate#1215]
Hi there,

I am using Turicreate 5.1  on Ubuntu 16.04 LTS.  It works very well for only using CPU to train the model. And I started to follow the procedure in LinuxGPU.md.

CUDA 8.0 + cuDNN 5 has been installed and tested. Turicreate still works fine with CPU at this time.

Then I uninstall mxnet and install the CUDA-enabled mxnet-cu80 package. Errors come out at the first line "import turicreate as tc" : 
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
Backend Qt5Agg is interactive backend. Turning interactive mode on.

I searched and suggested to upgrade numpy to -1.15.4 but turicreate and mxnet-cu80 1.1.0 don't accept that. Therefore I rolled back to numpy -1.13.3.

The error is still there. 

Thanks in advance.

**Comment by TobyRoseman** [comment]
@Quinn-0511 - Not sure how much help I'm going to be here. Turi Create [allows any version of numpy](https://github.com/apple/turicreate/blob/2da957ffd91f64769efc1d32558bbdec5450642c/src/unity/python/setup.py#L185) to be installed. If you can't upgrade numpy, then it must be MXNet (or something else in your environment) that's preventing it.

I'd recommend seeing if you can get just MXNet working in your environment.
