### ISSUE TITLE
Style Transfer and high res images

### ISSUE THREAD

**Issue by nuthinking** [apple/turicreate#1220]
By default the `style_transfer` task creates a model that can handle 600x600 CIImages. Is it possible to train the model so that it could handle much bigger images or should these be split in tiles?

**Comment by abhishekpratapa** [comment]
@nuthinking, I'm assuming you're talking about the CoreML export for the style transfer model based on your question about `CIImages`. There may have been some confusion here. **You can actually input any shape that you want into the network!**

You're probably looking at:

https://apple.github.io/turicreate/docs/userguide/style_transfer/export-coreml.html

On this page you'll see: 
```swift
let modelInputSize = CGSize(width: 600, height: 600)
```

This is actually not a default size. It's a size that's defined by the user. You can change that!

**Note**: we do support a notion of `flexible_shape` in the CoreML export, so we'll be able to take any image size as an input. However, if this isn't supported on your version of MacOS (You'd get an error in XCode if it wasn't), or you'd like to explicitly set an export shape, here's how to do it:

The default CoreML export size is in-fact 256x256, as you'll see in the doc-string

```python
'''
image_shape: tuple
            A tuple (defaults to (256, 256)) will bind the CoreML model to a fixed shape.
'''
```
So in your export code, just do the following (note the `image_shape` parameter):

```python
model.export_coreml('MyStyleTransfer.mlmodel', image_shape=(2048, 2048))
```

Hope that helps, if you have any further questions I'd be more than happy to help!

**Comment by nuthinking** [comment]
Thank you so much @abhishekpratapa. So if the default is 256x256 and the user can define the input size for the CIImage at runtime, why would you need to export it with a different image shape?

**Comment by abhishekpratapa** [comment]
I know it seems a bit contrived but the original reason was that if your version of CoreML does not support dynamic input image sizes (for example the first version of CoreML did not support this feature) then this allows the user to select a preset size for those older versions! However, if you are on the latest update this should not be an issue.
