### ISSUE TITLE
When I finish the train.py script， KeyError: 'mean_average_precision'

### ISSUE THREAD

**Issue by elite-kai** [apple/turicreate#1228]
Downloading https://docs-assets.developer.apple.com/turicreate/models/darknet.params
Download completed: /var/folders/6z/72vk4qs55x53kpxt4htmnw900000gn/T/model_cache/darknet.params
Setting 'batch_size' to 32
Using CPU to create model
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
| 1            | 10.968       | 25.6         |
| 2            | 10.891       | 47.4         |
| 3            | 10.651       | 62.3         |
| 4            | 10.842       | 78.0         |
| 5            | 10.480       | 92.8         |
| 6            | 10.283       | 107.7        |
| 7            | 9.766        | 123.2        |
| 8            | 9.531        | 138.8        |
| 9            | 9.075        | 154.3        |

    print(scores['mean_average_precision'])
KeyError: 'mean_average_precision'

Then I found that I only got the Object.model folder and didn't get the .mlmodel file.

**Comment by TobyRoseman** [comment]
@elite-kai - you'll need to provide more details for us to help you. What is the `scores` variable? Can you share the contents of your train.py?

**Comment by TobyRoseman** [comment]
Looking at the API docs for the [object detector's evaluate function](https://apple.github.io/turicreate/docs/api/generated/turicreate.object_detector.ObjectDetector.evaluate.html#turicreate.object_detector.ObjectDetector.evaluate), it does seem `scores` should have a `mean_average_precision`. 

Try doing `print(scores.keys())` to see what metrics are available.

I'd like to try to reproduce this issue. Are you using a publicly available dataset?

**Comment by nickjong** [comment]
In Turi Create 5.0, the default metrics for `object_detector` changed from `['average_precision', 'mean_average_precision']` to `['average_precision_50', 'mean_average_precision_50']`. As described in the [user guide](https://github.com/apple/turicreate/blob/master/userguide/object_detection/advanced-usage.md), the version with '_50' evaluates the metric at an overlap threshold of 50%. The other metric is an average of multiple overlap thresholds.

The text "This is the primary single-value metric." under "mean_average_precision_50" in the Python docs is meant to indicate that this is metric you get by default. Maybe we should make this more explicit, and we should update the user guide as well to reflect the change in default behavior.

**Comment by elite-kai** [comment]
Has been resolved by modifying the script

# train.py
import turicreate as tc

modelName = 'Object'

# Load the data
data = tc.SFrame('annotations.sframe')

# Make a train-test split
train_data, test_data = data.random_split(0.8)

# Automatically picks the right model based on your data.
model = tc.object_detector.create(train_data, feature='image', annotations='annotations', max_iterations=1000)

# Save the model for later use in Turi Create
# Important to save in case something after breaks the script
model.save(modelName + '.model')

# Mean average Precision
scores = model.evaluate(data, metric='all')
print(scores['mean_average_precision'])
#print(scores['accuracy']),

# Export for use in CoreML
model.export_coreml(modelName.title() + 'Classifier.mlmodel')
