### ISSUE TITLE
ToolkitError: No list column in "dataset".

### ISSUE THREAD

**Issue by nsharma02** [apple/turicreate#1231]
Using 'image' as feature column
---------------------------------------------------------------------------
ToolkitError                              Traceback (most recent call last)
<ipython-input-38-ea02e036e52a> in <module>
----> 1 model = turi.object_detector.create(imageData,max_iterations=100)

~/anaconda3/lib/python3.6/site-packages/turicreate/toolkits/object_detector/object_detector.py in create(dataset, annotations, feature, model, classes, batch_size, max_iterations, verbose, **kwargs)
    199                                                        target_type=[list, dict],
    200                                                        type_name='list',
--> 201                                                        col_name='annotations')
    202         if verbose:
    203             print("Using '%s' as annotations column" % annotations)

~/anaconda3/lib/python3.6/site-packages/turicreate/toolkits/_internal_utils.py in _find_only_column_of_type(sframe, target_type, type_name, col_name)
    100             image_column_name = name
    101     if image_column_name is None:
--> 102         raise ToolkitError('No %s column in "dataset".' % type_name)
    103     return image_column_name
    104 

ToolkitError: No list column in "dataset".

Any Help would be really appreciated

**Comment by TobyRoseman** [comment]
Hi @nsharma02 - 

Sorry for the unhelpful error message. Looks like the object detector is not able to automatically detect the column in `imageData` that contains the annotations. Assuming you have annotations, use the `annotations` parameter to set the column name, see [the relevant API doc](https://apple.github.io/turicreate/docs/api/generated/turicreate.object_detector.create.html#turicreate.object_detector.create) for details.

Also if you haven't already, take a look at [the object detector section of our user guide](https://apple.github.io/turicreate/docs/userguide/object_detection/).

Let us know if you have any more questions.

**Comment by TobyRoseman** [comment]
Let's leave this issue open until we have a better error.

The error message [here](https://github.com/apple/turicreate/blob/a7810cbcdc5eeb551853185db14fad16c4c75599/src/unity/python/turicreate/toolkits/_internal_utils.py#L102) should contain the same information as [the error three lines above it](https://github.com/apple/turicreate/blob/a7810cbcdc5eeb551853185db14fad16c4c75599/src/unity/python/turicreate/toolkits/_internal_utils.py#L99).

**Comment by nsharma02** [comment]
@TobyRoseman  - Thanks for your response. I used column name as annotations as per user guide doc. but still could not figure out what's the cause of error. Kindly help                                                            I'm sharing my code.. Please have a look.
<img width="1132" alt="screenshot 2018-12-05 at 11 03 39 am" src="https://user-images.githubusercontent.com/42535586/49492334-d8ff2380-f87d-11e8-8fce-1e458619c8f1.png">
<img width="1440" alt="screenshot 2018-12-05 at 11 03 29 am" src="https://user-images.githubusercontent.com/42535586/49492344-e3b9b880-f87d-11e8-8d32-9394a214f26f.png">
<img width="1139" alt="screenshot 2018-12-05 at 11 03 49 am" src="https://user-images.githubusercontent.com/42535586/49492349-ecaa8a00-f87d-11e8-8688-67c95dc177bc.png">
<img width="1131" alt="screenshot 2018-12-05 at 11 03 57 am" src="https://user-images.githubusercontent.com/42535586/49492358-f207d480-f87d-11e8-8079-574945057582.png">
<img width="864" alt="screenshot 2018-12-05 at 11 07 50 am" src="https://user-images.githubusercontent.com/42535586/49492373-05b33b00-f87e-11e8-9892-8056e8e9c964.png">

**Comment by TobyRoseman** [comment]
Looks like the JSON column is getting interpreted as a string column rather than a list column. Generally the right solution would be to use our [read_JSON function](https://apple.github.io/turicreate/docs/api/generated/turicreate.SFrame.read_json.html) but looks like that is not going to work for you because you're dealing with JSON that is one column of a CSV file.

Try changing the type of that column: `sf['annotations'] = sf['\annotations'].astype(list)`

**Comment by nsharma02** [comment]
created sframe following document https://apple.github.io/turicreate/docs/userguide/object_detection/data-preparation.html
