### ISSUE TITLE
Unclear error message when calculating jaccard and weighted_jaccard distance

### ISSUE THREAD

**Issue by alonpal** [apple/turicreate#1233]
For both jaccard and weighted_jaccard distances the following produces an unclear error:
 ```python
a = {'k': 'df'}
b = {'j': 1}
tc.toolkits.distances.jaccard(a, b)
```
```
ToolkitError: stod: no conversion
```

I would expect something similar to:
```
ToolkitError: at least one of the dictionary values could not be converted to a number.
```
This is especially confusing when using jaccard distance which does not consider the values of the dictionary.

**Comment by dhivyaaxim** [comment]
@znation  Please assign this ticket to me as I would like to try fixing it and contribute .Thanks in advance!
