### ISSUE TITLE
Importing a CSV without file extension

### ISSUE THREAD

**Issue by afranklin** [apple/turicreate#1237]
Turi Create returns an error when importing a CSV that doesn't have a file extension. The below example worked fine after renaming "data" to "data.csv"

RuntimeError: Unable to parse frame index file /Users/xxx/code/Modeling/temp/data

Can we automatically recognize it's a CSV, or at least return a more descriptive error message?

**Comment by nickjong** [comment]
Is it even intentionally the design that we infer file type from extension in the SFrame constructor, despite having static methods for parsing CSV from arbitrarily named files?

Maybe we should take a consistency pass over the API surface

**Comment by TobyRoseman** [comment]
I am not able to reproduce this issue. Calling `tc.SFrame.read_csv(...)`, with a CSV with no file extension, works.

**Comment by sachika11** [comment]
![Screenshot (41)](https://user-images.githubusercontent.com/67162589/85205910-07e3ca00-b33c-11ea-8bc0-c760accc2ed0.png)
how to solve this issue

**Comment by TobyRoseman** [comment]
@sachika11 - SFrames are saved as folders with several files inside of them. The file you are trying to open looks like one of those files. You should also be using `tc.load_sframe(...)` rather than `tc.SFrame(...)`. So call `tc.load_sframe(...)` and pass it the path to the folder with that file.

**Comment by oannaqvi77** [comment]
> ![Screenshot (41)](https://user-images.githubusercontent.com/67162589/85205910-07e3ca00-b33c-11ea-8bc0-c760accc2ed0.png) how to solve this issue

Use the file with .frame_idx extension and upload all of the files from zipped file.
