### ISSUE TITLE
Object Dection Visualization Error in Turicreate Explore

### ISSUE THREAD

**Issue by yashn35** [apple/turicreate#1244]
Hi All,

I have been recently exploring the object detection library, YOLO, for classification using Apple's Turicreate. However, while following this tutorial from Apple's GitHub: ### https://apple.github.io/turicreate/docs/userguide/object_detection/ 

I have been experiencing errors in the TuriCreateVisualization. When I run my program I am outputted with a box but **I can't read the prediction accuracy and what it has predicted since the text is too small.** Is there a way around this bug or problem, to see what the prediction and accuracy is?

I have attached a screenshot of the problem that is occuring. Please let me know if you have any solutions. [](url)
<img width="219" alt="objectdection_prediction_cupcap" src="https://user-images.githubusercontent.com/25993715/49691717-47054e00-fafd-11e8-8b35-16b481aa7331.png">

Thanks,
Yash

**Comment by znation** [comment]
Dupe of #781.
