### ISSUE TITLE
The Kernel appears to have died. Always when I am loading a large file

### ISSUE THREAD

**Issue by grNorway** [apple/turicreate#1247]
I am using Jupyter notebooks for creating aML Model with TuriCreate.

The steps that I am following are the above.

I have download a .csv and .json (same file) from https://www.kaggle.com/zynicide/wine-reviews 1

The file has 51 MB size.

I have made an environment turienv From Anaconda Navigation and the following steps work perfect for smaller CSV / JSON files.

1. source activate turienv
2. pip install turicreate=5.0
3. Jupiter notebook

----inside Notebook----

```
> import turicreate as tc
> 
> wine_data = tc.SFrame.read_json('winemag-data-130k-v2.json', orient='records')
> 
> wine_data.head() <-- I see that everything is loaded properly
> 
> wine_model = tc.text_classifier.create(wine_data,'title',features=['description'])
> 
> PROGRESS: Creating a validation set from 5 percent of training data. This may take a while.
>           You can set ``validation_set=None`` to disable validation tracking.
> 
> Logistic regression:
> --------------------------------------------------------
> Number of examples          : 123481
> Number of classes           : 113404
> Number of feature columns   : 1
> Number of unpacked features : 21030
> Number of coefficients      : 2384978493
> Starting L-BFGS
> --------------------------------------------------------
> +-----------+----------+-----------+--------------+-------------------+---------------------+
> | Iteration | Passes   | Step size | Elapsed Time | Training Accuracy | Validation Accuracy |
> +-----------+----------+-----------+--------------+-------------------+---------------------+
```
> And then in about 3-4 minutes I get error msg = The Kernel appears to have died.

Could anyone help?? I am new in Python and Jupyter is only env I have worked with. If there is an other env that I could run the same things with some guidance to have a more solid error msg that I could debug please let me know.

Edited: I am running the above on a 2018 MacBook Pro 16GB 512GB. I see on Activity Monitor Memory for python goes to 130GB and CPU 83%

Thanks in Advance

**Comment by TobyRoseman** [comment]
Hi @grNorway - by default `text_classifier.create` will train a logistic regression model with a coefficient for each word that is in your dataset at least twice. Sounds like your dataset is too large for this approach.

Take a look at the `word_count_threshold` in our [API documentation](https://apple.github.io/turicreate/docs/api/generated/turicreate.text_classifier.create.html#turicreate.text_classifier.create). Try setting that to a value larger than two.

**Comment by grNorway** [comment]
I still don't manage to classify the .csv file. Is there a limitation on the size of the file? 
I use also drop_stop_words and still I get a huge memory 140GB on python. Any solution how to Classify a csv file in that size ?

**Comment by TobyRoseman** [comment]
@grNorway - What values of `word_count_threshold` have you tried? I would start by trying a fairly large values (say `100`).

Taking another look at the output you shared, it looks like you have 113,404 classes but only 123,481 examples. That's is less than 1.09 examples on average per class. It is very difficult for a model to correctly predict a class, if it only has a small number of examples for that class. Having a large number of classes also increases training time. 

I recommend you explore how often classes appear in your dataset. You probably want to remove examples from your training data if their classes only appear a small number of times.
