### ISSUE TITLE
Visualizations are incomplete

### ISSUE THREAD

**Issue by Digital-Rabbit** [apple/turicreate#1248]
Unless the target for visualization is set explicitly to 'gui', inline visualizations render incompletely. In the course Machine Learning Foundations, the instructor uses the show() command to visualize plots for the First Name, Last Name, Country, and age. However, only First Name renders. The rest of the inline window shows a very large whitespace at the bottom of which has the buttons for exporting and so on. If I click the button Open in Vega Editor, I still see only one plot. 
But if I set the target to 'gui' the plots all render correctly in a separate window.
I am reporting this issue o behalf of a dozen users who asked me for assistance.

**Comment by TobyRoseman** [comment]
@Digital-Rabbit - could you give us code and some toy data to reproduce this issue?

**Comment by Digital-Rabbit** [comment]
import turicreate
sf = turicreate.SFrame("people-example-2.csv”)
sf.show()
 I sent the data separately

**Comment by amitdk** [comment]
I’m trying to invoke visualizations on a test SFrame loaded dataset in a Jupyter notebook and running into an issue where the visualization gets inlined in the notebook and does not render all the necessary visualizations. I’m not able to get these visualizations to show up in a separate window via the visualization.set_target=‘gui’ setting either. When I run an explore() on the SFrame, I do however see the data in a separate window. Is there something different I need to do to prevent the inlining of plots in a Juypter notebook? Here's the code :

import turicreate as tc
sales = tc.SFrame('~/Developer/Python/ml-course/home_data.sframe/')
tc.visualization.target='gui'
sales.show()

**Comment by igiloh** [comment]
@znation I've got the exact same bug running a Jupyter notebook and python 2.7 on Ubuntu 16.04.  
Downgrading to `turicreate==5.1` have eliminated the problem, and upgrading back to 5.2 has reproduced it.

**Comment by igiloh** [comment]
In addition - `sf.explore()` shows nothing but the "Materializing" line:  
![image](https://user-images.githubusercontent.com/11426676/49801164-1cf89980-fd52-11e8-8a8a-5e16e0d32c91.png)
That **wasn't** solved by downgrading to 5.1.

I'm working on a remote notebook server - so I first thought it's merely delay, but that doesn't seem to be the case.

I'm not sure if the two problems are related. Should I file a separate issue?

**Comment by Digital-Rabbit** [comment]
I was able to reproduce by upgrading to the latest TC release---5.2. 
<img width="934" alt="screen shot 2018-12-11 at 5 51 38 am" src="https://user-images.githubusercontent.com/7233812/49805050-0c700100-fd09-11e8-92a7-1b97ec7375c9.png">

**Comment by amitdk** [comment]
Yup - was wondering about that. Also of note, downgrading to 5.1 and setting the visualization target to ‘gui’ continues to keep the visualizations  inlined, although at-least now, all the visualizations show up in the inlined cell.

**Comment by znation** [comment]
@amitdk Can you confirm that you are using [set_target](https://apple.github.io/turicreate/docs/api/generated/turicreate.visualization.set_target.html#turicreate.visualization.set_target) to set the `gui` target? Assigning directly to the `target` property is not expected to work. If the set_target API doesn't work, please open a separate issue for that.

**Comment by znation** [comment]
@amitdk Note that the correct usage is `tc.visualization.set_target('gui')`. This works for me on TC 5.2.

**Comment by amitdk** [comment]
Ah! That worked - somehow thought that was a property. Thanks
