### ISSUE TITLE
load_images should have a way to order the images alphabetically by path

### ISSUE THREAD

**Issue by smahurkar** [apple/turicreate#125]
I have setup my annotations in a text file in the format:

```
#starting from 0000
[[{'coordinates': {'height': 178, 'width': 78, 'x': 96, 'y': 119},
'label': 'blah'}],
#0001
[{'coordinates': {'height': 150, 'width': 63, 'x': 97, 'y': 122},
'label': 'blah'}],
#0002
[{'coordinates': {'height': 223, 'width': 139, 'x': 136, 'y': 133},
'label': 'blah'}],
#0003
[],
#0004
[{'coordinates': {'height': 272, 'width': 138, 'x': 135, 'y': 137},
'label': 'blah'}],
#0005
[{'coordinates': {'height': 272, 'width': 153, 'x': 134, 'y': 137},
'label': 'blah'}],
#0006
[{'coordinates': {'height': 271, 'width': 154, 'x': 137, 'y': 138},
'label': 'blah'}],
#0007
[{'coordinates': {'height': 224, 'width': 137, 'x': 112, 'y': 112},
'label': 'blah'}],
#0008
[{'coordinates': {'height': 89, 'width': 139, 'x': 139, 'y': 177},
'label': 'blah'},
{'coordinates': {'height': 70, 'width': 136, 'x': 140, 'y': 109},
'label': 'test'}]]
```

My image files are named in the format: 0000.jpg, 0001.jpg, 0002.jpg, 0003.jpg etc

My python code:

```
import turicreate as tc

# Load images
sf = tc.image_analysis.load_images('test', with_path=True)

data = sf

# load data from file which contains annotations for images
# column contains type list of dictionaries
# files are ordered in increasing numbers order of naming
vals = eval(open("annotations.txt").read())

data["annotations"] = vals

# Save the data for future use
data.save('test.sframe')

print data

#explore ground truth data i.e. Images with bounding boxes
data['image_with_ground_truth'] = \
    tc.object_detector.util.draw_bounding_boxes(data['image'], data['annotations'])
data.explore()
```

The output is:

+-------------------------------+------------------------+
|              path             |         image          |
+-------------------------------+------------------------+
| /Users/mahusa7/Documents/t... | Height: 225 Width: 225 |
| /Users/mahusa7/Documents/t... | Height: 224 Width: 224 |
| /Users/mahusa7/Documents/t... | Height: 272 Width: 272 |
| /Users/mahusa7/Documents/t... | Height: 195 Width: 259 |
| /Users/mahusa7/Documents/t... | Height: 225 Width: 225 |
| /Users/mahusa7/Documents/t... | Height: 225 Width: 225 |
| /Users/mahusa7/Documents/t... | Height: 272 Width: 272 |
| /Users/mahusa7/Documents/t... | Height: 158 Width: 319 |
| /Users/mahusa7/Documents/t... | Height: 172 Width: 293 |
| /Users/mahusa7/Documents/t... | Height: 225 Width: 225 |
+-------------------------------+------------------------+
+-------------------------------+
|          annotations          |
+-------------------------------+
| [{'coordinates': {'y': 119... |
| [{'coordinates': {'y': 122... |
| [{'coordinates': {'y': 133... |
|               []              |
| [{'coordinates': {'y': 137... |
| [{'coordinates': {'y': 137... |
| [{'coordinates': {'y': 138... |
| [{'coordinates': {'y': 112... |
| [{'coordinates': {'y': 177... |
| [{'coordinates': {'y': 102... |
+-------------------------------+

I was expecting that the annotations column would get linked with images by sorting in naming order. However, it seems that is not the case.

How do I link the annotations column with the image column?

**Comment by gustavla** [comment]
Good point! The `tc.image_analysis.load_images` does not seem to give a consistent order (pretty much random when I try running it). This is design decision that is is worth re-visiting so thanks for pointing it out.

What you can do to fix it is to sort it manually after the call to `load_images`:
```python
sf = tc.image_analysis.load_images('test', with_path=True)
sf = sf.sort('path')
```
Let me know if that did not resolve your issue.

**Comment by smahurkar** [comment]
Thank you. This worked!

**Comment by helloniklas** [comment]
@smahurkar @gustavla  I set the random_order=False and it seemed to work.
```
images = tc.image_analysis.load_images(
    'assets',
    with_path=False, random_order=False
)
```

**Comment by znation** [comment]
Reopening to track a product change to reduce confusion here: let's make `random_order=False` the default for `load_images`.
