### ISSUE TITLE
style_transfer: explore stylize result image save to linux disk function 

### ISSUE THREAD

**Issue by tankfly2014** [apple/turicreate#1251]
I need .style_transfer.create and see result and save stylize result image to disk. (not xcode,only linux)
I read python code and c code. I think this function want edit c.  "explore" function

I need this : stylized_images.save_stylized_image('/home/a/testResult/', format='jpg')
my try code . 
------------
model = tc.style_transfer.create(styles, content, max_iterations=maxInt)    
    test_images = tc.load_images('/home/a/test/')
    stylized_images = model.stylize(test_images)
    stylized_images.save('/home/a/test/1.csv',format='csv')
/*    stylized_images.show()
/*    stylized_images.explore()
    **stylized_images.save('/home/a/test/1.jpg', format='jpg')**

**Comment by TobyRoseman** [comment]
The Turi Create image type does have a [save method](https://apple.github.io/turicreate/docs/api/generated/turicreate.Image.save.html#turicreate.Image.save). 

It looks like `stylized_images` is an SFrame. So you'll need to reference the entry you want and then call save on it. Something like the following should work:
`stylized_images[0]['stylized_images'].save('/home/a/test/1.jpg')`

I'm going to close this issue, but let me know if you have any more questions.

**Comment by tankfly2014** [comment]
yes.CLOSE DIALOG please
