### ISSUE TITLE
Turicreate Text Classifier predicts lower accuracy than CreateML Text Classifier

### ISSUE THREAD

**Issue by LeeCenY** [apple/turicreate#1255]
The same training data, turicreate 80% prediction accuracy is lower than createml 95%, 
but the creation of objects occupy memory, turicreate is lower than createml, memory very good,
the Turicreate .mlmodel file 1.5MB created object memory occupancy exceeds 6MB,
the Createml .mlmodel file 100KB created object memory occupancy exceeds 6MB. 
Turicreate How should I improve the prediction accuracy?

https://apple.github.io/turicreate/docs/userguide/text_classifier/
https://developer.apple.com/documentation/createml/creating_a_text_classifier_model

**Comment by TobyRoseman** [comment]
To improve the performance of Turi Create's text classifier, there are few things you could try:

1 - Try increasing the `word_count_threshold` parameter of [text_classifier.create](https://apple.github.io/turicreate/docs/api/generated/turicreate.text_classifier.create.html#turicreate.text_classifier.create). This will also decrease the size of the .mlmodel file.

2 - Trying increasing he `max_iterations` iteration parameter.

3 - The text classifier wraps logistic regression. You could preform [the preprocessing](https://github.com/apple/turicreate/blob/master/src/unity/python/turicreate/toolkits/text_classifier/_text_classifier.py#L120) yourself then try using different parameters when [creating the logistic regression model](https://github.com/apple/turicreate/blob/master/src/unity/python/turicreate/toolkits/text_classifier/_text_classifier.py#L136).
