### ISSUE TITLE
Image not show on Google Colab Jupyter Notebook

### ISSUE THREAD

**Issue by ancs21** [apple/turicreate#1269]
Method `img.show()`, not working on Jupyter Notebook.
Runtime:
- Python 3.6.7
- Google Colab Jupyter Notebook
- Turicreate 5.2.1

![error_img_show](https://user-images.githubusercontent.com/9210835/50372208-bbabb280-05fc-11e9-8c86-33a4913027fd.PNG)

**Comment by TobyRoseman** [comment]
@ancs21 - Your code works fine for me in Python 3.6 with a local instance of Jupiter Notebook. Could you please tell us the values you get for the following two expressions:
1 - `tc.visualization._plot._target`
2 - `get_ipython().__class__.__name__`

**Comment by ancs21** [comment]
Hello @TobyRoseman 

The values two expressions run on Google Colab Jupyter Notebook: 
1 - `'auto'`
2 - `'Shell'`

Thanks.

**Comment by TobyRoseman** [comment]
Thanks @ancs21. The second expression seems to be what is causing this issue.

[Looking at the code](https://github.com/apple/turicreate/blob/58936c60fcddec23ed00e2b781c652e2fed39ff4/src/unity/python/turicreate/data_structures/image.py#L230) we expect this values to be `"ZMQInteractiveShell"`.

**Comment by ancs21** [comment]
I understand. Many thanks @TobyRoseman 

**Fix this issues** with code:  `get_ipython().__class__.__name__ = "ZMQInteractiveShell"`

Check again: 
![tc](https://user-images.githubusercontent.com/9210835/50605643-6ffae200-0ef5-11e9-83f1-dc14784c451e.png)

**Comment by znation** [comment]
Reopening; we should fix this in Turi Create itself so users don't need the workaround.

**Comment by dhivyaaxim** [comment]
@TobyRoseman  @znation Please assign this ticket to me as I would like to try fixing it and contribute .Thanks in advance!

**Comment by znation** [comment]
Thanks @dhivyaaxim!
