### ISSUE TITLE
how to get a license for GraphLab Create

### ISSUE THREAD

**Issue by filippomortari** [apple/turicreate#127]
Dear all,

I understand this software has been open-sourced.

I am attending the Coursera Module `Machine Learning Foundations: A Case Study Approach`, which as you might know is heavily dependent on the tool. 

The software that runs on the IPython Notebook in Coursera workspace still requires an academic license. I tried to get one from [https://turi.com/download/academic.html](https://turi.com/download/academic.html) but my request fails systematically as the form submission leads to a redirect to beta.graphlab.com that produces a 500 Internal Server Error (see screenshot)
![screen shot 2017-12-18 at 12 22 12](https://user-images.githubusercontent.com/6270932/34206523-c72e8352-e57e-11e7-8609-ac000c934b79.png)
I contacted `contact@turi.com` but haven't received any reply, therefore I am stuck and cannot proceed with my course, so I'd appreciate some advice from someone that is contributing to the project who might know how to fix the aforementioned issue.

I know that opening an issue in here might not be the most appropriate, orthodox way of proceeding but I don't know how to escalate the issue.

Many thanks in advance,

Filippo Mortari

**Comment by afranklin** [comment]
Sorry, but we're unable to provide support for Graphlab Create / Coursera in this repo. However, I'll make sure someone takes a look at this SSL issue today. Thanks for your patience.

**Comment by filippomortari** [comment]
@afranklin yes, I imagined. I just needed an initial point of escalation. Thank you very much indeed. 👍

**Comment by ad8896** [comment]
@filippomortari - Hi, were you able to find a way around the issue? 
I'm also doing the same courses on Coursera, and hence unable to install graphlab or turicreate

**Comment by ad8896** [comment]
@afranklin - could you pls help. 

Thanks!

**Comment by tbrutch** [comment]
Same issue here.  I am also taking the UW Machine Learning course, and I am unable to get GraphLab set up on mac.  Assistance would be most appreciated.
