### ISSUE TITLE
-std= should not be used for setting C++ version

### ISSUE THREAD

**Issue by KOLANICH** [apple/turicreate#1272]
https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD

**Comment by hoytak** [comment]
Unfortunately, there is a bug in cmake prior to 3.8 that prevents us from using this option until we upgrade the minimum cmake version required.  We'll evaluate doing that.

**Comment by hoytak** [comment]
Resolved with https://github.com/apple/turicreate/pull/1359.

**Comment by KOLANICH** [comment]
@hoytak, you can safely put `20` there, CMake will fall back to the latest version available.
