### ISSUE TITLE
How to insert a none/missing value inside a std::vector<flexible_type> of type flex_type_enum::INTEGER (c++ API)?

### ISSUE THREAD

**Issue by gitturi** [apple/turicreate#1278]
I want to give a vector that has a missing value for prediction with knn model. The missing value was of type integer during training. How should this be done?

**Comment by znation** [comment]
@gitturi I'm not sure I fully understand the implications around using this in a KNN model, or how to deal with missing values for that model, but in general to set int values in a vector, I think you should be able to assign directly to an element of the vector, and the implicit constructor of `flexible_type` should allow it to work:

```c++
// where `vec` is an `std::vector<flexible_type>,
// `index` is an integer (valid index into `vec`),
// and `int_value` is an int/uint of up to 64 bits.
vec[index] = int_value;
```

However, if that doesn't compile, you could try explicitly converting to flexible type, as in:

```c++
vec[index] = flexible_type(int_value);
```

**Comment by hoytak** [comment]
Closing this -- please reopen if there is any followup.
