### ISSUE TITLE
SFRAME.SHOW() ERROR

### ISSUE THREAD

**Issue by ifegunni** [apple/turicreate#1281]
Hello, 

I tried visualizing my data using sf.show() but I keep getting this error:

Error: Requested port is unavailable: None
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-c2d40ce3c205> in <module>()
----> 1 sale.show()

C:\Users\obi4m\Anaconda3\envs\gl-env\lib\site-packages\graphlab\data_structures\sframe.pyc in show(self, columns, view, x, y)
   4950             __LOGGER__.warn("Column selection for SFrame.show is deprecated. To show only certain columns, use the sf[['column1', 'column2']] syntax or construct a new SFrame with the desired columns.")
   4951         from ..visualization.show import show
-> 4952         show(self, view=view, x=x, y=y)
   4953 
   4954     def pack_columns(self, columns=None, column_prefix=None, dtype=list,

C:\Users\obi4m\Anaconda3\envs\gl-env\lib\site-packages\multipledispatch\dispatcher.pyc in __call__(self, *args, **kwargs)
    276             self._cache[types] = func
    277         try:
--> 278             return func(*args, **kwargs)
    279 
    280         except MDNotImplementedError:

C:\Users\obi4m\Anaconda3\envs\gl-env\lib\site-packages\graphlab\canvas\glc_display_dispatch.pyc in show(obj, **kwargs)
      7     import graphlab.canvas.inspect
      8     import graphlab.canvas.views.sframe
----> 9     graphlab.canvas.inspect.find_vars(obj)
     10     return graphlab.canvas.show(graphlab.canvas.views.sframe.SFrameView(obj, params=kwargs))
     11 

C:\Users\obi4m\Anaconda3\envs\gl-env\lib\site-packages\graphlab\canvas\inspect.pyc in find_vars(var)
     42     (variable_name, variable) = _find_variable_name(var)
     43     if variable_name is not None:
---> 44         target.add_variable((variable_name,), variable)
     45     return variable_name
     46 

AttributeError: 'NoneType' object has no attribute 'add_variable'

What am i doing wrong?

**Comment by TobyRoseman** [comment]
@ifegunni - it looks like you're using Graph Lab Create. Please use Turi Create. To get started see our [Installation Instructions](https://github.com/apple/turicreate#installation).
