### ISSUE TITLE
Docker image effect of different Linux release btw host and container

### ISSUE THREAD

**Issue by davide445** [apple/turicreate#1283]
Just imported [https://hub.docker.com/r/jidebingfeng/turicreate](url) for testing my GPU installation and have a first test with Turi Create.

Noticed the dockerfile is pulling 
`
FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04`

My Kubuntu installation is on 18.04, not an expert but reading Docker share the kernel with the host, in this case I suppose they are different kernel releases.

There is a substantial overhead in running a release different btw host and image?

**Comment by TobyRoseman** [comment]
@davide445 - we didn't create that docker image and we also don't support that docker image. Perhaps you should contact the creator of that docker image.

If you have issue running Turi Create natively, let us know.

**Comment by davide445** [comment]
@TobyRoseman this is a general question, not specific for that docker file, useful for any beginner like me.

**Comment by davide445** [comment]
@TobyRoseman - that's a good point. I tried to use Turi Create on Docker in the first place since I was on Windows and all appear to be complicate in term of dependencies and path etc.
Now having natively on Linux maybe worth having a try to use it natively, but again reading the documentation is suggested the use of virtualenv, will be the same using conda?
