### ISSUE TITLE
Turi Create object detection annotation visualizations with SFrame.explore() are wrong

### ISSUE THREAD

**Issue by rringham** [apple/turicreate#1285]
**Environment:** macOS High Sierra, 10.13.6
**Python:** 3.6.5
**Turi Create version:** 5.2.1, installed via pip

**Issue:** when visualizing annotations with SFrame.explore(), the annotations are displayed very incorrectly - leading to my concern: is Turi Create training object detection models with incorrect annotations?

For example, with an annotation like the following on a black 1000x1000 image:
```
{'coordinates': {'height': 500, 'width': 500, 'x': 250, 'y': 250},
 'label': 'example'}
```
If I try to visualize this with Turi Create, this is what I see:

![image](https://user-images.githubusercontent.com/1619688/50692425-ce14eb80-1001-11e9-81fd-ebb54cd45856.png)

Obviously incorrect, as the annotation does not start at (0, 0).

If I draw the same annotation with PIL, it's obvious where the annotation should be:

![image](https://user-images.githubusercontent.com/1619688/50692464-f4d32200-1001-11e9-9e68-bfa113c9d3fe.png)

I've attached a zipped Jupyter Notebook that demonstrates this issue. Can I count on Turi Create to train my object detection model correctly, or is it possible that the training pipeline might also misinterpret annotation bounding box coordinates?

[Turi Create Annotation Visualization Test.ipynb.zip](https://github.com/apple/turicreate/files/2727294/Turi.Create.Annotation.Visualization.Test.ipynb.zip)

**Comment by gustavla** [comment]
@griffinwalkerMM It looks like you are interpreting x/y as the top-left corner, while Turi Create's convention is to define it as the center of the box. To address this, you could modify your annotation building function accordingly:

```python
def build_annotations(row):
    ret = {'coordinates':
                  {'x' : (row.bbox[0] + row.bbox[2]) / 2,
                   'y'  : (row.bbox[1] + row.bbox[3]) / 2,
                   'width': row.bbox[2],
                   'height': row.bbox[3]},
                  'label': row.label}
    return ret
```

@rringham I believe you are having the same issue, since your correct annotation is at the center of the image. However, according to our convention, the means you should have x=500 and y=500.

**Comment by rringham** [comment]
@gustavla Yeah, I'm definitely considering (x,y) to be top left.

Upon closer inspection, the [documentation](https://github.com/apple/turicreate/tree/master/userguide/object_detection) does indeed say (x,y) should be the center point:

> A bounding box is defined by four values (x, y, width, height) where (0, 0) is the top left corner. The center of the box is located at (x, y).

I think it'd be worth emphasizing that a bit in the documentation, it's easy to miss, and most rectangle conventions consider (x,y) to be top-left, not center.

Thank you for the reply though, should be straightforward for me to fix my code now.

**Comment by griffinwalkerMM** [comment]
@gustavla thanks for your help and so quickly! Can confirm this solved my issue as well.
