### ISSUE TITLE
graphlab create on amazon ec2(api not able to open session on browser)

### ISSUE THREAD

**Issue by jayshankarnair** [apple/turicreate#1287]
I am running the following code on python notebook
import graphlab
sales = graphlab.SFrame('home_data.gl/')
import matplotlib.pyplot as plt
%matplotlib inline
my_features = ['zipcode']
sales[my_features].show()
It produces the output
Canvas is accessible via web browser at the URL: http://localhost:59146/index.html
Opening Canvas in default web browser.

When i point my browser to above location.
I am getting the following error
This site can’t be reached localhost refused to connect.

**Comment by TobyRoseman** [comment]
I would check the security group being used by your EC2 instance. Make sure the port you're using (i.e 59146) is open for inbound traffic. 

This repository is for Turi Create not GraphLab Create. Please try using Turi Create. Let us know if you have the same problem with Turi Create or if it's missing the functionality you need.
