### ISSUE TITLE
Feature columns and target columns

### ISSUE THREAD

**Issue by varunlakshmanan** [apple/turicreate#1288]
What are feature columns and target columns, and what's the difference between them? I see that they are required to use the boosted trees or random forest classifier. If I have six groups of images each with their own label, is it possible to use the boosted trees, random forest, or SVM classifiers?

**Comment by TobyRoseman** [comment]
The target column is what the machine learning model is trying to predict. The feature columns are what the machine learning model uses to make the prediction. 

Taking housing data and trying to predict the sales price is a classic example of machine learning. In this example, the sale prices would the target column. The other information about the houses would be the feature columns, such as: number of bedrooms, number of bathrooms, square footage, etc.

It's possible to use those models on images, but it's probably not going to work very well. To classify images you should use our [image classifier](https://apple.github.io/turicreate/docs/userguide/image_classifier/).

I'm going to close this issue, but let us know if you have any more questions.
