### ISSUE TITLE
Linking errors building turi C API via build_capi.sh on CentOS 6.6

### ISSUE THREAD

**Issue by gitturi** [apple/turicreate#1289]
Hi, I am trying to build the C API from master branch on CentOS 6.6. I am running the following command: cuild_capi.sh -r -j 1
There are many linking errors of duplicate symbols, all the clashes are with openssl.o:(BIO_s_bio).
I've attached stdout and stderr the script outputs.
[stdout_capi.txt](https://github.com/apple/turicreate/files/2730509/stdout_capi.txt)
[stderr_capi.txt](https://github.com/apple/turicreate/files/2730510/stderr_capi.txt)

**Comment by TobyRoseman** [comment]
We now included our own copy of Open SSL under `deps`. Is this still an issue?

**Comment by TobyRoseman** [comment]
I haven't not heard back here. So I'm going to close this issue since it's likely already fixed. Please reopen if it's still a problem.
