### ISSUE TITLE
Column type of target "label" must be int or float

### ISSUE THREAD

**Issue by varunlakshmanan** [apple/turicreate#1295]
`Column type of target "label" must be int or float`

This is the error I'm getting when trying to train an image classification model with the example code given for a linear regression. It was my understanding that linear regressions could take string values for column types. Seeing as this isn't possible, is there a way I can use a linear regression to classify images? I'm primarily interested in utilizing the many modifiable parameters that a linear regression has (feature rescaling, changing default solver, step_size, max_iterations, max_depth, convergence_threshold, lbfgs_memory_level, l1 and l2 penalty (ridge, lasso, and elastic models)). If there's a way to modify all these parameters using just the standard image classifier toolkit, please let me know how (when I tried, I got an error that these parameters other than max_iterations were not recognized). 

Here is my code that causes the error: 

```
import turicreate as tc
import os

# 1. Load images (Note: you can ignore 'Not a JPEG file' errors)
data = tc.image_analysis.load_images('dataset', with_path=True)

# 2. From the path-name, create a label column
# data['label'] = data['path'].apply(lambda path: 'dog' if '/Dog' in path else 'cat')

# Note: If you have more than two classes, extract the folder names like this:
data["label"] = data["path"].apply(lambda path: os.path.basename(os.path.split(path)[0]))

# 3. Make a train-test split
train_data, test_data = data.random_split(0.8)

# 4. Create the model
model = tc.linear_regression.create(train_data, target='label', solver = 'lbfgs', max_iterations = 20, step_size = 2.0, convergence_threshold = 0.005, lbfgs_memory_level = 10, l1_penalty = 1.0,
                                    l2_penalty = 1.0) #step_size = 2.0, convergence_threshold = 0.05)

# 5. Save predictions to an SArray
predictions = model.predict(test_data)

# 6. Evaluate the model and save the results into a dictionary
metrics = model.evaluate(test_data)
print(metrics['accuracy'])

# 7. Save the model for later use in Turi Create
model.save('linearreg.model')

model.export_coreml('linearreg.mlmodel')
# 8. Export for use in Core ML

```

**Comment by TobyRoseman** [comment]
`max_iteraions` and `model` are the only parameter you can currently tune for the image classifier. See [the relevant API doc](https://apple.github.io/turicreate/docs/api/generated/turicreate.image_classifier.create.html#turicreate.image_classifier.create) for details.

I don't think the issue you're having with linear regression is related to how you wrote your code. I think linear regression just doesn't support image features and we have a bad error message for that case.

I would also expect logistic regression to perform poorly here too.

I can't give you an estimate of when the feature request might be done. However it should be a relatively straightforward change. If you'd like to make it yourself and put up a pull request, I'm happy to review it.

**Comment by varunlakshmanan** [comment]
Thanks for the help. I'll wait for the feature request to be completed (I'm not too experienced with pull requests.)
