### ISSUE TITLE
Text Classifier Documentation Improvements

### ISSUE THREAD

**Issue by euwars** [apple/turicreate#1297]
First i wanted to thank you guys for making Turi Create, it's very handy and easy to use. In fact i just released [my app ](https://getfilter.xyz) which i used turicreate text classification for it in 3 different languages.

I've tried multiple different ML Tasks that turicreate is offering, and i think pretty much Text Classification has the least helpful documentation for beginners and people that are not familiar with python, for example there are no links of datasets to practice with it. 

I was wondering if you are open to PRs to make it more beginner friendly?

**Comment by TobyRoseman** [comment]
@euwars - I'm glad you've found Turi Create useful. We are always open to PRs to make our product better.

I'm going to close this issue, but please let me know if you have any more questions. Looking forward to your PR.
