### ISSUE TITLE
Linear Regression Gives Incorrect Error Message with Image Column 

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#1298]
Using the [Kaggle Cats and Dogs dataset](https://www.microsoft.com/en-us/download/details.aspx?id=54765), the following code:
```python
import turicreate as tc
import os
data = tc.image_analysis.load_images('PetImages', with_path=True)
data['label'] = data['path'].apply(lambda path: 'dog' if '/Dog' in path else 'cat')
model = tc.linear_regression.create(data, target='label')
```
Give the following error message: `ToolkitError: Column type of target 'label' must be int or float.`

However linear regression does support string target types. The following works fine:
```python
data = tc.SFrame({'x': ['0', '1', '2', '99', '100', '101'], 'y':['low', 'low', 'low', 'high', 'high', 'high']})
model = tc.linear_regression.create(data, target='y')
```

**Comment by nickjong** [comment]
Well, following your example, I get:
```
>>> model.predict(data)
dtype: float
Rows: 6
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
>>> model.evaluate(data)
{'max_error': 0.0, 'rmse': 0.0}
```

It doesn't seem like we're doing anything sensible with the string targets. Maybe the model training here should throw an error too?

**Comment by shantanuchhabra** [comment]
I think it's because a validation set is automatically created when the `dataset_size >= 100` and the type of the target column is only checked for then. I think the fix is to do a sanity check on the target column (along with maybe other checks that are independent of creating a validation set) in the code path when no validation set is created.

**Comment by fareeha** [comment]
> I think it's because a validation set is automatically created when the `dataset_size >= 100` and the type of the target column is only checked for then. I think the fix is to do a sanity check on the target column (along with maybe other checks that are independent of creating a validation set) in the code path when no validation set is created.

@shantanuchhabra I already fixed this issue. We went over this fix yesterday - thanks for re-iterating it here..

**Comment by hoytak** [comment]
Huh.  Linear regression should not take string targets.
