### ISSUE TITLE
Consider pipenv for install

### ISSUE THREAD

**Issue by iandanforth** [apple/turicreate#13]
Pip is great! So is virtualenv! [Pipenv](https://github.com/pypa/pipenv) (from Kenneth Reitz) brings them together to simplify virtual env management and setup. It also provides deterministic builds. 

Thanks for the new library, I hope you'll evaluate pipenv and see if it's right for turicreate.

**Comment by Olamyy** [comment]
I'm not totally sure I understand how pipenv works but from the little I understand, I think it automatically makes every pypi package available for download.
So, if _turicreate_ is on pypi, `pipenv install turicreate` should be able to install it.

**Comment by gustavla** [comment]
Perhaps you meant as the recommended way to do a local build for Turi Create development? @iandanforth I'm curious to hear more about how you suggest we use pipenv.

**Comment by znation** [comment]
@gustavla Or perhaps in the installation instructions in README.md?

**Comment by Avimael6** [comment]
Avimael6

**Comment by Avimael6** [comment]
Iphon

**Comment by iandanforth** [comment]
The above comments are correct. "Integration" could be as simple as changing the install instructions README.md. This would save users from the small burden of managing virtual environments manually. Depending on the project this may or may not be desirable, I have found it to be generally more pleasant to work with. 

Secondarily the project could add Pipfile and Pipfile.lock dependency description files. These help produce deterministic builds and fully document expected versions of required libraries without much additional overhead. 

Usually these two steps are done together after a maintainer has played around with installing using pipenv on several systems and decided if they like the workflow.

**Comment by znation** [comment]
I played around with `pipenv` and personally didn't find it more intuitive or easy to use than `virtualenv`; I also haven't seen it gaining much traction lately. I'm going to close this issue until there is further evidence of adoption of pipenv over virtualenv, and/or a compelling reason for us to adopt it anyway.
