### ISSUE TITLE
Unsupported Colorspace Format Error

### ISSUE THREAD

**Issue by pranjalsatija** [apple/turicreate#1305]
This is somewhat related to #1264, but I think it's different enough to warrant its own issue.

I'm using a custom data set, so I can't share it here, but there were 3 images in my data set in the wrong colorspace format, and TC properly warned me about them and told me which images were the offending ones, as expected. After deleting them, a second issue occurs:
```
Traceback (most recent call last):
  File "make_predictions.py", line 14, in <module>
    sf['image'] = tc.image_analysis.resize(sf['image'], 150, 200)
  File "/usr/local/lib/python2.7/site-packages/turicreate/toolkits/image_analysis/image_analysis.py", line 159, in resize
    return image.apply(lambda x: _extensions.resize_image(x, width, height, channels, decode, resample_method))
  File "/usr/local/lib/python2.7/site-packages/turicreate/data_structures/sarray.py", line 1894, in apply
    dryrun = [fn(i) for i in self.head(100) if i is not None]
  File "/usr/local/lib/python2.7/site-packages/turicreate/toolkits/image_analysis/image_analysis.py", line 159, in <lambda>
    return image.apply(lambda x: _extensions.resize_image(x, width, height, channels, decode, resample_method))
  File "/usr/local/lib/python2.7/site-packages/turicreate/extensions.py", line 171, in <lambda>
    return lambda *args, **kwargs: _run_toolkit_function(fn, arguments, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/turicreate/extensions.py", line 160, in _run_toolkit_function
    raise _ToolkitError(ret[1])
turicreate.toolkits._main.ToolkitError: Unsupported colorspace format. Currently, only RGB and Grayscale are supported.
```

This is fine, and I understand that only RGB and Grayscale formats are supported, but there's no additional information here on which images are the offenders. I was able to solve this by using the `channels` attribute on `tc.Image` with a binary filter on my SFrame:

```python
sf = sf[sf['image'].apply(lambda img: img.channels <= 3)]
```

I still don't think this is the best solution because formats like YUV and HSV will still "pass" this test. Is there any way to get additional debugging information that tells us which images are causing trouble?

**Comment by nickjong** [comment]
We should probably emit error about unsupported formats when the image is first put into the SFrame anyway, not later when the user actually attempts to use it.

Note that the issue isn't really about number of channels. AFAICT, libjpeg (which we use for all our JPEG decoding) doesn't support conversion from CMYK data to the RGB assumed by our image type. If I'm not mistaken, most JPGs are actually stored in YUV anyway, but libjpeg converts that to RGB without a problem.

(For JPEGs specifically, it is correct to check for num_channels <4, since JPEG doesn't support RGBA. We do support 4-channel, RGBA PNG files though.)

**Comment by fareeha** [comment]
That’s a great point. I was going to convert the error to a warning after discussing with Toby but let’s place the 'log and throw' elsewhere. I’ll look for where to put it.

**Comment by pranjalsatija** [comment]
I think moving it into the SFrame initializer would be good. I dug through the source, and the code that throws the error above doesn’t have access to any path information, unless it’s secretly included in each Image somehow.

**Comment by nickjong** [comment]
Looks like this is the same underlying issue as #1279. Let's use that issue to track the work needed.
