### ISSUE TITLE
Clarification about confusion matrices

### ISSUE THREAD

**Issue by varunlakshmanan** [apple/turicreate#1319]
When using the image classifier toolkit to train a dataset of about 850 images with a 90-10 train-test split with six classes, I get the following confusion matrix. What do the values under the "count" column actually represent? It's unclear to me. 
![image](https://user-images.githubusercontent.com/17592868/51095886-08ab2080-1786-11e9-9e4a-fdcf139c508e.png)

**Comment by hoytak** [comment]
The count is the number of times the model predicted the given predicted_label with a given target_label.  In your case, the predicted label always match the target label, so you've got 100% accuracy.

**Comment by TobyRoseman** [comment]
This is basically the same thing as a [confusion matrix](https://en.wikipedia.org/wiki/Confusion_matrix) just in a different format. Also rows where the counts are zero are omitted.

Take the first row for example `17` is the number of times the model predicted `Clubbing` and the true value was `Clubbing`. 

Your model predicted everything correct. If it had not predicted everything correct, then there would be a row where the `target_label` and `predicted_labels` where not the same.

I'm going to close this issue but let me know if you have any additional questions.
