### ISSUE TITLE
Object detection prediction yields []

### ISSUE THREAD

**Issue by johnyquest7** [apple/turicreate#132]
I tried to create an object detection model. 
The output of the predict function is [] instead of a list with bounding box

**Comment by gustavla** [comment]
Hi @johnyquest7, thanks for trying out the detector! An empty list is a valid return if the model did not find an object with enough confidence. However, if you are getting this on an image where you feel there is an object that it should find, then we need to figure out why it wasn't able to learn this.

First of all, try lowering the confidence threshold. This should give you a lot of bounding boxes (although many of them seemingly random with very low confidence):

```python
model.predict(sf, confidence_threshold=0)
```

Is the top prediction at least somewhat reasonable? If not, then I would go back to your training data and visualize it to make sure everything looks good. You can also try making a prediction on a training sample - the model should get this right with high confidence. Also, how many classes and samples did you have in your training set? Let me know and hopefully we can track down the issue. This kind of feedback is really helpful for us, so thanks a lot!

**Comment by johnyquest7** [comment]
Thanks for the advise. I tried to visualize the original images with bounding boxes. Somehow the bounding boxes were not showing up. May be there was an error in defining the bounding boxes. Trying to find out. Will keep you posted.

**Comment by johnyquest7** [comment]
Initially I only ran 50 iterations on 200 image. Later I ran 200 iterations and it worked!
