### ISSUE TITLE
Object detection (prediction) on images larger than those in the training set

### ISSUE THREAD

**Issue by tamersalama** [apple/turicreate#1321]
I've followed the introductory example and was able to train a model to detect Bikes & Cars (IG02).
The created model performs adequately when predicting objects on new images of similar size to the training sample image sizes (~500KB). However, it falls shorts when dealing with large-size images (MB).

What would be a proper strategy when dealing with large predictions images... 
- Should I train models with large size images? or:
- Chunk the prediction images and pass each chunk to the model?, or:
- ...other?

**Comment by TobyRoseman** [comment]
I don't think there is a clear correct answer here. Both of your ideas sound viable.

Another idea: resize the these large images prior to calling predict.

Let us know what ends up working the best.
