### ISSUE TITLE
sf.show() error in graphlab : AttributeError: 'module' object has no attribute '_canvas'

### ISSUE THREAD

**Issue by rohitkes** [apple/turicreate#1328]
When I want to show the canvas for the dataframe using 
sf.frame() It says: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-5ed0e1e363af> in <module>()
----> 1 sf.show()

C:\Users\rkesarva\Anaconda2\lib\site-packages\graphlab\data_structures\sframe.pyc in show(self, columns, view, x, y)
   4950             __LOGGER__.warn("Column selection for SFrame.show is deprecated. To show only certain columns, use the sf[['column1', 'column2']] syntax or construct a new SFrame with the desired columns.")
   4951         from ..visualization.show import show
-> 4952         show(self, view=view, x=x, y=y)
   4953 
   4954     def pack_columns(self, columns=None, column_prefix=None, dtype=list,

C:\Users\rkesarva\Anaconda2\lib\site-packages\multipledispatch\dispatcher.pyc in __call__(self, *args, **kwargs)
    276             self._cache[types] = func
    277         try:
--> 278             return func(*args, **kwargs)
    279 
    280         except MDNotImplementedError:

C:\Users\rkesarva\Anaconda2\lib\site-packages\graphlab\canvas\glc_display_dispatch.pyc in show(obj, **kwargs)
      8     import graphlab.canvas.views.sframe
      9     graphlab.canvas.inspect.find_vars(obj)
---> 10     return graphlab.canvas.show(graphlab.canvas.views.sframe.SFrameView(obj, params=kwargs))
     11 
     12 

C:\Users\rkesarva\Anaconda2\lib\site-packages\graphlab\canvas\views\sframe.pyc in __init__(self, obj, params)
     29         self.scatter = graphlab.canvas.views.scatter.ScatterPlot(self.obj, self.params)
     30         self.heatmap = graphlab.canvas.views.heatmap.HeatmapView(self.obj, self.params)
---> 31         self.bar = graphlab.canvas.views.bar.BarGraphView(self.obj, self.params)
     32         self.boxwhisker = graphlab.canvas.views.boxwhisker.BoxWhiskerView(self.obj, self.params)
     33 

C:\Users\rkesarva\Anaconda2\lib\site-packages\graphlab\canvas\views\bar.pyc in __init__(self, obj, params)
      9         self.col1 = self.get_column('x')
     10         self.col2 = self.get_numeric_column('y', self.col1)
---> 11         self.__re_init()
     12 
     13     def __re_init(self):

C:\Users\rkesarva\Anaconda2\lib\site-packages\graphlab\canvas\views\bar.pyc in __re_init(self)
     17            self.col2 is None:
     18             return
---> 19         self.__summary = gl.extensions._canvas.streaming.groupby.summary()
     20         self.__summary.init(gl.SFrame([self.obj[self.col1], self.obj[self.col2]]))
     21 

C:\Users\rkesarva\Anaconda2\lib\site-packages\graphlab\__init__.pyc in __getattr__(self, name)
    232             pass
    233         graphlab.connect.main.get_unity()
--> 234         return getattr(self._wrapped, name)
    235 
    236     _sys.modules["graphlab.extensions"] = _extensions_wrapper(_sys.modules["graphlab.extensions"])

AttributeError: 'module' object has no attribute '_canvas'

**Comment by TobyRoseman** [comment]
@rohitkes - it looks like you're using GraphLab Create not Turi Create. Please try using Turi Create. Installation instructions are [here](https://github.com/apple/turicreate#installation).
