### ISSUE TITLE
Allow controlling non-maximum suppression threshold in predict

### ISSUE THREAD

**Issue by gustavla** [apple/turicreate#1333]
Right now, the documentation doesn't make it clear whether or not [predict](https://apple.github.io/turicreate/docs/api/generated/turicreate.object_detector.ObjectDetector.predict.html#turicreate.object_detector.ObjectDetector.predict) includes non-maximum suppression (NMS). It does and the threshold is 0.45 (which can checked by accessing `ObjectDetector.non_maximum_suppression_threshold`).

We don't expose any public API to override this value, as we do in `export_coreml`. We do allow `confidence_threshold` to be changed though in both, so I see no reason why we don't allow the NMS threshold too (which would make things more consistent).

Question: Should we extend this to `evaluate` too? If not, we give users the power to change these values but not the tools to decide the right value for their use case. If we allow this as an optional parameter anytime it would be used, should we just go ahead and create a function where the user can change the threshold instead?

**Comment by nickjong** [comment]
Yeah, I think we should definitely support this in evaluation, too
