### ISSUE TITLE
Unit Test Failure in Text Classifier on Python 2.7/3.6

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#1340]
The following unit test failed on [this](https://travis-ci.com/apple/turicreate/jobs/171305938) build: 
```
________________ TextClassifierCreateTests.test_validation_set _________________
self = <turicreate.test.test_text_classifier.TextClassifierCreateTests testMethod=test_validation_set>
    def test_validation_set(self):
        train = self.data
        valid = self.data
    
        # Test with a validation set
        model = tc.text_classifier.create(train, target='rating', validation_set=valid)
        self.assertTrue('Validation Accuracy' in model.classifier.progress.column_names())
    
        # Test without a validation set
        model = tc.text_classifier.create(train, target='rating', validation_set=None)
        self.assertTrue('Validation Accuracy' not in model.classifier.progress.column_names())
    
        # Test 'auto' validation set
        big_data = train.append(tc.SFrame({
            'rating': [5] * 100,
            'place': ['d'] * 100,
            'text': ['large enough data for %5 percent validation split to activate'] * 100
        }))
        model = tc.text_classifier.create(big_data, target='rating', validation_set='auto')
>       self.assertTrue('Validation Accuracy' in model.classifier.progress.column_names())
E       AssertionError: False is not true
turicreate/test/test_text_classifier.py:182: AssertionError
```

**Comment by TobyRoseman** [comment]
I can't reproduce this error on master with Python 2.7 (same python version as the failed Travis run).

@shantanuchhabra - any ideas how I might reproduce this?

**Comment by shantanuchhabra** [comment]
@TobyRoseman Unfortunately, I couldn't either. The Travis run is the only place where I see it. I'll let you know if I have an update though.

**Comment by shantanuchhabra** [comment]
As an update, this just repro’ed on Python 3.6 in this build: https://travis-ci.com/apple/turicreate/jobs/183295142

**Comment by TobyRoseman** [comment]
I finally figured out what's going on here. The data in this unit test is only 106 rows. So the `random_split(.95)` used to generate the validation split will occasionally (one time out a couple hundred) generate an empty validation set. When this happens the unit test fails.

We could fix this by just making the unit test run with a greater number of rows. However I think this intermitent failure is a legitimate problem. If the `validation_set` parameter is set to `auto` and you have enough data, you should always get a validation set. It also seems wrong that if you create two different model with the exact same data, you'll likely get slightly different sized validation sets. When we do auto validation splits I think we should require an exact split.
