### ISSUE TITLE
Style Transfer issue, Model fine tunig and general questions

### ISSUE THREAD

**Issue by josefgrunig** [apple/turicreate#1341]
First of all I want to say that I really appreciate the nice and hard work on Turi Create: its incredible how this tool simplifies Style Transfer. I am opening this issue because experimenting with it I found a visual issue and need some parameter clarification that I was not able to find in the docs.

The issue: I found that the resulting images have some strange color banding. They are always diagonal and present strange green/purple color. Maybe related to this bug: [#666](https://github.com/apple/turicreate/issues/666)
Please see image below:
![color-banding](https://user-images.githubusercontent.com/32868530/51428043-5220c300-1bff-11e9-8c16-7bcd962ca567.png)

Apart this, I am writing to show my results on my first style transfer test. Actually I was expecting something different thus I am asking here for more fine tuning on the parameters.

```
Schema
------
Model                                    : resnet-16
Number of unique styles                  : 1
Input image shape                        : (256, 256)

Training summary
----------------
Training time                            : 3h 54m
Training epochs                          : 2051
Training iterations                      : 10000
Number of style images                   : 1
Number of content images                 : 39
Final loss                               : 1.6845
```

Loss plots:
![contentstyleloss](https://user-images.githubusercontent.com/32868530/51428165-d4f64d80-1c00-11e9-8b7a-76007d0cab8b.jpg)

![totalloss](https://user-images.githubusercontent.com/32868530/51428170-dcb5f200-1c00-11e9-8fd5-6f1529c51597.jpg)

Results:
![styletransfer](https://user-images.githubusercontent.com/32868530/51428095-1afee180-1c00-11e9-8fff-47178bfc72a2.jpg)

What I am trying to reach out is to bring more pencil stroke on the final image. I would like it to look like a hand drawn painting. Is that possible or did I misunderstood how the algorithm works?
 
I have seen that I can manipulate the Style Loss Multiplier (**style_loss_mult**), but not sure how to change those numbers (sorry I am quite new to this subject)

I have trained on 40 portrait images, is that good or should I increase the number of images?
Should the content have a more general subject in it?

The Style image is 400x400px is that enough or should be higher in resolution? Or should it match the network size (256x256px)?

Using more similar styles in input can increase the quality of the network? 
Is it possible to blend between styles, like explained in the paper this algorithm comes from?

Any suggestion is welcome and much appreciated. I think answer to my questions could help a lot other people in the community looking for fine tunig their models

Thank you

**Comment by josefgrunig** [comment]
I have given another try with the more used StarryNight style:
![styletransfer](https://user-images.githubusercontent.com/32868530/51439940-4564a380-1cc1-11e9-84ac-9ffc7a68296e.jpg)
again here I get something different from what I am expecting. 
I am looking to achieve a result more like this one:
![1 majef5firoszp6pmtaqp_q](https://user-images.githubusercontent.com/32868530/51439947-58777380-1cc1-11e9-8d73-864f71832f29.jpeg)
Any hint or ideas?

**Comment by josefgrunig** [comment]
using `params={'style_loss_mult': [1e-2, 1e-2, 1e-2, 1e-2]}` I got a definitely more interesting result, will play around those values a little bit more.
Is it possible to get an explanation/documentation of all parameters of the style_transfer.create function?

![portrait2-5000it-256px-001sl](https://user-images.githubusercontent.com/32868530/51442332-0abc3480-1cdc-11e9-87ef-fb59ff6fc68f.png)

**Comment by tankfly2014** [comment]
HELLO.
TURI Style Transfer build image is  green/purple color.
This is a very very very very very very very very very very very bug.
haha.

**Comment by srikris** [comment]
@tankfly2014 Sorry for the trouble and the delay in fixing this issue. We are looking at this bug in #666. It's a tricky bug to fix and we haven't yet gotten to the bottom of it. We will keep you posted.

**Comment by Umity** [comment]
Waiting this to be fixed.. so frustrating that can’t use this feature on my app

**Comment by Umity** [comment]
any update on this? how could you created that demo images?

**Comment by Umity** [comment]
> @Umity We are looking into this. Can you share some of your images and results for us to better diagnose the issue.

Hi Krishna, thank you for asking. And I am really glad you guys are really looking into it.  

The results are awful. Do you think we are doing something wrong? I had around 5000 photos in my content folder, took more than a day to bake the model file and the result was bad. Here is the result image: https://imgur.com/a/PMVIBVY

There is a tutorial on web and you can see its result image in there: https://appcoda.com/coreml-turi-create/

I have a very simple question;

Are we doing something wrong? Or do you think you guys edited these photos https://apple.github.io/turicreate/docs/userguide/style_transfer/ with a different version of Turicreate???

**Comment by josefgrunig** [comment]
Hi @Umity,

I am a complete newby in the Style Transfer matter and came across the same issues. 
The main two problems in my case where the number of iterations and the style loss multipliers.
I wrote a short article on my test results [here](https://www.linkedin.com/pulse/style-transfer-neural-network-josef-grunig/); maybe it helps.

Regarding the banding issue #666 it gets less visible by raising number of iterations.
The reason I opened this thread was exactly for asking a more detailed explanations of those low level parameters that can definitely help in getting better result. 

I suggest also reading the paper this algorithm comes from [A Learned Representation For Artistic Style](https://arxiv.org/pdf/1610.07629.pdf), where those parameters are used.

**Comment by Umity** [comment]
> Hi @Umity,
> 
> I am a complete newby in the Style Transfer matter and came across the same issues.
> The main two problems in my case where the number of iterations and the style loss multipliers.
> I wrote a short article on my test results [here](https://www.linkedin.com/pulse/style-transfer-neural-network-josef-grunig/); maybe it helps.
> 
> Regarding the banding issue #666 it gets less visible by raising number of iterations.
> The reason I opened this thread was exactly for asking a more detailed explanations of those low level parameters that can definitely help in getting better result.
> 
> I suggest also reading the paper this algorithm comes from [A Learned Representation For Artistic Style](https://arxiv.org/pdf/1610.07629.pdf), where those parameters are used.

Wow great article! How can i reach you via email?

**Comment by Umity** [comment]
@josefgrunig

Wow! Great article! Thank you. How can i contact you via email?

**Comment by josefgrunig** [comment]
@Umity You can contact me from LinkedIn or: name dot surname at gmail dot com

**Comment by srikris** [comment]
@abhishekpratapa Can you share the new results based on your updated PR.
