### ISSUE TITLE
Suggested improvement to syntax of .unpack()

### ISSUE THREAD

**Issue by nicoinn** [apple/turicreate#1350]
I tend to face quite often the need to convert a list of dictionaries to an SFrame...

It's actually quite easy - just do
` tc.SFrame([dict1,dict2]).unpack("X1",column_name_prefix="")`

The first part will create a single column SFrame with a column name "X1" and the second will unpack "X1" into separate columns. The column_name_prefix="" means that I do not want any "X1" prefix anywhere.  

Now - imagine an unexperienced person looking at this line out of context --- guaranteed "WTF effect"!!!   The "X1" seems to come from nowhere!

The following would much clearer to read, and faster to write: 

` tc.SFrame([dict1,dict2]).unpack()`

The assumption there being that if an SFrame has only one column, unpack that one without prefix. Otherwise, throw an error!

I don't think that it is currently possible to use .unpack() without a column name argument --- so, such an alteration of the default behaviour should not break any code (?).

**Comment by hoytak** [comment]
That's a great request -- I like it!

**Comment by znation** [comment]
Fixed with #1456.
