### ISSUE TITLE
Turicreate model on GCP ML Cloud

### ISSUE THREAD

**Issue by mkhizeryounas** [apple/turicreate#1361]
Hi, Is there any way that I can train and host my turicreate models on GCP ML Cloud?

**Comment by TobyRoseman** [comment]
I'm not familiar with GCP ML Cloud and we haven't done any work to specifically support that. However if you can pip install packages on GCP ML Cloud, it should work. See for [Installation Instructions](https://github.com/apple/turicreate#installation) for details. Let us know if you get it working.
