### ISSUE TITLE
Size of Recommender Model

### ISSUE THREAD

**Issue by dogahe** [apple/turicreate#1400]
I am looking at ways that I can reduce the size of a recommender model I am working on. You can assume I want to train a model for recommending topics to readers. Using one dataset which has 6452 observations of (TopicID, UserID), there are 342 unique topics and 3281 unique users. The size of the model that was trained by using `tc.recommender.create` is 442 KB which is fine. 

Now I have a larger dataset with 3,549,113 observations, 2174 unique topics and 251,514 unique users, the size of the model is 32.2 MB which is really large for my application. I was wondering if you have any recommendations on what the different things that I can try are to reduce the size of the model. 

One thing I had in mind was to let say only try to make recommendations for the top topics (623 out of 2174), therefore removing all the observations for topics which are not among top 623. That resulted in 3,395,846 observations with 245,963 users and 623 topics and the size of the model becoming 28.8 MB, just a small decrease in size. 

Next thing, I am going to try is to remove all the observations by users who have only read one topic. Meaning if a user has only one row in the observations I am going to remove the data (that one row) for that user. Does this make sense to you? Would this make the model less effective? Any thoughts on this approach that I yet have to try to see how much it will reduce the size of the model?

**Comment by TobyRoseman** [comment]
@dogahe - To make sure we provide you with useful information, please provide some additional details: 

1 - Which recommender model type are you using? Is it `ItemSimilarityRecommender`?

2 - Are you concerned about the size of the output file when you call `model.save(...)` or `model.export_coreml(...)`?

**Comment by dogahe** [comment]
Hi @TobyRoseman - Yes, I believe based on the fact that data has only the two mentioned columns it picks ItemSimilarityRecommender. I am concerned about the size of the `.mlmodel` which is the output of `model.export_coreml`

**Comment by dogahe** [comment]
Even doing what I asked you if it makes sense to do only reduces the size of the model to 24.7 MB. I still would like to hear your thoughts on whether " remove all the observations by users who have only read one topic." affects the performance of recommendation? Even though for my case does not reduce the size of the model by too much. Also I would like to hear if there is anything you can suggest for me to do to reduce the size of the model?

**Comment by hoytak** [comment]
HEy @dogahe, if you go create the item similarity recommender directly (using tc.recommender.item_similarity_recommender.create), it has one additional parameter, only_top_k, which controls the size of the item similarity graph stored.  Decreasing this decreases the amount of storage required for the model but it may also decrease the accuracy.  By default it's 64, but you can probably drop that to 20 or 30 and still get decent results (check it in detail), which would cut the model size in half.

**Comment by dogahe** [comment]
@hoytak Thanks for the suggestion, however, the effect of changing `only_top_k` from default `only_top_k = 64` to `only_top_k = 4`, is to reduce the size of the model from 32.3 MB to 30.2 MB. I am still waiting for other suggestions if somebody here has any? Thanks a lot.

**Comment by hoytak** [comment]
This is weird.  I think I know what's going on, and it may be a bug.  Let me investigate.

**Comment by hoytak** [comment]
Confirmed.  This is a bug.  The export routines are not dropping the user indexing tables from the archive.  Fix in the works.
