### ISSUE TITLE
turicreate.show  bad_get error

### ISSUE THREAD

**Issue by radikal9** [apple/turicreate#141]
When I use turicreate.show to create a graph:

turicreate.show("Date", "Present")

With x=Date and y=Present ('Date' and 'Present' are columns in the spreadsheet attendance.csv) I get the following error:
Finished parsing file /Users/mobile/Attendance.csv
Parsing completed. Parsed 94 lines in 0.008757 secs.
Traceback (most recent call last):
  File "/Users/mobile/Attendance.py", line 4, in <module>
    turicreate.show("Date", "Present")
  File "/Users/mobile/anaconda/lib/python2.7/site-packages/turicreate/visualization/show.py", line 75, in show
    return tc.extensions.show(path_to_client, x, y, xlabel, ylabel, title)
  File "/Users/mobile/anaconda/lib/python2.7/site-packages/turicreate/extensions.py", line 168, in <lambda>
    return lambda *args, **kwargs: _run_toolkit_function(fn, arguments, args, kwargs)
  File "/Users/mobile/anaconda/lib/python2.7/site-packages/turicreate/extensions.py", line 157, in _run_toolkit_function
    raise _ToolkitError(ret[1])
turicreate.toolkits._main.ToolkitError: boost::bad_get: failed value get using boost::get
Adding an xlabel, ylabel and title returned the same error. 

Also, from the documentation it seems that the type of chart that will be returned is based on the number of lines in the document and type of content that is in the cell. Is there any way to add it the ability to select the graph type (obviously limited to the type of content). 

Finally, is there a way to add more than one set of data to a chart axis? For instance, in this case we have school attendance logs. I want to be able to plot the "Date" on the X axis and then on the Y axis show to factors "Present" (those who are at school)  and "Absent"

Thanks

**Comment by znation** [comment]
@radikal9 Can you upload the `attendance.csv` file in this issue, or another CSV file that reproduces this issue? I haven't seen this issue with any dataset I've tried so far.

As to your questions:

* I opened #142 to track adding an API to select plot type. Currently only the automatic selection is possible.
* I opened #143 to track allowing more than one series per axis in plots where this makes sense.

For your scenario of Absent/Present in one plot, you may be able to use a single two-column plot to represent what you want, by rearranging the data. I'm not sure what the current arrangement looks like, but assuming you have two columns like:

```
Columns:
	Date	str
	Attendance	str

Rows: 3

Data:
+----------+------------+
|   Date   | Attendance |
+----------+------------+
| 12/01/17 |   Absent   |
| 12/02/17 |  Present   |
| 12/03/17 |  Present   |
+----------+------------+
[3 rows x 2 columns]
```

You can plot this with `tc.show(sf['Date'], sf['Attendance'])`. If this isn't what you had in mind, please clarify what kind of plot you're looking for and there may be a workaround to get it without adding support for multiple series per axis. Hope that helps!

**Comment by radikal9** [comment]
Thanks @znation for the help. It won't allow me to attach a spreadsheet but here is a jpeg (it is very basic to recreate)

<img width="810" alt="screen shot 2017-12-26 at 4 39 14 pm" src="https://user-images.githubusercontent.com/33485975/34365189-844f6146-ea5b-11e7-8448-46f0ab37e82a.png">

When I run the code

import turicreate as tc
sf = tc.SFrame('/Users/name/Attendance.csv')
tc.show('Date', 'Present')

I get the error I listed above. 

When I use the code you supplied:

import turicreate as tc
sf = tc.SFrame('/Users/name/Attendance.csv')
tc.show(sf['Date'], sf['Present'])

It does open Turi Create Visualize and plot the x and y axis, place the dates and attendance but does not actually plot the content. 

<img width="582" alt="screen shot 2017-12-26 at 4 33 11 pm" src="https://user-images.githubusercontent.com/33485975/34365194-8ccfe82c-ea5b-11e7-82e8-5d68610fc4f3.png">

**Comment by znation** [comment]
Thanks @radikal9, I am keeping this issue to track `bad_get` and I opened #144 to track the box plot failing to render with this data.

**Comment by znation** [comment]
@radikal9 In the meantime you can probably work around this by using another library to generate the chart you're looking for, with the data from the SFrame. Something like this (using matplotlib below):

```python
import numpy as np
import matplotlib.pyplot as plt
ind = np.arange(len(sf))
width = 0.2
p1 = plt.bar(ind, list(sf['Present']), width, color='blue')
p2 = plt.bar(ind, list(sf['Absent']), width, color='red', bottom=list(sf['Present']))
plt.title('Attendance by Date')
plt.xticks(ind, list(sf['Date']))
plt.yticks(np.arange(0, 23, 5))
plt.legend((p1[0], p2[0]), ('Present', 'Absent'))
plt.show()
```
