### ISSUE TITLE
six dependency is too rigid

### ISSUE THREAD

**Issue by znation** [apple/turicreate#1417]
Current coremltools dependency version (as of 5.3): 2.0b1
Current coremltools version (as of this moment): 2.1

We should upgrade our dependency to coremltools 2.1 and test for compatibility.

**Comment by znation** [comment]
Note: There’s also an explicit requirement on `six==1.10.0` as well so that’ll need to be updated together. coremltools now specifies `>=1.10.0` so we should too. See https://github.com/apple/turicreate/blob/master/scripts/requirements.txt#L16

**Comment by znation** [comment]
Fixed by #1450.

**Comment by nickjong** [comment]
@TobyRoseman Can this be closed, then?

**Comment by TobyRoseman** [comment]
The `coremltools` dependency has been fixed in master. I have not looked into changing the `six`.

**Comment by znation** [comment]
Retitled to reflect the remaining work.

**Comment by TobyRoseman** [comment]
Sadly, it seems Turi Create isn't even listing `six` as a dependency in our `setup.py` despite using it directly in several places. I'll fix that.
