### ISSUE TITLE
Question: How to access/use  just want the SFrame

### ISSUE THREAD

**Issue by javadba** [apple/turicreate#1428]
I am only interested in alternatives to the pandas dataframe. Where/how can we access the (updated/improved?) SFrame *only* - and not the extra "make ML easy" mechanisms around it?

**Comment by srikris** [comment]
Making an SFrame as a separate package is a great feature request. Thanks for posting it here.

**Comment by znation** [comment]
Duplicate of #1273. Please follow that thread for more info, thanks!
