### ISSUE TITLE
How to treat duplicate data in Item Similarity Recommender

### ISSUE THREAD

**Issue by dogahe** [apple/turicreate#1433]
What's the recommended way of treating duplicate data points when I am trying to train an item_similarity_recommender? You can assume my model is for recommending topics to readers and some readers may have read the same topics multiple times and therefore the dataset contains duplicates. For example ["User1", "Topic1"], ["User1", "Topic1"], ["User1", "Topic1"], should I keep them repeated in the data or should I only keep one ["User1", "Topic1"]?

**Comment by hoytak** [comment]
Hello @dogahe, 

The item similarity recommender should handle multiple inputs, but by default duplicate entries won't have an effect on the resulting model.  If you want them to mean something, then scoring each user-item pair with something that increases with the number of hits could give you some gains.  For example, one interaction is 0.8, two is 0.9, 3 is 0.95, etc.
