### ISSUE TITLE
Box plot fails to render with a single data point per category

### ISSUE THREAD

**Issue by znation** [apple/turicreate#144]
See #141 for repro steps. The result looks like this:

<img width="582" alt="34365194-8ccfe82c-ea5b-11e7-82e8-5d68610fc4f3" src="https://user-images.githubusercontent.com/5673251/34387227-e6f17754-eafa-11e7-99d2-7075c7774995.png">

**Comment by igiloh** [comment]
I think we should produce a bar plot in this case. Especially if the X axis is in fact a string, as it is treated here.

**Comment by znation** [comment]
Fixed with #159
