### ISSUE TITLE
Add a numpy.ndarray to tc.Image converter as a util in Drawing Classifier.

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#1459]
It can potentially even be extended to Image Classifier. This should be in C++ so we can leverage the flex_image API and pass in a byte array.

**Comment by nickjong** [comment]
Wait, it looks like we do have this functionality already, see 
https://github.com/apple/turicreate/blob/3236aa1e64ec76a4f8b775432ff46ba22b983115/src/unity/python/turicreate/data_structures/sarray.py#L2413

**Comment by shantanuchhabra** [comment]
In addition, `turicreate.Image` has a hidden parameter of `_image_data` that can take in a bytearray directly. I think we can close this issue. @nickjong Thoughts?
