### ISSUE TITLE
Should I expect object detection on iPhone to be as good as using Turi Create on Mac?

### ISSUE THREAD

**Issue by dmcgloin** [apple/turicreate#148]
I've gone through the Object Detection tutorial here:

https://github.com/apple/turicreate/blob/master/userguide/object_detection/introduction.md

...and created my own inventory of images (100+ jpgs) to train to recognize a particular object. After a lot of struggling with docs, python learning (including switching between multiple Python environments), etc., I finally was able to generate several object detection predictions that I can visualize in the Turi Create visualizer.

I was very surprised that this worked at all (especially given the object I was trying to recognize).  I got several predictions with very good confidence levels.  **This is awesome stuff!!!**

However, after exporting the model to CoreML and embedding in a sample app using the same test images, I don't seem to get prediction results with the same high quality - either on the iOS Simulator or an actual iPhone X. The prediction results are OK, but definitely not as good as when run on the Mac. The prediction bounding boxes are not matching the location as well as on the Mac.

I'm using the Swift code in the 'Advanced Usage' tutorial here:

https://github.com/apple/turicreate/blob/master/userguide/object_detection/advanced-usage.md

...to calculate the "best prediction" using the non-maximum suppression example function, etc.

So, without going deep on what exactly could be wrong in my particular setup, I have some basic questions:

Should I expect similar results when run in iOS? Do I need to increase my training image set to a larger number, run more iterations, something else?

thanks in advance

Any info is appreciated.

**Comment by gustavla** [comment]
Hi @dmcgloin, thanks for trying out the object detector! The results should be consistent between Turi Create and all Core ML platforms (iOS, macOS). There could be slight numerical differences, but it would not be noticeable if you look at the bounding boxes.

One key difference is that in Core ML, you get relative coordinates, so make sure to account for that. It's also important to make sure you get the coordinate system of the view that you visualize bounding boxes in correct. To make sure, you should make sure that (0, 0) results in the upper-left corner (not lower-left, which I think might be the coordinate system of the view - if that's the case, you'll have to do 1 - y on that axis). Also make sure that (1, 1) results in the lower-right.

Let's see if that yields any issues and then take it from there.

**Comment by dmcgloin** [comment]
@gustavla Thanks very much for taking the time to respond to this inquiry.

I went back and scrutinized my rectangle calculations - but it still seems like the coordinate system and math is correct. I also tried drawing the returned rectangles outside of the app; I used Pixelmator to hand-identify the detected locations returned to the app.  The Pixelmator experiments matched what I was seeing in the CoreML app. The locations are just 5-10% off (if that makes sense); and they are not always consistently offset along some axis. In fact, sometimes one to three sides of the rectangle are pretty close, but the others are off - but not that far off.

Anyway, it also seems like the confidence values may be different as well - although it's hard to compare between Turi Create and CoreML since I don't know how to aggregate the confidence value of multiple predictions to perform the equivalent calculation that's shown in the Turi Create visualizer.

So, if you want, I can post the code and artifacts, but it would be better to do it privately if possible?

Finally, I just wanted to thank your team for putting this great work out there. I assume you guys are working on other related stuff - and it isn't your full time job to handhold us noobies.

**Comment by srikris** [comment]
@dmcgloin Did you end up getting your model deploying in your app?

**Comment by dmcgloin** [comment]
@srikris Thanks very much for following up! I updated my GitHub profile to include my email.

I did not get much further here. A combination of things were impeding progress: 1) Real life work :) 2) This issue 3) This other issue: https://github.com/apple/turicreate/issues/146 

#3 is sort of a big blocker because my app idea depended on using ARSCNView. Hopefully, this issue will get resolved soonish.

In any case, I'm happy to provide a reproducible sample with artifacts, etc. for this issue. I'll look for a request.

I guess I'm also wondering if ARKit 1.5 has any bearing on these issues?

**Comment by gustavla** [comment]
@dmcgloin Really sorry about the many issues that you've been having. #146 remains a very high priority for us, but the fix needs to go into macOS as opposed to Turi Create, so it makes the process slower.

Perhaps you could provide a Turi Create model and an image, and I can run it both inside Turi Create and using Core ML and we can look at what I get? I apologize for the slow response!

**Comment by dmcgloin** [comment]
Thanks @gustavla Can I send the model and image(s) privately? My email is in my profile.

**Comment by gustavla** [comment]
@dmcgloin Really sorry for letting this issue be unaddressed for so long. I have received the xcode project that you sent me and tried it out. It didn't seem to trigger any predictions at all. Even if I had seen predictions, I would need to calibrate my expectation by seeing some good results that you described seeing on macOS.

Your question was why are predictions different between macOS and iOS (which they should not be, so we definitely need to investigate that). To test this, did you ever try doing predictions on a set of already taken images and then compared the results? It's hard to do a perfectly fair comparison between macOS and iOS on a live app, especially since the sensors are different. That difference in sensors can also be what is causing a degradation in performance. If you want to target both macOS and iOS with a single model, I would recommend using training data that is a mix of data taken from MacBooks and iPhones.

Since this is such an old issue, please let me know if this investigation is still relevant too! I apologize again for not addressing it sooner.

**Comment by dmcgloin** [comment]
Hey @gustavla - I very much appreciate you taking the time to investigate and respond. It's been a while - and I honestly haven't had time to revisit this. But I see from one of the WWDC presentations that there are improvements in this area (I believe I saw a new API for getting the prediction bounding box - avoiding some of the intermediary calculations) - and I see your team has put out a few new releases. And it looks like 
https://github.com/apple/turicreate/issues/146 is resolved in macOS 10.14 - although I can't yet update my Mac with a beta.

In any case, this is exciting good stuff!

For me, when I get the time, I hope to start again with Xcode 10 and iOS 12 - and properly dive in again.

As such, I think it makes sense to close this issue. I apologize if I've wasted your time on this topic.

**Comment by gustavla** [comment]
@dmcgloin Definitely no wasted time! We're always happy about issues coming in. Sorry it just took me so long to get to it!

**Comment by cianiandreadev** [comment]
@andrewgleave seems that I have the same issue you had (#1016 ). 
How you solved the issue in detail? Do you have any hints for me please?

**Comment by andrewgleave** [comment]
Not really other than what I added above.

The aspect ratio of the external webcam was not the same as the ratio of the other windowed layers which was causing some skewing of the positioning. Looking at #1016 I think it would be useful to have a canonical MacOS example.

**Comment by cianiandreadev** [comment]
@andrewgleave , ok. In my case it's just about iOS (not MacOS app involved). Then probably your solution won't help. Thank you anyway.
