### ISSUE TITLE
Image with ground truth bounding box doesn't visually match the input params

### ISSUE THREAD

**Issue by amayers** [apple/turicreate#149]
I've been trying to get my setup fully working, and have now gotten everything to finally seem like it's matching up the annotations & images. However when I try to draw the bounding boxes that I am passing in as ground truth, the boxes don't match what I'd expect. I've verified that my annotations' bounding boxes are defined correctly in the JSON I'm importing and when exploring the `data` after I have added the annotation, the coordinates match what I'd expect. Every bounding box is drawn ~50% of it's width/height to the left/above the spot it should be as you can seen in the photo below. Is this something I'm doing wrong here?

<img width="1225" alt="screen shot 2017-12-30 at 8 58 47 pm" src="https://user-images.githubusercontent.com/868103/34458575-92d3da6a-eda5-11e7-91fc-ef678a3eca05.png">

```
import turicreate as tc

data = tc.image_analysis.load_images('test/image', with_path=True)
annotations = tc.SFrame.read_json('test/test.json', orient='records')
data = data.join(annotations, on={'path':'path'}, how='outer')

data.print_rows(num_rows=10, num_columns=40, max_column_width=80, max_row_width=800, output_file=None)

data['image_with_ground_truth'] = \
    tc.object_detector.util.draw_bounding_boxes(data['image'], data['annotations'])
data.explore()
```

The JSON:
```
[
  {
    "annotations" : [
      {
        "label" : "egg",
        "type" : "rectangle",
        "coordinates" : {
          "height" : 155,
          "x" : 196,
          "y" : 91,
          "width" : 203
        }
      }
    ],
    "path" : "\/Users\/amayers\/Desktop\/test\/image\/6657348_7d41427993.jpg"
  }
]
```

I've attached the JSON annotations file as well as one of the images so if you want to try this. You'd just need to change the `path` inside the JSON to match your path.
[Archive.zip](https://github.com/apple/turicreate/files/1594934/Archive.zip)

**Comment by igiloh** [comment]
Hi @amayers, thanks for the elaborate input!

Please note that the (x, y) coordinates in the annotations dictionary indicate the **center** of the object, and not the top-left corner, as indicated in the [User Guide](https://github.com/apple/turicreate/blob/master/userguide/object_detection/introduction.md#data-acquisition) and [API doc](https://apple.github.io/turicreate/docs/api/generated/turicreate.object_detector.create.html?highlight=annotations).

Looking at your example - the annotation seem to be indicating the top left corner, and not the center of the egg.
Can you please set the the annotations to indicate the center by changing all annotations' x and y coordinates to:
```
x = x + width/2
y = y + height/2
```
Then try to plot the bounding boxes again. You would probably need to recreate your model.

**Comment by amayers** [comment]
Ah, totally missed that. Seems like they shouldn't be called just `X` & `Y` then, but `centerX` & `centerY` since `X` & `Y` typically refer to the top left corner in most systems I've worked with. ¯\_(ツ)_/¯. Works great now. Thanks for the prompt response.

**Comment by srikris** [comment]
@amayers Did you end up deploying this model on your application?
