### ISSUE TITLE
Image classifier Error in python3.6

### ISSUE THREAD

**Issue by printdhruv** [apple/turicreate#1510]
`metrics = custommodel.evaluate(data)
  "/Users/dhruvkumarpatel/Desktop/ImageClassification.app/Contents/Resources/lib/python3.6/site-packages/turicreate/toolkits/image_classifier/image_classifier.py", line 802, in evaluate
evaluation_result['sorted_labels'] = hclusterSort(vectors, l2Dist)[0]['name'].split("|")
`
`
  File "/Users/dhruvkumarpatel/Desktop/ImageClassification.app/Contents/Resources/lib/python3.6/site-packages/turicreate/toolkits/image_classifier/image_classifier.py", line 731, in hclusterSort
    vecs = vectors[:]
`
`
TypeError: 'map' object is not subscriptable`

**Comment by TobyRoseman** [comment]
@abhishekpratapa - I think you should fix this one. Let's fix this for the next release.

You could just change `vectors` to `list(vector)`, but if it works, it's probably better to use `copy.copy`. Also would be great to have a unit test to cover this bug.

**Comment by printdhruv** [comment]
I am deploying a solution and can you tell me which turicreate version I should use meanwhile which doesn't have this bug?

**Comment by printdhruv** [comment]
` turicreate==5.2.1` works fine for me.

**Comment by AWOLASAP** [comment]
I ended up going into the image_classifier.py source code found in the error and turning vecs into a list with "list()" before hand and all worked. This was in turicreate 5.5.
<img width="594" alt="Edit" src="https://user-images.githubusercontent.com/36315256/57173647-1396c900-6de8-11e9-9c12-f00f8fbfd489.png">
