### ISSUE TITLE
Image should fit the frame size in Annotation UI

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#1518]
If I have a dataset with small images, I should be able to a larger version of my images to make it easier to annotate. I think it's worth maximizing the size while preserving the aspect ratio.

<img width="932" alt="image" src="https://user-images.githubusercontent.com/14062641/53987443-dbb82180-40d5-11e9-9ac6-0d078f2c8a12.png">

**Comment by abhishekpratapa** [comment]
fixed
