### ISSUE TITLE
Cursor should be in text field when user adds a new label

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#1519]
When I add a new label, the cursor should automatically be in the "Annotation Label" text field to make the process of annotation faster for the user.

<img width="932" alt="image" src="https://user-images.githubusercontent.com/14062641/53987509-16ba5500-40d6-11e9-954a-dc0d5515a4bd.png">

**Comment by abhishekpratapa** [comment]
Fixed
