### ISSUE TITLE
Labels created in Annotation UI with 0 assignments are lost on exiting the UI

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#1522]
We should support this use case for people who add all their labels before they start annotating.

For example, I added the following labels while annotating:
<img width="932" alt="image" src="https://user-images.githubusercontent.com/14062641/53988498-73b70a80-40d8-11e9-9851-03434bc12429.png">

I closed it and annotated again on the SFrame that I got as output from `tc.image_classifier.annotate` and saw the following:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/14062641/53988543-90ebd900-40d8-11e9-8e55-6a5cb263acd9.png">

**Comment by abhishekpratapa** [comment]
Non issue
