### ISSUE TITLE
Typing in + or - anywhere in the UI zooms in/out

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#1524]
macOS 10.14
Python 3.6

<img width="932" alt="image" src="https://user-images.githubusercontent.com/14062641/53988627-cbee0c80-40d8-11e9-87c3-7c7478dc6637.png">

This is an unexpected experience since my annotation labels could have + or - in them and that would trigger this as well.

**Comment by abhishekpratapa** [comment]
Cannot repro on given Machine.
