### ISSUE TITLE
Capitalisation vs lowercase labels

### ISSUE THREAD

**Issue by fareeha** [apple/turicreate#1528]
Interestingly the Annotation UI creates two different labels for the same label. For example, "Shoes" and "shoes" are treated as two different labels. It may be worth brainstorming if we would like to offer this feature or like to collapse the same words into one lowercase label.

**Comment by abhishekpratapa** [comment]
I think we shouldn't modify the user input. We should keep it as is. If the label is physically different then I believe it needs to remain that way. Closing for now! Re-Open if you feel otherwise!
