### ISSUE TITLE
Red scrollbar appears when image is too big.

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#1534]
For images that are too big to fit (I tried 1024x1024 grayscale), a red scrollbar appears. I think the scrollbar color and size should align with scrollbars in other TC visualizations -- maybe a classic gray scrollbar would work. 

<img width="932" alt="image" src="https://user-images.githubusercontent.com/14062641/53991275-12df0080-40df-11e9-85eb-1026c902b1eb.png">

**Comment by znation** [comment]
<img width="932" alt="screen shot 2019-03-07 at 2 12 07 pm" src="https://user-images.githubusercontent.com/5673251/53993004-03fa4d00-40e3-11e9-863d-9b7eb33ddba1.png">

Repros on non-annotation UI as well.
