### ISSUE TITLE
Double Quotes in labels during Annotation

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#1539]
Adding double quotes in the labels while annotating makes the label look like “label" when I would expect it to be like "label".

See:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/14062641/53992749-7c144300-40e2-11e9-963e-40e9c2b0beb9.png">
and 
<img width="932" alt="image" src="https://user-images.githubusercontent.com/14062641/53992775-8c2c2280-40e2-11e9-877d-a44ad464ef35.png">

**Comment by abhishekpratapa** [comment]
This is actually an autocorrect issue! Note, the label below actually has the correct quotations!

<img width="1121" alt="Screen Shot 2019-05-03 at 11 41 43 AM" src="https://user-images.githubusercontent.com/4616962/57158534-8aa47100-6d98-11e9-9c17-850b487ae43f.png">

The label at first autocorrects to the secondary quote.

<img width="1121" alt="Screen Shot 2019-05-03 at 11 41 56 AM" src="https://user-images.githubusercontent.com/4616962/57158587-a445b880-6d98-11e9-8eb8-487f521226d1.png">

But the user can actually go back and recorrect them!

<img width="1121" alt="Screen Shot 2019-05-03 at 11 42 03 AM" src="https://user-images.githubusercontent.com/4616962/57158630-bc1d3c80-6d98-11e9-9722-f9e485fe1fa6.png">

Good luck! Closing the issue for now!
