### ISSUE TITLE
Unable to run c++ unitests

### ISSUE THREAD

**Issue by mordoron** [apple/turicreate#154]
After installing and building, per the build.md file. Running:
```
cd debug/test
make
ctest 
```

Yields:
*********************************
No test configuration file found!
*********************************
Usage

  ctest [options]

running ```ctest .```
Yields:
Test project /Users/mordoron/GitHub/turicreate/debug/test
No tests were found!!!

Details:
MacOS High Sierra
version 10.13.2

**Comment by TobyRoseman** [comment]
@mordoron - thanks for reporting this issue. I've put up a pull request which fixes this issue for me. It would be helpful if you could verify the fix too.
