### ISSUE TITLE
Integer labels still create annotations with type str

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#1540]
The Image Classifier can take both Integer and String labels, so we should make the Annotation tool support that as well. If I start with an SFrame with only images to annotate, the dtype of the annotations is always assumed to be string.

Keep in mind that integer labels could be negative as well.

<img width="828" alt="image" src="https://user-images.githubusercontent.com/14062641/53993069-360baf00-40e3-11e9-8917-531a208908db.png">

**Comment by abhishekpratapa** [comment]
fixed with
