### ISSUE TITLE
Warning pops up even when I assign the output of the annotate function to a variable

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#1543]
I think the following warning should only appear if I don't assign the output of the annotate function to a variable? I could be convinced otherwise though.

```
*** WARNING: If you don't assign the output of the annotate function
                     to a variable all annotations are going to be lost.
                     To recover the last annotated SFrame call:

        `tc.image_classifier.recover_annotation()`
```

**Comment by znation** [comment]
@shantanuchhabra From a UX perspective I agree. But I'm not sure whether it's possible to do this -- do you know of a way?

**Comment by abhishekpratapa** [comment]
I've extensively searched around for a solution. Haven't found a solution as of yet. Closing for now. If you have any suggestions on how this could be done, please Re-Open this issue!
