### ISSUE TITLE
Banding effect on grayscale images in annotation and evaluation

### ISSUE THREAD

**Issue by znation** [apple/turicreate#1545]
See screenshot. The image doesn't quite display properly in the UI. The same image is positioned above in Preview for comparison.

**Comment by znation** [comment]
<img width="819" alt="screen shot 2019-03-07 at 2 45 48 pm" src="https://user-images.githubusercontent.com/5673251/53994867-45d9c200-40e8-11e9-88b3-fd1f9e5185f2.png">

**Comment by znation** [comment]
Same for evaluation:
<img width="932" alt="screen shot 2019-03-07 at 9 37 02 pm" src="https://user-images.githubusercontent.com/5673251/54009836-39be2680-4121-11e9-8786-d30445fb60d9.png">

**Comment by znation** [comment]
This also affects table view (`sf.explore()`).

<img width="932" alt="Screen Shot 2019-04-18 at 12 42 33 PM" src="https://user-images.githubusercontent.com/5673251/56386741-7b89c480-61d7-11e9-8448-399afc7da070.png">

**Comment by abhishekpratapa** [comment]
I'm unable to repro this. Do you have an SFrame to repro this?

**Comment by znation** [comment]
@abhishekpratapa I can't find the dataset I used to repro it originally, and none of the datasets I have now can repro it. I think it may have been a weird corner case, and/or an underlying issue with the data. Without the repro I don't think there is much we can do. Let's close this issue for now, and reopen if it comes up again.
