### ISSUE TITLE
gl_sframe::apply leads to an invalid free() on Linux

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#1560]
For an example of a failed build, see https://travis-ci.com/apple/turicreate/jobs/182839529

I was also able to repro this on a Linux machine running Ubuntu 18.04.2.

Repro steps:

1. In `src/unity/toolkits/drawing_classifier/data_preparation.cpp`, replace the following code snippet in the `_drawing_classifier_prepare_data` function:

```c++
for (int row_number = 0; row_number < (int)data.size(); row_number++) {
    const flexible_type &strokes = data[feature][row_number];
    flex_list current_stroke_based_drawing = strokes.to<flex_list>();
    bitmaps.push_back(
        convert_stroke_based_drawing_to_bitmap(
            current_stroke_based_drawing, row_number));
}
gl_sarray bitmaps_sarray(bitmaps);
gl_sframe converted_sframe = gl_sframe(data);
converted_sframe[feature] = bitmaps_sarray;
converted_sframe.materialize();
return converted_sframe;
```

with the following code snippet:

```c++    
gl_sframe selected_sframe = data.select_columns({feature});
selected_sframe = selected_sframe.add_row_number();
gl_sarray bitmaps_sarray = selected_sframe.apply([](
    const sframe_rows::row& sframe_row) {
    const flexible_type &strokes = sframe_row[0];
    int row_number = sframe_row[1];
    flex_list current_stroke_based_drawing = strokes.to<flex_list>();
    flex_image current_bitmap = convert_stroke_based_drawing_to_bitmap(
        current_stroke_based_drawing, row_number);
    return current_bitmap;
}, flex_type_enum::IMAGE);

gl_sframe converted_sframe = gl_sframe(data);
converted_sframe.replace_add_column(bitmaps_sarray, feature);
    
converted_sframe.materialize();
return converted_sframe;
```

2. Next, build Turi Create from source. 

3. Activate the virtual environment used for the build, and run the following Python script:
```python
import turicreate as tc
sf = tc.SFrame({"drawing": [ [[{"x":1,"y":1},{"x":2,"y":2}], [{"x":5,"y":5},{"x":10,"y":10}]] ], "label": [1]})
model = tc.drawing_classifier.create(sf, feature="drawing", target="label", num_epochs=1)
```

**Comment by ylow** [comment]
The code in turicreate/src/unity/toolkits/drawing_classifier/data_preparation.cpp has a lot of inefficiences. Most functions ought to take const ref instead of copy. For instance
```
flex_list simplify_drawing(flex_list raw_drawing, int row_number);
flex_nd_vec paint_stroke(flex_nd_vec bitmap ...)
```
should be 
```
flex_list simplify_drawing(const flex_list& raw_drawing, int row_number) 
flex_nd_vec paint_stroke(const flex_nd_vec& bitmap ...)
```

And so on.

My first suspicion is an out of bounds access.

Can we begin by adding some bounds check asserts to all the code here?
It will also be helpful to have  C++ tests for these code paths too.

**Comment by ylow** [comment]
Well... From a quick code review I see the bug immediately.
Line 312 in data_preparation.cpp returns a pointer to the stack.

**Comment by ylow** [comment]
Nope I was wrong here. flex_image does copy.

**Comment by hoytak** [comment]
Let's get https://github.com/apple/turicreate/pull/1607 done before we look at this more.  I'm very skeptical this is an issue with lambda apply.

**Comment by TobyRoseman** [comment]
#1607 has been merged long ago. Is this issue still relevant?

**Comment by TobyRoseman** [comment]
Sounds like this is no longer relevant. So I'm going to close this issue. If anyone thinks it's still relevant, feel free to reopen.
