### ISSUE TITLE
Installing turicreate on MacBook Pro with anaconda with python 3.7

### ISSUE THREAD

**Issue by lalitmach22** [apple/turicreate#1580]
Hi,
I have MacBook Pro with Mojave and latest anaconda which has python3.7.
I have been trying to install turicreate by terminal method using pip install turicreate and by using absolute path of who file, however error during both.
can someone help me in resolving this issue?

Thanks

**Comment by TobyRoseman** [comment]
Turi Create does not yet support Python 3.7. We're still waiting for some of our dependencies to support Python 3.7.

Closing this issue as a dup of #788.

**Comment by guyandtheworld** [comment]
@TobyRoseman Hey, it's been three months. It's still not supported?

**Comment by TobyRoseman** [comment]
@guyandtheworld - It's currently under active development. I even have [a work in progress pull request](https://github.com/apple/turicreate/pull/2079) up to support Python 3.7. We're having some issues with a couple of our dependencies. Once those are resolved, we'll release on PyPI. Subscribe to #788 for updates on Python 3.7 support.
