### ISSUE TITLE
Readme: Wrong links for Sound Classification and Drawing Classification

### ISSUE THREAD

**Issue by frogg** [apple/turicreate#1585]
These two links from the readme file lead to a "Page Not Found":

https://apple.github.io/turicreate/docs/userguide/sound_classifier
https://apple.github.io/turicreate/docs/userguide/drawing_classifier

**Comment by TobyRoseman** [comment]
Thanks for letting us know about this the issue. We updated our README a bit prematurely. Those toolkits are in `master` but they have not yet been released on PyPI. We will be releasing them soon.

If you're interest you can find the documents here:
[Sound Classifier](
https://github.com/apple/turicreate/tree/master/userguide/sound_classifier)
[Drawing Classifier](https://github.com/apple/turicreate/tree/master/userguide/drawing_classifier)

For now, I've removed those links. We'll add them back once we launch and those sections of the user guide are live.

I'll leave this issue open to make sure we add these links back once they are working.

**Comment by frogg** [comment]
Perfect, thanks for the explanation Toby!

**Comment by frogg** [comment]
Thanks, Toby!
