### ISSUE TITLE
Drawing classifier pretrained_model_url=None API change request

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#1614]
Drawing classifier uses pretrained_model_url as 

We should consider renaming the option to warm_start:
- 'auto' as the default
- string i.e a name of the model (e.g. quick-draw-1000) to refer to specific versions 
- URLs should be reserved for testing and extra customization.

**Comment by srikris** [comment]
@TobyRoseman Sound classifier should follow something similar too.

**Comment by shantanuchhabra** [comment]
Closed by #1610
