### ISSUE TITLE
Sound Classifier need "Advanced Usage" user guide page

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#1639]
With the 5.5 release the sounds classifier will have:
* A way of reusing deep feature across training (#1601)
* A way to control the custom neural network (#1477). Two layers of 100 units each will continue to be the default.

We need an advanced section of the user guide which explains each of these features in more detail and gives example code.

**Comment by coolioxlr** [comment]
+1

**Comment by TobyRoseman** [comment]
Done by #1722
