### ISSUE TITLE
auto mirroring

### ISSUE THREAD

**Issue by romanoss** [apple/turicreate#1653]
Hi,
when working on object detection with real world data, a feature witch mirrors images and annotations automatically would be real useful as it doubles the amount of input information without a lot of effort for the user and you know that data preparation is the most effort.
Please think about it.
kind regards
Roman

**Comment by shantanuchhabra** [comment]
Hi @romanoss ,

Just to make sure we understand your use case, do you mean something that visualizes the annotations on the images?

Thanks,
Shantanu

**Comment by romanoss** [comment]
Sorry for being not exact.
No, I mean an automatism which eg duplicates the training images and annotations automatically before training. Imaging when u train the detection of animals (cats). A mirrored image has for sure the same classification and is a very likely version of reality. Annotating large image training sets is painfully.
A simple flag like mirror='true' which adds a mirrored duplicate (with the mirrored annotation info) to the training data in object_detector.create() would be really helpful and should be easy to implement and goes well with the principles of turicreate (being comfortable) as I understand.
Thanks
Roman

**Comment by nickjong** [comment]
The object detection toolkit performs data augmentation automatically, and one of the augmentations is that with probability 0.5, each image is flipped horizontally. (There’s currently no way to disable this augmentation in the Python API, but we may expose augmentation options in general at a later date.)
