### ISSUE TITLE
Image Classification or Object detection for counting objects in an image

### ISSUE THREAD

**Issue by schmidarnold** [apple/turicreate#1656]
I would like count objects in an image. The position of the image does no matter. I think I have to use the object detection process with the coordinates of the objects as described in the doku, using sgframes. I am right or there exists a simpler method to count objects in an image, for example  balls in an image. 
Thanks
Arnold

**Comment by TobyRoseman** [comment]
@schmidarnold - Sounds like you need to use object detection, not image classification. Object detection will tell you where objects are located in an image. Image classification just assigns the overall image to a class.

For more information about object detection, take a look at the [object detection section of our user guide](https://apple.github.io/turicreate/docs/userguide/object_detection/).

**Comment by schmidarnold** [comment]
Thank you for your quick response. Perhaps you know if I can use existing
datasets like coco (common objects in context), so I could save me the work
to make photos of 100 of objects and create masks for the images. If yes,
perhaps you can give me the link where I can find further information how i
can use this images in turicreate to generate a model.
Thanks a lot and greets from Italy
Arnold

Am Fr., 22. März 2019 um 17:40 Uhr schrieb Toby Roseman <
notifications@github.com>:

**Comment by nickjong** [comment]
Yes, it should be possible to prepare the COCO dataset for use in our object detection toolkit. But it might help to understand more what you’re trying to do. For example, object detectors can identify specific classes of objects (as provided in the training data). Are you trying to train something more general, e.g. that can detect the presence of “arbitrary objects”?

Just to be clear, you could for example train an object detector to detect soccer balls. Then you could use that detector to find soccer balls in an arbitrary image, and thus find how many soccer balls. But it might not generalize to other kinds of balls or other objects.

**Comment by schmidarnold** [comment]
Thanks, I would like to count apples on a tree. Therefore for me its not
important the position, but only the number of visible apples on the tree.
I saw that in the coco dataset there are a lot of apples, also with images
where the apples are hanging on the tree. But if I am right, I have to
prepare the images for turicreate. I mean for every image I have to create
the masks or the rectangles around the apples. Can you tell me please if
this is right.
Thank all of you for your help
Arnold

Am Sa., 23. März 2019 um 21:17 Uhr schrieb Nick Jong <
notifications@github.com>:

**Comment by nickjong** [comment]
If I'm not mistaken, the COCO dataset includes annotations, so you would have to convert those annotations into the format accepted by the toolkit. I'm honestly not familiar with the particulars of how those annotations are stored, but you may find it helpful to look at the example we have for converting from another image segmentation dataset: https://apple.github.io/turicreate/docs/userguide/object_detection/data-preparation.html

Upon a cursory inspection, note that many of the examples for apples that I saw (via the "explore" functionality on the COCO website) includes sliced apples, and none were for apples hanging in trees. You might actually get better results just by finding a way to annotate some sample images from your intended application

**Comment by schmidarnold** [comment]
Thank you Nick, I will try to use my images.

Best regards from Italy
Arnold

Am Mo., 25. März 2019 um 23:43 Uhr schrieb Nick Jong <
notifications@github.com>:
