### ISSUE TITLE
Drawing classifier is missing from the API docs

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#1658]
The Drawing classifier is missing from the generated API docs. It needs to be added to the sphinx file.

**Comment by tcarson66** [comment]
THIS IS TRACEY NICHOLAS CARSON 
MY ESTRANGED HUSBAND AND HIS GIRLFRIEND AMY IRENE MAY HAVE TAKEN OVER MY ACCOUNTS.  PLEASE  BLOCK THEM FROM USING MY  EMAIL ACCOUNT AND ALL MY  MICROSOFT ACCOUNTS.  IF YOU HAVE ANY QUESTIONS PLEASE CONTACT ME AT THIS NUMBER 
4349415150
THEY HAVE ACCESS TO ALL MY ACCOUNTS PLEASE DON'T SEND ANYTHING TO ANY OF MY  ACCOUNTS 

tracey nicholas 

On Sunday, March 24, 2019 Krishna Sridhar <reply@reply.github.com> wrote:

The Drawing classifier is missing from the generated API docs. It needs to be added to the sphinx file.

**Comment by shantanuchhabra** [comment]
I believe this was fixed by #1650

**Comment by srikris** [comment]
We need to update the API docs then.
