### ISSUE TITLE
Allow build_python_wheel.sh --debug / remove it and keep scripts/make_wheel.sh

### ISSUE THREAD

**Issue by guy4261** [apple/turicreate#1661]
`built_python_wheel.sh` seems to support both `--release` and `--debug`:

```bash
[~/Documents/turicreate] (master)$ ./build_python_wheel.sh --help
Configures and builds a specified target.
...
  --release                        Build in release mode.
  --debug                          Build in debug mode (default).
```

But in practice has `release` [hard coded into it](https://github.com/apple/turicreate/blob/master/build_python_wheel.sh#L48).

Seems like `scripts/make_wheel.sh` does support it; so it might be less confusing to leave only one of them.

**Comment by TobyRoseman** [comment]
I think we should probably just remove the `built_python_wheel.sh` script.
