### ISSUE TITLE
Issue with resent-50 image classifier

### ISSUE THREAD

**Issue by yousifKashef** [apple/turicreate#1668]
I've been having trouble training an resent 50 model on both my computers (2015 iMac running latest Mojave and 2017 MacBook Air running High Sierra). I kept getting this error:

[14:08:26] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[14:08:26] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    model = tc.image_classifier.create(train_data, target='label', model='resnet-50')
  File "/anaconda2/envs/venv/lib/python2.7/site-packages/turicreate/toolkits/image_classifier/image_classifier.py", line 255, in create
    feature_extractor = _image_feature_extractor._create_feature_extractor(model)
  File "/anaconda2/envs/venv/lib/python2.7/site-packages/turicreate/toolkits/_image_feature_extractor.py", line 32, in _create_feature_extractor
    mxnetResNet = _pre_trained_models.ResNetImageClassifier()
  File "/anaconda2/envs/venv/lib/python2.7/site-packages/turicreate/toolkits/_pre_trained_models.py", line 111, in __init__
    self.mxmodel = _mx.model.load_checkpoint(_os.path.join(path, self.name), epoch)
  File "/anaconda2/envs/venv/lib/python2.7/site-packages/mxnet/model.py", line 421, in load_checkpoint
    save_dict = nd.load('%s-%04d.params' % (prefix, epoch))
  File "/anaconda2/envs/venv/lib/python2.7/site-packages/mxnet/ndarray/utils.py", line 175, in load
    ctypes.byref(names)))
  File "/anaconda2/envs/venv/lib/python2.7/site-packages/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:08:26] src/ndarray/ndarray.cc:1114: Check failed: fi->Read(data) Invalid NDArray file format

Stack trace returned 7 entries:
[bt] (0) 0   libmxnet.so                         0x0000000d17d8f7cf libmxnet.so + 59343
[bt] (1) 1   libmxnet.so                         0x0000000d17d8f56f libmxnet.so + 58735
[bt] (2) 2   libmxnet.so                         0x0000000d17d8ee79 libmxnet.so + 56953
[bt] (3) 3   libmxnet.so                         0x0000000d18e748e7 MXNDListFree + 1330215
[bt] (4) 4   libmxnet.so                         0x0000000d18d00201 MXNDArrayLoad + 241
[bt] (5) 5   libffi.6.dylib                      0x00000001019ce884 ffi_call_unix64 + 76
[bt] (6) 6   ???                                 0x00007ffeef4e4060 0x0 + 140732913303648

I initially thought that this bug was related to my python distribution or data, so I moved to an Anaconda Virtual environment and used the images from the cats and dogs dataset you guys provided. I still got this exact error message on both computers.

It only worked when I specified in my train.py scripts that it should use squeezenet_v1.1. Here's my train script:

import turicreate as tc

# Np GPU. Only CPU
tc.config.set_num_gpus(0)
print('GPU turned off. Using CPU')

# Load the data
data =  tc.SFrame('images.sframe')

# Make a train-test split
train_data, test_data = data.random_split(0.8)

# Use the CPU
tc.config.set_num_gpus(0)

# Create the model
model = tc.image_classifier.create(train_data, target='label', model='squeezenet_v1.1')

# Save predictions to an SArray
predictions = model.predict(test_data)

# Evaluate the model and print the results
metrics = model.evaluate(test_data)
print(metrics['accuracy'])

# Save the model for later use in Turi Create
model.save('mymodel.model')

# Export for use in Core ML
model.export_coreml('MyCustomImageClassifier.mlmodel')

What do you recommend I do to get around this problem?

**Comment by TobyRoseman** [comment]
It looks like MXNet can not open the downloaded model. What version of MXNet are you using? This can be determined by running `pip freeze | grep mxnet`.

**Comment by yousifKashef** [comment]
mxnet==1.1.0.post0

**Comment by TobyRoseman** [comment]
I am not able to reproduce this issue using `mxnet==1.1.0.post0` on either Mojave or High Sierra.

This issue is probably related to #1086.

**Comment by nickjong** [comment]
Are you still encountering this error? If so, please feel free to reopen!
