### ISSUE TITLE
Configure still checks for OpenMP; resulting Linux builds require it

### ISSUE THREAD

**Issue by znation** [apple/turicreate#1680]
There is a legacy dependency on OpenMP, which ./configure & cmake still check for. As a result, we end up with a dynamic link dependency on Linux for `libgomp1`, if it was present at build time, even though we don't seem to be using it.

We should remove the build time checks and dynamic linking.

**Comment by znation** [comment]
Seems the check and the requirement are coming from two different places (unrelated):

* CMakeLists.txt prints out that it's checking, but doesn't actually check for or link against OpenMP.
* At runtime, `import mxnet` on Linux depends on OpenMP, and we depend on mxnet.

**Comment by TobyRoseman** [comment]
@znation - It looks like the erroneous CMakeList.txt print statements has been removed; at least I can't find it. Given that we no longer depend on mxnet, can this issue be closed?
