### ISSUE TITLE
Class neuralnet_classifier does not exist

### ISSUE THREAD

**Issue by ymachupicchuy** [apple/turicreate#1684]
Hello, 

I can't save or load a model with turicreate and get the following error

> RuntimeError: Unable to load model from /Users/Picchu/Desktop/Test/proto/ai/imagenet: Class neuralnet_classifier does not exist.

**Saving**

```
import graphlab as gl
images = gl.image_analysis.load_images('img/', "auto", with_path=True, recursive=True)
images['image'] = gl.image_analysis.resize(images['image'], 256, 256, 3, decode=True)
deep_learning_model = gl.load_model('http://s3.amazonaws.com/GraphLab-Datasets/deeplearning/imagenet_model_iter45')
if (deep_learning_model):
    images['deep_features'] = deep_learning_model.extract_features(images)
    deep_learning_model.save('imagenet')
```

**Loading**
```
> import turicreate as tc
> deep_learning_model = tc.load_model('imagenet')
> image_train = gl.SFrame('training_data_extractedSframe')
```

What the problem?

Python Version: 2.7.11
PIP: 19.0.3
MAC OS X Mojave

**Comment by TobyRoseman** [comment]
Turi Create does not have a Neural Net work classifier. So you can't load that type of model with Turi Create.

It looks like you are trying to classify images. You should use the [image classifier](https://apple.github.io/turicreate/docs/userguide/image_classifier/).
