### ISSUE TITLE
Item Similarity Models with Different Sizes return different recommendations

### ISSUE THREAD

**Issue by dogahe** [apple/turicreate#1686]
I am working on a recommendation system using item similarity recommendation. I am experimenting with different model sizes and therefore I am trying the following lines of code for two different models:
`model1 = tc.recommender.item_similarity_recommender.create(data, user_id='UserID', item_id='TopicID')`, and
`model2 = tc.recommender.item_similarity_recommender.create(data, user_id='UserID', item_id='TopicID', only_top_k = 20)`.

Now when I try the two models in the task of recommendation, I was expecting that at least for the top 20 results (`only_top_k = 20`), the two models should recommend me the same items with the exact same order. But I am seeing that the following lines of code return me recommendations that are an item or two off in the top 20 recommendations. Is that expected? If so, how do you explain the discrepancy?
`r1 = model1.recommend_from_interactions(['topic1'], 100)`,
`r2 = model2.recommend_from_interactions(['topic1'], 100)`

I can provide more details of discrepancies if you tell me that they should match up.

**Comment by hoytak** [comment]
The only_top_k is an internal property of the model and controls how many similar items are held for each item in the lookup tables.  The recommendations are an aggregation of these similar items, so often the items that are in the top k recommendations in the end are not actually in the top k for the individual items.  Thus this basically controls how approximate the model is -- the full model would use the number of items in this case, but that's both huge and overkill in practice.
