### ISSUE TITLE
load_audio(...) should always glob path input

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#1688]
If you are in a directory with wav files, `load_audio('.')` will correctly load the audio files. However doing `load_audio('./*')` will not load any of the audio files.

**Comment by nickjong** [comment]
What does `load_images` do with file globs?

**Comment by TobyRoseman** [comment]
Surprisingly (at least to me) `load_image` doesn't seem to support file globs at all. For consistency `load_audio` and `load_images` should behave the same. Does anyone have a strong opinion about if we should support file globs or not in `load_image` and `load_audio`?

**Comment by nickjong** [comment]
Well, file globs, like `~`, aren't a file system thing, they're a shell thing. As such, they're not very portable. In general, our C++ APIs don't support these things. For `~`, we've manually inserted the conversion at the Python/C boundary, IIRC.

So we should try to be consistent with how the rest of the package uses these things, really. @hoytak Do you have additional context? (Corrections on my understanding above?)
