### ISSUE TITLE
[ranking_factorization_recommender] - Manually calculating prediction scores

### ISSUE THREAD

**Issue by benjaminbraunberkeley** [apple/turicreate#1691]
Hi,

I am contacting you because I am trying to manually calculate prediction scores, instead of re-using the predict function. But so far I get different scores than the ones given by the predict function.

I am training a ranking_factorization_recommender model with item features and observation features. There is no ‘target’ column. So the model is trying to predict the (user, item) pairs that happened (where the user bought the item).

For simplicity, let’s say here that there is only one feature, and it is binary (1 or 0). Let’s call it f.

Let’s say I want to make a prediction for user_a and item_1. The user_a is positive for the feature f: f_a = 1. Also, we know that the user has previously bought the item item_0.

Let’s call:

- Ua the latent vector for user_a
- w_a the weight term for user_a

- I_1 the latent vector for item_1  
- w_1 the weight term for item_1

- I_0 the latent vector for item_0 
- w_0 the weight term for item_0

- F the latent vector for the feature f
- w_f the weight term for the feature f

- mu the global bias term

The formula I am using is: 

z  = mu + w_a + w_1 + w_0 + 1* w_f   + np.dot(Ua.T,  I_1 + I_0 + F) + np.dot(I_1.T,   I_0 + F)+np.dot(I_0.T,  F)

So in order to get z, I sum the global bias, the different weight terms (the linear_terms given by the model.coefficients), and then I add the cross product of the latent factors (also from model.coefficients).

And then I compute the score by doing: score = sigmoid(z) = 1/ (1 + exp (-z))

However, I am getting different scores than the ones given by the predict() function… Is there something I am forgetting here? Or am I adding something extra? 

Thanks a lot in advance!

**Comment by hoytak** [comment]
Hello @benjaminbraunberkeley, 

Two things that may be helpful.  First, by default only the linear terms (and not full factors) on the additional side data are used by default in the model; passing in side_data_factorization=True causes the full factors to be trained. 

Also, with your formula, note that the F is multiplied by f (1 in your formula). 

So, assuming that you have all these correct, I'm not exactly sure what you have wrong, but there may be a factor of 2 or 0.5 on your products that isn't accounted for in your formula.   I'm not sure.  The formula used to calculate the predicted value is in the code starting at https://github.com/apple/turicreate/blob/86b724ae78469d472099cdee178ecbbbd28470b8/src/unity/toolkits/factorization/factorization_model_sgd_interface.hpp#L792.   fx is your z.  It's then translated through the sigmoid in line https://github.com/apple/turicreate/blob/86b724ae78469d472099cdee178ecbbbd28470b8/src/unity/toolkits/factorization/loss_model_profiles.hpp#L94, which you have correct. .

**Comment by hoytak** [comment]
Ah --  I think your f factor, if given as numeric, may be normalized across all values in that column.   I.e. it is actually set to be mean 0, std dev 1 across all values of f.

**Comment by benjaminbraunberkeley** [comment]
Thank you very much for your answer @hoytak! Very helpful :)

I was retrying just now by using the same formula with a normalized value for f; but I still couldn't get to the same score than the predict function.

I'm reading the code you directed me to. I'm wondering how the matrix 'x' is defined here. Does each row take into account the past items used by the user? 

Also, can it be that the normalization happens also for categorical variables (which values are only 0 and 1)? In this case, there would be many more multiplications in the sum, as all of the xis would be non zero. 

Thanks very much again

**Comment by hoytak** [comment]
Hey @benjaminbraunberkeley, 

Ah, diving in a bit more here.  x in there is essentially a sparse vector containing a flattened and vectorized version of the raw data.  Each user, item, and side variable category and numerical column is assigned a unique index.  Categorical variables have a 1 in the appropriate index when that category is present..

The normalization is mainly for numerical stability -- we did a lot of experiments to get to this -- and it's defined in
https://github.com/apple/turicreate/blob/a5e04b8151d8ea73bff968c3bebb3f835d0ef801/src/unity/toolkits/factorization/factorization_model.cpp#L47.  Looking at it -- the truncation of the std dev at 1 is something I forgot; hopefully that completes the picture. Normalization is not done for categorical variables.

**Comment by benjaminbraunberkeley** [comment]
Hello @hoytak Thanks very much for your answer! Super helpful :)

**Comment by hoytak** [comment]
You're welcome!  Glad to help.  Please reopen if you have more questions.
