### ISSUE TITLE
Precision Recall evaluation for recommendation model returns 0 for all cutoffs

### ISSUE THREAD

**Issue by ubuntudroid** [apple/turicreate#170]
I've trained a `ranking_factorization_recommender` using a CSV looking like this:

```
user_id,title
AxpA079gzBgiuKRDF8QEg22ZRgX2,The Simpsons
wIwyixUC19dlq546sjBkHPwpJh23,Game of Thrones
AxpA079gzBgiuKRDF8QEg22ZRgX2,Alf
...
```

My code looks like this:

```python
training_data, validation_data = tc.recommender.util.random_split_by_user(interactions, user_id='user_id', item_id='title', max_num_users=None)

model = tc.ranking_factorization_recommender.create(interactions, user_id='user_id', item_id='title')
model.evaluate(validation_data)
```

Evaluation gives me this result:
```
Precision and recall summary statistics by cutoff
+--------+----------------+-------------+
| cutoff | mean_precision | mean_recall |
+--------+----------------+-------------+
|   1    |      0.0       |     0.0     |
|   2    |      0.0       |     0.0     |
|   3    |      0.0       |     0.0     |
|   4    |      0.0       |     0.0     |
|   5    |      0.0       |     0.0     |
|   6    |      0.0       |     0.0     |
|   7    |      0.0       |     0.0     |
|   8    |      0.0       |     0.0     |
|   9    |      0.0       |     0.0     |
|   10   |      0.0       |     0.0     |
+--------+----------------+-------------+
[10 rows x 3 columns]
```

And when I try to recommend broadcasts for a new user for whom I have some interactions it always returns the same recommendations, no matter which interactions I define. They only change if the interaction contains items which are usually in the resulting list. Then these items are omitted (which is correct) and a few new ones are added at the bottom.

```python
user_interactions = tc.SFrame({'user_id':['new'], 'title':['The Big Bang Theory']})
results = model.recommend_from_interactions(user_interactions)
```

What am I doing wrong here? Shouldn't I receive different recommendations based on the given interactions?

**Comment by hoytak** [comment]
It appears to be that you are creating with `interactions`, which includes the validation_data.  Create the model with training_data and you will likely see different results. 

That said, this model is a bit tricky to use, and you will need to play around with the parameters to get a good model, particularly num_factors and num_iterations.   Generally, the item_similarity model is easier to use for this type of data.

**Comment by ubuntudroid** [comment]
Ah, I must have been deep asleep not to use `training_data` when doing the generation. After doing that the table looked like this - much better:

```
+--------+-----------------+-----------------+
| cutoff |  mean_precision |   mean_recall   |
+--------+-----------------+-----------------+
|   1    | 0.0255599396542 | 0.0121762334322 |
|   2    | 0.0216577695254 | 0.0195344648834 |
|   3    | 0.0191191830103 | 0.0245451548075 |
|   4    | 0.0174364628061 | 0.0286506966413 |
|   5    | 0.0161657189277 | 0.0320664603514 |
|   6    | 0.0155216432633 | 0.0361893107042 |
|   7    | 0.0149123824997 | 0.0401355849097 |
|   8    |  0.014277735871 | 0.0431030560513 |
|   9    | 0.0138711590783 | 0.0464779994945 |
|   10   | 0.0135139839851 | 0.0499214423695 |
+--------+-----------------+-----------------+
```

Then I switched to `item_similarity` and it works beautifully! Initially I went with the `ranking_factorization` because it supports side features, but now I simply clean up the data before and it works perfectly fine. Thanks so much! :)
