### ISSUE TITLE
Functionality of prediction_id in predict of Activity Classifier

### ISSUE THREAD

**Issue by shreyajain17** [apple/turicreate#1706]
The functionality of prediction_id column given as output of predict when making prediction per window is not clear in documentation. The output given at the moment is the following. 

```
|      253      |   1    | [  4.63483302e-04   9.9950... |
|      254      |   1    | [  7.90477672e-04   9.9914... |
|      255      |   1    | [  4.41032015e-02   9.5374... |
|      256      |   2    | [  7.02369167e-03   2.4149... |
|      257      |   2    | [  5.60363929e-04   3.1854... |
|      258      |   2    | [  1.27506602e-04   6.1436... |
|      259      |   2    | [  6.75232295e-05   2.6096... |
```

**Comment by shreyajain17** [comment]
@nickjong I don't think it should be solved with docs though. I mean the column `prediction_id` has no use if it just like the index/row number of the SFrame.

**Comment by nickjong** [comment]
From offline discussion, sounds like this is an occasion where the code is wrong, and needs to be fixed to match the intent captured in the user guide

**Comment by srikris** [comment]
@nickjong Is this fixed in #2431. If so, can this be closed?

**Comment by syoutsey** [comment]
If the `prediction_id` has been [removed](https://github.com/apple/turicreate/pull/2431/files#diff-eca1b17099e6523db8cc3aedf37c1ddbL449) from the output, then we'll also want to update the [docs](https://apple.github.io/turicreate/docs/userguide/activity_classifier/) to match this.

**Comment by nickjong** [comment]
No, our end goal was not to remove prediction ID but to implement it correctly (starting over from 1 within each session). In #2431 we punted on doing it correctly and just removed it temporarily.
