### ISSUE TITLE
RuntimeError.message is invalid in Python 3, replace in _

### ISSUE THREAD

**Issue by guy4261** [apple/turicreate#1739]
The code here says:  
https://github.com/apple/turicreate/blob/379494e63f9739703b226a9cbbae42d937d1f25c/src/unity/python/turicreate/data_structures/sframe.py#L1024

```python
except RuntimeError as e:
                if type(e) == RuntimeError and ("cancel" in e.message or "Cancel" in e.message):
                    raise e
```

But relying on `e.message` for an Exception is invalid in Python3. I think you can use `str(e)` instead.

```bash
[~]$ python2.7 -c 'print RuntimeError.message'
<attribute 'message' of 'exceptions.BaseException' objects>

[~]$ python3.6 -c 'print(RuntimeError.message)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: type object 'RuntimeError' has no attribute 'message'
```

**Comment by TobyRoseman** [comment]
Looks like `Exception.message` has been deprecated since Python 2.6.

We should use `str(e)` here. That works in both Python 2 and 3. We should also see where else in our code base we might be making the same mistake.
