### ISSUE TITLE
whatshouldisAy

### ISSUE THREAD

**Issue by berrylaw** [apple/turicreate#1740]
https://github.com/apple/turicreate/blob/379494e63f9739703b226a9cbbae42d937d1f25c/src/unity/python/turicreate/data_structures/sframe.py#L1024

**Comment by TobyRoseman** [comment]
This is the same issues as #1739. Closing as a duplicate.

@berrylaw - if you are asking how to fix this issues, you need to use `str(e)` rather than `e.message`. See my comment in #1739.
