### ISSUE TITLE
Lapack not properly detected on build

### ISSUE THREAD

**Issue by hoytak** [apple/turicreate#175]
When building on ubuntu 16.04, the build process does not error out if lapack is not present.  Everything compiles fine, but the use of most of the machine learning algorithms results in `std::logic_error: solve(): use of LAPACK must be enabled`.

**Comment by afranklin** [comment]
We should make sure that:

* We error out at compile time if lapack is not present
* We error out at runtime if lapack is not present

**Comment by znation** [comment]
@TobyRoseman I know you hit this recently; want to see if there is an easy way we can error out in `./configure` or during the build, if lapack is missing?
