### ISSUE TITLE
Magic string breaks SArray.explore()

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#1751]
I had an SArray which broke `explore()`. Eventually tracked the problem down to a single string value: `\\x`.

Running: ` tc.SArray(['\\x']).explore()` causes the following to get printed:
`Got error: "The data couldn’t be read because it isn’t in the correct format." while trying to read:
{"data_spec": {"values": [{"__idx": "0","SArray": "\x"}]}}`. A visualization window is create but it never finishes loading.

It seems that having `\\x` any where in the SArray causes explore to break. We get the same behavior with this code: `tc.SArray(['a', 'b', 'foo\\xbar', 'x', 'y', 'z']).explore()`.

**Comment by sirahd** [comment]
The cause for this is that `\x` is one of the special character for unicode that needs to be followed by hex number, e.g. `\x23`, but we didn't detect and add special escape `\x` character before we pass it to the swift UI.

**Comment by TobyRoseman** [comment]
@sirahd - Thanks for figuring that out. Are there any other special characters that we should be escaping but aren't?

**Comment by sirahd** [comment]
@TobyRoseman Assuming that the special characters are in Swift (where the error was previously thrown), there are `\0`,`\\`,`\t`,`\n`,`\r`,`\"`, `\'` and `\x` (https://docs.swift.org/swift-book/LanguageGuide/StringsAndCharacters.html). I have tested all of them with two `\` characters and they all work properly.
