### ISSUE TITLE
Sketch.num_na() is broken for float

### ISSUE THREAD

**Issue by guyinbar** [apple/turicreate#1759]
According to documentation, Sketch.num_na() should return the exact number of missing values (https://apple.github.io/turicreate/docs/api/generated/turicreate.Sketch.html#turicreate-sketch), however, when `dtype` is float,  it always returns 0.

```
sf = tc.SFrame({'A':[1.0, 2.0] + [float('nan')]*100})
print sf['A'].summary().num_na() 
print len(sf['A']) - len(sf['A'].dropna()) 
```

```
sf = tc.util.generate_random_sframe(10000, 'R', random_seed=11)
print sf['X1-R'].dtype
print sf['X1-R'].summary().num_na() 
print len(sf) - len(sf.dropna())
print sum(sf['X1-R'].apply(lambda x : math.isnan(x)))
```

**Comment by hoytak** [comment]
The name of this should be changed.  A float('nan') is not a missing value; that would be a python None.   dropna() and num_na() are not consistent in that they handle NAN differently.

**Comment by hoytak** [comment]
Let's change num_na to be num_missing.
