### ISSUE TITLE
Wrong behavior for nan converting from float to int

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#1761]
When changing the dtype of an SArray from float to int, `nan` get converted to very large number:
```python
In [1]: import turicreate as tc

In [2]: sa = tc.SArray([1.0,2.0,float('nan'),3.0])

In [3]: sa
Out[3]: 
dtype: float
Rows: 4
[1.0, 2.0, nan, 3.0]

In [4]: sa.astype(int)
Out[4]: 
dtype: int
Rows: 4
[1, 2, -9223372036854775808, 3]
```
I'm not certain what the best behavior would be here; it seems `nan` is a floating point only representation. It would probably be best to turn the `nan` into `None`. Raising an exception is also probably reasonable.

**Comment by hoytak** [comment]
We should turn this into a None.  It should be a simple fix.

**Comment by dhivyaaxim** [comment]
@TobyRoseman  Please assign this ticket to me as I would like to try fixing it and contribute. Thanks in advance!

**Comment by dhivyaaxim** [comment]
@TobyRoseman  Please assign this ticket to me as I would like to try fixing it and contribute. Thanks in advance!
