### ISSUE TITLE
Intermittent Python and C++ test failure in ActivityClassifierAutoValdSetTest

### ISSUE THREAD

**Issue by znation** [apple/turicreate#1763]
Rarely happens, but this is the result (seen in a Travis CI build on Linux, Python 3.5):

```
turicreate/test/test_activity_classifier.py::ActivityClassifierAutoValdSetTest::test_create_auto_validation_set_typical *** Error in `/home/travis/build/apple/turicreate/scripts/../deps/env/bin/python': malloc(): memory corruption (fast): 0x00000000059bf6e8 ***
scripts/run_python_test.sh: line 58:  7474 Aborted                 (core dumped) $cmd
```

See https://travis-ci.com/apple/turicreate/jobs/194576726

**Comment by znation** [comment]
Also causes an intermittent C++ unit test failure in `test_create_auto_validation_set_string_session_id`:

```
turicreate/test/test_activity_classifier.py::ActivityClassifierAutoValdSetTest::test_create_auto_validation_set_string_session_id *** Error in `/home/travis/build/apple/turicreate/scripts/../deps/env/bin/python': free(): invalid pointer: 0x00007f3670007b48 ***
scripts/run_python_test.sh: line 58:  9258 Aborted                 (core dumped) $cmd
```

See https://travis-ci.com/apple/turicreate/jobs/200612366 for an example of this.

**Comment by syoutsey** [comment]
For this release either fix or skip this test.

**Comment by shreyajain17** [comment]
I think this is fixed as we adopted the C++ implementation of AC since I can no longer see it. Still, I don't how to say if an intermittent test is fixed or not for certain.

**Comment by znation** [comment]
I think we can assume it's fixed, and close the issue. If it happens again on a Travis run, we can reopen the issue and link to the instance where it happened.
