### ISSUE TITLE
Feature request: support for dropna() on vectors

### ISSUE THREAD

**Issue by dbickson** [apple/turicreate#1804]
The current implementation supports dropping NaNs on floats.
It would be nice to support dropping Nans inside float vectors and shown below:
```
import turicreate as tc
import numpy as np
data = tc.SFrame({'a':[[0, np.nan],[1,2]]})
Columns:
	a	array

Rows: 2

Data:
+------------+
|     a      |
+------------+
| [0.0, nan] |
| [1.0, 2.0] |
+------------+
[2 rows x 1 columns]

data.dropna()
```

=> Currently nothing is dropped, it would be nice if the first row would be dropped.

**Comment by Jarvi-Izana** [comment]
for a flex_vec, if it contains nan, should it be treated as nan?

**Comment by Jarvi-Izana** [comment]
track by #2102
