### ISSUE TITLE
Bounding box errors and troubleshooting when using 'explore'

### ISSUE THREAD

**Issue by fbomb111** [apple/turicreate#1837]
In using the following with my own dataset:

```
data['image_with_ground_truth'] = \
    tc.object_detector.util.draw_bounding_boxes(data['image'], data['annotations'])
data.explore()
```

I often get the following error: 

```
/anaconda3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in <listcomp>(.0)
   2477         assert callable(fn), "Input must be callable"
   2478         test_sf = self[:10]
-> 2479         dryrun = [fn(row) for row in test_sf]
   2480         if dtype is None:
   2481             dtype = SArray(dryrun).dtype

/anaconda3/lib/python3.6/site-packages/turicreate/toolkits/object_detector/util/_visualization.py in draw_single_image(row)
    140                                     _width=image.shape[1],
    141                                     _height=image.shape[0],
--> 142                                     _channels=image.shape[2],
    143                                     _format_enum=FORMAT_RAW,
    144                                     _image_data_size=image.size)

IndexError: tuple index out of range
```

There is no indication of which image it failed on, or why (at least to me) it failed which is difficult to troubleshoot.  I ran `explore()` half-splitting my images until I finally found a culprit.

Here is the image:
![5290f4027491d09b](https://user-images.githubusercontent.com/482183/57240833-86c55880-6ffd-11e9-9f09-a3f7cd13fc79.jpg)

And the data in my SFrame for this image:

```
{'image': Height: 768px
 Width: 1024px
 Channels: 3,
 'name': '5290f4027491d09b',
 'annotations': [{'label': 'Window',
   'coordinates': {'x': 344.514048,
    'y': 252.271488,
    'width': 101.89312000000001,
    'height': 93.66297600000001}},
  {'label': 'Window',
   'coordinates': {'x': 674.277376,
    'y': 240.79296,
    'width': 59.78316799999993,
    'height': 163.097856}},
  {'label': 'Window',
   'coordinates': {'x': 702.357504,
    'y': 203.64288,
    'width': 77.89977599999997,
    'height': 103.29599999999999}}]}
```

Actually `data.explore()` runs fine unless I run `data['image_with_ground_truth'] = \
    tc.object_detector.util.draw_bounding_boxes(data['image'], data['annotations'])` (taken from the Readme) before it.

Any assistance would be greatly appreciated.  Also please consider my suggestion of providing a little more feedback about which image failed in this process so they are easier to isolate.  Thank you kindly!

**Comment by shantanuchhabra** [comment]
Hi @fbomb111 ,

Thanks for using and providing great feedback on the Turi Create Object Detector. We created an issue tracking making `draw_bounding_boxes` provide more helpful debugging information (#1839).

Regarding the error you get, let's confirm that this is the image that `draw_bounding_boxes` failed on. I downloaded the image and ran `draw_bounding_boxes` on just that image and the annotation you provided and I saw bounding boxes (see attachment). There could be a few possibilities:
- There is a bad image in your SFrame (probably the one you attached).
- There is no bad image in your SFrame and there's a bad codepath that gets triggered either on a particular image or on the SFrame as a whole.

Could you run the following code snippet (replace `sf`, `image_column_name`, and `annotation_column_name`) to see if this still points to the same image you attached?

```
for row in sf.num_rows():
    image = sf[image_column_name][row]
    annotation = sf[annotation_column_name][row]
    try:
        tc.object_detector.util.draw_bounding_boxes(image, annotation)
    except:
        print("Bad image row number:")
        print(row)
        print("Bad image")
        image.show()
``` 

Let us know what you get when you run this!

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/14062641/57244400-20d0d500-6fed-11e9-81cf-6ad9d0cdf7d7.png">

**Comment by fbomb111** [comment]
First off, thank you so much for the idea on how to capture the image names and row!  That helped and led me to find that I was looking at one index after the error index.  So here is the actual image I believe is causing the issue.

![9971996f732fce6e](https://user-images.githubusercontent.com/482183/57249692-9a7bb980-7013-11e9-98ec-23aa4290404d.jpg)

And it's associated data for that row in the SFrame

```
{'image': Height: 1024px
 Width: 680px
 Channels: 1,
 'name': '9971996f732fce6e',
 'annotations': [{'label': 'Window',
   'coordinates': {'x': 340.00374,
    'y': 688.01792,
    'width': 679.99252,
    'height': 571.1370239999999}}]}
```

**Comment by shantanuchhabra** [comment]
@fbomb111 After some investigation, it seems like the `draw_bounding_boxes` utility cannot support grayscale images. When we try to convert a grayscale image to a Pillow Image and then get the pixel data out, the shape gets registered as (height, width) and we lose the channel dimension, hence the "tuple index out of range" error. I'm working on a fix right now and will update this issue thread with more details. In the meantime, could you try converting all the grayscale images in your SFrame to RGB to visualize the bounding boxes on them?

**Comment by shantanuchhabra** [comment]
@fbomb111 Fix is up in #1845 !

**Comment by fbomb111** [comment]
@shantanuchhabra Thanks for the fast fix!  I will update and try it out tonight and report back.

**Comment by fbomb111** [comment]
@shantanuchhabra Sorry to bother you, but I am having trouble checking out the latest changes.  Would you suggest:
`pip3 install git+https://github.com/apple/turicreate.git` to get the latest from master?  

I'm getting some errors I think related to a missing `setup.py` ?  Still newish to python, just enough to be dangerous.

   ```
 ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/anaconda3/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/1c/whcs34_s7xjc5k2rmthb1v2c0000gq/T/pip-req-build-novgch0f/setup.py'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/1c/whcs34_s7xjc5k2rmthb1v2c0000gq/T/pip-req-build-novgch0f/
```

**Comment by shantanuchhabra** [comment]
Hi @fbomb111 ,

I don't think it's possible to pip install a git repository. You could, however, clone from master, build from source, and then work with Turi Create built from source. [Here](https://github.com/apple/turicreate/blob/master/BUILD.md) are the steps to make that happen.

This fix will become available in our next release, which will be in a few weeks. If you don't want to wait for the next release, here is a workaround code snippet to help you convert all the grayscale images in your SFrame to RGB so you can then visualize bounding boxes on them:

```python
import turicreate as tc
import numpy as np

def gray2rgb(image):
    # grayscale tc.Image -> RGB tc.Image
    if image.channels == 1:
        rgb_pixel_data = image.pixel_data[..., np.newaxis]
        image_rgb =  np.concatenate(3 * (rgb_pixel_data,), axis=-1)
        FORMAT_RAW = 2
        return tc.Image(_image_data=image_rgb.tobytes(),
                        _width=image_rgb.shape[1],
                        _height=image_rgb.shape[0],
                        _channels=image_rgb.shape[2],
                        _format_enum=FORMAT_RAW,
                        _image_data_size=image_rgb.size)
    return image

# Note: replace sf, "image", and "annotation"
sf["converted_image"] = sf["image"].apply(gray2rgb)

sf["bbox"] = tc.object_detector.util.draw_bounding_boxes(sf["converted_image"], sf["annotation"])
```

Feel free to follow up with more questions!

**Comment by fbomb111** [comment]
Thanks for providing such a great work around!  I was finally able to draw all my bounding boxes.
