### ISSUE TITLE
RuntimeError: CoreML Error: Unable to extract model type from stream in compiled model

### ISSUE THREAD

**Issue by maaaaaaaaaad** [apple/turicreate#1849]
Hi,
I'm trying to build an image similarity model in Jupyter Notebook according to the user guide provided by Apple (https://apple.github.io/turicreate/docs/userguide/image_similarity/). I used the same dataset to build a similar model last week but this time it won't work for some reason. All packages and Anaconda is up to date.

`reference_data  = tc.image_analysis.load_images('./dataset')
reference_data = reference_data.add_row_number()
reference_data.save('./NEWMARTINV2.sframe')
model = tc.image_similarity.create(reference_data)`

Get the following error:

RuntimeError                              Traceback (most recent call last)
/anaconda3/envs/turienv/lib/python3.6/site-packages/turicreate/extensions.py in __run_class_function(self, fnname, args, kwargs)
    275         try:
--> 276             ret = self._tkclass.call_function(fnname, argument_dict)
    277         except RuntimeError as exc:

turicreate/cython/cy_model.pyx in turicreate.cython.cy_model.UnityModel.call_function()

turicreate/cython/cy_model.pyx in turicreate.cython.cy_model.UnityModel.call_function()

RuntimeError: CoreML Error: Unable to extract model type from stream in compiled model: Error opening file stream: /var/folders/yb/dc523g_j3l14t3g0tbj6lydh0000gn/T/model_cache/resnet-50_modified.mlmodelc/coremldata.bin: unspecified iostream_category error

**Comment by TobyRoseman** [comment]
@maaaaaaaaaad - I'm sorry you're having this issue. Try clearing the model cache. In your case this would mean deleting all files under `/var/folders/yb/dc523g_j3l14t3g0tbj6lydh0000gn/T/model_cache/`. Then try it again. Please let us know if that works.

If that doesn't work, let us know which version of TuriCreate you are using.

**Comment by maaaaaaaaaad** [comment]
That solved it, thanks!
