### ISSUE TITLE
How to download the dataset cats-dogs.sframe?

### ISSUE THREAD

**Issue by JiangShj** [apple/turicreate#187]
I want to sue the example, but I don't find the way to download the datasets. Thanks for your suggestion!

**Comment by znation** [comment]
Hi @JiangShj - good question! [This page](https://github.com/apple/turicreate/blob/master/userguide/image_classifier/introduction.md#loading-data) shows how to create the dataset from your own set of cat & dog images. It expects a collection of images on the filesystem (they can be .jpg, .png, etc.) in two directories: `cat` and `dog`.

I'll keep this issue open to see if we can provide a pre-labeled set of images that will be usable out of the box so you don't need to find your own.

**Comment by JiangShj** [comment]
@znation Thanks for your reply，I have tried the experiment on image classification，It is so convenient and awesome! I look forward to the dataset for the object detection.
