### ISSUE TITLE
Regression in TC image classifier evaluate

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#1889]
The evaluation from 5.4 regressed on `confusion_matrix` and `roc_curve` which are missing from the evaluation dictionary.

The evaluation code path is also missing from the unit tests
https://github.com/apple/turicreate/blob/master/src/unity/python/turicreate/test/test_image_classifier.py

**Comment by TobyRoseman** [comment]
Dup of #1871, although that one only mentioned `roc_curve`.
