### ISSUE TITLE
Unable to access pre-trained drawing model

### ISSUE THREAD

**Issue by hipwelljo** [apple/turicreate#1892]
When I click the "[here](https://docs-assets.developer.apple.com/turicreate/)" link at the bottom of [this page](https://apple.github.io/turicreate/docs/userguide/drawing_classifier/advanced-usage.html) I get an Access Denied error.

**Comment by shantanuchhabra** [comment]
Hi @hipwelljo , thanks for using the Drawing Classifier, and for filing this issue! We'll work on hiding the link since the pre-trained model automatically gets downloaded depending on the value passed in to the `warm_start` parameter.
