### ISSUE TITLE
Clarify default warm start model behavior in the drawing documentation

### ISSUE THREAD

**Issue by hipwelljo** [apple/turicreate#1893]
Reading through [this page](https://apple.github.io/turicreate/docs/userguide/drawing_classifier/advanced-usage.html) at the bottom it says

> we provide the option of loading in a pretrained model for a warm start ... we have published our pre-trained model here

So I was under the impression if I wanted a warm start I have to download this model and specify the path to it in the parameters to `drawing_classifier.create`, but the [API docs](https://apple.github.io/turicreate/docs/api/generated/turicreate.drawing_classifier.create.html?highlight=drawing) indicate otherwise

> warm_start : string optional
> A string to denote which pretrained model to use. Set to “auto” by default which uses a model trained on 245 of the 345 classes in the Quick, Draw! dataset. To disable warm start, pass in None to this argument.

**Comment by shantanuchhabra** [comment]
Hi @hipwelljo , thanks for using the Drawing Classifier. To clarify, you don't need to manually download the pre-trained model that we published. All you need to do is pass in `"auto"` to the `warm_start` parameter (which is actually also the default value). If you don't want to use the published pre-trained model for a warm start, just pass in `"None"` to the `warm_start` parameter. We plan to add more options to pass in to the `warm_start` parameter.

I'll leave this issue open so we can address this lack of clarity in the documentation. Does this help answer your question? Feel free to follow up!

**Comment by hipwelljo** [comment]
Thanks for making it! It suits my use case precisely where I was using the image classifier previously, so hoping this will generate a much better model. :)

Thanks for confirming the API docs are correct. Yes it’d be great to have the guide clarified to better explain warm start. Thanks!
