### ISSUE TITLE
Error image_classifier, load_model

### ISSUE THREAD

**Issue by kuri54** [apple/turicreate#1897]
Turi Create==5.1, 5.4, 5.5
python==3.6
mxnet==1.1.0

The following error came out even though I did nothing.
I can't go ahead.

### **・model = tc.image_classifier.create(train_data, target='label')**
---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-6-0b735449dfb3> in <module>
----> 1 model = tc.image_classifier.create(train_data, target='label')

~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/turicreate/toolkits/image_classifier/image_classifier.py in create(dataset, target, feature, model, validation_set, max_iterations, verbose, seed, batch_size)
    145         feature = _tkutl._find_only_image_column(dataset)
    146 
--> 147     feature_extractor = _image_feature_extractor._create_feature_extractor(model)
    148 
    149     # Extract features

~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/turicreate/toolkits/_image_feature_extractor.py in _create_feature_extractor(model_name)
     30         if not os.path.exists(mlmodel_resnet_save_path):
     31             from turicreate.toolkits import _pre_trained_models
---> 32             mxnetResNet = _pre_trained_models.ResNetImageClassifier()
     33             feature_extractor = MXFeatureExtractor(mxnetResNet)
     34             mlModel = feature_extractor.get_coreml_model()

~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/turicreate/toolkits/_pre_trained_models.py in __init__(self)
    109         ], path)
    110         import mxnet as _mx
--> 111         self.mxmodel = _mx.model.load_checkpoint(_os.path.join(path, self.name), epoch)
    112 
    113 class SqueezeNetImageClassifierV1_1(ImageClassifierPreTrainedModel):

~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/mxnet/model.py in load_checkpoint(prefix, epoch)
    436     This class is designed for a single-data single output supervised network.
    437 
--> 438     Parameters
    439     ----------
    440     symbol : Symbol

~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/mxnet/ndarray/utils.py in load(fname)
    173                                   ctypes.byref(handles),
    174                                   ctypes.byref(out_name_size),
--> 175                                   ctypes.byref(names)))
    176     if out_name_size.value == 0:
    177         return [_ndarray_cls(NDArrayHandle(handles[i])) for i in range(out_size.value)]

~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/mxnet/base.py in check_call(ret)
    250     """
    251     out = (ctype * len(values))()
--> 252     out[:] = values
    253     return out
    254 

MXNetError: [22:18:48] src/ndarray/ndarray.cc:1805: Check failed: fi->Read(data) Invalid NDArray file format

Stack trace returned 7 entries:
[bt] (0) 0   libmxnet.so                         0x000000011364bc90 std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::NDArrayFunctionReg*>, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::NDArrayFunctionReg*>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::NDArrayFunctionReg*> > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::NDArrayFunctionReg*>, void*>*) + 2736
[bt] (1) 1   libmxnet.so                         0x000000011364ba3f std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::NDArrayFunctionReg*>, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::NDArrayFunctionReg*>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::NDArrayFunctionReg*> > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::NDArrayFunctionReg*>, void*>*) + 2143
[bt] (2) 2   libmxnet.so                         0x000000011364b669 std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::NDArrayFunctionReg*>, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::NDArrayFunctionReg*>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::NDArrayFunctionReg*> > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mxnet::NDArrayFunctionReg*>, void*>*) + 1161
[bt] (3) 3   libmxnet.so                         0x0000000114dd63f4 mxnet::NDArray::Load(dmlc::Stream*, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> >*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) + 468
[bt] (4) 4   libmxnet.so                         0x0000000114c10c6f MXNDArrayLoad + 255
[bt] (5) 5   _ctypes.cpython-36m-darwin.so       0x000000010b6cff67 ffi_call_unix64 + 79
[bt] (6) 6   ???                                 0x00007ffee711c040 0x0 + 140732775120960

### **・model = tc.load_model('modelname.model/')**
MXNetError: [22:26:46] src/ndarray/ndarray.cc:1114: Check failed: fi->Read(data) Invalid NDArray file format

Stack trace returned 7 entries:
[bt] (0) 0   libmxnet.so                         0x00000001158062cf libmxnet.so + 58063
[bt] (1) 1   libmxnet.so                         0x000000011580606f libmxnet.so + 57455
[bt] (2) 2   libmxnet.so                         0x0000000115805979 libmxnet.so + 55673
[bt] (3) 3   libmxnet.so                         0x00000001168e7e57 MXNDListFree + 1316471
[bt] (4) 4   libmxnet.so                         0x0000000116776d21 MXNDArrayLoad + 241
[bt] (5) 5   _ctypes.cpython-36m-darwin.so       0x000000010d420f67 ffi_call_unix64 + 79
[bt] (6) 6   ???                                 0x00007ffee533af50 0x0 + 140732743790416

There was a similar error in the previous issue, and I was suspected of the mxnet version. What is the cause of this time?

I had a case that I wanted to move in a hurry, but I lost the chance because the program didn't work.

**Comment by kuri54** [comment]
Additional Information:
This error does not appear on iMac Pro (Turi Create==5.5, python==3.6, mxnet==1.1.0.post0).
I get this error on my MacBook Pro (Turi Create==5.1, 5.4, 5.5, python==3.6, mxnet==1.1.0, 1.1.0.post0).

It seems that the parameters of ResNet 50 have not been downloaded successfully.

**Comment by TobyRoseman** [comment]
@kuri54 - Try clearing your Turi Create model cache. 

Run the following to determine the path of your model cache:
```python
import turicreate as tc
print(tc.config.get_runtime_config()['TURI_CACHE_FILE_LOCATIONS'] + 'model_cache')
```
Try deleting all files in this directory.

**Comment by kuri54** [comment]
@TobyRoseman 

I fixed it as you wrote.
Thanks!
