### ISSUE TITLE
Annotations should error out on empty Frame

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#1915]
Right now, I get back a new SFrame without an annotation column
```
In [16]: aa = tc.image_classifier.annotate(sf[0:0])

In [17]: aa
Out[17]:
Columns:
	path	str
	image	Image

Rows: 0

Data:
	[]
```

**Comment by dhivyaaxim** [comment]
@znation Please assign this ticket to me as I would like to try fixing it and contribute .Thanks in advance!

**Comment by znation** [comment]
Thanks @dhivyaaxim!
