### ISSUE TITLE
Add .get_deep_features to image classifier as well

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#1916]
Image. classifier currently spends most of its time doing feature preprocessing and extracting deep features. 

Doing common machine tasks, such as k-fold validation or hyper-parameter search, will result in a large amount of duplicated work; the preprocessing and feature extraction for an example will be identical across folds or hyper-parameter runs.

We need a way to avoid this large amount of duplicated work.

**Comment by TobyRoseman** [comment]
The biggest question for me: where in our namespace do we put this function? The same deep features are used by the image classifier and the image similarity toolkits. Do we want something that only works for the image classifier, or do we also want to do something that works for image similarity as well?

If we want something that works only for the image classifier, then we should put it under `tc.image_classifier.`. If we want something that work for both, we probably want to add it to the top level namespace.

**Comment by srikris** [comment]
Why not add it to both name spaces?

**Comment by nickjong** [comment]
I think this question merits a broader conversation about data preprocessing (and possibly augmentation) throughout Turi Create. More and more of our toolkits share this kind of preprocessing: image classifier, sound classifier, one-shot object detection

**Comment by TobyRoseman** [comment]
Another option is to add the `get_deep_features` method under `tc.image_analysis`. I think that makes more sense than making it a top level method or adding it to more than one place.

**Comment by TobyRoseman** [comment]
This functionality was added in #3210
