### ISSUE TITLE
Confusing console output on drawing_classifier.evaluate(...)

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#1918]
```python
In [17]: len(test_data)
Out[17]: 143

In [18]: _ = model.evaluate(test_data)
Predicting 144/143

In [19]: len(longer_test_data)
Out[19]: 429

In [20]: _ = model.evaluate(longer_test_data)
Predicting 257/429
```
The output from the first call to `evaluate(...)` is really the most confusing. How is it predicting one more examples than was passed in? This seems like an off by one bug.

The output from the second call to `evaluate(...)` makes it seem like it never finishes. The last/only output makes it seem like it's only about half done. The final output should probably be `Predicting X/X` where `X` is the number of examples passed in.

Both calls to evaluate finish quickly. I would recommend only outputting progress info if it's been at least 30 seconds.

**Comment by znation** [comment]
If we expect this to consistently take longer than a few seconds, we should use a `table_printer` with progress. If we expect it to consistently take less than a few seconds, let's print nothing (at least by default).

**Comment by srikris** [comment]
Unfortunately, this depends on the size of the dataset.

**Comment by znation** [comment]
In that case I think we should always use a table printer with progress (similar to other create/evaluate type methods that might finish in a few seconds or a few days).

**Comment by znation** [comment]
And probably a `verbose=True` parameter that the user can call with `False` to prevent output.
