### ISSUE TITLE
Error Creating Model

### ISSUE THREAD

**Issue by elseagle** [apple/turicreate#194]
`training_data, validation_data = tc.recommender.util.random_split_by_user(terravas, 'user_id', 'service_name')`

This is what I got 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-217-4b342fbf3878> in <module>()
----> 1 training_data, validation_data = tc.recommender.util.random_split_by_user(terravas, 'user_id', 'service_name')

/home/elseagle/venv/local/lib/python2.7/site-packages/turicreate/toolkits/recommender/util.pyc in random_split_by_user(dataset, user_id, item_id, max_num_users, item_test_proportion, random_seed)
    656     """
    657 
--> 658     assert user_id in dataset.column_names(), \
    659         'Provided user column "{0}" not found in data set.'.format(user_id)
    660     assert item_id in dataset.column_names(), \

/home/elseagle/venv/local/lib/python2.7/site-packages/pandas/core/generic.pyc in __getattr__(self, name)
   3612             if name in self._info_axis:
   3613                 return self[name]
-> 3614             return object.__getattribute__(self, name)
   3615 
   3616     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'column_names'

**Comment by gustavla** [comment]
It looks like you are putting in a pandas DataFrame into the function while it is expecting an SFrame. We should probably raise a more user-friendly error in such cases. Thanks for pointing it out!

**Comment by elseagle** [comment]
Okay. Noted

**Comment by elseagle** [comment]
What actually happened was  I analyzed the data in pandas and wanted to use tc to set a recommender_system but I didn't rename my dataframe for tc modeling so it kept reading from the pandas  perspective
