### ISSUE TITLE
Evaluation UI is slow a very large dataset

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#1940]
I can't quite tell if it is #1934 or not but on an SFrame with > 20K rows, the evaluation UI experience is slow. 

Please close if this is related to #1934.

**Comment by srikris** [comment]
@znation I think it might be okay to restrict the images being shown to almost 100 per class. We can always performance optimize it and add more classes. I think the issue is in the fact that we are probably trying to render all images.

**Comment by znation** [comment]
@srikris Makes sense, I'll see if capping at 100 images per class improves the UX perf.
