### ISSUE TITLE
Verbose parameter in predict, predict_topk and classify in Sound Classifier 

### ISSUE THREAD

**Issue by shreyajain17** [apple/turicreate#1947]
Whether I set the `verbose` parameter to True or False, the output from predict, predict_topk and classify for the same dataset and other arguments gives the exact same result. 

```
model.predict_topk(test_set, k=5)
Out[67]: 
Columns:
	id	int
	class	str
	probability	float

Rows: 400

Data:
+----+------------+-----------------+
| id |   class    |   probability   |
+----+------------+-----------------+
| 0  |  sneezing  |  0.417031806707 |
| 0  |  rooster   |  0.271323435009 |
| 0  |    dog     |  0.217150485516 |
| 0  | clock_tick | 0.0281529854983 |
| 0  | helicopter | 0.0246068299748 |
| 1  |  sneezing  |  0.376313689351 |
| 1  |    dog     |  0.269497287273 |
| 1  |  rooster   |  0.265654413402 |
| 1  | helicopter | 0.0242995586712 |
| 1  | clock_tick | 0.0242125522811 |
+----+------------+-----------------+
[400 rows x 3 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [68]: model.predict_topk(test_set ,k=5, verbose=False)
Out[68]: 
Columns:
	id	int
	class	str
	probability	float

Rows: 400

Data:
+----+------------+-----------------+
| id |   class    |   probability   |
+----+------------+-----------------+
| 0  |  sneezing  |  0.417031806707 |
| 0  |  rooster   |  0.271323435009 |
| 0  |    dog     |  0.217150485516 |
| 0  | clock_tick | 0.0281529854983 |
| 0  | helicopter | 0.0246068299748 |
| 1  |  sneezing  |  0.376313689351 |
| 1  |    dog     |  0.269497287273 |
| 1  |  rooster   |  0.265654413402 |
| 1  | helicopter | 0.0242995586712 |
| 1  | clock_tick | 0.0242125522811 |
+----+------------+-----------------+
[400 rows x 3 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.
```

**Comment by TobyRoseman** [comment]
Based on the output you shared, it doesn't look like any information is getting printed out either when `verbose=True` or `verbose=False`. The sound classifier only outputs progress info if it takes more than 20 seconds to do the preprocessing or more than 20 seconds to do the feature preprocessing. 

@shreyajain17 - Are you using a very small test set, or does your test set already contain the extracted deep features?

**Comment by shreyajain17** [comment]
@TobyRoseman The test set is small as it is a small subset of ESC-10. I will try with a big set and if it shows different results I will close it.

**Comment by shreyajain17** [comment]
With bigger dataset, different values passed in verbose parameter will actually show different results. 

@TobyRoseman is correct. The sound classifier only outputs progress info if it takes more than 20 seconds to do the preprocessing or more than 20 seconds to do the feature preprocessing.
