### ISSUE TITLE
Links in README.md are Dead

### ISSUE THREAD

**Issue by Reubend** [apple/turicreate#195]
The readme file has several dead links, which refer to files that no longer exist. There is a section which says
`With Turi Create, you can tackle a number of common scenarios:`
and underneath are links like [Recommender systems](https://github.com/apple/turicreate/blob/master/userguide/recommender/introduction.md) which redirect to a 404 page.

**Comment by emannuelOC** [comment]
I fixed them in my forked and created a pull request. 
However maybe some files should be renamed. There's an inconsistency in the naming of the files:
`Classifiers`, `Regression` and `Neearest Neighboors` have their guides as `classifier.md`, `regression.md` and `nearest_neighboors.md`, respectively, while the others have a `README.md` file.

```
You can also work with essential machine learning models, organized into algorithm-based toolkits:
* [Classifiers](userguide/supervised-learning/classifier.md)
* [Regression](userguide/supervised-learning/regression.md)
* [Graph analytics](userguide/graph_analytics/README.md)
* [Clustering](userguide/clustering/README.md)
* [Nearest Neighbors](userguide/nearest_neighbors/nearest_neighbors.md)
* [Topic models](userguide/text/README.md)
```

**Comment by TobyRoseman** [comment]
@Reubend - I'm sorry you ran into this issue. Now that #199 has been merge, none of the links on `README.md` are broken any more.
