### ISSUE TITLE
Hot to use Turi to speed up the data preparation?

### ISSUE THREAD

**Issue by topinvestor** [apple/turicreate#1950]
I am building a word tagger.

This is the string I would send:
`Field01Value Field02Value Field03Value Field04Value
`

This is the end result.
```

<NLModel: 0x10053cea0>
{token: Field01Value tag: Optional("Field01")}
{token: Field02Value tag: Optional("Field02")}
{token: Field03Value tag: Optional("Field03")}
{token: Field04Value tag: Optional("Field04")}
```

Currently I am doing it via Xcode playground but the training is very slow. 80% of the time is spend in preparing the tables. Are there a way to speed up this process using Turi for data preparations?

Here is my code with Xcode playground:
```

import Cocoa

var str = "Hello, playground"


import CreateML
import Foundation

var data = try MLDataTable(contentsOf: URL(fileURLWithPath: "MyData.csv"))

let derivedColumnTokens = data.map { row -> [String]  in
    let tokens = [
        
         row.values[5].stringValue!,        // Field01,
         row.values[6].stringValue!,        // Field02,
         String(row.values[7].intValue!),   // Field03,
         String(row.values[8].intValue!),   // Field04,
          ] as [Any]
    //return String(format: "%@", tokens)
    return  tokens as [Any] as! [String]
}

//print(derivedColumnTokens)

//
let data0: [String: MLDataValueConvertible] = [
    "tokens": [ [derivedColumnTokens[1][5],  
                derivedColumnTokens[1][6],
                 derivedColumnTokens[1][7], 
                derivedColumnTokens[1][8],
        ],
    ],
    "labels": [ [          "Field01",
                           "Field02",
                           "Field03",
                           "Field04"],
    ]
    ]
var tableResults = try MLDataTable(dictionary: data0)

for i in 2...derivedColumnTokens.count-1 {
 
    let table = try MLDataTable(dictionary:  [
        "tokens": [ [
            derivedColumnTokens[1][5],  
            derivedColumnTokens[1][6], 
            derivedColumnTokens[1][7],
            derivedColumnTokens[i][8]],
            ],
            "Field01": [ [
            "Field02",
            "Field03",
            "Field04",
      ],
            ]
        ]
    )
    tableResults.append(contentsOf: table)
}


print(tableResults)

/////////////////////

let (trainingData, testingData) = tableResults.randomSplit(by: 0.8, seed: 5)

let wordtagger = try MLWordTagger(trainingData: trainingData,
                                           tokenColumn: "tokens",
                                               labelColumn: "labels")

//////////
let metadata = MLModelMetadata(author: "",
                               shortDescription: "",
                               version: "1.0")

try wordtagger.write(to: URL(fileURLWithPath: “MyModel.mlmodel"),
                              metadata: metadata)
//////////


```

**Comment by TobyRoseman** [comment]
I'm not going to be able to answer the question of whether Turi Create will be faster or not. 

Turi Create can [read CSV files](https://apple.github.io/turicreate/docs/api/generated/turicreate.SFrame.read_csv.html#turicreate.SFrame.read_csv). I don't understand what data preparation you're doing but the SFrame does have [a large number of method for data manipulation](https://apple.github.io/turicreate/docs/api/generated/turicreate.SFrame.html#turicreate.SFrame). However Turi Create does not have a Word Tagger.

See our user guide for some general information about [working with tabular data](https://apple.github.io/turicreate/docs/userguide/sframe/tabular-data.html).

I'm going to close this issue. Feel free to open new issues if you have specific questions about Turi Create that aren't covered in our documentation.

**Comment by topinvestor** [comment]
Data preparation is transposing the table coming from relational database as:

Field01,Field02,Field03,Field04

to the form:

tokenColumn: "tokens",
labelColumn: "labels"

Could  SFrame help for this task?

**Comment by TobyRoseman** [comment]
@topinvestor - I would recommend taking a look at [SFrame.unstack(...)](https://apple.github.io/turicreate/docs/api/generated/turicreate.SFrame.unstack.html#turicreate.SFrame.unstack).

**Comment by topinvestor** [comment]
Thank you, would look at it.

What do you recommend about speeding up the the training phase when using Turi and Core ML?
