### ISSUE TITLE
Different behavior between Model and Core ML model?

### ISSUE THREAD

**Issue by th85ac** [apple/turicreate#1957]
I've read the previous posts regarding the differences between Model and Core Model (for object detection) and followed all the steps provided. However, I still get partially different results.

I've run the IG02 Data Test. I've created the model (80% train, 20% test) using turicreate and got the expected results.
For example for the picture bike_007 ...  <img width="255" alt="Screenshot 2019-05-26 at 23 09 25" src="https://user-images.githubusercontent.com/22947199/58387196-5d4f8980-800b-11e9-99aa-b80930eaf0e8.png"> the data is

[
  {
    "label": "bike",
    "confidence": 0.840157,
    "type": "rectangle",
    "coordinates": {
      "y": 104.533,
      "x": 455.369,
      "width": 255.036,
      "height": 162.651
    }
  }
]

However,  when exporting the model to a mlmodel format and running it within an iOS app (one of the examples provided by Apple) using Vision and "request.imageCropAndScaleOption = .scaleFill" I've got the following as observation (VNRecognizedObjectObservation)...

(x: 0.5115232020616531, y: 0.6123300045728683, width: 0.40042564272880554, height: 0.33921515941619873)

or in the non-normalized coordinates...

(x: 327.374849319458, y: 293.9184021949768, width: 256.27241134643555, height: 162.8232765197754)

The width and height are basically the same but not the coordinates x and y. I am expecting these figures  to be the coordinates of the center of the bounding box as calculated by turicreate but they are not... Why? I am using the latest version of turicreate, Xcode, iOS and mac osx.

**Comment by nickjong** [comment]
At present, Turi Create and Vision don't use the same representation of bounding boxes. For Turi Create (and the raw CoreML model), we location of a bounding box is given by its center. The Vision framework returns observations with their standard representation, given IIRC the position of the lower-left corner. Is that consistent with what you're observing?

I'll use this issue to track clarifying the user guide, which should flag the inconsistency in representations

**Comment by th85ac** [comment]
Thank you... this seems to be the case for the x coordinate. For example in the case above transforming from the lower-left corner to the center gives 327.374849319458 + 256.27241134643555/2 = 455.5110549926758 which is very similar to what the turi create model produces 455.369. 

But it is not the case for the y coordinate (and this is something it can be replicated with any picture)... 293.9184021949768 - 162.8232765197754 / 2 = 212.5067639350891 which is NOT close to 104.533. The bounding box appears always below the place it should be.

**Comment by nickjong** [comment]
Sorry, my description above was not quite complete. The Vision framework gives the position of the lower-left corner (not the upper-left) because it uses a coordinate system where the origin is at the lower-left corner of the image. So y=0 is the bottom and y=377 is at the top. So here it's more like
```
center_y_vision = 293.9184021949768 + 162.8232765197754 / 2 = 375.33
center_y_turi = 480 - 375.33 = 104.67
```
So the first line converts from the bottom of the box (in Vision coordinates, origin at bottom of image) to the center of the box, and the second line converts from Vision coordinates to Turi Create coordinates (origin at top of image, noting that you scaled the image to 640 x 480).

Does that make sense?

**Comment by th85ac** [comment]
Thank you so much. You nailed it. It would be good to clarify in the user guide as you mentioned above.

**Comment by nickjong** [comment]
Yup, I filed #1984 to track that clarification
