### ISSUE TITLE
Annotations when column 'annotations' already exists

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#1979]
```
data_h = data.head()

# Annotate 2 images
data_a = tc.image_classifier.annotate(data_h)

# Call annotation again
data_new_a = tc.image_classifier.annotate(data_a)
```

<img width="815" alt="image" src="https://user-images.githubusercontent.com/1875987/58536351-244b1c80-81a5-11e9-8f34-2950dde5259b.png">

**Comment by znation** [comment]
Expected: unlabeled items remain unlabeled.
Actual: unlabeled items are now 0.

TODO: see if this repros with string labels and not int. (Guessing they will get "" as the label.)

**Comment by srikris** [comment]
This seems to only be an issue with the UI and not with the SFrame output.
