### ISSUE TITLE
Document various Object Detection coordinate systems across libraries

### ISSUE THREAD

**Issue by nickjong** [apple/turicreate#1984]
The user guide for Object Detection should call out the fact that Turi Create and Vision use different coordinate systems and different representations of bounding boxes. Clarity here would prevent user confusion such as #1957

**Comment by syoutsey** [comment]
Hi @jakesabathia2, was there a commit/PR that addresses this issue?

**Comment by jakesabathia2** [comment]
Yes PR #2320
