### ISSUE TITLE
Sound Classifier training shows some randomness

### ISSUE THREAD

**Issue by fareeha** [apple/turicreate#1996]
The SC model training on CPU with validation data turned off seems to be non-deterministic for the same train and test data split used (ESC-50). 

Run1: 
Linux Ubuntu 16.04 = {train_accuracy: 0.9106, test_accuracy: 0.925} 
Mac = {train_accuracy: 0.9175, test_accuracy: 0.9375}

Run2: 
Linux Ubuntu 16.04 = {train_accuracy: 0.9094, test_accuracy: 0.9375} 
Mac = {train_accuracy: 0.9187, test_accuracy: 0.9375}

**Comment by TobyRoseman** [comment]
Yes, training is non-deterministic. Different training runs may find different local minimums. I believe this will be the case for all of our deep learning toolkits. I don't think this is an issue.

**Comment by srikris** [comment]
Might be worth having a seed

**Comment by TobyRoseman** [comment]
I like the idea of having a random seed. However once we implement #1573, I think it will be almost impossible for the same training data and the same seed to produce the same model on both Linux and macOS.

**Comment by nickjong** [comment]
I don't think we need behavior to be identical across platforms, but results should be reproducible

**Comment by fareeha** [comment]
It turns out fixing the seed for MXNET and numpy removes the randomness within the same platform across trials. It looks like the seed for MXNET helps control the random weights init by Xavier and fixing the seed for numpy helps control the random shuffle in `_sframe_loader`, among other things possibly.

Fixing seed - CPU with no validation

Run1: 
Linux = {train_accuracy: 0.9206, test_accuracy: 0.9375} 
Mac = {train_accuracy: 0.9194, test_accuracy: 0.9375}

Run2: 
Linux = {train_accuracy: 0.9206, test_accuracy: 0.9375} 
Mac = {train_accuracy:0.9194 , test_accuracy: 0.9375}
