### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by znation** [apple/turicreate#2]
In the 4.0.0 release, only Python 2.7 is supported. We should support Python 3 as well.

Open question: which versions of Python 3?

**Comment by bear24rw** [comment]
>Open question: which versions of Python 3?

3.6 at a minimum. Can't live without f-strings.

**Comment by Kharms** [comment]
Ditto, 3.6 is great.

**Comment by laventura** [comment]
Seconding (thirding?) request for Py 3.6 support. 👍

**Comment by omarsar** [comment]
Still waiting for Python 3.6> support @ @

**Comment by jVirus** [comment]
Python 3.6, please 😍

**Comment by tilledminds** [comment]
3.6 for sure.

**Comment by alanwilter** [comment]
I need python 3 for sure, whatever you offer. If goes only for 3.6, than I have more than ever a reason to move from 3.5.

**Comment by titomiguelcosta** [comment]
please please, add support for python 3.6

**Comment by tuanavu** [comment]
Yes, 3.6 please!

**Comment by Legendgp** [comment]
3.6, please.

**Comment by joshij1979** [comment]
Python 3.6 ..  please
