### ISSUE TITLE
Implementing OCR in iOS app using turicreate

### ISSUE THREAD

**Issue by Daemon-Devarshi** [apple/turicreate#201]
I have to implement OCR in iOS for a certain font. I think the way to achieve this is:

- Train model for OCR by capturing image of each alphabet and tagging it with respective character
- Use native capabilities to detect characters from a scanned image
- Feed character images identified, in sequence, to trained model
- Based on prediction from model recognize each character, display the same, in sequence, to user

Wanted to validate the approach as well as know if there is any better approach to implement the requirement using turicreate? Please suggest.

**Comment by KevinGong2013** [comment]
I have a similar repo to do this, but that work in progress. ^_^

**Comment by CogMachines** [comment]
Your approach may work, but it may depend on the number of images per character label you will be using for training and the model you will be using for classification.  Have you decided what algorithm you will be using to do the classification?  Once you collect all of your training data, it is quite easy to set up turicreate to do the training and classification.

**Comment by srikris** [comment]
Unfortunately, our policy does not include providing advice on training models that are outside the scope of the tool. We wish you the best with your app.

**Comment by dimebt** [comment]
I have trained object detection model to predict "a" and "b" characters and passed a prediction from test image and i got not very good predictions (some characters was not predicted at all). Model was trained with sample data set of 30 images per character and max_iteration=1000 (6h training) and this is my final prediction on a test image: 

![tmpwxjeju](https://user-images.githubusercontent.com/22096002/42722816-2924f34a-8753-11e8-8fca-b7436424c7cf.jpg)

How can this object recognitions accuracy improve?
