### ISSUE TITLE
import turicreate as tc has a error why?

### ISSUE THREAD

**Issue by wangchuanya** [apple/turicreate#202]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-b996469cf675> in <module>()
----> 1 import turicreate as tc

/root/anaconda2/envs/turi/lib/python2.7/site-packages/turicreate/__init__.py in <module>()
     28 from turicreate.version_info import __version__
     29 
---> 30 from turicreate.data_structures.sgraph import Vertex, Edge
     31 from turicreate.data_structures.sgraph import SGraph
     32 from turicreate.data_structures.sarray import SArray

/root/anaconda2/envs/turi/lib/python2.7/site-packages/turicreate/data_structures/__init__.py in <module>()
     15 __all__ = ['sframe', 'sarray', 'sgraph', 'sketch', 'image']
     16 
---> 17 from . import image
     18 from . import sframe
     19 from . import sarray

ImportError: cannot import name image

**Comment by elseagle** [comment]
are you on wsl?

**Comment by elseagle** [comment]
try pip installinng sframe in your virtual environment and check the dependency page to install ` liblas`

**Comment by znation** [comment]
@wangchuanya This error indicates the file `/root/anaconda2/envs/turi/lib/python2.7/site-packages/turicreate/data_structures/image.py` is missing (or corrupt?). Could you try uninstalling turicreate with:

`pip uninstall turicreate`

And reinstalling with:

`pip install turicreate`

and see if the issue still repros? Thanks!

**Comment by afranklin** [comment]
@wangchuanya Can you please try @znation's suggestion and let us know if the issue still repos? thanks.
