### ISSUE TITLE
[ranking_factorization_recommender] - negative sampling 

### ISSUE THREAD

**Issue by benjaminbraunberkeley** [apple/turicreate#2025]
Hi,

I am currently using the ranking_factorization_recommender. When the BPR is done and a negative sample is chosen, I believe that the sample is currently chosen among all other possibilities.

I was wondering if it could be possible to modify this and make use of a column giving information on the items. When sampling for negative samples (ie looking for user/item pairs that never existed) at training time, items would be sampled only from a particular category. I believe that this would speed up the training process, as mentioned here (from paper http://www.shuwu.name/sw/PRFM.pdf ): " when the number of items is very large, the random sampler will derive massive meaningless and ineffective training instances which can not provide much helpful information to tune the personalized ranking lists. For example, in common sense, we can not say that a user dislikes a smart phone because he likes a toothbrush, and this pair, i.e., toothbrush and smart phone, is meaningless in real-world scenarios."

Would you know where in the code I should look at in order to modify this sampling strategy? Or are you planning to enable this feature altogether? 

Thank you very much in advance

Best,

Benjamin

**Comment by hoytak** [comment]
Hello @benjaminbraunberkeley,

Thanks for your interest in this!  I'm happy to provide you with some guidance if you want to dig into this more.  I don't think we'll be implementing this, but you're welcome to play around with it.  The sampling code is in the choose_negative_example method of src/unity/toolkits/factorization/ranking_sgd_solver_base.hpp.  

The challenge with weighted sampling strategies is that there are a lot of side effects that are not immediately intuitive here. The negative sampling works more as a regularizer on the solution than as an objective to maximize the difference between the positive and negative examples.  The real objective is to end up with a solution such that the predicted scores of the negative items -- those that the negative sampling suppresses -- are actually ranked according to the users preferences.  In other words, the question to ask is actually "Which unobserved items are most resistant to being suppressed?"  This question then leads us to assume that the sampling should be effectively exchangeable or uniform.  Thus, if you target ones that are the most "sensible" to suppress, you may decrease their predictive score while, as a side effect, you increase the predicted score of less desirable user-item pairs.  

Looking at the paper you mentioned, I'm quite skeptical.  First, it's relatively expensive to do their sampling - while theirs converges faster per iteration, each iteration is substantially more expensive than MF-BPR.    One could do 20-30 iterations of the MF-BPR method in one iteration of PRFM.  (See Figure 3 vs. Figure 4).  Second, we did not find vanilla MF-BPR to perform that well; it should be combined with choosing the negative sample as the one in a large randomly drawn pool that has the largest predicted score, then adjust the negative sampling pool size -- how many negative samples are considered before one is chosen for the sgd descent -- to accommodate users rating a small proportion of items.   This is still very efficient.   Third, AUC is a weird metric in this case for the reasons given above, and the fact that they don't give details on the number of iterations for different methods in Table 2 or Table 3 also makes me skeptical.

**Comment by benjaminbraunberkeley** [comment]
Hi @hoytak! Thanks very much again for your detailed answer! That's very helpful
