### ISSUE TITLE
SoundClassifier Prepocessing Issue

### ISSUE THREAD

**Issue by joshalva** [apple/turicreate#2027]
Hi, 
I'm currently working on an app that uses turicreate's sound classifier, everything works fine but I get issues on building the archive for submitting to TestFlight. 
I can't address the issue either to the model or to the libAudioPreprocessing.dylib. The recurrent error that I get, even trying all the suggested fixes I found around the web, is "Invalid Swift Support - The SwiftSupport folder is missing.". Is there anyone with the same issue that solved? Thanks in advance

**Comment by TobyRoseman** [comment]
Let's track this issue in #2050. That issue is more general (mentions the recommenders dylib too). #2050 also contains a workaround for this issue.
