### ISSUE TITLE
SoundClassifier python example deploy iOS error, model spec incomplete?

### ISSUE THREAD

**Issue by erik-cog** [apple/turicreate#2030]
Following the turicreate guide for the sound classifier verbatim, with turicreate v5.6 and (v5.6 of libAudioPreprocessing.dylib, both added to project, lib added to build phases following guide), the app crashes when trying to init the model. Specifically, the mlmodel appears to be missing part of its input pipeline, the TCSoundClassifierPreprocessing. Is it possible the model spec isn't being fully fleshed out in `model = tc.sound_classifier.create(train_set, target='category', feature='audio'), model.export_coreml('sound_classifier.mlmodel')`?

The app crashes in the model's .m file at:
`convenience init() {`
`        try! self.init(contentsOf: type(of:self).urlOfModelInThisBundle)`
`}`

The xcode debugger output is:
`[coreml] This custom model requires an implementation named 'TCSoundClassifierPreprocessing' which was not found in the gloabl namespace`

... similar output repeated ...

`[coreml] MLModelAsset: load failed with error Error Domain=com.apple.CoreML Code=5 "This custom model requires an implementation named 'TCSoundClassifierPreprocessing' which was not found in the gloabl namespace" UserInfo={NSLocalizedDescription=This custom model requires an implementation named 'TCSoundClassifierPreprocessing' which was not found in the gloabl namespace}`

`Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=com.apple.CoreML Code=5 "This custom model requires an implementation named 'TCSoundClassifierPreprocessing' which was not found in the gloabl namespace" UserInfo={NSLocalizedDescription=This custom model requires an implementation named 'TCSoundClassifierPreprocessing' which was not found in the gloabl namespace}: file`

**Comment by erik-cog** [comment]
I should have specified the turicreate SoundClassifier example I followed (no changes except exported coreml model filename): https://apple.github.io/turicreate/docs/userguide/sound_classifier/.

**Comment by TobyRoseman** [comment]
@erik-cog - are you using the right `.dylib` file? If you are writing an app for a Mac or the iOS simulator, you want the `.dylib` file in the x86_64 sub folder. If you are writing an iOS app for the iPhone/iPad, you would want the `.dylib` file in the arm64 subfolder.

**Comment by erik-cog** [comment]
@TobyRoseman - I used the arm64 dylib with an iPhone device. I originally tried the x84_64 version with the simulator (with error), and later refreshed the project after removing all instances of the original dylib, adding the arm64, and repeating the build phases and general linked libraries and embedded binaries steps with the same error.

**Comment by erik-cog** [comment]
Poking around in Library/Python/2.7/lib/python/site-packages/turicreate/toolkits/sound_classifier/sound_classifier.py, in the function `export_coreml(self, filename)`, it starts creating the spec on line 664, builds a pipeline with the preprocessing specified as including the TCSoundClassifierPreprocessing:
`preprocessing_model.customModel.className = 'TCSoundClassifierPreprocessing'`
However, this does not seem to make it into the model it subsequently exports. My coremltools version is at 2.1, which should be recent enough (its the last non-beta release). 

The pipeline spec appears to be generated properly, but the top_level_spec appears to be not assembled properly. Perhaps it would be cleaner to define the Pipeline and incorporate the input, preprocessing, the vggish model and the custom network we train on top and save that pipeline.spec? I've tried a few other ways of saving but with no success:
```
coremltools.utils.save_spec(top_level_spec.spec, 'spec_'+filename)
coremltools.utils.save_spec(pipeline, 'pipeline_'+filename)
mlmodel = coremltools.models.MLModel(top_level_spec.spec)
mlmodel.save(filename)
```

**Comment by TobyRoseman** [comment]
I'm not able to reproduce this issue. I just deployed and ran a sound classifier model on iOS using the 5.6 Python wheel and dylib.

The `TCSoundClassifierPreprocessing` custom model is included in the `libAudioPreprocessing.dylib` file. The implementation can be found [here](https://github.com/apple/turicreate/blob/411fa92aa926726a01f5218615e80d0a38fdf82e/src/objc/AudioPreprocessing.m#L246).

I don't really know what's going on here. It seems the dylib file is not actually being deployed to the iOS device.

Here are somethings you could try:
- Delete the dylib file from your project and re-add it. Make sure the "Copy items if needed" button is selected.
- In addition to the instructions in the user guide, make sure the dylib file is included in both "Link Binary With Libraries" and "Embed Libraries", under "Build Phases". It should have automatically been added there but please verify.
- Make sure that the dylib file has the correct target membership in the inspector (i.e. right side) panel.

**Comment by erik-cog** [comment]
Ran thru the dylib adding process twice more, with a new error the second time, about bitcode compilation of the dynlib, so following https://stackoverflow.com/questions/31088618/impact-of-xcode-build-options-enable-bitcode-yes-no I disabled bitcode build and lo and behold, it works!
