### ISSUE TITLE
question: style transfer

### ISSUE THREAD

**Issue by romanoss** [apple/turicreate#2032]
what does "include_flexible_shape" in style_transfer.py exactly do?

**Comment by TobyRoseman** [comment]
@romanoss - Did you figure out the answer? If so, please share the answer, or even better submit a pull request to make this clear in the documentation.

**Comment by romanoss** [comment]
@TobyRoseman 

Dear Toby
I figured it out.
As you are a much more experienced ml expert than I, you always knew the answer.
The better questions are:
Why is there only a basic documentation of tc?
Why is tc not developing more?
I can see createml is the main dev effort, but serving more models and parametric options can be a way
for tc to be more important - in the meanwhile tc more and more seems to be a playground.
I only made experiences with your yolo model and the style transfer model.
For the yolo model, there is good news in createml.
I am currently trying out style transfer models and I see that the is so much development in this area,
It's not easy to see why the transfer results are not as good as single model results in tf, but I like the possibility of calculating several styles into one model.
vgg19 with cocotrain images can produce quite nice tf models.
And so on.....
Hope the tc team will not only do bugfixing in the future.

Why am I not submitting a pull request for documentation?
Hmm. Maybe because the pros should have done it.

**Comment by TobyRoseman** [comment]
@romanoss - Sorry but I don't know the answer to this question. I do agree the docstring information for that parameter isn't clear. Let's leave this issue open until that is fixed.

If you have specific feature requests or specific issues with the documentation, please open up additional GitHub issues.

**Comment by romanoss** [comment]
@TobyRoseman
flexible_shape is a model feature, that you can add with coremltools.
It allows input and output images of a model to be defined, so that the image size is flexible in a defined range. Eg in style transfer the produced model can accept images in a size range from 64 to infinity (which means only memory is the limit) - when one uses a 6MPixel image memory usage jumps to over 1 GB :)

**Comment by TobyRoseman** [comment]
@romanoss - Thanks for the information. I'll dig into this parameter a bit more myself and then put up a pull request to update the docstring.
