### ISSUE TITLE
Performance Issues in TC5  xgboost

### ISSUE THREAD

**Issue by guy4261** [apple/turicreate#2033]
Hello,

We've ([@guyinbar](https://github.com/guyinbar) and I) noticed performance degradation in the TC5 versions.

You can run the zipped Python script under multiple environments using `tox`, and you'll see it too. On 1M rows the differences are ~10s in TC4, 20s in all TC5 variants. But this is not a matter of import times, etc - when you raise the number of rows/columns you'll see more clear differences.

[xgboost_tc_performance_test.zip](https://github.com/apple/turicreate/files/3264801/xgboost_tc_performance_test.zip)

**Comment by hoytak** [comment]
Confirmed resolved (as a workaround) by https://github.com/apple/turicreate/pull/2141.  Root cause is https://github.com/apple/turicreate/issues/2175; tracked separately.
