### ISSUE TITLE
SArray == doesn't work for tc.Image types

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#2042]
Using turicreate 5.6 the following code:
```python
import turicreate as tc

i = tc.load_images('./test/images/sample.png')
i = i['image']

print("Images are equal: " + str(
    i[0] == i[0]
))
print("SArray indexes equals: " + str(
    i == i
))
```
Produces: 
```
Images are equal: True
SArray indexes equals: [0]
```

So `==` works when comparing instances of `tc.Image` directly but doesn't work when they are inside an `SArray`.

**Comment by chidauri** [comment]
@TobyRoseman Hi, i am looking forward to fix this, i have a doubt, do we need to run ./configure and then build using "make" everytime we do a change? And is there any discussion platform for this repo?

**Comment by sirahd** [comment]
I have tracked down the comparison logic to [unity_sarray_binary_operations.cpp](https://github.com/apple/turicreate/blob/037e112032c40c330885bf9cb7ba136d7a61e020/src/core/storage/sframe_interface/unity_sarray_binary_operations.cpp#L527) where the equality is performed by address comparison for every type. The fix would be to use image comparison if both elements are images. Are there any other types that would require special handling other than image?
