### ISSUE TITLE
recommend_from_interactions --exclude doesn't work properly

### ISSUE THREAD

**Issue by junyafang** [apple/turicreate#2044]
![图片](https://user-images.githubusercontent.com/46369892/59239630-bf77d380-8c34-11e9-971e-545703599f49.png)
![图片](https://user-images.githubusercontent.com/46369892/59239678-e7673700-8c34-11e9-825b-d4172a80025c.png)
recommend can gets rid of 14 correctly,but recommend_from_interactions  doesn't work properly.

**Comment by junyafang** [comment]
Who can tell me how to make it work ? Many thanks!

**Comment by hoytak** [comment]
Just use the movieID column of the exclude_pairs SFrame, and the movieID column of ob as well. 

The real bug here is that the recommend_from_interactions should not accept user information as part of either parameter and should instead error out.  Essentially, all the user data is dropped and not handled consistently, which is causing this issue.

**Comment by junyafang** [comment]
> 
> 
> Just use the movieID column of the exclude_pairs SFrame, and the movieID column of ob as well.
> 
> The real bug here is that the recommend_from_interactions should not accept user information as part of either parameter and should instead error out. Essentially, all the user data is dropped and not handled consistently, which is causing this issue.

Thanks for your reply!As shown below, recommend_from_interactions still can't rule out movieid 14.
Also,I would like to make a personalized recommendation system，if I don't use the userId，dose the result of recommendation have personality? Please help me...
![图片](https://user-images.githubusercontent.com/46369892/59396810-f842b480-8dbc-11e9-82cf-1f8258c1ae6b.png)
![图片](https://user-images.githubusercontent.com/46369892/59396862-232d0880-8dbd-11e9-828c-a3e9fc99f453.png)

**Comment by dhivyaaxim** [comment]
@znation  Please assign this ticket to me as I would like to try fixing it and contribute .Thanks in advance!

**Comment by znation** [comment]
Hi @dhivyaaxim, sure, thanks for your help!
