### ISSUE TITLE
Turicreate GPU Utilisation  - 5.6 version

### ISSUE THREAD

**Issue by dhgokul** [apple/turicreate#2047]
@gustavla  @srikris  
Modified turicreate script to set GPU option 
**Code snippet :** 
tc.config.set_num_gpus(-1)

Run turicreate script and check top cmd, multiple process is created
![top_cmd](https://user-images.githubusercontent.com/5689804/59357847-2a1a3380-8d49-11e9-9692-8350984a1405.jpeg)

Checked nvidia GPU and we are able to see only single GPU process instead of (4 GPUS) process updated in turicreate command

![turicreate_GPU](https://user-images.githubusercontent.com/5689804/59357864-30101480-8d49-11e9-8e9f-bfc3b1922fbb.jpeg)

**Cuda version :**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176 

Ubuntu version: 16.04.6 LTS 

**Turicreate version :**   5.6

Any help appreciated !!!

**Comment by TobyRoseman** [comment]
@dhgokul - What toolkit are you using? How large is your data? Have you tried increasing the batch size?

**Comment by dhgokul** [comment]
@TobyRoseman Thanks for your response ! 
toolkit - turicreate object detection
Dataset size around kb 
No we are using default batch size

**Comment by dhgokul** [comment]
@TobyRoseman Increased batch size to 64 in create method, still single GPU only running. Any changes need to be done ?

**Comment by TobyRoseman** [comment]
@dhgokul - For the one GPU which is getting used, is it being used close to 100%?

I would try increasing the batch size even more.

Also let's make sure we're finding all of your GPUs. Please verify that the following finds all four of your GPUs:
```python
from turicreate.toolkits._mxnet import _mxnet_utils
print(_mxnet_utils.get_num_gpus_in_use())
```

**Comment by dhgokul** [comment]
@TobyRoseman  Yes, CPU utilized ~ 100 , when increase higher batch size , i got memory error
WARNING:

    You may not have enough free GPU memory to create this model, which may
    result in a fatal crash or lower performance. We recommend that you have at
    least 11430 MiB available on each GPU, while currently you have only 11272
    MiB free (out of 11439 MiB) on GPU #0. Please close all other processes
    that may be using this GPU.

Run the code snippet and no of GPU is 1 . how to utilize all gpus ?

Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from turicreate.toolkits._mxnet import _mxnet_utils
>>> print(_mxnet_utils.get_num_gpus_in_use())
1

**Comment by TobyRoseman** [comment]
So it looks we're only finding one of your GPUs. That explains why Turi Create is only using one GPU.

The other GPUs may not be setup correctly. What's the output of the following system command?
`nvidia-smi --query-gpu=index,gpu_name,memory.free,memory.total --format=csv,noheader,nounits`

**Comment by dhgokul** [comment]
@TobyRoseman Please see the details below

~/turicreate# nvidia-smi --query-gpu=index,gpu_name,memory.free,memory.total --format=csv,noheader,nounits
**0, Tesla K80, 785, 11439**

**Comment by TobyRoseman** [comment]
@dhgokul - Are you sure you have four GPUs? It looks like only one is setup. In order for Turi Create to use GPUs they must be properly setup through the NVIDIA System Management Interface. 

This isn't a Turi Create issue, so I'm going to close this issue. Let us know if you have any other questions.

**Comment by dhgokul** [comment]
@TobyRoseman Thanks will check GPU setup
