### ISSUE TITLE
Object Detection Data Question?

### ISSUE THREAD

**Issue by arinasawa** [apple/turicreate#2065]
I have a question regarding the data collection aspect of object detection. Suppose I have 3 classes: Banana, Tomato, and Potato that I want to recognize. Is it fine if in my dataset there are images that contain 2 of these classes such as Banana and Tomato but I only label one. Would that make the model confused? Or do I have to label all instances of every class in every image?

**Comment by srikris** [comment]
You should label every instance in the image to get the best results. The network will be robust to a small fraction of badly labelled data but not systematically missing labels in all images. To get the best performance, the data quality should be high.

**Comment by arinasawa** [comment]
Ok all right thanks. Also I have been trying to train my machine learning models on the could using intel AI devcloud but I can't figure out how. Can you look into it? Training on my Mac takes forever because I have an integrated gpu!
