### ISSUE TITLE
Unclear error message in apply method when most values are None

### ISSUE THREAD

**Issue by alonpal** [apple/turicreate#2066]
When all rows used by the `apply` method for type inference return `None`, then the resulting `SArray` defaults to float.  I know this can be solved by specifying `dtype` but the error message should be clearer, especially when considering lazy operations.

Running:

```python
import turicreate as tc
a = tc.SArray(list(range(100000)))
b = a.apply(lambda x: None if x < 1000 else str(x))
b.materialize()
```

Results in:
`TypeError: Cannot convert 41666 to float`

I suggest something along the lines of `TypeError: Cannot convert 41666 of type XXXX to float which is the type of the SArray. If this is not the correct type try specifying it during creation`

**Comment by dhivyaaxim** [comment]
@TobyRoseman @znation Please assign this ticket to me as I would like to try fixing it and contribute .Thanks in advance!
