### ISSUE TITLE
Turicreate model support - Object detection

### ISSUE THREAD

**Issue by dhgokul** [apple/turicreate#2072]
@TobyRoseman  Object detection - What types of model support in turicreate other than dark-yolo ?

turicreate.object_detector.create(dataset, annotations=None, feature=None, **model='darknet-yolo'**, classes=None, batch_size=0, max_iterations=0, verbose=True, **kwargs)

**Comment by TobyRoseman** [comment]
@dhgokul - currently only `darknet-yolo` is supported. Let us know if you have suggestions for other models we should support.

**Comment by TobyRoseman** [comment]
We are already tracking adding support for additional object detection models in the following issue: #1734.

**Comment by dhgokul** [comment]
@TobyRoseman  Is there any support for Android version like tensorflow which has support both iOS and Android ?

**Comment by TobyRoseman** [comment]
@dhgokul - I'm not sure I understand your question. Turi Create does not support exporting models to TensorFlow. If that doesn't answer your question, please clarify your question.

**Comment by Zumbalamambo** [comment]
@dhgokul apple does not like android sorry
