### ISSUE TITLE
Input feature features was presented as an array of size (1, 50, 6), but the model expects an input of size (1, 50, 7).

### ISSUE THREAD

**Issue by RobinChao** [apple/turicreate#209]
when use the activity classifier model in iOS app,  the console log output 'Input feature features was presented as an array of size (1, 50, 6), but the model expects an input of size (1, 50, 7).'

**Comment by alonpal** [comment]
Thank you for trying out the activity classifier. I assume you are referring to the user guide example. There is a mistake in the example where the model also considers the ```user_id``` column.
You can fix this by replacing the model creation with:
```
features = ['acc_x', 'acc_y', 'acc_z', 'gyro_x', 'gyro_y', 'gyro_z']
model = tc.activity_classifier.create(train, session_id='exp_id', target='activity', features=features, prediction_window=50)
```
Or by removing the ```user_id``` column before model creation via:
```
data = data.remove_column('user_id')
```
We will update the example to reflect these changes.
