### ISSUE TITLE
Model output sensitive to Xavier initialization

### ISSUE THREAD

**Issue by fareeha** [apple/turicreate#2092]
In some cases Xavier init of the softmax layer for the same model, same classes and same data produced accuracy disparity > 10% across two different trials. It's not clear how much a random seed effects a model's accuracy. 

<img width="1379" alt="TC Training - classes axis" src="https://user-images.githubusercontent.com/6214406/60233226-4b544700-9854-11e9-89b0-763ea6d9601b.png">

<img width="1389" alt="TC train repeat" src="https://user-images.githubusercontent.com/6214406/60233259-5c04bd00-9854-11e9-8f09-9209395d60bf.png">

**Comment by TobyRoseman** [comment]
Is there a preposed fix or workaround for this issue? Should we just add a seed parameter (similar to #2081 for the activity classifier)?

**Comment by fareeha** [comment]
To make the output deterministic at every run for the same configuration, it helps to fix the seed for numpy and mxnet.

**Comment by nickjong** [comment]
Let's start by trying to understand more fully the sensitivity to the weight initialization. That will inform whether we resolve this by changing how we initialize/train or just by providing more guidance in documentation
