### ISSUE TITLE
MAC - Turicreate tc.object_detector.util.draw_bounding_boxes error

### ISSUE THREAD

**Issue by dhgokul** [apple/turicreate#2094]
@srikris  @gustavla 

MAC - Install turicreate in virtual env and run the below code for prediction and visualise image with bounding box

Got error as TypeError: cannot concatenate 'str' and 'exceptions.AttributeError' objects

Code snippet :

import turicreate as tc
#load image 
test = tc.SFrame({'image': [tc.Image('amit1517.jpg')]})
#load the model
model = tc.load_model('mymodel.model')
test['predictions'] = model.predict(test)
print(test['predictions'])
#this part work only on Mac
test['image_with_predictions'] = \
    tc.object_detector.util.draw_bounding_boxes(test['image'], #test['predictions'])
test.explore()

Error :

Traceback (most recent call last):

  File "test.py", line 9, in <module>

    test['image_with_predictions'] = tc.object_detector.util.draw_bounding_boxes(test['image'], test['predictions'])

  File "/Users/test/venv/lib/python2.7/site-packages/turicreate/toolkits/object_detector/util/_visualization.py", line 163, in draw_bounding_boxes

    annotated_images = sf.apply(draw_single_image)

  File "/Users/test/venv/lib/python2.7/site-packages/turicreate/data_structures/sframe.py", line 2479, in apply

    dryrun = [fn(row) for row in test_sf]

  File "/Users/test/venv/lib/python2.7/site-packages/turicreate/toolkits/object_detector/util/_visualization.py", line 155, in draw_single_image

    raise _ToolkitError("Received exception at row " + str(row_number) + ": " + e)

TypeError: cannot concatenate 'str' and 'exceptions.AttributeError' objects

**Comment by fareeha** [comment]
@dhgokul What version of TC are you using?

**Comment by fareeha** [comment]
A quick fix is to edit the line to `raise _ToolkitError("Received exception at row " + str(row_number) + ": " + str(e))` in your local code. This change will ship in our next version release of PyPI.
