### ISSUE TITLE
Object Detection Example data path error

### ISSUE THREAD

**Issue by adityas** [apple/turicreate#2096]
I am following the steps in Task Focused Toolkits > Object Detection > [Data Preparation](https://apple.github.io/turicreate/docs/userguide/object_detection/data-preparation.html)

**Steps to Reproduce:**
After downloading and decompressing the data, when using the provided example script to turn the data into an sFrame, I get the following error:

`turicreate.toolkits._main.ToolkitError: ~/Downloads/ig02 not found.`

**Resolution**:
This was resolved by using an absolute path. 

Suggested change: Either the documentation or the way the path is read by `tc.image_analysis.load_images` may need to be modified. Thanks!

**Comment by mfriedel** [comment]
I ran into the same problem (and used the same solution) when walking through this code.

**Comment by TobyRoseman** [comment]
`~` maps to the user's home directory. This path will contain the user's username which will be different for everyone. So I think it makes sense to use a relative path here.
