### ISSUE TITLE
Download yolo config and weight from trained model

### ISSUE THREAD

**Issue by dhgokul** [apple/turicreate#2107]
@TobyRoseman Is there any possible way to get yolo config and yolo weight file when train turicreate model
sample : cfg/yolov3.cfg yolov3.weights

**Comment by TobyRoseman** [comment]
I know of no way to get the data in that format.

You should be able to get the data as numpy arrays with the following code:
```python
mxnet_params = my_object_detection_model._model.collect_params()
net_params = { k : mxnet_params[k].data().asnumpy()
                                   for k in mxnet_params }
```

Hope that helps.

**Comment by dhgokul** [comment]
Thanks @TobyRoseman will check
