### ISSUE TITLE
No draw_strokes link in API docs

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#2112]
The "util.draw_strokes" entry in the "utilities" table at the bottom of [the Drawing Classifier API docs](https://apple.github.io/turicreate/docs/api/turicreate.toolkits.drawing_classifier.html) looks like a link and should be a link, but isn't actually a link.

Also when building the documentation this warning appears **hundreds** of time:
`<partial node>:: WARNING: toctree contains reference to nonexisting document 'generated/util.draw_strokes'`

**Comment by nickjong** [comment]
Pulling into 5.7 since I expect this to be a simple fix...
