### ISSUE TITLE
Exporting Image Similarity model to CoreML?

### ISSUE THREAD

**Issue by jgaynor** [apple/turicreate#212]
After creating an Image Similarity model it appears as if there's no way to export this model to Core ML currently. Is this correct? If so, which model do you suggest if I'm looking to pass a model an image and match it to a predefined list of images as best as possible? Would image classification work in that case?

**Comment by srikris** [comment]
This is correct. This is currently not supported.

We'd like to understand your use case a bit better i.e where are the images stored? Is this for an app that you are building?

**Comment by jgaynor** [comment]
Thanks for your reply. This is for an iOS app where the images would be stored locally (within the app or model). The user’s camera would be used to recognize a series of predefined cards.

**Comment by srikris** [comment]
@jgaynor We are happy to discuss your use case a bit more because it's something that will come up for other people.  If you have an email account that we can reach you from GitHub, we can definitely follow up.

**Comment by jgaynor** [comment]
Thank you for your reply - you can reach me via email at jgaynor@weblications.com.

**Comment by alonpal** [comment]
@jgaynor We are working on supporting this feature, thank you for your patience.

**Comment by srikris** [comment]
We think we have a solution. Worked in progress on #242. Feel free to comment on that.

**Comment by znation** [comment]
Fixed in #242.
