### ISSUE TITLE
not able to install graphlab

### ISSUE THREAD

**Issue by sreejacg** [apple/turicreate#2139]
ERROR: HTTP error 404 while getting https://get.graphlab.com/GraphLab-Create/2.1/mail id/product key

Please help

**Comment by sreejacg** [comment]
the above error is resolved

I am getting the below

ERROR: sphinx 1.3.5 has requirement colorama>=0.3.5, but you'll have colorama 0.2.5 which is incompatible.
ERROR: s3transfer 0.2.0 has requirement botocore<2.0.0,>=1.12.36, but you'll have botocore 0.73.0 which is incompatible.
ERROR: numpydoc 0.9.1 has requirement sphinx>=1.6.5, but you'll have sphinx 1.3.5 which is incompatible.
ERROR: boto3 1.9.162 has requirement botocore<1.13.0,>=1.12.162, but you'll have botocore 0.73.0 which is incompatible.
ERROR: boto3 1.9.162 has requirement jmespath<1.0.0,>=0.7.1, but you'll have jmespath 0.5.0 which is incompatible.
ERROR: jupyterlab-launcher 0.11.2 has requirement jsonschema>=2.6.0, but you'll have jsonschema 2.5.1 which is incompatible.
ERROR: s3fs 0.2.1 has requirement botocore>=1.12.91, but you'll have botocore 0.73.0 which is incompatible.
ERROR: s3fs 0.2.1 has requirement six>=1.12.0, but you'll have six 1.10.0 which is incompatible.

ERROR: Cannot uninstall 'colorama'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by TobyRoseman** [comment]
This its the repository for Turi Create not GraphLab Create. GraphLab Create has long been deprecated. Please use Turi Create instead. If there is a reason you can not use Turi Create, please open a separate issue.
