### ISSUE TITLE
Breaks compatability with click library.

### ISSUE THREAD

**Issue by skirdey** [apple/turicreate#2165]
https://github.com/apple/turicreate/blob/4a8bbf96c6dfd1b302fc264e58ddc2c04f398431/src/python/turicreate/_sys_util.py#L76

RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8

**Comment by TobyRoseman** [comment]
Related to #1862

**Comment by hoytak** [comment]
We should just remove that line and make sure all the tests pass.  I believe that was a workaround for something that is no longer an issue.
