### ISSUE TITLE
 Internal groupby does not use atomics where appropriate

### ISSUE THREAD

**Issue by hoytak** [apple/turicreate#2175]
Currently, the internal groupby operators always use locks, even when a lockfree implementation is possible.  This can cause significant slowdowns, most notably when groupby COUNT aggregation is used on a dataset where most of the items are the exact same category.  

The correct behavior should be to define the groupby operator APIs to control whether the core algorithm locks or doesn’t lock based on the result of this API.  The operators that can should then use lock-free operations.

**Comment by hoytak** [comment]
To do this: 

First, write a benchmark test in the C++ code that can be executed.  Use sframe testing utils.  Benchmark on one with groupby count on a binary category.  This should show a lot of slowdown and not be faster with more threads.  Follow sframe/sframe_bench.cpp example. 

Add a virtual function `virtual bool lock_needed() const = 0;` to base class in https://github.com/apple/turicreate/blob/master/src/core/storage/sframe_data/group_aggregate_value.hpp.

Individual implementations in https://github.com/apple/turicreate/blob/master/src/core/storage/sframe_data/groupby_aggregate_operators.hpp then implement this, with count, min, max, etc. using approiate atomic operations instead of relying on the lock. 

Then, the add implementation in https://github.com/apple/turicreate/blob/master/src/core/storage/sframe_data/groupby_aggregate_impl.cpp#L237 would query this to see if it needs to be locked or not.  If not, it skips the lock/unlock step.

**Comment by hoytak** [comment]
This ends up being harder than anticipated due to some other parts of the groupby code base, so I think we should push this out to 5.8 to give us time to do it right and fully bake this release.

**Comment by Jarvi-Izana** [comment]
Sounds like a plan. I will all my code change.

**Comment by Jarvi-Izana** [comment]
#2210
