### ISSUE TITLE
[Question] Do we have ML example tasks for timeseries data anomaly detect ?

### ISSUE THREAD

**Issue by foreversunyao** [apple/turicreate#2177]
as title .

**Comment by foreversunyao** [comment]
like EWMA or Seasonal data trend related

**Comment by TobyRoseman** [comment]
@foreversunyao - no we do not have examples of that. Can you tell us more about your use case?

**Comment by foreversunyao** [comment]
@TobyRoseman  yeah, I was trying to use turicreate to do some anomaly detect on the monitor data(trend metrics), don't know Turi can work on this data by using EWMA ?
