### ISSUE TITLE
Smaller data set, larger mlmodel size

### ISSUE THREAD

**Issue by Daemon-Devarshi** [apple/turicreate#219]
I am using around 12 images to obtain a trained modal using turiecreate, total size is approximately 1000 KB. Dimension of each image varies from 176x417 to 400x448. The size of final mlmodel obtained is around 94.2 MB. Is there any to bring down the size of final mlmodel? Please suggest.

Here is the script used to load image data into data frame:

```
import turicreate as tc

# load data
image_data = tc.image_analysis.load_images('images', with_path=True)  
  
labels = ['1', '4', '8', '9', 'a']
  
def get_label(path, labels=labels):  
    for label in labels:  
        if label in path:  
            return label  
  
image_data['label'] = image_data['path'].apply(get_label)  
 
# save data  
image_data.save('chars.sframe')
 
# explore  
image_data.explore()
```

Here is the script used to obtain the model:

```
import turicreate as tc

# Load the data
data = tc.SFrame('chars.sframe')

# Make a train-test split
train_data, test_data = data.random_split(0.8)

# Create a model
model = tc.image_classifier.create(train_data, target='label', max_iterations=1000)

# Save predictions to an SFrame (class and corresponding class-probabilities)
predictions = model.classify(test_data)

# Evaluate the model and save the results into a dictionary
results = model.evaluate(test_data)
print "Accuracy         : %s" % results['accuracy']
print "Confusion Matrix : \n%s" % results['confusion_matrix']

# Save the model for later usage in Turi Create
model.save('Chars.model')
```

Here is the script used to convert obtained model into Core ML model:

```
import turicreate as tc
model = tc.load_model('Chars.model')
model.export_coreml('Chars_CoreML.mlmodel')
```

**Comment by igiloh** [comment]
Hi @Daemon-Devarshi , thank you for taking interest in the image classifier!

By default, the classifier uses resnet model, which is indeed larger in model size.
Please try adding the parameter `model='squeezenet_v1.1'` to your `create()` call. Using squeezenet should provide a much smaller model.
