### ISSUE TITLE
one_shot_object_detector gets killed because high memory usage

### ISSUE THREAD

**Issue by MaximBazarov** [apple/turicreate#2191]
I'm running to this issue, with a simple data set of 180 images, pretty small, on the peak before getting killed python process uses 62 GB of memory 16 is physical and the rest is a swap.

Here's the project with all the images and the script: [https://github.com/MaximBazarov/experiment_one_shot_object_detector](https://github.com/MaximBazarov/experiment_one_shot_object_detector)

**python3 model_create.py**          
**Python 3.6.5**
**pip freeze**
```sh
certifi==2019.6.16
chardet==3.0.4
coremltools==2.1.0
decorator==4.4.0
graphviz==0.8.4
idna==2.8
llvmlite==0.29.0
mxnet==1.1.0.post0
numba==0.45.0
numpy==1.17.0
pandas==0.25.0
Pillow==6.1.0
prettytable==0.7.2
protobuf==3.9.0
python-dateutil==2.8.0
pytz==2019.2
requests==2.22.0
resampy==0.2.1
scipy==1.3.0
six==1.12.0
turicreate==5.6
urllib3==1.25.3
```

the last breath: 
```sh
| 23750            | 22m 34s      | 8.75%            |
| 24000            | 22m 51s      | 9%               |
| 24250            | 22m 59s      | 9%               |
| 24500            | 23m 7s       | 9.25%            |
[1]    5051 killed     python3 model_create.py

```

**Comment by syoutsey** [comment]
Hi @MaximBazarov we have an issue tracking this bug along with it's fix here: https://github.com/apple/turicreate/issues/2038
