### ISSUE TITLE
load_model can't find a model

### ISSUE THREAD

**Issue by MaximBazarov** [apple/turicreate#2198]
Trying to load a previously saved by `model.export_coreml('grn.mlmodel')` model:
```python
import turicreate as tc
model = tc.load_model('grn.mlmodel')
```
heres the files tree
```
.
├── grn.mlmodel
├── model_create.py
└── test_model.py
```

Getting  an error:
```
Traceback (most recent call last):
  File "test_model.py", line 5, in <module>
    model = tc.load_model('grn.mlmodel')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/turicreate/toolkits/_model.py", line 68, in load_model
    raise IOError("Directory %s does not exist" % location)
OSError: Directory grn.mlmodel does not exist
```

**Comment by MaximBazarov** [comment]
same goes for ```model = tc.load_model('grn.mlmodel/')``` in case it makes diference

**Comment by abhishekpratapa** [comment]
@MaximBazarov unfortunately CoreML models aren't loadable in TuriCreate. The `load_model` function only works for models saved in TuriCreate. This means using the `save` method present on a trained TuriCreate model.

The `export_to_coreml` method creates a CoreML file that can be consumed by Xcode, for example maybe an iOS app. I'm not certain what your code is in the file `model_create.py` but I suspect you have an `export_to_coreml` call in there. Change that to `save` and you'll have a loadable TuriCreate model.

If you need any other help please feel free to re-open the issue!
