### ISSUE TITLE
No matching distribution found for coremltools==0.6.3

### ISSUE THREAD

**Issue by iblisylvie** [apple/turicreate#22]
![2017-12-09 8 45 36](https://user-images.githubusercontent.com/1615429/33795751-0ea45758-dd22-11e7-9098-821b5f10f521.png)

The latest version of coremltool I am able to install is 0.5.1 with python 2.7.10

**Comment by gustavla** [comment]
What is your OS? It looks like at 0.5.1 they had a single wheel covering all platforms, but after that they switched to one for macOS (only 10.12/10.13) and one for Linux. If you do not have either of those platforms (such as macOS 10.11), you will probably run into issues.

I noticed that the readme says Turi Create supports 10.11, but now looking at the coremltools wheels, that can't be the case.

**Comment by gustavla** [comment]
Actually, support for macOS 10.11 is a typo (#24). We will look into if we can add support soon (#23). Let me know if you are on a different platform altogether though.

**Comment by srikris** [comment]
Using #23 to track the mac10.11 support.

**Comment by iblisylvie** [comment]
Thanks for the answering. My os is 10.11.6.

**Comment by cnnsbs** [comment]
I have same problem.
python 2.7.13, anaconda, windows 10

**Comment by mnazam** [comment]
Same problem as above on Windows 10.

**Comment by gustavla** [comment]
@cnnsbs @mnazam Are you trying this using WSL? I think this might be the error you would get if you do it on Windows but without WSL.

**Comment by ariosking** [comment]
same problem，can't install via pip install -U turicreate

**Comment by igiloh** [comment]
Hi @ariosking, thank you for your input!
Can you please tell us which OS you're using?
And if it's windows 10 - are you using WSL?

**Comment by T-Cornelis** [comment]
@igiloh @gustavla  Hello, I have the same problem on Windows 10. I have an x64 PC and have installed WSL. Had the problem both before and after installing WSL (dunno how to check whether the WSL is working).

**Comment by RSherwoodJr** [comment]
Just want to chime in: I'm having the same issue on Windows 10.  Tried on both Python 3.6 and 2.7, with and without 2.7 virtual environments.

**Comment by gustavla** [comment]
@T-Cornelis @RSherwoodJr Can you please confirm that WSL is enabled? From what I understand, it must be enabled by the user and not simply installed. I don't know exactly how to do this, but a search for "Enable WSL" seems to give plenty of tutorials of how to do it.

**Comment by T-Cornelis** [comment]
I enabled it already once. Here is the result that I got when I tried enabling the WSL again:

`PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Path          :
Online        : True
RestartNeeded : False`

Still getting the same issues (which prevent me from installing turicreate).

**Comment by gustavla** [comment]
@T-Cornelis Thanks for the quick response. Can you try directly downloading the coremltools wheel from https://pypi.python.org/pypi/coremltools/0.8 and then running `pip install <path to file>.whl`? It should be the manylinux1 corresponding to your Python version. Let's see if that gives us any more information.

**Comment by T-Cornelis** [comment]
The result I got is the following:
`(py27) C:\Users\<user name>\Downloads>pip install coremltools-0.8-py2.7-none-manylinux1_x86_64.whl
coremltools-0.8-py2.7-none-manylinux1_x86_64.whl is not a supported wheel on this platform.`
Sorry for the late reply this time.

**Comment by gustavla** [comment]
@T-Cornelis I'm still learning how WSL works from online resources (I have never tried it myself), and it looks like you first enable WSL and then install a linux distribution. Have you installed Ubuntu? Your prompt looks like a Windows one, so could you run bash first and then the pip command from inside bash (to make it absolutely certain that your are executing this from the WSL).
