### ISSUE TITLE
User guide documentation link to downloadable content is broken

### ISSUE THREAD

**Issue by syoutsey** [apple/turicreate#2207]
In our Random Forest Classifier we reference a `mushroom.csv` [file](https://apple.github.io/turicreate/docs/userguide/supervised-learning/random_forest_classifier.html) which is no longer stored at that URL on Github. This is almost certainly because of the recent code refactoring we did which changed the paths of content in our repo, which we then reference in our user guide.

We should audit all URLs with linked content and ensure they are correct.

**Comment by abhishekpratapa** [comment]
#2055 actually fixes this!

The URLs didn't propagate because the user guide doesn't get updated until a new release.

For instance:

https://github.com/apple/turicreate/blob/master/userguide/supervised-learning/random_forest_classifier.md

**Comment by syoutsey** [comment]
Keeping this open to verify URLs are fixed when we push docs as part of 5.7 release.
