### ISSUE TITLE
hi, I'm trying to use itemcontent recommender but getting the following error

### ISSUE THREAD

**Issue by ashwini02590** [apple/turicreate#2214]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/newenv/lib/python3.6/site-packages/turicreate/extensions.py in __run_class_function(self, fnname, args, kwargs)
    273         try:
--> 274             ret = self._tkclass.call_function(fnname, argument_dict)
    275         except RuntimeError as exc:

turicreate/_cython/cy_model.pyx in turicreate._cython.cy_model.UnityModel.call_function()

turicreate/_cython/cy_model.pyx in turicreate._cython.cy_model.UnityModel.call_function()

RuntimeError: Column name __implicit_user__ does not exist.

During handling of the above exception, another exception occurred:

ToolkitError                              Traceback (most recent call last)
<ipython-input-42-2bb7f93df4e2> in <module>
      2                                           observation_data= dfRating,
      3                                     item_id='anime_id',
----> 4                                     target='user_rating')
      5 
      6 content_similarity = itemcontent_model.get_similar_items()

~/newenv/lib/python3.6/site-packages/turicreate/toolkits/recommender/item_content_recommender.py in create(item_data, item_id, observation_data, user_id, target, weights, similarity_metrics, item_data_transform, max_item_neighborhood_size, verbose)
    251     extra_data = {"nearest_items" : graph}
    252     with QuietProgress(verbose):
--> 253         model_proxy.train(observation_data, user_data, item_data, opts, extra_data)
    254 
    255     return ItemContentRecommender(model_proxy)

~/newenv/lib/python3.6/site-packages/turicreate/extensions.py in <lambda>(*args, **kwargs)
    288         elif name in self._functions:
    289             # is it a function?
--> 290             ret = lambda *args, **kwargs: self.__run_class_function(name, args, kwargs)
    291             ret.__doc__ = "Name: " + name + "\nParameters: " + str(self._functions[name]) + "\n"
    292             try:

~/newenv/lib/python3.6/site-packages/turicreate/extensions.py in __run_class_function(self, fnname, args, kwargs)
    275         except RuntimeError as exc:
    276             # Expose C++ exceptions using ToolkitError.
--> 277             raise _ToolkitError(exc)
    278         ret = _wrap_function_return(ret)
    279         return ret

ToolkitError: Column name __implicit_user__ does not exist.

**Comment by syoutsey** [comment]
Hi @ashwini02590 can you share any code and/or datasets you're using which reproduce this error? We'd like to debug this but will have a hard time without more information. Thanks!

**Comment by ashwini02590** [comment]
Hi @syoutsey this is the code i used.

dfRating = tc.SFrame.read_csv("anime.user_merged.csv", header=True,
                                delimiter=',')
dfAnime = tc.SFrame.read_csv("anime_filtered.csv", header=True,
                                delimiter=',')

content_model= tc.recommender.item_content_recommender.create(dfAnime,"anime_id", observation_data=dfRating,max_item_neighborhood_size=64, verbose=True)

**Comment by ashwini02590** [comment]
Hi, any update on this error "RuntimeError: Column name implicit_user does not exist."

**Comment by syoutsey** [comment]
Can you provide the `.csv` files you're using which reproduce this error? Thanks!

**Comment by TobyRoseman** [comment]
Closing this issue.

@ashwini02590 - feel free to reopen with the requested information.
