### ISSUE TITLE
How to evaluate item content recommender?

### ISSUE THREAD

**Issue by ashwini02590** [apple/turicreate#2215]
Hi, when i try to evaluate the item content recommender, i get the an error saying data set must have a column pertaining to user ids. Since the content recommender doesn't use user interaction, why does it need the user id? Any way I can get evaluation

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-49-c6131c5f6f70> in <module>
----> 1 itemcontent_model.evaluate(validation_data1)

~/newenv/lib/python3.6/site-packages/turicreate/toolkits/recommender/util.py in evaluate(self, dataset, metric, exclude_known_for_precision_recall, target, verbose, **kwargs)
   1730                                                      exclude_known=exclude_known_for_precision_recall,
   1731                                                      verbose=verbose,
-> 1732                                                      **kwargs)
   1733             ret.update(results)
   1734             if verbose:

~/newenv/lib/python3.6/site-packages/turicreate/toolkits/recommender/util.py in evaluate_precision_recall(self, dataset, cutoffs, skip_set, exclude_known, verbose, **kwargs)
   1547                item_column in dataset.column_names(), \
   1548             'Provided data set must have a column pertaining to user ids and \
-> 1549              item ids, similar to what we had during training.'
   1550 
   1551         dataset = self.__prepare_dataset_parameter(dataset)

AssertionError: Provided data set must have a column pertaining to user ids and              item ids, similar to what we had during training.

**Comment by syoutsey** [comment]
Hi @ashwini02590, @znation wrote a nice summary of the need for user IDs here: https://github.com/apple/turicreate/issues/1182#issuecomment-435171757. Does this answer your question?

**Comment by ashwini02590** [comment]
Hi @syoutsey! Thanks for the explanation. I'm a little confused though. So is there a way I can provide the user ID data, since I do have data on user interactions. I have item data (item id, name, genre, plot etc) and the user interaction data (user id, item id, rating).  I would like to generate content based recommendations. Mainly I would like to evaluate it in terms of RMSE so that I can compare it with the RMSE of the item-similarity recommender and the matrix factorisation recommender. Could you please help? thanks!

**Comment by syoutsey** [comment]
Take a look at our [user guide](https://apple.github.io/turicreate/docs/userguide/recommender/coreml-deployment.html) section on interacting with Core ML. You'll see sample code detailing how to pass in user interaction data to generate recommendations, as well as associated probabilities for each recommendation. Hopefully, the following code from the user guide is what you're looking for. If not, we'd like to hear more about your specific use case and what more you'd need out of Turi Create to support it.

```
let interactions = NSMutableDictionary();
interactions[242] = 6.5; 
// this signifies that the user interacted with item 242 and rated it 6.5 on their scale.
let modelInput = MyRecommenderInput(interactions: interactions as! [Int64 : Double], k: 1);
```

**Comment by ashwini02590** [comment]
thanks a ton @syoutsey, I shall try this :) is there a way I can do a hybrid recommender combining the weighted predicted ratings from other recommenders(item similarity, popularity,factorisation )?

**Comment by TobyRoseman** [comment]
@ashwini02590 - We don't have anything like the hybrid recommender that you mention.

I like the idea. It probably wouldn't be too difficult to do something simple which wraps multiple recommender models and combines the ranking from each. Feel free to open a new feature request issue for that. Or let us know if you implement something along these lines.
