### ISSUE TITLE
macbook pro 2018 why?

### ISSUE THREAD

**Issue by LemonAndroid** [apple/turicreate#2216]
[launcher-install-log.txt](https://github.com/apple/turicreate/files/3478291/launcher-install-log.txt)

**Comment by syoutsey** [comment]
This its the repository for Turi Create not GraphLab Create. GraphLab Create has long been deprecated. Please use Turi Create instead. If there is a reason you can not use Turi Create, please open a separate issue.

**Comment by LemonAndroid** [comment]
i'm disabled

**Comment by LemonAndroid** [comment]
@syoutsey
