### ISSUE TITLE
virtual function should be avoid during construction and destruction.

### ISSUE THREAD

**Issue by guihao-liang** [apple/turicreate#2234]
```
ImageClassification::ImageClassification(
    const std::shared_ptr<unity_sframe> &data,
    const std::vector<std::string> &data_columns,
    const std::string &annotation_column)
    : AnnotationBase(data, data_columns, annotation_column) {
  addAnnotationColumn();
  checkDataSet();
  // temporay workaround for avoiding resizing undefined images, check issue #1977
  _splitUndefined(data_columns.at(0), false, false);
  // must be called after _splitUndefined
  _createFeaturesExtractor();
}
```
Just realize that virtual functions are called inside constructors.

we should provide a separate `init` function to group all virtual functions. After the object is constructed, we should call `init()` explicitly to enforce virtual functions to be invoked with the right version. 

The reason is that during the construction phase, all base classes are constructed before derived class. And the virtual function to be used won't go down to derived class since the derived class hasn't been initialized yet. The runtime system will identify the object as the base class temporarily, instead of the derived class. Only after base classes are all ready, the type of the object will be the derived class. Therefore, It will be super insidious if you have a class inherit `ImageClassification`. 

The work might be non-trivial for you. ;-)

**Comment by znation** [comment]
Have we considered simply making this class sealed (non-inheritable)? I'm not sure we have any use case for inheritance here. (Or is that how we're sharing code with Drawing Classifier?)

**Comment by guihao-liang** [comment]
long overdue. close it.
