### ISSUE TITLE
[Question] How to set TMPDIR/caching location

### ISSUE THREAD

**Issue by NicholasMorris** [apple/turicreate#2237]
I am attempting to create an object detection model based on this data https://www.kaggle.com/c/kuzushiji-recognition. The data becomes too large for my on-device storage during the modelling stage which then causes an error. I have tried setting the the TMPDIR environment variable to be /Volumes/.../tmp, however, this does not solve the issue. /Volumes/.../tmp never has any data written to it.

Can you please advise how to set the location where data should be cached during the modelling stage?

**Comment by TobyRoseman** [comment]
Hi @NicholasMorris - Try doing this at the very begnining of your script:
```python
import turicreate as tc
tc.config.set_runtime_config('TURI_CACHE_FILE_LOCATIONS', ' /Volumes/.../tmp ) 
```
Let us know if that fixes the issue.

**Comment by NicholasMorris** [comment]
Hi @TobyRoseman, thank you for your prompt response! That has worked!
