### ISSUE TITLE
OSOD logging output don't appear during process (5.7)

### ISSUE THREAD

**Issue by MaximBazarov** [apple/turicreate#2244]
Hi there, trying to use version 5.7, and want to thank y'all for all that fixes, now it works in Google Colab as well on CUDA 100.

Only one concern I found so far it that's the logs I have during the model creation process from the augmented images
```sh
Setting 'batch_size' to 32
Using GPU to create model (Tesla T4)
Setting 'max_iterations' to 5000
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
| 1            | 5.738        | 17.7         |
| 13           | 5.218        | 28.2         |
```
and it's working, I can see that, but there's no output for quite some minutes.
For me, it's important learning, what's the capacity of this approach.
Could you please take a look at it?

[Here's the code](https://colab.research.google.com/drive/1GaJLOhdrN-OG8zsL4vgo-wBcqJh6CPYv#scrollTo=6Q6YYscrpqmw&line=6&uniqifier=1)

**Comment by MaximBazarov** [comment]
Still no logs btw, using only one image as a source

**Comment by TobyRoseman** [comment]
@MaximBazarov - I'm glad to hear you are liking 5.7. I'm not understand the issue. Is the problem that you are not seeing any output for several minutes once you call `tc.one_shot_object_detector.create(...)`?

**Comment by MaximBazarov** [comment]
@TobyRoseman yes, for several hours, the notepad is busy, GPU is working, but no output at all. Basically, the last output I saw is that in the first message. 
It might be an issue with Google Collab though, not sure tbh, sorry can't provide more information.

**Comment by TobyRoseman** [comment]
@MaximBazarov - Is this still an issue with the most recent version TuriCreate?

**Comment by MaximBazarov** [comment]
@TobyRoseman Yes, it works! Thank you very much!
