### ISSUE TITLE
Object detection: Setting minimum confidence threshold

### ISSUE THREAD

**Issue by joymkj** [apple/turicreate#2254]
I exported a .mlmodel from Turicreate and dropped it in Apple's [breakfast recognition example app](https://developer.apple.com/documentation/vision/recognizing_objects_in_live_capture). Is it possible to set a minimum confidence threshold here?

**Comment by nickjong** [comment]
If you have a static confidence threshold you want to use, you could always set it at export time using the `confidence_threshold` parameter of `export_coreml`: https://apple.github.io/turicreate/docs/api/generated/turicreate.object_detector.ObjectDetector.export_coreml.html#turicreate.object_detector.ObjectDetector.export_coreml

Regardless of what confidence threshold is set as the exported model's default, you can override the threshold on iOS 13 or later using the new `featureProvider` property of `VNCoreMLModel`: https://developer.apple.com/documentation/vision/vncoremlmodel/3131933-featureprovider?language=objc

We'll use this issue to cover updating our User Guide to demonstrate how to use this new API, but let us know if you have any further questions!

**Comment by nickjong** [comment]
Actually, looks like we already have #798 covering this topic. I'll close this one as a dupe. Still let us know if you have any further questions!
