### ISSUE TITLE
Illegal instruction (core dumped) error after Turicreate version 5.4

### ISSUE THREAD

**Issue by halilkabaca** [apple/turicreate#2266]
Hello,

I have an old Dell Optiplex 330 desktop with Xeon E5420 and If i try to install Turi Create version later than 5.4 I get Illegal instruction (core dumped) error when i try to import it. If i use 5.4 or earlier it works.

What has changed after version 5.4 that could cause this?

Looking forward to hearing from you
Regards
Halil

**Comment by TobyRoseman** [comment]
@halilkabaca - what operating system are you using? Also is there any additional information you can give us (such as a stack trace)?

**Comment by halilkabaca** [comment]
**Operating system:**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Dump:**
I only have this entry on /var/log/syslog:

Aug 25 07:06:55 elastic kernel: [97665.124790] traps: python[24248] trap invalid opcode ip:7f0999b7c684 sp:7ffec75bb7a0 error:0 in libunity_shared.so[7f0998fcb000+21e600$

Does that help?

**Comment by halilkabaca** [comment]
Same happens on my Dell PowerEdge 6850 server with 4 Xeon 3.16 MP Cpus. Can it be related to Xeon?

**Comment by syoutsey** [comment]
Seems to be caused by the fix for #1441.

**Comment by hoytak** [comment]
Yes.  The specific part of this is that commit 4c43bc upgrades the march target to nehalem, which includes the SSE 4.2 and POPCNT/LZCNT instructions, which we use in some of the core routines. The rather ancient Xeon E5420 processor does not have these.  It's possible to compile an egg with a legacy version of all of these, but our newer dependencies will also start requiring some of these instructions, so changing this on our end might not solve all of this and also may impact performance of some routines.  

It's unclear what to do here.

**Comment by syoutsey** [comment]
Keeping open during 6.0 to evaluate instruction set compatibility with `manylinux2010`.

**Comment by syoutsey** [comment]
BRB: `manylinux2010` now dictates what instruction sets we support, we should follow this.
