### ISSUE TITLE
csv header parsing problem with BOM UTF8

### ISSUE THREAD

**Issue by KeyboardNerd** [apple/turicreate#227]
I'm using Python 2.7.13 with turicreate version 4.0 shown by "pip show turicreate".

To recreate the bug, 
1. Write character 'a' to "buggy.csv" in UTF-8 encoding.

2. Run the following code:
`import turicreate as tc
data1 = tc.SFrame('buggy.csv')
print data1['a']
`

Expected output:
[]

Actual output:
RuntimeError: Column name a does not exist.

I used a debugger and found that the corresponding column in data1 for 'a' is '\xef\xbb\xbfa', which means that the BOM is incorrectly parsed as header.

**Comment by TobyRoseman** [comment]
@KeyboardNerd - Does it work if you do: `data1 = tc.SFrame.read_csv('buggy.csv')`? This is the intended way to read CSV files. 

What you're doing should probably give an error. I'll take a look at that. Please attach `buggy.csv` to this issue.

**Comment by KeyboardNerd** [comment]
@TobyRoseman no the result is the same, here's stack trace
`Parsing completed. Parsed 0 lines in 0.009459 secs.
Traceback (most recent call last):
  File "/Users/Sida/Projects/turicreate/test/test2.py", line 4, in <module>
    print data1['a']
  File "/usr/local/lib/python2.7/site-packages/turicreate/data_structures/sframe.py", line 3517, in __getitem__
    return self.select_column(key)
  File "/usr/local/lib/python2.7/site-packages/turicreate/data_structures/sframe.py", line 3030, in select_column
    return SArray(data=[], _proxy=self.__proxy__.select_column(column_name))
  File "/usr/local/lib/python2.7/site-packages/turicreate/cython/context.py", line 49, in __exit__
    raise exc_type(exc_value)
RuntimeError: Column name a does not exist.`

You can remove the ".txt" for the csv file.
[buggy.csv.txt](https://github.com/apple/turicreate/files/1679773/buggy.csv.txt)

**Comment by srikris** [comment]
Good find. Interestingly, the column name is parsed incorrectly

```
In [13]: data1
Out[13]:
Columns:
	a	str

Rows: 0

Data:
	[]

In [14]: data1.column_names()
Out[14]: ['\xef\xbb\xbfa']
```
We'll investigate
