### ISSUE TITLE
Support for polygons while image annotations

### ISSUE THREAD

**Issue by Gurdev-Singh** [apple/turicreate#2277]
I have tried Turicreate to develop a custom object detection model and it works fine if I create the annotations as rectangular bounding boxes. I would like to know if there is any plan to support annotations for object detection with polygon shapes created from RectLabel or similar such image annotation app?

**Comment by syoutsey** [comment]
Hi @Gurdev-Singh, we're tracking OD annotation with this issue: https://github.com/apple/turicreate/issues/828

**Comment by dhgokul** [comment]
Guys turicreate support only rect bounding box ? not polygons ?

**Comment by ryouchinsa** [comment]
[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can read/write/export the YOLO segmentation format.
```
class_index x1 y1 x2 y2 x3 y3 ...
0 0.180027 0.287930 0.181324 0.280698 0.183726 0.270573 ...
```
![yolo_polygon](https://user-images.githubusercontent.com/1954306/214472214-a9c2775d-247a-4bd1-87f6-9d90818ef8ff.jpg)
