### ISSUE TITLE
Opening SFrame.read_csv from s3 bucket

### ISSUE THREAD

**Issue by sbaner03** [apple/turicreate#2278]
I have a problem loading a csv file into an SFrame using SFrame.read_csv. I have updated my security credentials in os.Enviornment. Yet it says file not found.

**Comment by TobyRoseman** [comment]
What error and stack trace are you getting? 

Also the security credentials go in `os.environ` not `os.Enviornment`. The relevant entries are `os.environ['AWS_ACCESS_KEY_ID']` and `os.environ['AWS_SECRET_ACCESS_KEY']`.

**Comment by sbaner03** [comment]
Hi,

os.environ['AWS_ACCESS_KEY_ID'] = S3_ACCESS_KEY
os.environ['AWS_SECRET_ACCESS_KEY'] = S3_SECRET_KEY

I have tried 2 approaches:

1) sf = SFrame(data = 's3://mrlanalytics/TCI_Inv/SM/SM_SL_2018.csv')
Error: OSError: Cannot open s3://mrlanalytics/TCI_Inv/SM/SM_SL_2018.csv for
read. Cannot open s3://mrlanalytics/TCI_Inv/SM/SM_SL_2018.csv


2) sf = SFrame.read_csv('s3://mrlanalytics/TCI_Inv/SM/SM_SL_2018.csv')
Error: Cannot open s3://mrlanalytics/TCI_Inv/SM/SM_SL_2018.csv for read.
Cannot open s3://mrlanalytics/TCI_Inv/SM/SM_SL_2018.csv

**Comment by hoytak** [comment]
Hello @sbaner03, 

Which version of Turi Create are you using?  We put out a bunch of improvements to the s3 reading in 5.7.  In particular the error reporting is improved.

**Comment by sbaner03** [comment]
Hi,
I am using 5.7.1. The entire error is pasted below. Also the file in the s3 bucket has public read access - I am able to open it in pandas using df = pd.read_csv('s3://mrlanalytics/TCI_Inv/SM/SM_SL_2018.csv')

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1040             with cython_context():
-> 1041                 errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
   1042         except Exception as e:

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_csvs()

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_csvs()

OSError: Cannot open s3://mrlanalytics/itemMaster.csv for read. Cannot open s3://mrlanalytics/itemMaster.csv

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-5-7de132a6a936> in <module>()
----> 1 itemMaster = SFrame.read_csv('s3://mrlanalytics/itemMaster.csv')

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in read_csv(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1510                                   false_values=false_values,
   1511                                   _only_raw_string_substitutions=_only_raw_string_substitutions,
-> 1512                                   **kwargs)[0]
   1513 
   1514 

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
    973                                  true_values=true_values,
    974                                  false_values=false_values,
--> 975                                  _only_raw_string_substitutions=_only_raw_string_substitutions)
    976                 column_type_hints = SFrame._infer_column_types_from_lines(first_rows)
    977                 typelist = '[' + ','.join(t.__name__ for t in column_type_hints) + ']'

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in read_csv(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1510                                   false_values=false_values,
   1511                                   _only_raw_string_substitutions=_only_raw_string_substitutions,
-> 1512                                   **kwargs)[0]
   1513 
   1514 

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1039                 glconnect.get_server().set_log_progress(False)
   1040             with cython_context():
-> 1041                 errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
   1042         except Exception as e:
   1043             if type(e) == RuntimeError and "CSV parsing cancelled" in str(e.args[0]):

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/_cython/context.py in __exit__(self, exc_type, exc_value, traceback)
     47             if not self.show_cython_trace:
     48                 # To hide cython trace, we re-raise from here
---> 49                 raise exc_type(exc_value)
     50             else:
     51                 # To show the full trace, we do nothing and let exception propagate

OSError: Cannot open s3://mrlanalytics/itemMaster.csv for read. Cannot open s3://mrlanalytics/itemMaster.csv

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1040             with cython_context():
-> 1041                 errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
   1042         except Exception as e:

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_csvs()

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_csvs()

OSError: Cannot open s3://mrlanalytics/itemMaster.csv for read. Cannot open s3://mrlanalytics/itemMaster.csv

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-5-7de132a6a936> in <module>()
----> 1 itemMaster = SFrame.read_csv('s3://mrlanalytics/itemMaster.csv')

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in read_csv(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1510                                   false_values=false_values,
   1511                                   _only_raw_string_substitutions=_only_raw_string_substitutions,
-> 1512                                   **kwargs)[0]
   1513 
   1514 

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
    973                                  true_values=true_values,
    974                                  false_values=false_values,
--> 975                                  _only_raw_string_substitutions=_only_raw_string_substitutions)
    976                 column_type_hints = SFrame._infer_column_types_from_lines(first_rows)
    977                 typelist = '[' + ','.join(t.__name__ for t in column_type_hints) + ']'

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in read_csv(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1510                                   false_values=false_values,
   1511                                   _only_raw_string_substitutions=_only_raw_string_substitutions,
-> 1512                                   **kwargs)[0]
   1513 
   1514 

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1039                 glconnect.get_server().set_log_progress(False)
   1040             with cython_context():
-> 1041                 errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
   1042         except Exception as e:
   1043             if type(e) == RuntimeError and "CSV parsing cancelled" in str(e.args[0]):

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/_cython/context.py in __exit__(self, exc_type, exc_value, traceback)
     47             if not self.show_cython_trace:
     48                 # To hide cython trace, we re-raise from here
---> 49                 raise exc_type(exc_value)
     50             else:
     51                 # To show the full trace, we do nothing and let exception propagate

OSError: Cannot open s3://mrlanalytics/itemMaster.csv for read. Cannot open s3://mrlanalytics/itemMaster.csv

**Comment by Jarvi-Izana** [comment]
Are you using the public s3 region? Have you tried to set `export TURI_S3_REGION=<YOUR_S3_REGION>`?

**Comment by sbaner03** [comment]
Hi,
Tried fixing the s3 region but got the same error

os.environ['AWS_ACCESS_KEY_ID'] = S3_ACCESS_KEY
os.environ['AWS_SECRET_ACCESS_KEY'] = S3_SECRET_KEY
config.set_runtime_config('TURI_FILEIO_INSECURE_SSL_CERTIFICATE_CHECKS', 1)
os.environ['TURI_S3_REGION'] ='ap-south-1'
itemMaster = SFrame.read_csv('s3://mrlanalytics/itemMaster.csv')


---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1040             with cython_context():
-> 1041                 errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
   1042         except Exception as e:

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_csvs()

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_csvs()

OSError: Cannot open s3://mrlanalytics/itemMaster.csv for read. Cannot open s3://mrlanalytics/itemMaster.csv

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-3-7de132a6a936> in <module>()
----> 1 itemMaster = SFrame.read_csv('s3://mrlanalytics/itemMaster.csv')

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in read_csv(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1510                                   false_values=false_values,
   1511                                   _only_raw_string_substitutions=_only_raw_string_substitutions,
-> 1512                                   **kwargs)[0]
   1513 
   1514 

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
    973                                  true_values=true_values,
    974                                  false_values=false_values,
--> 975                                  _only_raw_string_substitutions=_only_raw_string_substitutions)
    976                 column_type_hints = SFrame._infer_column_types_from_lines(first_rows)
    977                 typelist = '[' + ','.join(t.__name__ for t in column_type_hints) + ']'

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in read_csv(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1510                                   false_values=false_values,
   1511                                   _only_raw_string_substitutions=_only_raw_string_substitutions,
-> 1512                                   **kwargs)[0]
   1513 
   1514 

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1039                 glconnect.get_server().set_log_progress(False)
   1040             with cython_context():
-> 1041                 errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
   1042         except Exception as e:
   1043             if type(e) == RuntimeError and "CSV parsing cancelled" in str(e.args[0]):

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/_cython/context.py in __exit__(self, exc_type, exc_value, traceback)
     47             if not self.show_cython_trace:
     48                 # To hide cython trace, we re-raise from here
---> 49                 raise exc_type(exc_value)
     50             else:
     51                 # To show the full trace, we do nothing and let exception propagate

OSError: Cannot open s3://mrlanalytics/itemMaster.csv for read. Cannot open s3://mrlanalytics/itemMaster.csv

**Comment by Jarvi-Izana** [comment]
Thanks @sbaner03. Currently, the flag `TURI_S3_REGION` doesn't support 
```
os.environ['TURI_S3_REGION']=
```
You need to either set through shell `export` or `config.set_runtime_config`.  I know it's cumbersome.

The issue is related to s3 region for sure. I can repro it locally and we are working on it.

**Comment by sbaner03** [comment]
Hi,
It seems like you are right. My notebook instance has a different region from the s3 bucket instance. When the two regions are common, I have been able to read the csv into a Sframe. However, when I use config.set_runtime_config('TURI_S3_REGION','ap-south-1'), it still triggers an error. 

os.environ['AWS_ACCESS_KEY_ID'] = S3_ACCESS_KEY
os.environ['AWS_SECRET_ACCESS_KEY'] = S3_SECRET_KEY
config.set_runtime_config('TURI_FILEIO_INSECURE_SSL_CERTIFICATE_CHECKS', 1)
config.set_runtime_config('TURI_S3_REGION','ap-south-1')
sf = SFrame.read_csv('s3://mrlanalytics/HM_SM_BILL/SM_Transactions_YTD.csv')


---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1040             with cython_context():
-> 1041                 errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
   1042         except Exception as e:

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_csvs()

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_csvs()

OSError: Cannot open s3://mrlanalytics/HM_SM_BILL/SM_Transactions_YTD.csv for read. Cannot open s3://mrlanalytics/HM_SM_BILL/SM_Transactions_YTD.csv

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-4-380bde96bc8c> in <module>()
      3 config.set_runtime_config('TURI_FILEIO_INSECURE_SSL_CERTIFICATE_CHECKS', 1)
      4 config.set_runtime_config('TURI_S3_REGION','ap-south-1')
----> 5 sf = SFrame.read_csv('s3://mrlanalytics/HM_SM_BILL/SM_Transactions_YTD.csv')

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in read_csv(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1510                                   false_values=false_values,
   1511                                   _only_raw_string_substitutions=_only_raw_string_substitutions,
-> 1512                                   **kwargs)[0]
   1513 
   1514 

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
    973                                  true_values=true_values,
    974                                  false_values=false_values,
--> 975                                  _only_raw_string_substitutions=_only_raw_string_substitutions)
    976                 column_type_hints = SFrame._infer_column_types_from_lines(first_rows)
    977                 typelist = '[' + ','.join(t.__name__ for t in column_type_hints) + ']'

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in read_csv(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1510                                   false_values=false_values,
   1511                                   _only_raw_string_substitutions=_only_raw_string_substitutions,
-> 1512                                   **kwargs)[0]
   1513 
   1514 

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1039                 glconnect.get_server().set_log_progress(False)
   1040             with cython_context():
-> 1041                 errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
   1042         except Exception as e:
   1043             if type(e) == RuntimeError and "CSV parsing cancelled" in str(e.args[0]):

~/anaconda3/envs/python3/lib/python3.6/site-packages/turicreate/_cython/context.py in __exit__(self, exc_type, exc_value, traceback)
     47             if not self.show_cython_trace:
     48                 # To hide cython trace, we re-raise from here
---> 49                 raise exc_type(exc_value)
     50             else:
     51                 # To show the full trace, we do nothing and let exception propagate

OSError: Cannot open s3://mrlanalytics/HM_SM_BILL/SM_Transactions_YTD.csv for read. Cannot open s3://mrlanalytics/HM_SM_BILL/SM_Transactions_YTD.csv

**Comment by srikris** [comment]
This is still an issue for. Marking it as P2.
