### ISSUE TITLE
Style transfer on GPU

### ISSUE THREAD

**Issue by carlosdelamora** [apple/turicreate#2309]
So the documentation [here](https://github.com/apple/turicreate/blob/master/LinuxGPU.md) claims that it is possible to run Style transfer on the GPU's. I have tried using the following docker image [dimage](https://hub.docker.com/r/jidebingfeng/turicreate/dockerfile). But when I run my model it runs in the CPU instead of the GPU. 

`<pre>Using 'image' in style_dataset as feature column and using 'image' in content_dataset as feature column 

Using CPU to create model
Analyzing visual features of the style images
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
| 1            | 9728.506     | 15.7         |
| 2            | 669566535834.055| 58.1         |</pre>`

On top of that it diverges quickly. Do we have a good docker image that runs style transfer successfully on the GPU? Also it would be great if the image already has jupyter notebook.

**Comment by TobyRoseman** [comment]
We didn't create that docker image. However it does look reasonable.

The only thing I can suggest trying is adding `/usr/local/cuda/extras/CUPTI/lib64` to your `LD_LIBRARY_PATH`. Also make that CUDA 8 is the right version for you.

What is the output of `turicreate.config.get_num_gpus()`?

**Comment by carlosdelamora** [comment]
The output of `turicreate.config.get_num_gpus()` is `-1`. I have also added `/usr/local/cuda/extras/CUPTI/lib64` to my `LD_LIBRARY_PATH`. Now `echo $LD_LIBRARY_PATH` outputs `/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/extras/CUPTI/lib64`

I am not sure on how to determine that CUDA 8 is or is not the right version.

**Comment by TobyRoseman** [comment]
I'm guessing the system isn't setup correctly for your GPUS. See if the NVIDIA System Management Interface can even find your GPUs. From the command line try running:
`nvidia-smi --query-gpu=index,gpu_name,memory.free,memory.total --format=csv,noheader,nounits`

**Comment by carlosdelamora** [comment]
You are correct `nvidia-smi: command not found` I am going to close this ticket since the problem is not really with turicreate
