### ISSUE TITLE
pep8 compatible code style check before build

### ISSUE THREAD

**Issue by guihao-liang** [apple/turicreate#2312]
I found this in a project of my personal interest and it might help us:
```
# .travis
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
```
A universal python coding style consistent with pep8 is super helpful, isn't it?

**Comment by TobyRoseman** [comment]
@guihao-liang - generally you shouldn't be assigning issues to other people. Also generally more than one person shouldn't be assigned to the same issues.

**Comment by guihao-liang** [comment]
@TobyRoseman Thanks for letting me know!
