### ISSUE TITLE
Style transfer - iOS app results not as impressive as turicreate stylized images.

### ISSUE THREAD

**Issue by saddif** [apple/turicreate#2314]
Hello,

This is amazing work guys, i have a question:

I have been making models using the style transfer, they look pretty amazing when testing them in jupyter notebook with the function (similar to pytorch/ tensorflow versions)

sample_image = test_images['image'][0]
stylized_image = model.stylize(sample_image, style=0)
tcshow(stylized_image)

However using the model in iOS app - they dont seem as impressive at all. Is there a reason for this? i have used the following iOS app code structures for testing the models

https://medium.com/@iliastukalov/in-august-2018-apple-released-a-beta-version-of-turi-create-framework-which-is-used-for-training-2874364950d1 

https://medium.com/@alexiscreuzot/building-a-neural-style-transfer-app-on-ios-with-pytorch-and-coreml-76e00cd14b28 (this is a pytorch to ios tutorial but i used the turicreate model in the ios app supplied with a few tweaks to feed in the turicreate model)

https://hackernoon.com/diy-prisma-fast-style-transfer-app-with-coreml-and-tensorflow-817c3b90dacd . (this is tensorflow to ios tutorial but again fed in the turicreate model to the app) 

I am feeding into the models to the last two apps using this code

        let models = oneStyle256()
        let styleArray = try? MLMultiArray(shape: [1] as [NSNumber], dataType: .double)
        for i in 0...((styleArray?.count)!-1) {
            styleArray?[i] = 0.0
        }
        styleArray?[0] = 1.0
     
        let image = input.inputImage
        let outFeatures = try models.prediction(image: image , index: styleArray!)
        let result = MLModelProviderOutput(outputImage: outFeatures.featureValue(for: outputName)!.imageBufferValue!, outputName: outputName)
        return result

Is there any good way to replicate the turicreate model.stylize(sample_image, style=0) method inside an iOS app.

PS. i am not a ML expert or anything, and turicreate has made ML super accessible to people like me, so hats off to you all.

Thanks in advance for any help/pointers on improving iOS style transfer

**Comment by abhishekpratapa** [comment]
@saddif thank you again for using our style transfer toolkit!

The iOS CoreML model and the TuriCreate model should be performing the same on similar images, so it's hard off the top of my head to say why exactly this is occurring.

If you have any of the following:

- Before and after pictures
- The CoreML model
- The TuriCreate model
- Your Xcode and MacOS version

that you could share it would be super helpful in diagnosing the issue.

I have a suspicion that the model input size for the iOS CoreML based app is very small, perhaps (256, 256) just by looking at the model name you have above `oneStyle256 `. And this may be contributing to your lack of quality. Though I'd have to understand the issue a whole lot better.

**Comment by saddif** [comment]
Hi, thanks for the quick reply. I think u might be correct - I’ll try training with a higher input resolution and see if that makes it better. Thanks for your help

**Comment by TobyRoseman** [comment]
I'm going to close this issue due to inactivity. @saddif - if training with a higher input resolution did not solve the problem, please let us know.
