### ISSUE TITLE
what is the replacement of tc.feature_engineering? 

### ISSUE THREAD

**Issue by thealokkr** [apple/turicreate#2318]
Hi 
I need to custom build a feature engineering transformer however feature_engineering has been deprecated. It seems that feature engineering has been moved inside individual models.
Is there any equivalent of feature_engineering to use?

**Comment by TobyRoseman** [comment]
@thealokkr - You probably want to write a function and use the SFrame/SArray `.apply` function. Can you give us more information about what you are trying to do? We may be able to help.

**Comment by thealokkr** [comment]
Thanks for the reply, Yes a custom function can be written but inside that function i need to use categorical imputer. I can custom code the categorical imputer as well but that would be re-inventing the wheel.  Is it possible to use feature_engineering directly on SFrame like it used to be done in graphlab?

**Comment by TobyRoseman** [comment]
Sorry, `feature_engineering` has been removed. There is currently no replacement.

I'd like to understand more about your use case. Do you just want to impute the most popular category for missing values? Or do you need something more complicated?
