### ISSUE TITLE
Importing Turicreate Version 4.1 with Python3.6

### ISSUE THREAD

**Issue by gamemania** [apple/turicreate#2342]
Hi,

We have been trying to work in a virtual machine at work to convert our Python 2 jobs to Python 3. Whenever we were using turicreate4.0 with Python2.7 we had no issues. When we switched to Python 3 we keep seeing this error:

"Traceback (most recent call last):
  File "src/features/build_features.py", line 5, in <module>
    import turicreate as tc
  File "/env/lib/python3.6/site-packages/turicreate/__init__.py", line 30, in <module>
    from turicreate.data_structures.sgraph import Vertex, Edge
  File "/env/lib/python3.6/site-packages/turicreate/data_structures/__init__.py", line 18, in <module>
    from . import sframe
  File "/env/lib/python3.6/site-packages/turicreate/data_structures/sframe.py", line 16, in <module>
    from ..connect import main as glconnect
  File "/env/lib/python3.6/site-packages/turicreate/connect/main.py", line 13, in <module>
    from ..cython.cy_unity import UnityGlobalProxy
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory"

We have searched a lot for this same error and the instructions were mainly focused on either using sudo, or installing some other packages via apt-get. We **do not** have any of the necessary privileges to do any of those fixes, and also the same package is working in the same machine in a Python 2.7 environment. Could you please help us how to get rid of this import issue without suggesting to use any sudo or apt-get. We can install packages to the virtual environment through pip; but we cannot use sudo.

Thank you for your time!

**Comment by TobyRoseman** [comment]
@gamemania - please try using `virtualenv`. See our [installation instructions](https://github.com/apple/turicreate#installation) for details.

**Comment by gamemania** [comment]
Hi,

We are already using a virtualenv. I forgot to mention that. We create a python3.6 virtual environment and still see the same error.

Kind regards,
Murat.


On Sep 23, 2019, at 15:39, Toby Roseman <notifications@github.com> wrote:

﻿

@gamemania<https://github.com/gamemania> - please try using virtualenv. See our installation instructions<https://github.com/apple/turicreate#installation> for details.

**Comment by znation** [comment]
Hi @gamemania, I think this may be fixed in later releases of Turi Create. I'm not sure exactly which release it would have been fixed in, but could you try upgrading to a later (5.x) release and see if it works (both for your use case, and if it fixes this issue in particular)?

**Comment by gamemania** [comment]
Hi @znation thank you very much for the suggestion. Here is the error I get when we have turicreate5.7.1:
"ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory". 

When we use turicreate 4.0 with Python 2.6, we are not seeing any error. I am not sure why is this problem occurring in Python 3.x (we tried on 3.5, 3.6, and 3.7), and turicreate >= 4.1.0.

Thank you all again for all your help!

**Comment by TobyRoseman** [comment]
The most recent issue (i.e. the libbz2.so.1.0 issue) looks like a dup of #2302.

**Comment by TobyRoseman** [comment]
Closing this issue. The original problem has been fixed and we have another issue (#2302) for the new problem mentioned here.
