### ISSUE TITLE
graphlab.toolkits.cross_validation.shuffle which was originally present in Graphlab Create is missing in TuriCreate

### ISSUE THREAD

**Issue by soubh1k** [apple/turicreate#236]
Previously to shuffle a SFrame, we used graphlab.toolkits.cross_validation.shuffle. However, in TuriCreate this is missing.

**Comment by soubh1k** [comment]
I think your work-around is better as the shuffle function originally present in graphlab creates a new SFrame. However, your method does not require to create a new SFrame.

**Comment by gustavla** [comment]
@soubh1k Actually, the sort does not happen in-place, so it does create a new SFrame which is why I had to capture the results of the sort with `sf = ...`.
