### ISSUE TITLE
CoreML could not detect object in iPhone camera's portrait mode 

### ISSUE THREAD

**Issue by kid9591** [apple/turicreate#2375]
I successfully trained an Object Detection model and exported in CoreML format.
My model has 300 iterations and mean_average_precision is about 0.7.

I then validate it with some images using TC and bounding box drawing util and it could recognize the object pretty well. 

I then downloaded the sample project for recognizing objects in live capture here: 
https://developer.apple.com/documentation/vision/recognizing_objects_in_live_capture

What it's weird is that the object couldn't be detected in iPhone camera's portrait mode, no bounding box is drawn, VNDetectedObjectObservation hasn't returned any results. However, I rotated the iPhone 90 degrees counter-clockwise((home button on the right) and the bounding box appeared. If I move the phone horizontally, the offset between the bounding box and the object become larger.

![portrait camera - no detection](https://user-images.githubusercontent.com/7839927/65872506-e35d5180-e3aa-11e9-990b-47d25cfeb2cf.jpg)

![landscape - detected](https://user-images.githubusercontent.com/7839927/65872576-0ee03c00-e3ab-11e9-8812-535065310f46.jpg)

![moving camera horizontally - offset appears](https://user-images.githubusercontent.com/7839927/65872610-20294880-e3ab-11e9-875c-e2b9e35d4e92.jpg)

I'm not sure that it could be a problem of Turi Create or Core ML, or the source code itself. Could anyone explain to me, please?

**Comment by syoutsey** [comment]
Hi @kid9591, this is almost certainly because of the way the iPhone captures photos and then associates EXIF data describing the phone's rotation at capture. It's likely that the photos you trained with had a different orientation than the image being used for inference.

You can view the EXIF data of a photo in Finder on macOS - this should help reveal whether the images you used were "rotated" when training the OD model.

**Comment by TobyRoseman** [comment]
Possibly related to #1147.

**Comment by ryouchinsa** [comment]
[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can remove the EXIF orientation flags from images and convert images to the front orientation. If necessary, you can rotate the image right/left by 90 degrees.
You can export/import the Turi Create CSV format.
