### ISSUE TITLE
Activity Classifier create() in py3.5 takes 3-7x longer to execute for MXNET than TF

### ISSUE THREAD

**Issue by fareeha** [apple/turicreate#2427]
Ubuntu 18.04, Python 3.5 

**MXNET - Python 3.5 and 1 GPU**
Training time:  17.4s
`create()` time: 283.25s

**MXNET - Python 3.5 and 4 GPUs**
Training time:  49.93s
`create()` time: 204.95 

**TF - Python 3.5 and 1 GPU**
Training time:  21.00s
`create()` time:  50.07s

**TF - Python 3.5 and 4 GPUs**
Training time:  24.78s
`create()` time:  54.98s

**Comment by TobyRoseman** [comment]
@fareeha - Now that we're using TensorFlow and only supporting one GPU, is this issue good to close?

**Comment by fareeha** [comment]
> @fareeha - Now that we're using TensorFlow and only supporting one GPU, is this issue good to close?

Yes let's close it - this issue was targeting performance regression on MXNet, specifically how long `create()` was taking to execute: 283.25s for MXNet vs 50.07s on TF. 

I'm not certain if the 17.4s vs 21.0s training time difference is interesting to investigate.

**Comment by TobyRoseman** [comment]
Ok, closing this issue as @fareeha suggested.
