### ISSUE TITLE
Jobs take longer in AC MXNET from Python 2.7 to Python 3.5

### ISSUE THREAD

**Issue by fareeha** [apple/turicreate#2428]
Ubuntu 18.04
The same job with the same number of iterations in Py 2.7 and Py 3.5

**MXNET - Python 2.7 and 1 GPU**
Training time:  11.1s
create() time:  25.88s

**MXNET - Python 2.7 and 4 GPUs**
Training time:  19.0s
create() time:  43.28s

**MXNET - Python 3.5 and 1 GPU**
Training time:  17.4s
create() time: 283.25s

**MXNET - Python 3.5 and 4 GPUs**
Training time:  49.93s
create() time: 204.95

**Comment by TobyRoseman** [comment]
Since we're no longer using MXNet, I'm going to close this issue.
