### ISSUE TITLE
Activity Classifier MXNET compute time increases on Py2.7 w/ number of GPUs

### ISSUE THREAD

**Issue by fareeha** [apple/turicreate#2429]
Ubuntu 18.04 
MXNET compute time goes up, with the number of GPUs available for the same job on Python 2.7

**MXNET - Python 2.7 and 1 GPU**
Training time:  11.1s
create() time:  25.88s

**MXNET - Python 2.7 and 4 GPUs**
Training time:  19.0s
create() time:  43.28s

**MXNET - Python 3.5 and 1 GPU**
Training time:  17.4s
create() time: 283.25s

**MXNET - Python 3.5 and 4 GPUs**
Training time:  49.93s
create() time: 204.95

**Comment by TobyRoseman** [comment]
Since we're no longer using MXNet or even supporting multiple GPUs, I'm going to close this issue.
