### ISSUE TITLE
Nearest Neighbors Log 

### ISSUE THREAD

**Issue by dogahe** [apple/turicreate#2460]
`model = tc.nearest_neighbors.create(references)` with an SFrame of all strings outputs `Starting brute force nearest neighbors model training.` with no more logs to follow it. Although I think the model still gets created properly, or at least I hope. But maybe just the log does not reflect the progress and completion.

**Comment by TobyRoseman** [comment]
Does the call to `tc.nearest_neighbors.create` return? If so, try calling `print(model)`.

**Comment by dogahe** [comment]
You could try it out with this as references 
`test_references = tc.SFrame({'text1': ['Hi, how are you?', 'I am great, thanks!']})`. The model gets created and print shows:

```
Class                          : NearestNeighborsModel

Attributes
----------
Method                         : brute_force
Number of distance components  : 1
Number of examples             : 2
Number of feature columns      : 1
Number of unpacked features    : 1
Total training time (seconds)  : 1.0089
```

So as I mentioned before the problem is only the generation of logs. But also I am curios why the `Distance` is not shown in the `print` statement. I am curios to know what distance function was used.
