### ISSUE TITLE
mxnet 1.5 requires AVX2, which is not present on nehalem CPU's [resulting in illegal instruction segfault]

### ISSUE THREAD

**Issue by elrid** [apple/turicreate#2471]
Right now turicreate has minimum requirement of nehalem cpu architechture, but one of the dependencies (mxnet==1.5.0) requires AVX2 instruction set, which is not present on nehalem architechture.

Version for python2.7 still uses 1.1, last mxnet without AVX2 requirement, so you may need to bump the requirements for turicreate, or bump down mxnet

**Comment by TobyRoseman** [comment]
`mxnet==1.5.0` is only used for Python 3.7 on macOS. Note: Python 3.7 is not supported on Linux.

For Python 2.7, 3.5, and 3.6 - AVX2 support should not be needed. For those versions of Python TuriCreate uses `mxnet >= 1.1.0, < 1.2.0`. Which means `mxnet==1.1.0.post0` is used unless the user's environment has other requirements for MXNet. This version of MXNet does not need AVX2 support.

TuriCreate is currently in the process of migrating from MXNet to TensorFlow which should remove the need for AVX2 support with Python 3.7 on macOS and allow us to support Python 3.7 on Linux.

**Comment by TobyRoseman** [comment]
With the release of TuriCreate 6.0, MXNet is no longer a dependency. We now use TensorFlow instead. So this should no longer be an issue.
