### ISSUE TITLE
"make python_source" build is slow

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#2477]
Steps to reproduce:
```bash
cd debug/src/python/
make -j
touch ../../../src/python/turicreate/__init__.py 
make python_source
```
Despite there being only python changes, the `make python_source` seems to be doing just as much work as `make -j`.

`make python_source` should be very quick, just a couple of seconds. It should just copy the python files. On my machine the `make python_source` takes almost 30 seconds.

This only started to be an issue recently. It's likely related to the recent remotefs build changes.

**Comment by TobyRoseman** [comment]
Even with out any changes `make python_source` takes about as much time as `make -j`:

```bash
cd debug/src/python/
time make -j
time make python_source
```

**Comment by TobyRoseman** [comment]
@hoytak - do you have any ideas what the issue might be here? It was working (i.e. it was faster) shortly before I created this issue.

**Comment by TobyRoseman** [comment]
Looks like this was caused by #2432. Adding `tctensorflow` as a dependency to `python_source` is what's slowing this down.

Since `make python_source` is intended only to pick up python changes, I don't think we want `tctensorflow` to be a dependency. The `tctensorflow` target doesn't even contain any python.

I think the correct behavior is to have `tctensorflow` be a dependency of `make` when run in `(debug|release)/src/python` but not have it be a dependency `make python_source`.

**Comment by hoytak** [comment]
That could make sense, especially with the name "python_source"; let's do that.
