### ISSUE TITLE
Issue for supporting Google Colab Jupyter Notebook under plot.show() function

### ISSUE THREAD

**Issue by dhivyaaxim** [apple/turicreate#2483]
plot.show() function doesn't  have support for Google Colab Jupyter Notebook .

**Comment by TobyRoseman** [comment]
Is this the same root issue as #1269? Does the workaround mentioned there also work here?

**Comment by dhivyaaxim** [comment]
@TobyRoseman   Please assign this ticket to me as I would like to try fixing it and contribute .Thanks in advance!
