### ISSUE TITLE
AttributeError: 'SentenceClassifier' object has no attribute 'export_coreml'

### ISSUE THREAD

**Issue by Padalingam** [apple/turicreate#249]
I got this when i try to run my .csv file

import turicreate as tc
# Load data
data = tc.SFrame.read_csv('ratings-one.csv')
#data = tc.SFrame({'rating': [1, 5], 'text': ['hate it', 'love it']})

# Create a model
model = tc.sentence_classifier.create(data, 'rating', features=['text'])

# Make predictions & evaluation the model
predictions = model.predict(data)
print(predictions)
results = model.evaluate(data)
#print(results)

# Save the model for later use in Turi Create
model.save('MySentenceClassifier.model')

# Export for use in Core ML
model.export_coreml('MySentenceClassifier.mlmodel')

and my csv file is 

rating | text
-- | --
1 | This is too good
1 | This is too wonderful
1 | This is too awesome
1 | This is too good
1 | This is worth to watch
0 | This is too bad
0 | This is not good
0 | This is very bad
1 | This is fantastic

**Comment by znation** [comment]
Thanks for the issue report @Padalingam! This has been fixed in master with #99 and will be released in the upcoming 4.1 release.

**Comment by afranklin** [comment]
Turi Create 4.1 is now available.
