### ISSUE TITLE
Will you add cross_validation.KFold in turicreate or not?

### ISSUE THREAD

**Issue by hri-tikkumar** [apple/turicreate#2493]
**will you add cross_validation.KFold in turicreate or not?**
@igiloh @Kagandi @znation @srikris @hoytak @afranklin

_Originally posted by @hri-tikkumar in https://github.com/apple/turicreate/issues/117#issuecomment-545753326_

**Comment by znation** [comment]
#117 looks like a reasonable feature request; not sure why it got closed. Reopening that one.

**Comment by hri-tikkumar** [comment]
@znation thank you! for opening #117 again.
