### ISSUE TITLE
Exported Object Detection models have input image width and height swapped

### ISSUE THREAD

**Issue by nickjong** [apple/turicreate#2498]
Our Core ML export for OD incorrectly swaps the height and width of the images expected by the network. This hasn't been an issue until we began supporting non-square output grids, which imply non-square input images. CoreML/Vision will silently resize images to the incorrectly specified dimensions, resulting in erratic performance.

This appears to be fixed in the C++ code path being adopted for our 6.0 release, but we should explicitly test this path.

**Comment by shreyajain17** [comment]
I have verified the issue has been resolved in the cpp code path. 

```
model = tc.object_detector.create(data, 'annotation', max_iterations=1
    ...: , grid_shape=[15,10])
model.export_coreml(/path)
```
Verified by opening coreml model in Xcode, the input shape was (15x32, 10x32) which is the expected output.

**Comment by shreyajain17** [comment]
```model = tc.object_detector.create(data, 'annotation', max_iterations=1, 
   ...: grid_shape=[15,10]) 
model.export_coreml('verify_od.mlmodel')  
import coremltools
model3 = coremltools.models.MLModel('verify_od.mlmodel')
model3.get_spec()  ```
Output -
```specificationVersion: 3
description {
  input {
    name: "image"
    shortDescription: "Input image"
    type {
      imageType {
        width: 320
        height: 480
        colorSpace: RGB
      }
    }
  }```
