### ISSUE TITLE
Object detection not using all CPUs Ubuntu

### ISSUE THREAD

**Issue by BillyBag2** [apple/turicreate#2499]
Using Ubuntu 18.04.3 on a 2x4 core xeon and I only get 200% CPU usage. I have tried to set OMP_NUM_THREADS=8 and also to 32. These make no difference to the performance. The timing, CPU usage and memory usage are all the same. With it set to 32 turicreate bleats about adding code to set TURI_DEFAULT_NUM_PYLAMBDA_WORKERS. Adding this code stops the bleating but performance is the same, CPU usage, timing and memory usage.

**Comment by TobyRoseman** [comment]
@BillyBag2 - Is this still an issue with the latest version of TuriCreate?

**Comment by TobyRoseman** [comment]
I haven't heard back here. So I'm going to close this issue. Please reopen, if it is still a problem in the latest version of TuriCreate.

**Comment by BillyBag2** [comment]
Thanks for keeping an eye on this issue. The platform I was using did not run the latest version as it uses an instruction set that was not supported. So I have, so far, been unable to test this. I have a plan to set up a new machine and will test this.
