### ISSUE TITLE
"non_maximum_suppression_threshold" should be deleted for future OD

### ISSUE THREAD

**Issue by jakesabathia2** [apple/turicreate#2506]
Now in `init_training()`, a state `non_maximum_suppression_threshold ` is added to store the information of the you threshold for nms. 
The reason is the threshold is only for the inference part,
and we want users to choose the threshold by themselves.

**Comment by srikris** [comment]
@nickjong @jakesabathia2 Is this fixed in #2487? If so, can we close this?

**Comment by jakesabathia2** [comment]
Do we haven't, I'll put a separate PR for this.
