### ISSUE TITLE
Removing duplicates based on a subset of columns

### ISSUE THREAD

**Issue by alonpal** [apple/turicreate#2540]
It would be useful to remove duplicate rows of an SFrame based on a subset of columns, similar to pandas' `drop_duplicates`.

In pandas:
```python
df = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'], 'C': [1, 2, 3]})
df.drop_duplicates(subset=['A'])
```
Results in:
```
   A  B  C
0  a  b  1
1  b  a  2
```

As a workaround I used the following but I am not sure if `SELECT_ONE` preserves its choice across columns
```python
sf = tc.SFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'], 'C': [1, 2, 3]})
sf.groupby('A', {col: tc.aggregate.SELECT_ONE(col) for col in sf.column_names() if col != 'A'})
```

**Comment by dhivyaaxim** [comment]
@TobyRoseman  Please assign this ticket to me as I would like to try fixing it and contribute .Thanks in advance!
