### ISSUE TITLE
SFrame plus operator should append

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#2569]
Given two SFrames:
```python
sf1 = tc.SFrame({'a': [1,2,3]})                                                                                                                     
sf2 = tc.SFrame({'a': [6,7]})                                                                                                                       
```
This does not work: `sf1 + sf2`. However this does work `sf1.append(sf2)`. 

Expected: `sf1 + sf2` should work and it should be equivalent to calling`sf1.append(sf2)`. This can be achieved by implementing `SFrame.__add__` and having it call `self.append`.

**Comment by dhivyaaxim** [comment]
@TobyRoseman  Please assign this ticket to me as I would like to try fixing it and contribute .Thanks in advance!
