### ISSUE TITLE
Wrong git SHA in egg/wheel

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#257]
`tc.version_info.git_sha` seems wrong.

```python
In [1]: import turicreate as tc

In [2]: tc.version_info.version
Out[2]: '4.1'

In [3]: tc.version_info.git_sha
Out[3]: '54b25133c1d8b8d84e2e580f546a23348f3c6796'
```

However that doesn't seem to even be a commit in this repository:
https://github.com/apple/turicreate/commit/54b25133c1d8b8d84e2e580f546a23348f3c6796

I would expect it to match the SHA listed here (`39e7f27`): https://github.com/apple/turicreate/releases/tag/v4.1

**Comment by znation** [comment]
@TobyRoseman Hmm, thanks for checking on this. Looks like our build system logic around git sha is a bit messed up.
