### ISSUE TITLE
ModuleNotFoundError: No module named 'turicreate'

### ISSUE THREAD

**Issue by MartinaRogach** [apple/turicreate#2589]
I installed turicreate using virtualenv
MacBook-Pro-Martina:~ martina$ pip3 install virtualenv
MacBook-Pro-Martina:~ martina$ virtualenv venv
MacBook-Pro-Martina:~ martina$ source ~/venv/bin/activate
(venv) MacBook-Pro-Martina:~ martina$ pip install -U turicreate
MacBook-Pro-Martina:~ martina$ which pip3
/Users/martina/venv/bin/pip3
 MacBook-Pro-Martina:~ martina$ which python3
/Users/martina/venv/bin/python3

Then I make project on PyCharm
And when I ran file this error occurred

  File "/Users/martina/PycharmProjects/testing/venv/testing.py", line 1, in <module>
    import turicreate as tc
ModuleNotFoundError: No module named 'turicreate'

Do I make any wrong steps?

**Comment by TobyRoseman** [comment]
@MartinaRogach - It's not clear what you are trying to do. Are you trying to install an official release of TuriCreate and use it? Or our you trying to setup a dev environment for making changes to TuriCreate?

We have [instructions for installing TuriCreate](https://github.com/apple/turicreate#installation) and  [instructions for building TuriCreate](https://github.com/apple/turicreate/blob/master/BUILD.md).

**Comment by syoutsey** [comment]
@MartinaRogach I don't actively use PyCharm, is it possible it's not using the same `venv` you activated from the Terminal? This would explain Turi Create not being found.

**Comment by TobyRoseman** [comment]
Closing this issue. @MartinaRogach - feel free to reopen and clarify what you're trying to accomplish.
