### ISSUE TITLE
Got the Error in recommender system

### ISSUE THREAD

**Issue by Padalingam** [apple/turicreate#259]
When i tried to run the recommended system, i got the following error

import turicreate as tc
data = tc.SFrame({'user_id': ["Ann", "Ann", "Ann", "Brian", "Brian", "Brian"],
                         'item_id': ["Item1", "Item2", "Item4", "Item2", "Item3", "Item5"],
                         'rating': [1, 3, 2, 5, 4, 2],
                 'country':["United States","United States","United States","United States","United States","United States"]
                 })
m = tc.factorization_recommender.create(data, target='rating')

recommendations = m.recommend()
country = 'United States'
recommendations=m.recommend(users=users['user_id'][users['country']==country].unique(), items=items['item_id'][items['country']==country])
print recommendations

Error is
Traceback (most recent call last):
  File "sample.py", line 14, in <module>
    recommendations=m.recommend(users=users['user_id'][users['country']==country].unique(), items=items['item_id'][items['country']==country])
NameError: name 'users' is not defined

**Comment by TobyRoseman** [comment]
@Padalingam - The issue is this part of code on line 14: 
`users['user_id'][users['country']==country].unique()`.
There isn't a variable called `users`.

I think what you are trying to get recommendations for all users of a country and limit those recommendations to only items rated by users of that country. If that is the case, I would recommend creating a temporary variables to make things easier.

Replace line 14 with the following:
```python
country_ratings = data[data['country']==country]
recommendations = m.recommend(users=country_ratings['user_id'].unique(),
                               items=country_ratings['item_id'].unique())
```

**Comment by znation** [comment]
Sounds like this issue has been resolved. @Padalingam, please reopen if you continue to see an issue here after applying @TobyRoseman's suggested change. Thanks!

**Comment by Padalingam** [comment]
Its working fine. Now, my question is after i got the recommended model. how can i store it as a .mlmodel file and to use that recommended model into my iOS project

**Comment by TobyRoseman** [comment]
@Padalingam - That is an open issue, which we are tracking in #34.
