### ISSUE TITLE
Can not load saved model with S3 path

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#2595]
We have the ability to load save SFrames and SArrays using S3 paths. However we can not load saved model using S3 paths. We get the error: `ValueError: Unsupported protocol `.

We should support loading model with S3 paths.

**Comment by srikris** [comment]
Is this a regression from 5.8? or was it always broken?

**Comment by TobyRoseman** [comment]
> Is this a regression from 5.8? or was it always broken?

It does not work in 5.8. I believe it worked at some point.

I just put up a PR. It was a simple fix.
