### ISSUE TITLE
Need the ability to set a smaller batch size for image classifier & image similarity

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#26]
The feature extractor used image classifier and image similarity sets the [batch size to 512](https://github.com/apple/turicreate/blob/39da210238b3381c74f6d6a96779fa1637c11255/src/unity/python/turicreate/toolkits/_image_feature_extractor.py#L74) and we should expose that parameter all the way up to the image classifier and image similarity.

**Comment by gustavla** [comment]
If we do this, it would be good to expose this for object detection too to allow low-memory GPUs. However, it is harder since it doesn't use a stopping criterion based on a validation set and instead a heuristic to set the number of iterations. This heuristic would get more complicated.

**Comment by TobyRoseman** [comment]
This is fixed in beta 1 of version 5.0
