### ISSUE TITLE
Document which platforms turicreate is able to support GPU acceleration.

### ISSUE THREAD

**Issue by otto-schnurr** [apple/turicreate#260]
It's helpful that `turicreate` communicates at runtime that ["Using GPUs is currently not supported on Mac"][runtime error]. However, runtime feedback can be a little late in a setup process (e.g. after working through how to install MXNet from source with CUDA support on a Mac).

Could this limitation be mentioned in the [GPU documentation]? It may help some Mac enthusiasts with NVIDIA cards find this out early and avoid going down the road of trying to setup GPU support for  `turicreate` on their Mac.

[runtime error]: https://github.com/apple/turicreate/blob/v4.1/src/unity/python/turicreate/toolkits/_mxnet_utils.py#L85
[GPU documentation]: https://github.com/apple/turicreate/blob/master/README.md#gpu-support

**Comment by helloniklas** [comment]
@otto-schnurr since MXNet 1.0 works fine with NVIDIA eGPU on Mac if you build from source... won't Turi Create 4.1 work with this?

**Comment by otto-schnurr** [comment]
@helloniklas Yeah, I don't know the backstory behind the toolkit error. In case it involves something more than just MXNet capability, I haven't tried to venture past it.

But yes, even with a CUDA-enabled MXNet, I seem to eventually run into this toolkit error when I try to [`set_num_gpus()`] to 1 on my Mac.

[`set_num_gpus()`]: https://apple.github.io/turicreate/docs/api/generated/turicreate.config.set_num_gpus.html#turicreate.config.set_num_gpus
