### ISSUE TITLE
Toolkits are missing __repr__

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#2606]
Currently, we get the following output with some toolkits in 6.0 master (using DC as an example). 
```
In [31]: model
Out[31]: DrawingClassifier_beta
```

Close this issue when all boxes are checked:

- [x] Drawing Classifier (#2669)
- [x] Object Detector (#2671)
- [x] Style Transfer (#2711)
- [x] Activity classifier (#2680)

**Comment by srikris** [comment]
```
In [10]: model
Out[10]: ObjectDetector_beta
```
@nickjong Can be all fixed in one PR since it's probably the same template that needs to be moved from 5.8

**Comment by shantanuchhabra** [comment]
This is a little more nuanced than just a copy-paste. State variables need to be added/modified, and the summary struct needs to be modified in some places too. I suggest breaking this up into separate issues (and PRs, albeit small). What do you think @srikris @nickjong ?

**Comment by srikris** [comment]
Based on offline conversations, I think it might make sense to put it into a single PR. It should be a pretty small PR.

**Comment by srikris** [comment]
On second thought, doing it by toolkit would actually be simpler and easier to review. It would also ensure we don't have any regressions.

**Comment by shantanuchhabra** [comment]
Per offline discussion, updated this issue to track all toolkits and will put up PRs per toolkit.
