### ISSUE TITLE
Object detector default max iterations doesn't work

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#2608]
```
/Volumes/Data/srikris/workspace/turicreate/debug/src/python/turicreate/extensions.pyc in __run_class_function(self, fnname, args, kwargs)
    275         except RuntimeError as exc:
    276             # Expose C++ exceptions using ToolkitError.
--> 277             raise _ToolkitError(exc)
    278         ret = _wrap_function_return(ret)
    279         return ret

ToolkitError: Option 'max_iterations' must be in the range [1, 2147483647].. operator() from /Volumes/Data/srikris/workspace/turicreate/src/model_server/lib/extensions/option_info.cpp at 160
```

**Comment by shreyajain17** [comment]
The value of `max_iterations` that you passed was 0 or None?

**Comment by srikris** [comment]
I was not using anything. Sorry, I should have made a clear repro step in the original bug report as I am unable to repro it now on current master. This may have been fixed. If you can verify that default and 0 both works on current master then please close this issue.

**Comment by shreyajain17** [comment]
It works for me for default and 0. It does not work when you pass `None`. I think it breaks appropriately as it can only take `int` as input (mentioned in API docs)
