### ISSUE TITLE
API_END in mps_trainer.h needs better logging

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#2613]
[The current logging](https://github.com/apple/turicreate/blob/dbf8fef9256b9a650c7e5e567d5023bfbf546821/src/ml/neural_net/mps_trainer.h#L19) is very minimal. We should print all the information we have available. We probably want to at least log the type of exception. Probably also want to catch common/expected types of exceptions and provide more info.

This is issue is hindering us from further debugging #2600.

**Comment by nickjong** [comment]
This code path is going away in 6.0. `mps_trainer.h` is only for the old Python implementations to talk to the MPS backend.
