### ISSUE TITLE
Can not load SFrame from S3 on Linux

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#2648]
This seems to happen with any SFrame but only on Linux.

**Comment by syoutsey** [comment]
@TobyRoseman Does this also apply to loading any remote SFrame period, say like using one of the SFrames listed in our user guide?

**Comment by TobyRoseman** [comment]
> @TobyRoseman Does this also apply to loading any remote SFrame period, say like using one of the SFrames listed in our user guide?

I believe it affects all SFrame. We don't believe we have any S3 SFrames in our user guide.
