### ISSUE TITLE
Setting number of GPUs to 0 on a CUDA machine should disable use of GPUs

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#2651]
For image classifier, the following command doesn't force compute on the CPUs
```
tc.config.set_num_gpus(0)
```

**Comment by nickjong** [comment]
Looks like TensorFlow only controls this via the environment variable `CUDA_VISIBLE_DEVICES`: https://github.com/tensorflow/tensorflow/issues/9201

**Comment by srikris** [comment]
So should we set that variable when the config sets the number of GPUs? or should we only enable this config parameter on the Mac?
