### ISSUE TITLE
Plot API for inline display in Jupyter Notebook

### ISSUE THREAD

**Issue by znation** [apple/turicreate#266]
Currently, the `show` method is the only way to get a plot from SFrame/SArray, and the plot immediately opens in a native GUI app.

Ideally, we should provide a way to create and manipulate plot objects in the API, which can then be rendered to Jupyter Notebook (see http://ipython.readthedocs.io/en/stable/config/integrating.html#rich-display )

The resulting plot object could also be:
* shown in native GUI (`.show()`)
* saved to a file (`.save()`)
* combined with other plot objects into a tiled view (perhaps `tc.show(a, b, c, d)` where a,b,c,d are plot objects)

**Comment by znation** [comment]
I'm rethinking overloading `tc.show` - it is a bit too overloaded already. Perhaps something like `tc.visualization.tile(a,b,c,d)` to explicitly tile multiple plots. We could add other things under the `tc.visualization` namespace, like explicit plot types (where we currently auto-select among plot types under the hood; users may sometimes want to choose).

**Comment by abhishekpratapa** [comment]
Fixed with #294
