### ISSUE TITLE
Unfix numpy dependency

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#2664]
Currently in our [setup.py](https://github.com/apple/turicreate/blob/b0d779698669ea4f3056056f7b45247f8c25dea2/src/python/setup.py#L117) we fix our numpy dependency: `numpy==1.16.4`.

This is likely to cause dependency conflicts in our users' environments. Instead we should fix a minimum version. However we should be aware that the dependency range that `coremltools` specifies is [not accurate](https://github.com/apple/coremltools/issues/456).

**Comment by srikris** [comment]
@TobyRoseman What's left to be done on this?

**Comment by TobyRoseman** [comment]
> @TobyRoseman What's left to be done on this?

The coremltools python package needs to do a release with my fix. Then turicreate needs to depend on that new version and unfix the numpy dependency.

**Comment by TobyRoseman** [comment]
The 3.2 release of coremltools does not fix [the underlying issue](https://github.com/apple/coremltools/issues/456). Removing from the current milestone.
