### ISSUE TITLE
Add batch_size as an option to image_classifier and reduce the default from 512 for memory reasons.

### ISSUE THREAD

**Issue by tarakinsuide** [apple/turicreate#267]
Why is my training file throwing this error?

My code is below:
```
import turicreate as tc

# Load the data
data = tc.SFrame('/home/tarak/PycharmProjects/turicreate1/peacock.sframe')

# Make a train-test split
train_data, test_data = data.random_split(0.8)

# Create a model
model = tc.image_classifier.create(train_data, target='label',  max_iterations=1000)

# Save predictions to an SFrame (class and corresponding class-probabilities)
predictions = model.classify(test_data)

# Evaluate the model and save the results into a dictionary
results = model.evaluate(test_data)
print ("Accuracy         : %s" % results['accuracy'])
print ("Confusion Matrix : \n%s" % results['confusion_matrix'])

# Save the model for later usage in Turi Create
model.save('peacock.model')
```

**Comment by tarakinsuide** [comment]
[15:58:47] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[15:58:47] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
Resizing images...
Performing feature extraction on resized images...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by gustavla** [comment]
Hi @tarakinsuide! Sorry you are having issues like this. Let's see if you can figure out what's going on.

Can you try firing up python and doing:
```python
>>> import mxnet
```
Does that produce the same error? I suspect your MXNet installation is broken somehow. Which version do you have (`pip freeze | grep -i mxnet`)?

**Comment by askayastha** [comment]
Hi @gustavla. I am facing the same issue when running it on an Ubuntu 18.04 LTS cloud instance. Any idea, when this is going to be fixed?

**Comment by srikris** [comment]
Some clarifying questions to narrow down the issue:
- How large are your images
- How much memory does your machine have?
- Are you using the CPU or the GPU?

**Comment by askayastha** [comment]
@srikris Here's my data and instance configuration:

- I am using the [Kaggle Cats and Dogs Dataset](https://www.microsoft.com/en-us/download/details.aspx?id=54765) with around 30 KB per image (approx. 500 X 500 px).
- I am using an instance of 4 GB memory.
- I am using 2 core Intel(R) Xeon(R) CPU @ 2.30GHz without the GPU.

**Comment by srikris** [comment]
Can you try reducing the batch_size to 32? The default batch size might be larger.

**Comment by askayastha** [comment]
@srikris I am just getting started with turicreate. Where can we set the batch_size in this framework?

`# Load the data
data = tc.SFrame('cats-dogs.sframe')

# Make a train-test split
train_data, test_data = data.random_split(0.8)

# Automatically pick the right model based on your data.
# Note: Because the dataset is large, model creation may take hours.
model = tc.image_classifier.create(train_data, target='label')

# Save predictions to an SArray
predictions = model.predict(test_data)

# Evaluate the model and save the results into a dictionary
metrics = model.evaluate(test_data)
print(metrics['accuracy'])

# Save the model for later use in Turi Create
model.save('mymodel.model')

# Export for use in Core ML
model.export_coreml('MyCustomImageClassifier.mlmodel')`

**Comment by srikris** [comment]
Before I suggest a workaround for this, can you try this:

```
model = tc.image_classifier.create(train_data, target = 'label', model = 'squeezenet_v1.1')
````

And see if that crashes.

**Comment by askayastha** [comment]
@srikris Using squeezenet_v1.1 didn't work. Here's full the error log:

Downloading https://docs-assets.developer.apple.com/turicreate/models/squeezenet_v1.1-symbol.json
Download completed: /var/tmp/model_cache/squeezenet_v1.1-symbol.json
Downloading https://docs-assets.developer.apple.com/turicreate/models/squeezenet_v1.1-0000.params
Download completed: /var/tmp/model_cache/squeezenet_v1.1-0000.params
[14:23:47] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[14:23:47] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
Resizing images...
Performing feature extraction on resized images...
^AcCorrupt JPEG data: 401 extraneous bytes before marker 0xd9
Corrupt JPEG data: 240 extraneous bytes before marker 0xd9
Corrupt JPEG data: 215 extraneous bytes before marker 0xd9
Corrupt JPEG data: 131 extraneous bytes before marker 0xd9
Corrupt JPEG data: 161 extraneous bytes before marker 0xd9
Warning: unknown JFIF revision number 0.00
Corrupt JPEG data: 1406 extraneous bytes before marker 0xd9
Corrupt JPEG data: 258 extraneous bytes before marker 0xd9
Corrupt JPEG data: 102 extraneous bytes before marker 0xd9
Corrupt JPEG data: 2229 extraneous bytes before marker 0xd9
Corrupt JPEG data: 1158 extraneous bytes before marker 0xd9
Corrupt JPEG data: 67 extraneous bytes before marker 0xd9
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by askayastha** [comment]
@srikris Without any modification, the sample code from turicreate docs doesn't get this error in my mid-2012 MacBook Air with far less CPU and memory specs. However, due the size of the dataset I had to cancel the training and run it on a cloud instance.

**Comment by askayastha** [comment]
@srikris Here's the mxnet version.
mxnet==1.1.0.post0

**Comment by askayastha** [comment]
@srikris Setting the batch_size to 32 solved the issue. I see that the default batch size was 512.

Thanks.

**Comment by srikris** [comment]
Great. We will pull that into the next release thanks.

**Comment by gustavla** [comment]
That's really good to know, thanks @askayastha. There is an issue tracking this #26 and I was never convinced it was a memory issue. It looks like it is thanks to your experiment, so that is really useful to know. We'll add this option.

**Comment by TobyRoseman** [comment]
@askayastha @tarakinsuide - with the release of beta 1 for Turi Create 5.0, a `batch_size` parameter has been added to `create`, `predict`, `classify`, and `evaluate`. We have also reduced the default value to 64.
