### ISSUE TITLE
Regularization Parameters in Factorization Machine

### ISSUE THREAD

**Issue by bszeng** [apple/turicreate#2675]
When I called the `factorization_recommender.create()` function to build a factorization machine model, I can't match the `regularization` and `linear_regularization` to r0, r1 and r2 in libFM:

r0=bias regularization,
r1=1-way regularization
r2=2-way regularization

Thanks for any help.

**Comment by syoutsey** [comment]
Hi @bszeng are you able to provide a dataset or something to reproduce this issue?

**Comment by bszeng** [comment]
Thank you for your prompt reply @syoutsey .

The result of `FactorizationRecommender.show` is as follows, where I can only find two regularization parameters.  Is there any need for additional information?

```
Schema
------
User ID                          : user_id
Item ID                          : item_id
Target                           : rating
Additional observation features  : 11
User side features               : []
Item side features               : []

Statistics
----------
Number of observations           : 587911
Number of users                  : 3594
Number of items                  : 153

Training summary
----------------
Training time                    : 3.532

Model Parameters
----------------
Model class                      : FactorizationRecommender
num_factors                      : 11
binary_target                    : 0
side_data_factorization          : 1
solver                           : sgd
nmf                              : 0
max_iterations                   : 10000

Regularization Settings
-----------------------
regularization                   : 0.0001
regularization_type              : normal
linear_regularization            : 0.0001

Optimization Settings
---------------------
init_random_sigma                : 0.01
sgd_convergence_interval         : 4
sgd_convergence_threshold        : 0.0
sgd_max_trial_iterations         : 5
sgd_sampling_block_size          : 131072
sgd_step_adjustment_interval     : 4
sgd_step_size                    : 0.0
sgd_trial_sample_minimum_size    : 10000
sgd_trial_sample_proportion      : 0.125
step_size_decrease_rate          : 0.75
additional_iterations_if_unhealthy : 5
adagrad_momentum_weighting       : 0.9
num_tempering_iterations         : 4
tempering_regularization_start_value : 0.0
track_exact_loss                 : 0
```

**Comment by hoytak** [comment]
Hello @bszeng, 

The issue may be due to some of the ways we scale the data ahead of time.  Take a look at 

https://github.com/apple/turicreate/issues/1691

Let me know if that helps.

**Comment by bszeng** [comment]
Hi @hoytak, I'm not sure that it is correct to define the optimization problem as formula (1) and the global bias term _μ_ in formula (2) isn't regularized. 

![image](https://user-images.githubusercontent.com/45512350/69433624-e9522c00-0d76-11ea-9632-66c0f3187fa2.png)
