### ISSUE TITLE
User guide needs to updated to incorporate the new AC export_coreml format

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#2676]
With 6.0, we now have one feature vector per feature and one combined state. The user guide has to reflect this change (while continuing to document version 5.8-) and the code should be tested in the app. 

<img width="818" alt="image" src="https://user-images.githubusercontent.com/1875987/69128290-c961f600-0a60-11ea-840d-3cbbf36ac75f.png">v

**Comment by syoutsey** [comment]
Working on this.
