### ISSUE TITLE
turicreate.load_audio does not fail on invalid path

### ISSUE THREAD

**Issue by hoytak** [apple/turicreate#2686]
Turicreate load_audio does not fail if a path does not exist:

```
data = tc.load_audio("Path does not exist")
```

simply produces an empty sframe.

**Comment by dhivyaaxim** [comment]
@hoytak Please assign this ticket to me as I would like to try fixing it and contribute .Thanks in advance!

**Comment by shreyajain17** [comment]
It also seems to not work on relative path.
