### ISSUE TITLE
Activity Classifier Name Error with Advanced Parameters

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#2689]
Stacktrace:
```
File "turicreate/toolkits/activity_classifier/_activity_classifier.py", line 166, in create
    set_keys = set(params.keys())
NameError: name 'params' is not defined
```
[`params` does indeed seem not to be defined](https://github.com/apple/turicreate/blob/93335055e6619e8e3eed4a65962c875b921bda48/src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py#L166). It's not immediately clear to me how to fix it.

**Comment by shreyajain17** [comment]
I think I made params when tensorflow was optional. I removed params when it wasn't need but forgot to remove the code to update `advanced_paramters_` and add them to params. I don't think we have `advanced_parameters_` as of now. I think we could just remove the `advanced_parameters` code for now.

**Comment by dhivyaaxim** [comment]
@TobyRoseman  Please assign this ticket to me as I would like to try fixing it and contribute .Thanks in advance!
