### ISSUE TITLE
Never call tensorflow.compat.v1.reset_default_graph()

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#2731]
Calling this function basically clears TensorFlow's state, which will destroy the image feature extractors and any Sound Classifier instances. If the user has TensorFlow objects in their environment, it will also remove them.

Many of our toolkit assume only their objects are in the default graph. We need to fix this assumption before we remove the call to reset the default graph. 

I think there are two basic approaches for this fix:
1 - Use a scope/namespace. #2712 is doing this for the Sound Classifier. 
2 - Use different TensorFlow sessions/graphs for each toolkit instances.
The second one is almost certainly preferable.

**Comment by fareeha** [comment]
Maybe we want to create graph context managers for each of the TF toolkits similar to #2741

**Comment by fareeha** [comment]
#2741
