### ISSUE TITLE
Error comparing  recommender models

### ISSUE THREAD

**Issue by subodhchhabra** [apple/turicreate#2758]
while calling tc.recommender.util.compare_models(tst, models=[m1, m2, m3]), statement errors with following error ..

TypeError                                 Traceback (most recent call last)
<ipython-input-22-49698e8a1e95> in <module>
----> 1 tc.recommender.util.compare_models(tst, models=[m1, m2, m3], verbose=False)

~/anaconda3/envs/turi/lib/python3.7/site-packages/turicreate/toolkits/recommender/util.py in compare_models(dataset, models, model_names, user_sample, metric, target, exclude_known_for_precision_recall, make_plot, verbose, **kwargs)
    323                        verbose=verbose,
    324                        cutoffs=list(range(1,11,1))+list(range(11,50,5)),
--> 325                        **kwargs)
    326         results.append(r)
    327 

TypeError: evaluate() got an unexpected keyword argument 'verbose'

**Comment by syoutsey** [comment]
Hi @subodhchhabra, what version of Turi Create are you running? How about operating system?

**Comment by subodhchhabra** [comment]
mac OS 10.14.6, 
TuriCreate - 5.8

**Comment by TobyRoseman** [comment]
After looking at the relevant code, I'm guessing at least one of the models isn't a recommender.

@subodhchhabra - what types of models are `m1`, `m2`, and `m3`?

**Comment by subodhchhabra** [comment]
yes, I did miss that , so I guess we need to check of model type is a recommender.

**Comment by TobyRoseman** [comment]
> yes, I did miss that , so I guess we need to check of model type is a recommender.

Agreed. `turicreate.recommender.util.compare_models` should make sure all of the models passed in our sub classes of `turicreate.toolkits.recommender.util._Recommender`.
