### ISSUE TITLE
TF OD regression in MAP

### ISSUE THREAD

**Issue by shreyajain17** [apple/turicreate#2770]
Training Dataset - ig02

Metrics from 5.8 

MAP 50 - 0.64646 
AP 50 Bikes -0.75243 
AP 50 Cars- 0.54048 

Metrics from 6.0

MAP 50 - 0.26645
AP 50 Bikes - 0.43206
AP 50 Cars -  0.10083

**Comment by jakesabathia2** [comment]
I think this is duplicated with https://github.com/apple/turicreate/issues/2769
