### ISSUE TITLE
Style Transfer inference is 4x slower in master versus in 5.8.

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#2798]
Repro steps:
1. Follow the user guide and train a model.
2. Stylize a content image.

Inference time was about 250 milliseconds per image in 5.8, and is 1 second per image in master.

**Comment by guihao-liang** [comment]
Reproduced. Working on it. Good catch.

**Comment by guihao-liang** [comment]
![image](https://user-images.githubusercontent.com/14238915/72392102-07d40400-36e4-11ea-8112-afdd76aeec1a.png)
from my inspection, the most time spent on `stylize` function is on
1. create_compute_context::create_style_transfer 400ms
2. tf_model_backend::predict 414 ms

The bottleneck is on the python call layer.
![image](https://user-images.githubusercontent.com/14238915/72392769-b3ca1f00-36e5-11ea-9069-ee0954aa50bf.png)

Besides that, revealed another bug the table printer will duplicate the result for the last entry,
![image](https://user-images.githubusercontent.com/14238915/72392833-e1af6380-36e5-11ea-986d-0cd1575aaf3e.png)
Where I only have one image to stylize. This is an easy fix.

**Comment by guihao-liang** [comment]
Per discussion with @shreyajain17, the Tensorflow graph is re-initialized every time when `predict` is called, which is to accommodate different image sizes. @abhishekpratapa can give more explanation on this issue and make a decision to mark this as a known issue or not. My investigation stops here. I will wait for final decisions from @abhishekpratapa.

**Comment by abhishekpratapa** [comment]
If you pass in the shape as a placeholder then we can prevent re-initializing the graph every-time. This I suspect is the correct solution.

**Comment by guihao-liang** [comment]
talked with @shantanuchhabra and he will provide more information about platform, CPU or GPU path, for me to reproduce.

**Comment by guihao-liang** [comment]
As it's tested locally on 10.15 with **GPU** path by @shreyajain17, the performance of stylizing a single image is around 110ms. #2937 resolves regressions on the **CPU** path.
