### ISSUE TITLE
How to test the turi detection model on video ?

### ISSUE THREAD

**Issue by ShreshthSaxena** [apple/turicreate#2814]
Is there a built-in function for prediction on videos ?

**Comment by TobyRoseman** [comment]
Currently TuriCreate has no support for video. However that's a great feature request. I'll leave this issue open to track that feature request.

@ShreshthSaxena - please give us more details about what you would like TuriCreate to support. Are you using an image classifier model, an object detection or some other type of model?

**Comment by ShreshthSaxena** [comment]
I'm using an object detection model for detecting objects in videos. 
Is it possible to export the turicreate model to a format other than 'mlmodel' (ex h5) where I can use it to predict on videos?
Makes it better to test the model instead of having to run it on an app every time.
Thanks

**Comment by TobyRoseman** [comment]
@ShreshthSaxena - it is not possible to export TuriCreate models to anything except CoreML (or TuriCreate's own binary format).

I'm going to close this issue as a duplicate of #343.
