### ISSUE TITLE
Remove all remnants of MXNet 

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#2826]
MXNet is no longer a dependency of TuriCreate. However we still have [lots of dead code that uses it](https://github.com/apple/turicreate/search?q=mxnet&unscoped_q=mxnet). We should remove this dead code.

**Comment by RonsenbergVI** [comment]
When will version 6.1 be ready? As tc 5.8 requires mxnet<1.2.0 >=1.1.0 I am experiencing difficulties using it with other current libraries without having to use old versions (current version is >1.5 and most libraries that I use have already moved to newer versions)
