### ISSUE TITLE
OD: invalid coordinate value gets no error and make it through

### ISSUE THREAD

**Issue by Jarvi-Izana** [apple/turicreate#2833]
#2830 

same repro, except change the `func` into:
```
 39 def func(x):
 40     for y in x:
 41         # y["coordinates"]['x'] = None # y["coordinates"]['y'] = None
 42         y["coordinates"]['width'] = None
 43         y["coordinates"]['height'] = None
 44     return x
```

feel free to play with it.

**Comment by jakesabathia2** [comment]
hmmmm cool ;)

**Comment by jakesabathia2** [comment]
```
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
| 1            | 4.39937      | 2.92s        |
| 2            | 4.5508       | 3.53s        |
| 3            | 4.50975      | 4.63s        |
| 4            | 4.43646      | 5.56s        |
| 5            | 4.30856      | 6.29s        |
| 6            | 4.39513      | 7.02s        |
| 11           | 4.18712      | 10.68s       |
| 16           | 4.43339      | 14.34s       |
| 21           | 4.43974      | 18.50s       |
| 26           | 3.96112      | 22.16s       |
| 31           | 3.98385      | 25.81s       |
| 36           | 3.64385      | 29.48s       |
| 41           | 3.83445      | 34.50s       |
| 46           | 4.22252      | 38.24s       |
| 51           | 3.56531      | 43.04s       |
| 56           | 4.0538       | 46.69s       |
| 61           | 3.85165      | 51.21s       |
| 66           | 3.63041      | 54.87s       |
| 71           | 3.45167      | 58.53s       |
| 76           | 3.37094      | 1m 2s        |
| 81           | 3.50457      | 1m 6s        |
| 86           | 3.10482      | 1m 10s       |
| 91           | 3.43324      | 1m 13s       |
| 96           | 3.18027      | 1m 17s       |
| 100          | 3.40443      | 1m 20s       |
+--------------+--------------+--------------+
```
haha interesting ;)

**Comment by Jarvi-Izana** [comment]
I bet the missing value is skipped. Check the log while you run this code snippet. If there's a log associated with it, it should be better we can surface it to users.

what you need to do is to get the log file location of current running python process
```
tc.config.get_server_log_location()
```

don't close the process. At the same time,
```
tail -f <log>
```
and run the repro code. In this way, you can check whether the missing value is logged or not.

**Comment by jakesabathia2** [comment]
'None' is converted to `0` in data iterator. nvm it is a easy fix.

**Comment by Jarvi-Izana** [comment]
> `None` is converted to `0` in the data iterator. nvm, it is an easy fix.

Okay, it should be an easy fix in the documentation to mention how None is treated under a certain context. It's reasonable to set None as 0 for width and height but not for x and y. You can surface it to the user to let them know None is treated as zero during runtime so they can choose to stop the training process and call `dropna` first.

**Comment by jakesabathia2** [comment]
> > `None` is converted to `0` in the data iterator. nvm, it is an easy fix.
> 
> Okay, it should be an easy fix in the documentation to mention how None is treated under a certain context. It's reasonable to set None as 0 for width and height but not for x and y. You can surface it to the user to let them know None is treated as zero during runtime so they can choose to stop the training process and call `dropna` first.

hmmmm I don't think either this 4 number should be `None`,
if width and height is `0` that means the bounding box is invalid.

**Comment by Jarvi-Izana** [comment]
> > > `None` is converted to `0` in the data iterator. nvm, it is an easy fix.
> > 
> > 
> > Okay, it should be an easy fix in the documentation to mention how None is treated under a certain context. It's reasonable to set None as 0 for width and height but not for x and y. You can surface it to the user to let them know None is treated as zero during runtime so they can choose to stop the training process and call `dropna` first.
> 
> hmmmm I don't think either this 4 number should be `None`,
> if width and height is `0` that means the bounding box is invalid.

it could mean there's no bounding box?
