### ISSUE TITLE
AC: validation data with missing values isn't dropped when creating model.

### ISSUE THREAD

**Issue by jakesabathia2** [apple/turicreate#2841]
```
validation_set = tc.SFrame({'exp_id':[987,None],'activity':['standing','standing'],
		'acc_x':[0.,None],'acc_y':[0.,None],'acc_z':[0.,9.8],'gyro_x':[0.,3.1],'gyro_y':[0.,1.1],'gyro_z':[0.,9.8]})
	model = tc.activity_classifier.create(data,session_id='exp_id',target='activity',
		max_iterations=max_iterations,prediction_window=prediction_window, validation_set=validation_set)
```
In this case the second row of validation data should be dropped ;).
5.8 intends to do this as well but I believe this case is not properly handled due to a bug here:
https://github.com/apple/turicreate/blob/5b909fbde6a4f36adf2fe94a849abdbb4333ac40/src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py#L244
which should be 
```
_tkutl._handle_missing_values(validation_set, feature, 'validation_set')
```
instead.

This should be a quick fix, @srikris do you think it is 6.0 issue or 6.1 ?

**Comment by srikris** [comment]
Let's please take this for 6.1
