### ISSUE TITLE
Image similarity for image outside of reference dataset

### ISSUE THREAD

**Issue by pbojinov** [apple/turicreate#285]
From what I understand after reading the docs on [similar images](https://github.com/apple/turicreate/blob/master/userguide/image_similarity/README.md), the examples provide a way to find the most similar images in the reference dataset for all images in the reference dataset.

How would one find similar images in the dataset to an image outside of the dataset? Is this currently possible with the image similarity method described in the docs?

**Comment by srikris** [comment]
The `query` method lets you query for new images. For example, the following code will give you the 10 closest images in your dataset given 10 new images

```
similar_images = model.query(new_images[0:10], k=10)
```
