### ISSUE TITLE
IOError: [Errno 13] Permission denied: '/var/tmp/model_cache/resnet-50-symbol.json'

### ISSUE THREAD

**Issue by Padalingam** [apple/turicreate#286]
**Error**
Done.
Downloading https://docs-assets.developer.apple.com/turicreate/models/resnet-50-symbol.json
Traceback (most recent call last):
  File "classifier.py", line 9, in <module>
    model = turi.image_classifier.create(trainingBuffers, target="chairType", model="resnet-50")
  File "/Library/Python/2.7/site-packages/turicreate/toolkits/image_classifier/image_classifier.py", line 116, in create
    ptModel = _pre_trained_models.MODELS[model]()
  File "/Library/Python/2.7/site-packages/turicreate/toolkits/_pre_trained_models.py", line 98, in __init__
    ], path)
  File "/Library/Python/2.7/site-packages/turicreate/toolkits/_pre_trained_models.py", line 52, in _download_and_checksum_files
    with open(fn, 'wb') as f:
IOError: [Errno 13] Permission denied: '/var/tmp/model_cache/resnet-50-symbol.json'

**Comment by gustavla** [comment]
Hi @Padalingam, thanks for trying out the image classifier! Before the classifier is used, it downloads a model file from the internet and it looks like Turi Create wanted to put the model in a location that you don't have access to. This should not happen and is a bug that we need to address. Thanks for bringing it to our attention!

In the meantime, I think I have a work-around for you. The directory where the model gets saved can be manually specified using the environment variable `TURI_CACHE_FILE_LOCATIONS`. I see that you are on a Mac, so this typically involves adding the following line to the end of `~/.bash_profile` (if you don't have this file, then create an empty one first):

```
export TURI_CACHE_FILE_LOCATION=~/turicreate
```

Of course, you can choose the location yourself, but I recommend placing it in your home directory under `~/...` to ensure permissions to write to it.

**Comment by Padalingam** [comment]
This is working fine, when i tried to run as a root user.

**Comment by TobyRoseman** [comment]
@gustavla - I agree we need a better error message here (and everywhere else we download model assests) that tells users how to change the cache location. If you think any thing else needs to be done, please share details.
