### ISSUE TITLE
Help Needed on image classification

### ISSUE THREAD

**Issue by Padalingam** [apple/turicreate#288]
Hi All,
Can any one help me on this below questions
1) what will be the input image size and its height/width?
2) How many images, do i need to put on my dataset to get good prediction result?

Explanation Needed:
I got this warning lot of times when i run two label image classification
WARNING: The number of feature dimensions in this problem is very large in comparison with the number of examples. Unless an appropriate regularization value is set, this model may not provide accurate predictions for a validation/test set.
Logistic regression:
--------------------------------------------------------
Number of examples          : 51
Number of classes           : 2
Number of feature columns   : 1
Number of unpacked features : 1000
Number of coefficients    : 1001
Starting L-BFGS
--------------------------------------------------------
+-----------+----------+-----------+--------------+-------------------+
| Iteration | Passes   | Step size | Elapsed Time | Training-accuracy |
+-----------+----------+-----------+--------------+-------------------+
| 1         | 3        | 0.019608  | 1.040894     | 1.000000          |
| 2         | 8        | 0.035423  | 1.106335     | 1.000000          |
| 3         | 9        | 0.035423  | 1.127258     | 1.000000          |
| 4         | 10       | 0.035423  | 1.147626     | 1.000000          |
| 5         | 11       | 0.035423  | 1.169925     | 1.000000          |
| 6         | 12       | 0.035423  | 1.191988     | 1.000000          |
+-----------+----------+-----------+--------------+-------------------+
TERMINATED: Iteration limit reached.
This model may not be optimal. To improve it, consider increasing `max_iterations`.

3) Why this operation is terminated
4) Instead of terminated, How can i get success message?

**Comment by TobyRoseman** [comment]
@Padalingam -

1 - The Image Classifier automatically resizes images for you. So you don't need to worry about that.

2 - There's no hard and fast rules here, but only 50 examples is certainly on the low end. It could work, but more data would be better.

3 & 4 - It's just a warning. I would not worry too much about this warning. It's probably fine. Try out the model on a test set.
