### ISSUE TITLE
Can I add self edge to graph?

### ISSUE THREAD

**Issue by bale-john** [apple/turicreate#2888]
Hi!
I come from PowerGraph in which self edges are not allowed. It's maybe a naive question, but does some one mind telling me why and can I do it in turi?

**Comment by TobyRoseman** [comment]
TuriCreate supports having edges where the source and destination are the same vertex. 

Here is a simple example:
```python
from turicreate import SGraph, Vertex, Edge
g = SGraph()
verts = [Vertex('V0'), Vertex('V1'), Vertex('V2')]
g = g.add_vertices(verts)
g = g.add_edges(Edge('V1', 'V1'))
print(g.get_edges())
```
