### ISSUE TITLE
Error In installing turicreate

### ISSUE THREAD

**Issue by henrycao2019** [apple/turicreate#2894]
I am trying to install turicreate with:

pip3 install Turicreate

However, I am getting the following message. I have both Python 3.6 and 3.7 installed.

    ERROR: Command errored out with exit status 1:
     command: 'c:\users\hcao6\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hcao6\\AppData\\Local\\Temp\\pip-install-hmt_alj4\\Turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\hcao6\\AppData\\Local\\Temp\\pip-install-hmt_alj4\\Turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\hcao6\AppData\Local\Temp\pip-record-0z9hjwcn\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\hcao6\venv\include\site\python3.7\Turicreate'
         cwd: C:\Users\hcao6\AppData\Local\Temp\pip-install-hmt_alj4\Turicreate\
    Complete output (28 lines):
    running install

            ==================================================================================
            TURICREATE ERROR

            If you see this message, pip install did not find an available binary package
            for your system.

            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).

            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7

            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`

            ==================================================================================

    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\hcao6\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hcao6\\AppData\\Local\\Temp\\pip-install-hmt_alj4\\Turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\hcao6\\AppData\\Local\\Temp\\pip-install-hmt_alj4\\Turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\hcao6\AppData\Local\Temp\pip-record-0z9hjwcn\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\hcao6\venv\include\site\python3.7\Turicreate' Check the logs for full command output.

**Comment by TobyRoseman** [comment]
Hi @henrycao2019 - it looks like your operating system is Windows. TuriCreate does not support Window directly. However we do support [Windows 10 via WSL](https://github.com/apple/turicreate#supported-platforms). I'm going to close this issue, but let me know if you have any questions.

We are tracking native Windows support in #533.

**Comment by rajputsanyamsingh** [comment]
> I am trying to install turicreate with:
> 
> pip3 install Turicreate
> 
> However, I am getting the following message. I have both Python 3.6 and 3.7 installed.
> 
> ```
> ERROR: Command errored out with exit status 1:
>  command: 'c:\users\hcao6\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hcao6\\AppData\\Local\\Temp\\pip-install-hmt_alj4\\Turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\hcao6\\AppData\\Local\\Temp\\pip-install-hmt_alj4\\Turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\hcao6\AppData\Local\Temp\pip-record-0z9hjwcn\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\hcao6\venv\include\site\python3.7\Turicreate'
>      cwd: C:\Users\hcao6\AppData\Local\Temp\pip-install-hmt_alj4\Turicreate\
> Complete output (28 lines):
> running install
> 
> 
> 
>         ==================================================================================
>         TURICREATE ERROR
> 
>         If you see this message, pip install did not find an available binary package
>         for your system.
> 
>         Supported Platforms:
>             * macOS 10.12+ x86_64.
>             * Linux x86_64 (including WSL on Windows 10).
> 
>         Support Python Versions:
>             * 2.7
>             * 3.5
>             * 3.6
>             * 3.7
> 
> 
>         Another possible cause of this error is an outdated pip version. Try:
>             `pip install -U pip`
> 
>         ==================================================================================
> 
> 
> 
> ----------------------------------------
> ```
> 
> ERROR: Command errored out with exit status 1: 'c:\users\hcao6\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\hcao6\AppData\Local\Temp\pip-install-hmt_alj4\Turicreate\setup.py'"'"'; **file**='"'"'C:\Users\hcao6\AppData\Local\Temp\pip-install-hmt_alj4\Turicreate\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\hcao6\AppData\Local\Temp\pip-record-0z9hjwcn\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\hcao6\venv\include\site\python3.7\Turicreate' Check the logs for full command output.

same problem with me even i m using wsl and also other requirements are fulfilled but still unable to install .
