### ISSUE TITLE
Error while installing Turicreate on Mac

### ISSUE THREAD

**Issue by indra7979** [apple/turicreate#2903]
I am trying to install turicreate with:

pip3 install Turicreate

However, I am getting the following message. I have both Python 3.6 and 3.7 installed.

`_Collecting Turicreate
  Using cached https://files.pythonhosted.org/packages/1e/c6/3f63d7ea7f0660016e18e5f638a60b523d7ac3d42aef39cd0dfe52e5db95/turicreate-6.0.tar.gz
Installing collected packages: Turicreate
    Running setup.py install for Turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/indra/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pd/xr2bn9cx12sd2rr2ccg8b0c40000gn/T/pip-install-9fpt0u_h/Turicreate/setup.py'"'"'; __file__='"'"'/private/var/folders/pd/xr2bn9cx12sd2rr2ccg8b0c40000gn/T/pip-install-9fpt0u_h/Turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pd/xr2bn9cx12sd2rr2ccg8b0c40000gn/T/pip-record-7tazhy87/install-record.txt --single-version-externally-managed --compile --install-headers /Users/indra/env/include/site/python3.8/Turicreate
         cwd: /private/var/folders/pd/xr2bn9cx12sd2rr2ccg8b0c40000gn/T/pip-install-9fpt0u_h/Turicreate/
    Complete output (28 lines):
    running install
    
    
    
            ==================================================================================
            TURICREATE ERROR
    
            If you see this message, pip install did not find an available binary package
            for your system.
    
            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).
    
            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7
    
    
            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`
    
            ==================================================================================
    
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/indra/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pd/xr2bn9cx12sd2rr2ccg8b0c40000gn/T/pip-install-9fpt0u_h/Turicreate/setup.py'"'"'; __file__='"'"'/private/var/folders/pd/xr2bn9cx12sd2rr2ccg8b0c40000gn/T/pip-install-9fpt0u_h/Turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pd/xr2bn9cx12sd2rr2ccg8b0c40000gn/T/pip-record-7tazhy87/install-record.txt --single-version-externally-managed --compile --install-headers /Users/indra/env/include/site/python3.8/Turicreate Check the logs for full command output._`

I am using a MacOS Version 10.15.2. Please help me out.

**Comment by TobyRoseman** [comment]
I tired just tried running `pip3 install Turicreate` on macOS 10.15.2 with python 3.7. It worked fine for me.

@indra7979 - I'm not sure why you're having this issue. My best guess would be that your `pip3` is old. Please update it (by running `pip3 install --upgrade pip`) and then try to install TuriCreate again.

**Comment by nicoinn** [comment]
The last line in your log shows that you are trying to install it on a Python 3.8 setup. 

`/Users/indra/env/include/site/python3.8/Turicreate Check the logs for full command output._`


You are probably in a wrong virtualenv or you aren't running the python version you think you are using.

**Comment by TobyRoseman** [comment]
Thanks @nicoinn. I agree, that is the issue.
