### ISSUE TITLE
Failing Unit Test on macOS 10.14+

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#2904]
Several unit tests from `test_recommender.py` and `test_audio_functionality.py` are failing due to #2835.

#2898 is working on fixing it, but it's not ready yet. Until it is ready we should temporarily skip these unit tests.

**Comment by srikris** [comment]
@TobyRoseman Can we close this?

**Comment by TobyRoseman** [comment]
@srikris - I don't think we should close this yet; the issue has not been fixed in master yet.

When #2909 is merged, let's close this issue and open up a new P1 issue to re-enable 10.13 in GitLab.
