### ISSUE TITLE
Can't export activity classifier to CoreML.

### ISSUE THREAD

**Issue by mecid** [apple/turicreate#2945]
Can't export activity classifier to CoreML. It works well with TuriCreate 5, broken with 6.0.

`
turicreate.toolkits._main.ToolkitError: Could not export model: validator error: Layer 'features' of type 320 has 1 inputs but expects at least 2.
`

**Comment by syoutsey** [comment]
Hi @mecid are you able to share the SFrame which you're trying to export?

**Comment by mecid** [comment]
@syoutsey I'm not sure that I can share the model, but here is the code which I use to train and export model.

`
import turicreate as tc

data = tc.SFrame('data.sframe')

train, test = tc.activity_classifier.util.random_split_by_session(data, session_id = 'day', fraction=0.8)
model = tc.activity_classifier.create(train, session_id='day', target='activity', prediction_window=1)

metrics = model.evaluate(test)
model.save('RawSleepClassifier.model')
model.export_coreml('RawSleepClassifier.mlmodel')
`

**Comment by TobyRoseman** [comment]
I just tried exporting an activity classifier model with 6.0 and it worked for me.

@mecid - Can you tell us a bit more about your dataset? Roughly how many row and columns? What are the types of your columns?

**Comment by mecid** [comment]
@TobyRoseman my dataset looks like this

`day,value,activity
1,7.49629198749759,1`

**Comment by TobyRoseman** [comment]
@mecid - thank you for the information. I'm now able to reproduce the issue.

This issue seems to be happening when ever there is only one feature column. Something in the Activity Classifier's `export_coreml` seems to be incorrectly assuming there will alway be more than one feature column.

The easiest way to reproduce this error is to use the [HAPT Dataset](https://apple.github.io/turicreate/docs/userguide/activity_classifier/data-preparation.html) and the following code:
```python
import turicreate as tc
data = tc.load_sframe('./hapt_data.sframe/')
data = data.remove_columns(['acc_y', 'acc_z', 'gyro_x', 'gyro_y', 'gyro_z'])
model = tc.activity_classifier.create(data, session_id='exp_id', target='activity',
                                      prediction_window=50)
model.export_coreml('MyCustomActivityClassifier.mlmodel')
```

**Comment by mecid** [comment]
@TobyRoseman awesome! Do we have any workaround?

**Comment by TobyRoseman** [comment]
@mecid - for a workaround you could add a column to your dataset which just always has the same constant for each row (i.e. `data['constantColumn'] = 1`).

I've tested doing this with the HAPT Dataset. Doing this doesn't seem to affect the test accuracy. I'd recommend you verify that's true for your dataset too.

Also you'll need to add the constant column to any prediction calls to your exported CoreML model.

**Comment by mecid** [comment]
@TobyRoseman nice, thanks!
