### ISSUE TITLE
Turicreate < 6.0 fails to download/install on Linux with pip 20

### ISSUE THREAD

**Issue by ewh** [apple/turicreate#2948]
I'm currently on Linux with pip 20.0.1 (very recently released).
```
pip download turicreate==5.8  # will fail because of 'mxnet' unmet dependency.
```
```
pip download turicreate==6.0 . # will succeed
```
With pip 19, both commands will succeed. Is turicreate < 6.0 expected to work on Linux with pip 20?

**Comment by syoutsey** [comment]
Turi Create version 5.8 and below rely on MXNet for training select toolkits. Depending on which package installer used, there were previously warnings about MXNet and dependencies. Turi Create 6.0 removes MXNet and no longer encounters these warnings or errors. We encourage all our users to switch to use Turi Create 6.0 to avoid these issues.

Regarding the specific pip 19 failures, I've seen pip 19 successfully install Turi Create with a warning about MXNet. It could be that pip 20 now regards the dependency issues as errors and fails to install.

If you need to use Turi Create 5.8 for some reason, or if 6.0 isn't meeting your needs, please reopen this issue and we can diagnose further.
