### ISSUE TITLE
Follow up with SFrame.show() and Turi Create Canvas

### ISSUE THREAD

**Issue by Varun51194** [apple/turicreate#295]
We are trying to use Turi Create for STAT/CSE 416.  We're having problems with the following:

**************
- turicreate.SFrame.show()
- turicreate.canvas.set_target('ipynb')

Currently, SFrame.show() is not implemented for linux systems.
https://apple.github.io/turicreate/docs/api/generated/turicreate.SFrame.show.html#turicreate.SFrame.show

We also need to be able to change the canvas target to be able to show these visualizations, and currently when I try running
turicreate.canvas.set_target('ipynb')

I get the error that
`AttributeError: 'module' object has no attribute 'canvas’`.

***************

Have these been implemented for Linux yet?

Cheers,
Varun

**Comment by maherkarim** [comment]
Hi,
I have the same in mac

**Comment by srikris** [comment]
Could you clarify more on what your issue us? The following function does not exist in the surface area. 
```
turicreate.canvas.set_target('ipynb')
```

.show should work flawlessly on the Mac
