### ISSUE TITLE
Unable to do prediction on OneshotDetection

### ISSUE THREAD

**Issue by zubairbaqai** [apple/turicreate#2954]
When i save the model and load it back i get 
turicreate.toolkits._main.ToolkitError: No neural network compute context provided

furthermore when i tried to print back the value before saving the model i am getting [] 

i am trying to run the example code of stop sign , still fails . hope someone can help me

**Comment by shreyajain17** [comment]
This should fix the first error you are getting. For the seance one, how many iterations are you training the model for?

**Comment by zubairbaqai** [comment]
i tried with 5000 as well . still no success

**Comment by shantanuchhabra** [comment]
Tracking the empty predictions in a separate issue (#2964) and letting this issue track the `turicreate.toolkits._main.ToolkitError: No neural network compute context provided` error.

**Comment by fareeha** [comment]
@zubairbaqai Can you tell us what platform (Linux, Mac), GPU and TuriCreate version you are using?
