### ISSUE TITLE
TUricreate 6.0 - Segmentation fault (core dumped)  - Object detection

### ISSUE THREAD

**Issue by dhgokul** [apple/turicreate#2960]
Upgrade version to 6.0 and run object detection python script, we have faced Segmentation fault issue

Log :
Downloading https://docs-assets.developer.apple.com/turicreate/models/darknet.mlmodel
Download completed: /var/tmp/model_cache/darknet.mlmodel
Segmentation fault (core dumped) 

GPU :
# nvidia-smi 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |

**Comment by TobyRoseman** [comment]
@dhgokul - can you share more details? Sounds like you're using Linux and GPUs. What version of Linux? What version of Python are you using? Are you able to share the dataset? If not, approximately how large is your dataset?

**Comment by dhgokul** [comment]
@TobyRoseman Thanks for your reply!

Python 3.5
Linux - Ubuntu 16.04.6 LTS
Image total size - 35M
Image count = 300

**Comment by TobyRoseman** [comment]
Does the segmentation fault happen all the time or is it intermittent? Are you using a fresh virtual environment just for TuriCreate, or have you installed other python packages (ex: TensorFlow) in the same python environment?

**Comment by dhgokul** [comment]
@TobyRoseman  We tried in both venv by install as new turicreate version and upgrade exiting turicreate version from 5.8 to 6.0. we got this issue

**Comment by TobyRoseman** [comment]
TuriCreate 6.0 now uses TensorFlow for deep learning. I would assume that when you install TuriCreate, TensorFlow 2.1 gets installed, but please check which version of TensorFlow gets installed. Then see if you have the [right versions of cuDNN and CUDA installed for your version of TensorFlow](https://www.tensorflow.org/install/source#gpu).

**Comment by dhivyaaxim** [comment]
@TobyRoseman Thanks! Object detection will use darknet yolo or tensorflow model in turicreate 6.0?

**Comment by TobyRoseman** [comment]
@dhivyaaxim - Internally TuriCreate's object detection toolkit uses a TensorFlow implementation of darknet-yolo.

**Comment by dhivyaaxim** [comment]
@TobyRoseman Thanks! any performance improvement in latest turicreate 6.0 object detection ?

**Comment by TobyRoseman** [comment]
> @TobyRoseman Thanks! any performance improvement in latest turicreate 6.0 object detection ?

I don't believe we saw a significant improvements (or regressions) from TuriCreate 5.8 to 6.0 for object detection.

**Comment by TobyRoseman** [comment]
This is likely the same issues as #3003.

**Comment by TobyRoseman** [comment]
We have identified an issue with the Object Detector when TensorFlow 2.1 is installed. See #3003 for details.

@dhgokul - What version of TensorFlow are you using?

**Comment by TobyRoseman** [comment]
@dhgokul - I haven't heard back from you, so I'm going to close this issue. I strongly suspect this is the same issue as #3003. Please reopen this issue if you are in fact using TensorFlow 2.0.0 or 2.0.1 in your environment.
