### ISSUE TITLE
Compilation doubt

### ISSUE THREAD

**Issue by Shekharrajak** [apple/turicreate#2968]
Hi,

I am following: https://github.com/apple/turicreate/blob/master/BUILD.md#compiling but when I run `./configure` it create only `release` folder (no debug folder) in root folder (not in src).

Please help me to test my changes locally, so that I can create PR.

Thanks,
Shekhar

**Comment by TobyRoseman** [comment]
Please share the entire output of `./configure`. First do a `./configure --cleanup`. Then run a `./configure` again and share the entire output.

Also please let us know what operating system you are using.

**Comment by Shekharrajak** [comment]
In release section I see error:


```
-- Building Curl library.
CMake Error at /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/ExternalProject.cmake:3150 (add_custom_target):
  add_custom_target cannot create target "ex_libcurl" because another target
  with the same name already exists.  The existing target is a custom target
  created in source directory
  "/Users/turicreate".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  deps/cmake/ExternalProjectLibCurl.cmake:17 (ExternalProject_Add)
  CMakeLists.txt:1147 (include)


```

And end 

```
-- Configuring incomplete, errors occurred!
```

**Comment by hoytak** [comment]
@Shekharrajak: Two things. 
1.  Update to master.  There was an issue earlier that I fixed with the build process that could have produced this.  
2.  Make sure that there are no duplicate files in deps/cmake.  CMake configurations there are automatically configured.
