### ISSUE TITLE
SFrame.apply() doesn't work for saving images

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#2987]
For any SFrame with images in it, trying to save the images using an `apply` only saves a small fraction of the images in the SFrame, not all. The expected behavior should be that all images in the SFrame get saved.

To repro, take any SFrame with >100 images in it, and run:

```python
import turicreate as tc
sf = tc.SFrame('sframe_path.sframe')
sf["image"].apply(lambda im: im.save(id(im) + '.png'))
```

**Comment by TobyRoseman** [comment]
After changing `id(im)` to `str(id(im))` , it works for me.

I'm on macOS 10.14 using Python 3.7.

@shantanuchhabra - what OS and Python version was this on? Have you tried using an absolute path (i.e. something like `"/tmp/" + str(id(im)) +".png")?

**Comment by shantanuchhabra** [comment]
That works, thanks!
