### ISSUE TITLE
Cannot infer 'feature' column for Object Detection classifier

### ISSUE THREAD

**Issue by SoCohesive** [apple/turicreate#299]
Hello!

I am having difficulty setting up the data for an Object Detection classifier. 

For now I am keeping data very simple:
 - 5 images with annotation data

The SFrame is as follows: 

+-------------------------------+------------------------+
|          annotations          |         image          |
+-------------------------------+------------------------+
| [{'label': 'image_1', 'ty... | Height: 400 Width: 600 |
| [{'label': 'image_1, 'ty... | Height: 600 Width: 450 |
| [{'label': 'image_1', 'ty... | Height: 244 Width: 236 |
| [{'label': 'image_1', 'ty... | Height: 183 Width: 275 |
| [{'label': 'image_1', 'ty... | Height: 660 Width: 940 |
+-------------------------------+------------------------+
[5 rows x 2 columns]

My annotation data is structured as follows:
annotations = tc.SArray([
 [
  {'label': 'test', 'type': 'rectangle', 'coordinates': {'height': 197, 'width': 320, 'x': 342, 'y': 254}}
 ],
 [
  {'label': 'test', 'type': 'rectangle', 'coordinates': {'height': 253, 'width': 389, 'x': 221, 'y': 356}}
 ],
 [
  {'label': 'test', 'type': 'rectangle', 'coordinates': {'height': 116, 'width': 221, 'x': 130, 'y': 186}}
 ],
 [
  {'label': 'test', 'type': 'rectangle', 'coordinates': {'height': 101, 'width': 177, 'x': 174, 'y': 107}}
 ],
 [
  {'label': 'test', 'type': 'rectangle','coordinates': {'height': 439, 'width': 725, 'x': 574, 'y': 351}}
 ]
])

My data is:
data = tc.SFrame({'image': images, 'annotations': annotations})

I am able to see the image results with correct bounding boxes in the explorer. However, the model is not created due to this error: 

 
raise ToolkitError('No "{col_name}" column specified and more than one {type_name} column in "dataset". Can not infer correct {col_name} column.'.format(col_name=col_name, type_name=type_name))
turicreate.toolkits._main.ToolkitError: No "feature" column specified and more than one image column in "dataset". Can not infer correct feature column.

**Comment by srikris** [comment]
Can you share the exact code you have written?

**Comment by SoCohesive** [comment]
Yup! I kept it very simple for now...

```python
#First include module turicreate
import turicreate as tc

#Define where the cat can be found in image
annotations = tc.SArray([
 [
  {'label': 'test', 'type': 'rectangle', 'coordinates': {'height': 197, 'width': 320, 'x': 342, 'y': 254}}
 ],
 [
  {'label': 'test', 'type': 'rectangle', 'coordinates': {'height': 253, 'width': 389, 'x': 221, 'y': 356}}
 ],
 [
  {'label': 'test', 'type': 'rectangle', 'coordinates': {'height': 116, 'width': 221, 'x': 130, 'y': 186}}
 ],
 [
  {'label': 'test', 'type': 'rectangle', 'coordinates': {'height': 101, 'width': 177, 'x': 174, 'y': 107}}
 ],
 [
  {'label': 'test', 'type': 'rectangle','coordinates': {'height': 439, 'width': 725, 'x': 574, 'y': 351}}
 ]
])
#load images
images = tc.SArray([
 tc.Image('test_1.jpg'),
 tc.Image('test_2.jpg'),
 tc.Image('test_3.jpg'),
 tc.Image('test_4.jpg'),
 tc.Image('test_5.jpg')
])

#merge images and annotations
data = tc.SFrame({'image': images, 'annotations': annotations})
print(data)

# this part work only on Mac.
data['image_with_ground_truth'] = \
    tc.object_detector.util.draw_bounding_boxes(data['image'], data['annotations'])
data.explore()

train_data, test_data = data.random_split(0.8)

# Create a model
model = tc.object_detector.create(train_data, max_iterations=1000)

# Save predictions to an SArray
predictions = model.predict(test_data)

# Evaluate the model and save the results into a dictionary
metrics = model.evaluate(test_data)

# Save the model for later use in Turi Create
model.save('TuriTestDetector.model')
# Export for use in Core ML
model.export_coreml('MLTuriTestDetector.mlmodel')
```

**Comment by srikris** [comment]
From the error message `No "feature" column specified and more than one image column in "dataset". Can not infer correct feature column.`, I can see that we were trying to infer which column in the dataset we should use as the image column. Because you have 2, one was your ground truth while the other you had drawn bounding boxes on it to annotate.

use the following to make it clear:

```
model = tc.object_detector.create(train_data, feature = 'image', max_iterations=1000)
```
Details on the API docs are here.
https://apple.github.io/turicreate/docs/api/generated/turicreate.object_detector.create.html#turicreate.object_detector.create
