### ISSUE TITLE
gcc 7 crashes

### ISSUE THREAD

**Issue by andikleen** [apple/turicreate#30]
I get a compiler segfault while building on linux with g++ 7 or 8

This patch fixes it (removing attribute flatten from the destructor)

diff --git a/src/flexible_type/flexible_type.hpp b/src/flexible_type/flexible_type.hpp
index 4bf49c15..385951fe 100644
--- a/src/flexible_type/flexible_type.hpp
+++ b/src/flexible_type/flexible_type.hpp
@@ -1526,7 +1526,7 @@ inline FLEX_ALWAYS_INLINE_FLATTEN flexible_type::flexible_type(std::initializer_
   val.vecval->second = std::move(flex_vec(list));
 }
 
-inline FLEX_ALWAYS_INLINE_FLATTEN flexible_type::~flexible_type() {
+inline flexible_type::~flexible_type() {
   reset();
 }

Submitted a gcc bug here https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83346

**Comment by afranklin** [comment]
This appears to be a gcc bug - we will explore a workaround.

**Comment by znation** [comment]
I'm unable to repro with gcc 7.3.0 (on Ubuntu 18.04 beta):
```shell
root@88a88af16ed3:/turicreate/debug/src/unity# gcc --version
gcc (Ubuntu 7.3.0-11ubuntu1) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

@andikleen Can you provide a specific gcc version that will repro with this issue? Thanks!

**Comment by andikleen** [comment]
See the first line.

I think it's because you were so glacial with the bug (several months) that the gcc people already fixed it faster (also see the link) and the fix is  already in 7.3

**Comment by znation** [comment]
Thanks @andikleen, I'll close this issue.

**Comment by andikleen** [comment]
You can't close it because gcc 7.2 will still crash without the patch
