### ISSUE TITLE
Figure out "_advanced_parameters" for drawing classifier

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#3007]
`TuriCreate.drawing_classifier.create` has special behavior if an `_advanced_parameters` parameter is used. However [the code](https://github.com/apple/turicreate/blob/7f17481969c9faea99a6c0ed4e15fff5f9ccdda4/src/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py#L172) will not work because the `params` variable it reference is not defined.

@shantanuchhabra - do you know if we want to support `_advanced_parameters` being passing in to `TuriCreate.drawing_classifier.create` or should we just get rid of it?

**Comment by shantanuchhabra** [comment]
I think we can just get rid of it.
