### ISSUE TITLE
GroupBy uses a lot of memory

### ISSUE THREAD

**Issue by mxlei01** [apple/turicreate#3009]
I have a fairly large dataset, around 300GB in total.

`stack`, `apply`,  `unpack`, works pretty fast and uses minimal memory, usually in a few minutes, however the GroupBy function would increase memory usage to last least 60GB which crashed my 64GB machine constantly.

Is there a way to reduce memory consumption by GroupBy? Or an alternative method?

Currently thinking if I can instead do a unique on the key, and do a selection based on each unique, then doing some logic to recreate groupBy with something slower but uses less memory?

**Comment by TobyRoseman** [comment]
@mxlei01 - Could you tell us a little more about your use case? Which group by operation(s) are you using?

The first thing I would try is decreasing the `TURI_SFRAME_GROUPBY_BUFFER_NUM_ROWS` runtime config values. You can see the current value with:
```python
print(tc.config.get_runtime_config()['TURI_SFRAME_GROUPBY_BUFFER_NUM_ROWS'])
```
If you want to set that value to 3 million, you can do that with:
```python
tc.config.set_runtime_config('TURI_SFRAME_GROUPBY_BUFFER_NUM_ROWS', 3000000)
```

**Comment by mxlei01** [comment]
@TobyRoseman 

There is a column in my SFrame called user_id, and there's multiple rows with the same user_id, all I want to do is groupby and then aggregate the data into a list.

Would it help if I changed `TURI_SFRAME_GROUPBY_BUFFER_NUM_ROWS ` and wrote the SFrame to a file and then read it back so that everything that was supposed to be computed gets computed?

**Comment by TobyRoseman** [comment]
Making sure that the SFrame is fully evaluated is a good idea. It's not nessecary to write and read from disk in order to do this. You can just call `sframe.materialize()`.

I recommend trying different values for `TURI_SFRAME_GROUPBY_BUFFER_NUM_ROWS` and running `sframe.materialize()` right before the problematic `groupby`. Please let us know if that works.

**Comment by mxlei01** [comment]
@TobyRoseman 

Not sure if I should open another issue, but I've added some code to basically take out data from a dictionary and append to a dictionary.

```
def get_user_id(row):
    if "user_id" in row["packed_data"]["data"]:
        return row["packed_data"]["data"]["user_id"]
    else:
        return ""

sf["user_id"] = sf.apply(lambda x: get_user_id(x))
```

And it's giving me runtime issues:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/.pyenv/versions/3.7.5/envs/375/lib/python3.7/site-packages/turicreate/data_structures/sframe.py in materialize(self)
   3928         with cython_context():
-> 3929             self.__proxy__.materialize()
   3930 

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.materialize()

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.materialize()

RuntimeError: vector

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-15-f10d57cf7ea5> in <module>
----> 1 sf_data.materialize()

~/.pyenv/versions/3.7.5/envs/375/lib/python3.7/site-packages/turicreate/data_structures/sframe.py in materialize(self)
   3927         """
   3928         with cython_context():
-> 3929             self.__proxy__.materialize()
   3930 
   3931     def is_materialized(self):

~/.pyenv/versions/3.7.5/envs/375/lib/python3.7/site-packages/turicreate/_cython/context.py in __exit__(self, exc_type, exc_value, traceback)
     48             if not self.show_cython_trace:
     49                 # To hide cython trace, we re-raise from here
---> 50                 raise exc_type(exc_value)
     51             else:
     52                 # To show the full trace, we do nothing and let exception propagate

RuntimeError: vector
```

Sounds like another memory issues?

These are the current settings:

```
import turicreate as tc

tc.config.set_runtime_config('TURI_SFRAME_GROUPBY_BUFFER_NUM_ROWS', 500000)
tc.config.set_runtime_config('TURI_SFRAME_JOIN_BUFFER_NUM_CELLS', 25242880)
tc.config.set_runtime_config('TURI_FILEIO_MAXIMUM_CACHE_CAPACITY', 1147483648)
tc.config.set_runtime_config('TURI_FILEIO_MAXIMUM_CACHE_CAPACITY_PER_FILE', 84217728)
```

**Comment by mxlei01** [comment]
@TobyRoseman 

Instead of actually doing an apply, I did an unpack instead, and it has the same affects:

```
sf["user_id"] = (
    sf["data"]
    .unpack(
        column_name_prefix="",
        limit=["user_id"]
    )["user_id"]
)
```
On the other hand, setting:

```
tc.config.set_runtime_config('TURI_SFRAME_GROUPBY_BUFFER_NUM_ROWS', 50000)
```

Still goes out of memory for GroupBy though, I have around 300GB of data.

What would be the next step?

Sort, and then Slice on the SFrames based on index, where the index and while the next index are not the same key, so that we won't be cutting two of the same key into different slices, then groupby by each slice, and then append?

Sounds like a lot of hoops to jump through though?

**Comment by TobyRoseman** [comment]
@mxlei01 - The `apply`/`unpack` issue is a separate problem. Please create a separate issue for that.

I'll try to reproduce this problem. In order to do that I'll need to know more about your dataset. I know it's approximately 300GB. How many rows? How many columns and what types? What is the column type of the `groupby` and roughly how many groups are there?

One quick thing that's probably worth trying: right before doing the `groupby`, run `sort` on that column.

**Comment by hoytak** [comment]
groupby concat is inherently really memory intensive as it essentially ends up storing the lists of values in the intermediate parts in memory.  This is especially true if there are a lot of common values.  For instance, if one value grouped on contains 50% of values in your dataset, 50% of your data gets dumped into one in-memory list.  Unfortunately, it's really hard to get around this in the general case at the lower level.

What's your use case for using concat?  There may be other ways around it. 

However, assuming concat is the easiest way, there could be a few ways around it.  One would be to do a group-by count first to see if there are any values that are heavily used, then treat those separately using a filter_by operation.

**Comment by mxlei01** [comment]
@TobyRoseman 

The data has a few columns:
date_time: str
accept_language: str
ua: str
lindo_events: List[dict]
data: dict

```
+-----------+-----------------+-----+--------------+-----------------+
| date_time | accept_language | ua  | lindo_events |      data       |
+-----------+-----------------+-----+--------------+-----------------+
| str       | str             | str | List[dict]   | dict(id="abcd") |
+-----------+-----------------+-----+--------------+-----------------+
```

Particularly data has a key called id, and one row only has 1 unique id.

So basically I'm trying to unpack the data's id into it's seperate column, and then packing all the columns except the id into one column, so it will be:

```
+-----+------------------------------+
| id  |         packed_data          |
+-----+------------------------------+
| str | dict of everything except id |
+-----+------------------------------+
```

Once I groupby user ID, I would get left with a list of dictionaries with their datetime

```
+-----+------------------------------------------------------------------+
| id  |                              concat                              |
+-----+------------------------------------------------------------------+
| str | [{dict of everything except id}, {dict of everything except id}] |
+-----+------------------------------------------------------------------+
```

@hoytak 

I haven't counted exactly, but I think there's less than a hundred dictionaries per id. I'm trying to group them into a list of lists, where each event in the session is less than a duration of time, for example an hour.

```
+-----+--------------------------------------------------------------------------------------------------------------------------------------+
| id  |                                                               sessions                                                               |
+-----+--------------------------------------------------------------------------------------------------------------------------------------+
| str | [[{dict of everything except id}, {dict of everything except id}], [{dict of everything except id}, {dict of everything except id}]] |
+-----+--------------------------------------------------------------------------------------------------------------------------------------+
```

Essentially trying to recreate Beam's session windows: [https://beam.apache.org/documentation/programming-guide/#provided-windowing-functions](Beam Session Window Documentation)

**Comment by mxlei01** [comment]
As a workaround
```
sf = sf.groupby("user_id", operations=...)
```

Was turned into:
```
from more_itertools.more import ichunked

sf_portions = []
for user_id in ichunked(sf["user_id"].unique(), 1000000):
    sf_portion = (
        sf
        .filter_by(values=[i for i in user_id], column_name="user_id")
        .groupby("user_id", operations=...)
    )
sf = sf_portions[0]
for sf_portion in sf_portions:
    sf = sf.append(sf_portion)
```

I think it should work for now, I may just have to monkey patch groupby with this function so that it's going to work on all the groupby I have later.

Going to close the issue since there's workaround.
