### ISSUE TITLE
`SArray.filter_by` should support a lambda function

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#3015]
Currently, `SArray.filter_by` has the following signature:

```
Parameters
----------
values : SArray | list | numpy.ndarray | pandas.Series | str
The values to use to filter the SArray. The resulting SArray will
only include rows that have one of these values in the given
column.

exclude : bool
If True, the result SArray will contain all rows EXCEPT those that
have one of the ``values``.

Returns
-------
out : SArray
The filtered SArray.
```

It would be nice for the supported values to also include a lambda function to replicate the Python `filter` behavior.

**Comment by TobyRoseman** [comment]
I'm not convinced it makes sense to make this change. It's basically just adding a second way of the doing what `filter` already does. That seems to go against the Python ethos of "There should be one-- and preferably only one --obvious way to do it.". 

@shantanuchhabra - what do you think?

**Comment by shantanuchhabra** [comment]
I didn't know SArray had a [`filter` method](https://apple.github.io/turicreate/docs/api/generated/turicreate.SArray.filter.html#turicreate-sarray-filter). Closing this issue since the `filter` method already addresses this.
