### ISSUE TITLE
Getting support vectors of SVM Classifier

### ISSUE THREAD

**Issue by navanchauhan** [apple/turicreate#3035]
Is there any chance we can extract the actual support vectors from a trained model?

**Comment by TobyRoseman** [comment]
You should be able to get that from the `coefficients` member.  Here is a quick example on toy data:

```python
import turicreate as tc

toy_data = tc.SFrame({
    'x': [-5,-5,10,10], 
    'y': [-5,-5,10,10],
    'label': ['a','a','b','b']})

model = tc.svm_classifier.create(toy_data, target='label')

my_coefficients = model.coefficients
print(my_coefficients)
```

I'm going to close this issue, but let me know if you further questions.

**Comment by navanchauhan** [comment]
Can I manually run a SVM classification task with these coefficients?

For e.g

I have two categories `a` and `b`, training will give me two coefficients and one intercept

Is it possible to manually classify a single value of `a` and `b` with the coefficient and intercept?

**Comment by TobyRoseman** [comment]
@navanchauhan - you should be able to manually classify a single example.

SVM classifiers work by calculating a "margin" value, which is the distance of the example from the hyperplane.

Take a look at [the SVM page of our User Guide](https://apple.github.io/turicreate/docs/userguide/supervised-learning/svm.html) for more information here. Also you can get the margin value from an `svm_classifer` by passing `output_type="margin"` to the `predict` function - see the [API documentation](https://apple.github.io/turicreate/docs/api/generated/turicreate.svm_classifier.SVMClassifier.predict.html#turicreate.svm_classifier.SVMClassifier.predict).

If this margin value is greater than or equal to zero, one class is predicted, else the other class is predicted.

If both `a` and `b` are numerical values, it's easy to calculate the margin. Simply multiple the value of `a` and `b` with their corresponding coefficient, then add the intercept. [Here](https://github.com/apple/turicreate/blob/8700c39388c4784a79ac8a4f763ac1346ad9cf83/src/toolkits/supervised_learning/linear_svm.cpp#L260) is our code for doing this.

Let me know if you have any more questions.

**Comment by navanchauhan** [comment]
@TobyRoseman 

ahh, this gave me an idea. In reference to #2880 something like 

https://github.com/eloquentarduino/micromlgen

or

https://github.com/emlearn/emlearn


A simple port function can be created to output these numeric classifiers as C code, if you guys have your hands full with your work I can start working on this as a separate library
