### ISSUE TITLE
Style Transfer Does Not Work

### ISSUE THREAD

**Issue by azamsharp** [apple/turicreate#3036]
The code included: https://apple.github.io/turicreate/docs/userguide/style_transfer/ does not at all. It throws the following exception. 

failed assertion `MTLTextureDescriptor has height (65536) greater than the maximum allowed size of 16384.'

Even though the image size for test, content and style images are 256 X 256.

**Comment by TobyRoseman** [comment]
@azamsharp - what operating system are you using?

**Comment by azamsharp** [comment]
macOS Catalina

**Comment by TobyRoseman** [comment]
@azamsharp - I just ran the style transfer code from the user guide on macOS Catalina. It works fine  for me. Could you please provide the full output/stack-trace? Also it would be helpful to know some details about your dataset.
