### ISSUE TITLE
turicreate

### ISSUE THREAD

**Issue by srivatsan18** [apple/turicreate#3038]
Unable to install Turicreate

**Comment by TobyRoseman** [comment]
@srivatsan18 - Please give us some more information. 

1 - What version of Python are you using?
2 - What operating system are you using?
3 - Are you trying to install by running `pip install turicreate`? Or are you doing something else?
4 - Are you getting any error messages?

**Comment by srivatsan18** [comment]
i am currently using python 3.7
windows 10 home
i tried pip install turicreate in my anaconda prompt
error message stating failed to build turicreate   Turicreate error

**Comment by PeterNoob** [comment]
same problem
tried 3.6 3.7 virtual environment
I am thinking   turicreate stop support anaconda  on windows  anymore

**Comment by TobyRoseman** [comment]
TuriCreate does not natively support Windows. However you can run TuriCreate on Windows 10 using WSL.

The error message you received should have made it clear that we don't support Windows. Let me know if that isn't the case or if you have ideas about how to make it more clear.

We are already tracking the issue of native Windows support in #533. 

I'm going to close this issue as a duplicate but let me know if you have any more questions.
