### ISSUE TITLE
SFrame is not working within  turicreate

### ISSUE THREAD

**Issue by AkramKamel** [apple/turicreate#3053]
I'm using turicreate in the course "" in coursera , after importing turicreate without problems
 whenever I try to use the the SFrame to open any file it gives error as follow :

sf = turicreate.sframe('people-example.csv')

AttributeError                            Traceback (most recent call last)
<ipython-input-13-be06bc4b9ba4> in <module>
----> 1 sf = turicreate.sframe('people-example.csv')

AttributeError: module 'turicreate' has no attribute 'sframe'

please help

**Comment by TobyRoseman** [comment]
You want `turicreate.SFrame` not `turicreate.sframe`. The "S" and "F" in SFrame are capitalized.

**Comment by AkramKamel** [comment]
I'm sorry but the same error appears when using the S F capitalized

sf = turicreate.SFrame('people-example.csv')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-bcf297396ba4> in <module>
----> 1 sf = turicreate.SFrame('people-example.csv')

AttributeError: module 'turicreate' has no attribute 'SFrame'

**Comment by TobyRoseman** [comment]
Do you get an error when you import turicreate?

How are you importing turicreate?

If you're doing:
`import turicreate as tc`
then you need to do:
`sf = tc.SFrame('people-example.csv')`

If you want to do:
`sf = turicreate.SFrame('people-example.csv')`
then you need to just do:
`import turicreate`

**Comment by AkramKamel** [comment]
Thanks for the quick respond 
I import turicreate first by using 

import turicreate

it is imported with no errors 

then when I try to use the sframe it gives the error mentioned before

sf = turicreate.SFrame('people-example.csv')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-bcf297396ba4> in <module>
----> 1 sf = turicreate.SFrame('people-example.csv')

AttributeError: module 'turicreate' has no attribute 'SFrame'

**Comment by TobyRoseman** [comment]
Something seems wrong with your install of Turicreate. How did you install TuriCreate? Did you get any errors when installing TuriCreate?

What is the output of the code below?
```python
import turicreate
print(dir(turicreate))
```

**Comment by AkramKamel** [comment]
actually i install it by download it and unzipped it in the jupyter directory then i started to import it as mentioned 

the output is 
import turicreate
print(dir(turicreate))

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

**Comment by TobyRoseman** [comment]
Ok, yes something is wrong with your install. Just downloading and unzipping will not correctly install it.

Please uninstall turicreate from your environment and then reinstall it [following our installation instructions](https://github.com/apple/turicreate#installation).

You want to run:
```bash
pip uninstall -y turicreate
pip install turicreate
```

From inside of your notebook, you can just run
```bash
! pip uninstall -y turicreate
! pip install turicreate
```

**Comment by AkramKamel** [comment]
I unistalled the turicreate and when used the command to install it it gave me this results 

! pip install turicreate

Collecting turicreate
  Using cached turicreate-6.0.tar.gz (1.9 kB)
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py): started
  Building wheel for turicreate (setup.py): finished with status 'error'
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate: started
    Running setup.py install for turicreate: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\akm\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\AKM\\AppData\\Local\\Temp\\pip-install-du37bijz\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\AKM\\AppData\\Local\\Temp\\pip-install-du37bijz\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\AKM\AppData\Local\Temp\pip-wheel-2hnad33h'
       cwd: C:\Users\AKM\AppData\Local\Temp\pip-install-du37bijz\turicreate\
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build\bdist.win32\wheel
  running install
  
  
  
          ==================================================================================
          TURICREATE ERROR
  
          If you see this message, pip install did not find an available binary package
          for your system.
  
          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).
  
          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7
  
  
          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`

Important note :
I used jupyter notebook under Anaconda 
I've Win 10   32- bit operating system under x64 based processor

**Comment by TobyRoseman** [comment]
As [mentioned in our top level readme](https://github.com/apple/turicreate#supported-platforms), we don't natively support Windows. With Windows 10 you can use TuriCreate via WSL.

We're tracking the issue of native Windows support in #533

**Comment by MaheshMaheshMahesh** [comment]
I also have the same problem. Although I have installed the turicreate via WSL on windows 10. But the problem is same.
