### ISSUE TITLE
Convert Core ML Model to Tensorflow Lite

### ISSUE THREAD

**Issue by aof-github** [apple/turicreate#3057]
Hello,

I need convert a trained model (activity classification) of Core ML to Tensorflow Lite. With other methods like onnxmltools or mmdnn it doesn't work.

Is it possible to do it with this solution? Or is any plan to do it? 

Thanks in advance

**Comment by TobyRoseman** [comment]
We do not have this functionality. That being said, the [Activity Classifier does now have a TensorFlow implementation](https://github.com/apple/turicreate/blob/master/src/python/turicreate/toolkits/activity_classifier/_tf_model_architecture.py). Getting a trained TensorFlow models from your TuriCreate model may not be too much work now. 

We're already tracking this issue in #2930. So I'm going to close this issue, but let me know if you have any questions.
