### ISSUE TITLE
Activity Classification Section is Incomplete and Out of Date

### ISSUE THREAD

**Issue by azamsharp** [apple/turicreate#3058]
The Activity Classification section is incomplete and out of date. When downloading the HAPT dataset, it does not contain anything called labels.txt. Also, there are no column names X1, X2 etc. 

The "hapt_data.sframe" file is also missing and nowhere to be found. Please provide working code and examples for the book. Most of the examples in the book are not working at all.

**Comment by TobyRoseman** [comment]
I just ran all of the code from our [HAPT Data Preparation page](https://apple.github.io/turicreate/docs/userguide/activity_classifier/data-preparation.html) with a fresh download of [the data](http://archive.ics.uci.edu/ml/machine-learning-databases/00341/HAPT%20Data%20Set.zip). Everything works fine for me. 

I suspect what's happing here is that you need to change the value of the `data_dir` variable on the second line of code. If you just unzip the zip file it will put everything in the current directory. As the document states:
`The code below assumes the data was unzipped into a directory named HAPT Data Set`.

The `labels.txt` file is located under the `RawData` subfolder. Also `X1`, `X2`, etc is what columns get named when they don't have a names (i.e. in this case when the CSV files don't have a header line).

@azamsharp - I'll leave this issue open. Let me know if changing the `data_dir` variable works for you. Also let me know if you have any questions, or ideas about how to make things clearer. What other examples in the user guide are you having issues with?

**Comment by azamsharp** [comment]
Thanks! Do you have an example of sample iOS app which will use that model

**Comment by TobyRoseman** [comment]
Let's track the sample iOS app request in #3059.

**Comment by TobyRoseman** [comment]
@azamsharp - I'm going to close this issue. If there are problems with other parts of the User Guide, please open new issues.
