### ISSUE TITLE
Can I save turicreate model with joblib? 

### ISSUE THREAD

**Issue by eveTu** [apple/turicreate#3064]
Hey, 
I am a beginner with turicreate library and I am not much sure about the saving model options. 
The only way to save a model is with model.save? 
Can I save a turicreate model (especially recommendation models) with joblib library? 

The goal is to deploy the recommendation models with AWS SageMaker.

**Comment by TobyRoseman** [comment]
`model.save` is the only way to save a model. You can also use `model.export_coreml` to export the model to Core ML format.

I'm not really familiar with either Joblib or AWS SageMaker. Are you just trying to use Joblib to get caching?

The following seems to work for me using a recommender model. Although I'm not sure the cache is actually being used; it seems to be calling the model each time:
```python
from joblib import Memory
import turicreate as tc

cachedir = '/tmp/cache'
mem = Memory(cachedir)
cache = mem.cache(model.recommend)

r = cache(users)
r = cache(users)   # this still seems to be calling the model
```
