### ISSUE TITLE
low hardisk high memory case

### ISSUE THREAD

**Issue by getsanjeevdubey** [apple/turicreate#3076]
@TobyRoseman  I am new to sframes. Could you please help me with a couple of doubts:
1. How does sframes manage between residing on RAM vs Disk?
2. I have an instance with 64 GB RAM but just 10GB disk space. On a group by operation I get an error OSError: Fail to write. Disk may be full.
Does this mean data is that large, that it has exploded both RAM and disk, if not how can I force sframes to first use RAM as much as possible, then reside on disk.

**Comment by TobyRoseman** [comment]
@getsanjeevdubey - I think @hoytak will be able to answer your specific questions much better than I can. 

In general SFrames are "disk backed", meaning we assume we can write the SFrame to disk. I don't believe there is any way to change that.

**Comment by hoytak** [comment]
They are disk backed, but you can force them to be mostly in-memory by increasing these environment variables (or using tc.config.set_runtime_config): TURI_FILEIO_MAXIMUM_CACHE_CAPACITY and TURI_FILEIO_MAXIMUM_CACHE_CAPACITY_PER_FILE to be 64GB (parameter in bytes).  They are by default 4GB.

**Comment by getsanjeevdubey** [comment]
@hoytak @TobyRoseman Thanks for your response.
