### ISSUE TITLE
Unsupported engine type

### ISSUE THREAD

**Issue by ozgurshn** [apple/turicreate#3078]
Hello, running an activity classifier model on Apple Watch series 2 with OS 5.3.5 gives me an error. Model has been trained on Create ML. Can I find a solution by training this model with TuriCreate?
 WatchKit Extension[587:818956] [espresso] [Espresso::handle_ex_] exception=Unsupported engine type

**Comment by TobyRoseman** [comment]
Without trying it, there is no way to know for sure. However the implementation of the activity classifier is pretty similar between Create ML and TuriCreate. So it's likely you'll hit the same issue.

I think it's worth trying TuriCreate. [Training an activity classifier with TuriCreate should be easy](https://apple.github.io/turicreate/docs/userguide/activity_classifier/). If you do run into an issue with TuriCreate, I'll try to help you here. 

I'd also encourage you to [report the issue you're having with Create ML](https://developer.apple.com/bug-reporting/).

**Comment by ozgurshn** [comment]
I can not replicate this issue with Xcode 13.4. It's occurred in Xcode 13.3.1 when I run the prediction in do try catch block. I submitted the report to Apple. Now my model works, I close this issue. Thanks
