### ISSUE TITLE
SFrame visualization problem

### ISSUE THREAD

**Issue by AkramKamel** [apple/turicreate#3081]
Dear all

I'm having a problem using the code :
Input
sf.show (view = "scatter plot" , x = "sqft_living" , y ="price")
output
TypeError                                 Traceback (most recent call last)
<ipython-input-9-8197449504c8> in <module>
----> 1 sf.show (view = "scatter plot" , x = "sqft_living" , y ="price")

TypeError: show() got an unexpected keyword argument 'view'

note that I imported turicreat and SFrame :
import turicreate as tc
sf = tc.SFrame('home_data.sframe')

I was able to explore the data normally but when trying to visualize it the problem happened

I also tried the code : 
hp.show(view ="Bar Chart", x="sqft_Living", y="price")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-d6f7dbe27c23> in <module>
----> 1 sf.show(view ="Bar Chart", x="sqft_Living", y="price")

TypeError: show() got an unexpected keyword argument 'view'

**Comment by TobyRoseman** [comment]
It doesn't look like [SFrame.show](https://apple.github.io/turicreate/docs/api/generated/turicreate.SFrame.show.html#turicreate.SFrame.show) takes any parameters. I think you probably want [turicreate.visualization.scatter](https://apple.github.io/turicreate/docs/api/generated/turicreate.visualization.scatter.html#turicreate.visualization.scatter).

Try: `turicreate.visualization.scatter(sf["sqft_living"], sf["price"])`.

**Comment by TobyRoseman** [comment]
@AkramKamel - I'm going to close this issue. Feel free to reopen if my solution didn't work for you.
