### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by ChrisLane** [apple/turicreate#3099]
_Issue details copied/modified from #788_

As of October 14th, 2019 Python 3.8 has been officially released. We should support it.

At an absolute minimum these things will need to be done:
- [ ] Ensure everything builds with 3.8 and that the built package can be imported.
- [ ] All unit test pass on both macOS and Linux.
- [ ] Upload 3.8 wheel to PyPI on next release.

**Comment by TobyRoseman** [comment]
Before we can support Python 3.8 all of our Python dependencies must support it. Looks like there are still two dependencies that don't support Python 3.8.

Adding a few more progress check boxes:
- [ ] [TensorFlow supports Python 3.8](https://github.com/tensorflow/tensorflow/issues/33374)
- [ ] [CoreMLTools supports Python 3.8](https://github.com/apple/coremltools/issues/684)
- [ ] Update [the versions of our dependencies](https://github.com/apple/turicreate/blob/6fa89a994c471194b5f09ae80fd1d5a951f52638/src/python/setup.py#L128)

**Comment by igi-chris** [comment]
This put me off using this library. I had an issue with Pandas running out of memory for large data frames so wanted to try the `sframe` from this library, but don't really want to install an old Python version just to try this out.

**Comment by laksh225** [comment]
CoreMLTools does support Python 3.8. I installed coremltools using pip install coremltools and imported it.

![Screenshot from 2020-05-19 18-56-54](https://user-images.githubusercontent.com/56289983/82332441-03f21e80-9a03-11ea-886e-c09c49020c69.png)

OUTPUT : (venv) laksh@L-ubuntu18:~$ python
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import coremltools
>>>

**Comment by TobyRoseman** [comment]
Supporting Python 3.8 on Linux is blocked by #3003. In order to support Python 3.8 we need to upgrade our TensorFlow dependency and not have things segfault.

**Comment by TobyRoseman** [comment]
TuriCreate 6.4 has been released with Python 3.8 support.

**Comment by ankur290109** [comment]
Getting below error while installing Turicreate, I have installed Python 3.8 and Anaconda 3:-

ERROR: Failed building wheel for turicreate
Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
Running setup.py install for turicreate ... error
ERROR: Command errored out with exit status 1:
command: 'C:\Users\Abhishek\anaconda3\envs\virtual_environment_name\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Abhishek\AppData\Local\Temp\pip-install-qhqi5iee\turicreate\setup.py'"'"'; file='"'"'C:\Users\Abhishek\AppData\Local\Temp\pip-install-qhqi5iee\turicreate\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\Abhishek\AppData\Local\Temp\pip-record-92_w9hxx\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Abhishek\anaconda3\envs\virtual_environment_name\Include\turicreate'
cwd: C:\Users\Abhishek\AppData\Local\Temp\pip-install-qhqi5iee\turicreate
Complete output (28 lines):
running install

        ==================================================================================
        TURICREATE ERROR

        If you see this message, pip install did not find an available binary package
        for your system.

        Supported Platforms:
            * macOS 10.12+ x86_64.
            * Linux x86_64 (including WSL on Windows 10).

        Support Python Versions:
            * 2.7
            * 3.5
            * 3.6
            * 3.7
            * 3.8

        Another possible cause of this error is an outdated pip version. Try:
            `pip install -U pip`

        ==================================================================================



----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Abhishek\anaconda3\envs\virtual_environment_name\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Abhishek\AppData\Local\Temp\pip-install-qhqi5iee\turicreate\setup.py'"'"'; file='"'"'C:\Users\Abhishek\AppData\Local\Temp\pip-install-qhqi5iee\turicreate\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\Abhishek\AppData\Local\Temp\pip-record-92_w9hxx\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Abhishek\anaconda3\envs\virtual_environment_name\Include\turicreate' Check the logs for full command output.

**Comment by syedmeesamali** [comment]
Sad to see no follow-up or updates after this?

**Comment by ra-esmith** [comment]
I am also crashing 
  '"'"''"'"''"'"' % ('"'"'/private/var/folders/8v/j5fgb3w544716cd7dht792480000gn/T/pip-install-tpux1xna/turicreate_ec9e2137ae384b658bb6ff108c3b94d9/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d /private/var/folders/8v/j5fgb3w544716cd7dht792480000gn/T/pip-wheel-dtzt07tk
  cwd: /private/var/folders/8v/j5fgb3w544716cd7dht792480000gn/T/pip-install-tpux1xna/turicreate_ec9e2137ae384b658bb6ff108c3b94d9/
  Building wheel for turicreate (setup.py) ... error
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
  Running command python setup.py clean
  running clean
  'build/lib' does not exist -- can't clean it
  'build/bdist.macosx-11-universal2' does not exist -- can't clean it
  'build/scripts-3.8' does not exist -- can't clean it
Failed to build turicreate
ERROR: Could not build wheels for turicreate, which is required to install pyproject.toml-based projects
evan@Poseidon test %
