### ISSUE TITLE
gcc 7 build failure

### ISSUE THREAD

**Issue by andikleen** [apple/turicreate#31]
/src2/src2/turicreate/src/unity/toolkits/coreml_export/MLModel/src/NeuralNetworkValidator.cpp: At global scope:
/src2/src2/turicreate/src/unity/toolkits/coreml_export/MLModel/src/NeuralNetworkValidator.cpp:738:18: error: ‘function’ in namespace ‘std’ does not name a template type
     typedef std::function<Result(const CoreML::Specification::NeuralNetworkLayer& specLayer)> validateSpecLayerFn;

plus lots of follow on errors

**Comment by andikleen** [comment]
diff --git a/src/unity/toolkits/coreml_export/MLModel/src/NeuralNetworkValidator.cpp b/src/unity/toolkits/coreml_export/MLModel/src/NeuralNetworkValidator.cpp
index cc34b407..1228519f 100644
--- a/src/unity/toolkits/coreml_export/MLModel/src/NeuralNetworkValidator.cpp
+++ b/src/unity/toolkits/coreml_export/MLModel/src/NeuralNetworkValidator.cpp
@@ -12,6 +12,7 @@
 #include <algorithm>
 #include <sstream>
 #include <type_traits>
+#include <functional>
 
 namespace CoreML {
 

fixes the build

**Comment by andikleen** [comment]
#include <functional>

that's the missing line

**Comment by gustavla** [comment]
Thanks so much @andikleen for pointing this out and suggesting a solution! This seems to have been addressed exactly as you proposed by #108.
