### ISSUE TITLE
Saving to S3 assume key prefix already exists

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#3108]
If I try to save an SFrame doing this `sf.save('s3://my-bucket/myFolder/mySFrameName')`, that will only work if the key prefix "myFolder/mySFrameName" already exists in my bucket. 

The best behavior here isn't clear to me, but certainly the current behavior is not right. If only `s3://my-bucket/myFolder/` exists than it should still have the SFrame.

I think we may want to be even more accepting, but I'm not sure. I think if the `myFolder` key prefix doesn't even exist, we should still save it to 's3://my-bucket/myFolder/mySFrameName'. Do other people have thoughts here?

**Comment by TobyRoseman** [comment]
@guihao-liang - was this fixed by #3105?

**Comment by guihao-liang** [comment]
Yeas, for your case here, `myFolder` must exist.
