### ISSUE TITLE
ImportError: cannot import name libinfo  - How can I fix this

### ISSUE THREAD

**Issue by johnyquest7** [apple/turicreate#311]
ImportErrorTraceback (most recent call last)
<ipython-input-23-5c80cf7862a7> in <module>()
      1 model = tc.image_classifier.create(
----> 2                train_data, target='label')

/usr/local/lib/python2.7/dist-packages/turicreate/toolkits/image_classifier/image_classifier.pyc in create(dataset, target, feature, model, max_iterations, verbose, seed)
    114 
    115     # Load pre-trained model & feature extractor
--> 116     ptModel = _pre_trained_models.MODELS[model]()
    117     feature_extractor = _image_feature_extractor.MXFeatureExtractor(ptModel)
    118 

/usr/local/lib/python2.7/dist-packages/turicreate/toolkits/_pre_trained_models.pyc in __init__(self)
     97             (self.params_url, self.params_md5),
     98         ], path)
---> 99         import mxnet as _mx
    100         self.mxmodel = _mx.model.load_checkpoint(_os.path.join(path, self.name), epoch)
    101 

/usr/local/lib/python2.7/dist-packages/mxnet/__init__.py in <module>()
     23 
     24 from .context import Context, current_context, cpu, gpu
---> 25 from . import engine
     26 from .base import MXNetError
     27 from . import base

/usr/local/lib/python2.7/dist-packages/mxnet/engine.py in <module>()
     21 
     22 import ctypes
---> 23 from .base import _LIB, check_call
     24 
     25 

/usr/local/lib/python2.7/dist-packages/mxnet/base.py in <module>()
     28 import inspect
     29 import numpy as np
---> 30 from . import libinfo
     31 warnings.filterwarnings('default', category=DeprecationWarning)
     32 

ImportError: cannot import name libinfo

**Comment by gustavla** [comment]
Hi @johnyquest7, sorry you are having problems creating a classifier! Let's first see if this is an issue with one of our dependencies (MXNet). Could you try running this:
```python
import mxnet
```
Do you get the same error? In that case, we can try to re-install MXNet:
```
pip uninstall mxnet
pip install mxnet==0.12.1
```
Did it help? Let's start with that and take it from there.

**Comment by johnyquest7** [comment]
Thanks @gustavla 
Following worked 
pip uninstall -y mxnet && pip install mxnet-cu80==0.12.1

**Comment by johnyquest7** [comment]
When i tried to run the code again, same error popped up. Previous fix did not work.

ImportErrorTraceback (most recent call last)
<ipython-input-49-265f02e9c062> in <module>()
----> 1 import mxnet as mx

/usr/local/lib/python2.7/dist-packages/mxnet/__init__.py in <module>()
     23 
     24 from .context import Context, current_context, cpu, gpu
---> 25 from . import engine
     26 from .base import MXNetError
     27 from . import base

/usr/local/lib/python2.7/dist-packages/mxnet/engine.py in <module>()
     21 
     22 import ctypes
---> 23 from .base import _LIB, check_call
     24 
     25 

/usr/local/lib/python2.7/dist-packages/mxnet/base.py in <module>()
     28 import inspect
     29 import numpy as np
---> 30 from . import libinfo
     31 warnings.filterwarnings('default', category=DeprecationWarning)
     32 

ImportError: cannot import name libinfo

**Comment by johnyquest7** [comment]
When I tried import mxnet following error appeared

**Comment by gustavla** [comment]
Any luck trying newer mxnet versions? For instance `pip install mxnet==1.1.0`?

**Comment by johnyquest7** [comment]
I was pulling my hair out.
You are a life saver. That solved the issue!

**Comment by gustavla** [comment]
Great to hear, @johnyquest7! On that note we plan to extend official support in 4.2 to MXNet 1.1.0. Right now in 4.1.1 you get a warning about it, but so far we have not seen any issues.

**Comment by johnallen24** [comment]
I am getting the same error. I tried uninstalling and reinstalling MXNet including version 1.1.0 (https://github.com/apple/turicreate/issues/311) but the same error appears. 

This is what is shown to me: 
Traceback (most recent call last):
  File "create2.py", line 12, in <module>
    model = tc.object_detector.create(train_data, feature='image', annotations='annotations')
  File "/home/sankhe.ku/anaconda2/envs/venv/lib/python2.7/site-packages/turicreate/toolkits/object_detector/object_detector.py", line 145, in create
    from ._mx_detector import YOLOLoss as _YOLOLoss
  File "/home/sankhe.ku/anaconda2/envs/venv/lib/python2.7/site-packages/turicreate/toolkits/object_detector/_mx_detector.py", line 9, in <module>
    import mxnet as _mx
  File "/home/sankhe.ku/anaconda2/envs/venv/lib/python2.7/site-packages/mxnet/__init__.py", line 25, in <module>
    from . import engine
  File "/home/sankhe.ku/anaconda2/envs/venv/lib/python2.7/site-packages/mxnet/engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "/home/sankhe.ku/anaconda2/envs/venv/lib/python2.7/site-packages/mxnet/base.py", line 30, in <module>
    from . import libinfo
ImportError: cannot import name libinfo

**Comment by gustavla** [comment]
@johnallen24 Sorry to hear this! Let's try to figure it out. First, can you confirm that this happens when you do `import mxnet`?

Let's make sure MXNet is first completely uninstalled:

1. Run `pip uninstall mxnet` and if you have installed any of the CUDA mxnet's, uninstall those too (e.g. `pip uninstall mxnet-cu80`. You can see all installed mxnet's using  `pip freeze | grep mxnet`.
2. Run `import mxnet`. Make sure it fails to import, so there is no lingering mxnet installation.
3. Run `pip install mxnet==1.1.0` again.

Do you still get libinfo? If that's the case, we probably want to re-file this on the MXNet side, since they'll be more equipped to address it.

**Comment by ZucchiniTang** [comment]
@johnallen24 I came across this problem and fixed that just now. I installed CUDA again and checked the mxnet's version(should be same with CUDA if you are using GPU). I follow [this](https://stackoverflow.com/questions/50560395/how-to-install-cuda-in-google-colab-gpus) to install, hope it can help you.

**Comment by kld123509945** [comment]
gustavla provide the right solution. While I have to say that if everyone suffers this problem when they install and use turicreate as a 'turicreate rookie' (just like myself), the turicreate is still not simple as it claimed, and the problem should be updated as it is now 2019...
