### ISSUE TITLE
Will Radeon 5700 XT as eGPU be utilized for object detection on macOS?

### ISSUE THREAD

**Issue by justvil** [apple/turicreate#3118]
Hi,

I've been doing object detection training using the internal Vega 20 on my MBP, but it's starting to take a long time and I don't feel comfortable running the laptop for 12h at 100°C every few days.

I was thinking of buying the 5700 XT in an eGPU form and connecting it to the MBP, but did not find any information whether it is officially supported on turicreate object detection.

Thanks!

**Comment by nickjong** [comment]
Yes, the Radeon 5700 XT is expected to work with Object Detection! Let us know if you have any issues with it
