### ISSUE TITLE
tc.version_info.git_sha is empty

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#3130]
This value was set in the 6.0 release. It's missing in the 6.1 and 6.2 releases.

**Comment by pradeek232662** [comment]
HI @TobyRoseman  I would like to solve the issue. Can you assign it to me.

**Comment by TobyRoseman** [comment]
Thanks @pradeek232662. I have assigned the issue to you.

I just noticed that `tc.version_info.build_number` is also not getting set.

[Here is where the git_sha should be getting set](https://github.com/apple/turicreate/blob/ea8873d6fa597d4a9f9a26db3c8e4540eba7efbd/scripts/make_wheel.sh#L360). A [couple of lines above that](https://github.com/apple/turicreate/blob/ea8873d6fa597d4a9f9a26db3c8e4540eba7efbd/scripts/make_wheel.sh#L354) is where the build number should be getting set. 

I strongly suspect both problems where introduced when we moved to [black](https://github.com/psf/black) style formatting. I think the fix here will be very similar to #3077.
