### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by anoop447** [apple/turicreate#3134]
turicreate is not supporting python 3.8.
we cannot install turicreate as it tells it is not finding an available binary package in our system.
it is only supporting upto 3.7.
we need the update soon.

**Comment by TobyRoseman** [comment]
We are already tracking this issue in #3099.

**Comment by AmanLonare** [comment]
![image](https://user-images.githubusercontent.com/25256179/95740405-0d2da180-0caa-11eb-8054-98f74755ba65.png)


I am still getting the same error even though it is showing that turicreate is available for 3.8. How to resolve this issue?

**Comment by TobyRoseman** [comment]
@AmanLonare - It looks like your operating system is Windows. TuriCreate does not have native Windows support. You need to use WSL (preferably Ubuntu 18) in order to use TuriCreate on Windows. We're tracking native Windows support in #533.
