### ISSUE TITLE
The calculation task is too large for the local machine to complete

### ISSUE THREAD

**Issue by zhudouxiaolee** [apple/turicreate#3135]
How to submit the calculation task to the cluster machine instead of using the local machine resources to run the graph calculation

**Comment by zhudouxiaolee** [comment]
I have a problem. How can the graphlab program run tasks on the spark cluster! thanks.

**Comment by TobyRoseman** [comment]
This repository is for Turi Create, not GraphLab.

We are already tracking support for distributed execution in #1043.

**Comment by zhudouxiaolee** [comment]
> This repository is for Turi Create, not GraphLab.
> 
> We are already tracking support for distributed execution in #1043.

thanks, Got it. At present, turicreate doesn't support distributed, right?

**Comment by TobyRoseman** [comment]
@zhudouxiaolee - that's correct. At present, TuriCreate does not have built in distributed support.
