### ISSUE TITLE
Error installing turicreate in wsl 

### ISSUE THREAD

**Issue by ashleelsamrat** [apple/turicreate#3147]
pip3 install -U turicreate
Collecting turicreate
  Using cached turicreate-6.0.tar.gz (1.9 kB)
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uhaa883s/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uhaa883s/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-86gbwz9b
       cwd: /tmp/pip-install-uhaa883s/turicreate/
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build/bdist.linux-x86_64/wheel
  running install

          ==================================================================================
          TURICREATE ERROR

          If you see this message, pip install did not find an available binary package
          for your system.

          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).

          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7

          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`

          ==================================================================================

  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uhaa883s/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uhaa883s/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3vjz28yd/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/devdarmok/.local/include/python3.8/turicreate
         cwd: /tmp/pip-install-uhaa883s/turicreate/
    Complete output (28 lines):
    running install

            ==================================================================================
            TURICREATE ERROR

            If you see this message, pip install did not find an available binary package
            for your system.

            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).

            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7

            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`

            ==================================================================================

    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uhaa883s/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uhaa883s/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3vjz28yd/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/devdarmok/.local/include/python3.8/turicreate Check the logs for full command output.

I have installed python 3.6 and upgraded pip to latest version still getting same error.

**Comment by TobyRoseman** [comment]
At least with the output you shared, you are using Python 3.8 not Python 3.6:
`--install-headers /home/devdarmok/.local/include/python3.8/turicreate`

We don't support Python 3.8 yet. We're tracking that issue in #3099. 

You also tried it with Python 3.6? If so, please post the full output from that installation attempt. I suspect what's happening is it's still using python 3.8, not python 3.6.

**Comment by Akumar132232** [comment]
I have downgraded the python version for my new environment but then also I am getting the same error.

**Comment by TobyRoseman** [comment]
@Akumar132232 - please post the full output you get when you trying to install with Python 3.6. As I said before I suspect it's still using Python 3.8.

**Comment by TobyRoseman** [comment]
The original issue here was the lack of Python 3.8 support. TuriCreate now support Python 3.8. The WSL issue mentioned here are already well documentation in other open issues: #3147 and #3149. So I'm going to close this issue.

**Comment by ankur290109** [comment]
Getting below error while installing Turicreate, I have installed Python 3.8 and Anaconda 3:-

ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Abhishek\anaconda3\envs\virtual_environment_name\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Abhishek\\AppData\\Local\\Temp\\pip-install-qhqi5iee\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\Abhishek\\AppData\\Local\\Temp\\pip-install-qhqi5iee\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Abhishek\AppData\Local\Temp\pip-record-92_w9hxx\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Abhishek\anaconda3\envs\virtual_environment_name\Include\turicreate'
         cwd: C:\Users\Abhishek\AppData\Local\Temp\pip-install-qhqi5iee\turicreate\
    Complete output (28 lines):
    running install



            ==================================================================================
            TURICREATE ERROR

            If you see this message, pip install did not find an available binary package
            for your system.

            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).

            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7
                * 3.8

            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`

            ==================================================================================



    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Abhishek\anaconda3\envs\virtual_environment_name\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Abhishek\\AppData\\Local\\Temp\\pip-install-qhqi5iee\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\Abhishek\\AppData\\Local\\Temp\\pip-install-qhqi5iee\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Abhishek\AppData\Local\Temp\pip-record-92_w9hxx\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Abhishek\anaconda3\envs\virtual_environment_name\Include\turicreate' Check the logs for full command output.
