### ISSUE TITLE
Errors in installing Turicreate for python 3.7

### ISSUE THREAD

**Issue by alanbazzaz** [apple/turicreate#3155]
Please help. Getting these errors while installing Turicreate on mac os 10.15.4

 Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/setup.py'"'"'; __file__='"'"'/private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-wheel-pRR8e7
       cwd: /private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/
  Complete output (11 lines):
  running bdist_wheel
  /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/ffi/build.py", line 168, in <module>
      main()
    File "/private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/ffi/build.py", line 162, in main
      main_posix('osx', '.dylib')
    File "/private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/ffi/build.py", line 109, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Successfully built resampy absl-py gast termcolor keras-applications opt-einsum wrapt
Failed to build llvmlite
ERROR: tensorflow 2.1.0 has requirement scipy==1.2.2; python_version < "3", but you'll have scipy 1.2.3 which is incompatible.
ERROR: awscli 1.6.2 has requirement rsa==3.1.2, but you'll have rsa 4.0 which is incompatible.
ERROR: tensorboard 2.1.0 has requirement requests<3,>=2.21.0, but you'll have requests 2.9.1 which is incompatible.
Installing collected packages: numpy, scipy, pillow, pytz, pandas, funcsigs, llvmlite, numba, resampy, protobuf, coremltools, absl-py, gast, termcolor, h5py, keras-applications, astor, google-pasta, mock, opt-einsum, grpcio, keras-preprocessing, tensorflow-estimator, werkzeug, rsa, cachetools, pyasn1-modules, google-auth, markdown, oauthlib, requests-oauthlib, google-auth-oauthlib, tensorboard, wrapt, backports.weakref, tensorflow, turicreate
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/setup.py'"'"'; __file__='"'"'/private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-record-YphDqm/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/llvmlite
         cwd: /private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/
    Complete output (14 lines):
    running install
    running build
    got version from file /private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/llvmlite/_version.py {'version': '0.32.0', 'full': '26059d238f4ba23dff74703dd27168591d889edd'}
    running build_ext
    /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/ffi/build.py", line 168, in <module>
        main()
      File "/private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/ffi/build.py", line 162, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/ffi/build.py", line 109, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/setup.py'"'"'; __file__='"'"'/private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-install-iQyI2T/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/4b/z5jd4tdj3dz2jc707ns1z4t80000gp/T/pip-record-YphDqm/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/llvmlite Check the logs for full command output.
Alans-iMac:alan Alan$

**Comment by TobyRoseman** [comment]
`llvmlite` (which is a transitive dependency of TuriCreate) recently dropped support for Python 2.7 and Python 3.5. We just [released a point release](https://github.com/apple/turicreate/releases/tag/6.2.1) to fix this issue.

**Comment by alanbazzaz** [comment]
Can TuriCreate run under python 3.8?

**Comment by TobyRoseman** [comment]
@alanbazzaz - TuriCreate can not currently run under Python 3.8. We are tracking that issue in #3099.

**Comment by VeneratioVitae** [comment]
I've tried installing Turicreate for some days now and it keeps stoppng at llvmlite-0.33.0-cp37-cp37m-manylinux1_x86_64.whl (18.3 MB)  download...
![Linux install issue](https://user-images.githubusercontent.com/66384688/89725655-9c4bde00-da09-11ea-9f4b-e8390275f5c9.png)

I came across this thread this morning and said to follow @TobyRoseman earlier comment about a fix in a point release... I downloaded that and tried installing to my virtual environment in WSL and got another error
![Turicreate not fixed](https://user-images.githubusercontent.com/66384688/89725713-2a27c900-da0a-11ea-8259-7282f23edcde.png)
I need some help... Thanks

**Comment by 8bitmp3** [comment]
Hey @VeneratioVitae, can you share your environment details and all the steps you've taken when attempting to install Turi Create? For example:

```shell
# Step 1: 
command line
# Step 2
command line
...
# Set up a virtual env
virtualenv venv
...
```

It may help to figure out what may be missing the [Installation guide](https://github.com/apple/turicreate#installation), especially for [Linux](https://github.com/apple/turicreate/blob/master/LINUX_INSTALL.md). We could also try to update the [Common installation issues page](https://github.com/apple/turicreate/blob/master/INSTALL_ISSUES.md).

fyi I had an issue with Python 3.7 until I did a clean (re)install of all py3's, since there were a few them all over the place, from [python.org/downloads](https://www.python.org/downloads/). Then, I made sure my virtual environment for Turi Create pointed to the "right" py3.

**Comment by 8bitmp3** [comment]
> Further retries kept stopping on the same 'llvmlite-0.33.0' dependency download... I tried pip uninstalling and reinstalling, same result.

@VeneratioVitae 
- Maybe it's to do with your LLVM version (see one of the comments [here](https://stackoverflow.com/questions/61352848/error-in-installing-turi-create-on-windows) about the unsupported version). I don't have experience with LLVM on WSL, but [this](https://superuser.com/questions/1496102/install-llvm-9-wiht-wsl-ubuntu) could help.
- Have you taken a look at the `scipy` workaround [here](https://stackoverflow.com/questions/61314669/error-while-installing-turicreate-while-building-wheel-for-llvmlite) of StackOverflow?
- I'd also skip installing Jupyter in your 'venv' until you get Turi Create up and running, since the latter already comes with a bunch of data science libraries.

**Comment by VeneratioVitae** [comment]
Thank you @8bitmp3 ... I wonder about the scipy workaround but i'll try it nonetheless... Maybe i'll start afresh with a new virtual environment and follow the instructions all over from the beginning like you suggested. I really hope something works out or i might just have to go back to Pandas/Scikit learn. But i must say i've enjoyed Graphlab Create so far and that's why i can't wait to get Turicreate. Thank you for your help
