### ISSUE TITLE
Error in Installing turicreate

### ISSUE THREAD

**Issue by tssrao** [apple/turicreate#3191]
** I have installed WSL in my Windows 10 Pro PC.
I am using Python 3.7.7
I have successfully created a virtual environment.
I am getting an error while installing turicreate. 
please go through it and help me.**

(venv) tssrao@DESKTOP-PJJ7B1L:~$ pip3 install turicreate
Collecting turicreate
  Using cached turicreate-6.0.tar.gz (1.9 kB)
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/tssrao/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q0y1iu22/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q0y1iu22/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-htcji0xw
       cwd: /tmp/pip-install-q0y1iu22/turicreate/
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build/bdist.linux-x86_64/wheel
  running install

          ==================================================================================
          TURICREATE ERROR

          If you see this message, pip install did not find an available binary package
          for your system.

          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).

          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7

          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`

          ==================================================================================

  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: /home/tssrao/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q0y1iu22/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q0y1iu22/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-38e1obcn/install-record.txt --single-version-externally-managed --compile --install-headers /home/tssrao/venv/include/site/python3.8/turicreate
         cwd: /tmp/pip-install-q0y1iu22/turicreate/
    Complete output (28 lines):
    running install

            ==================================================================================
            TURICREATE ERROR

            If you see this message, pip install did not find an available binary package
            for your system.

            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).

            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7

            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`

            ==================================================================================

    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/tssrao/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q0y1iu22/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q0y1iu22/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-38e1obcn/install-record.txt --single-version-externally-managed --compile --install-headers /home/tssrao/venv/include/site/python3.8/turicreate Check the logs for full command output.
![Screenshot (6)](https://user-images.githubusercontent.com/64457083/82035836-b6517b00-96bd-11ea-92ee-434dd9fb1f2c.png)

**Comment by TobyRoseman** [comment]
@tssrao - TuriCreate does seem to have issues running with WSL. However depending on your version of WSL and Ubuntu it should work. However I don't think that is the issue you are having here.

It looks like you are not actually using Python 3.7.7. Based on the output you shared, it seems you are actually using Python 3.8. Credit for spotting this issue goes to @ShubhamSharma1560. For more details see their explanation [here](https://github.com/apple/turicreate/issues/3226#issuecomment-644568139)

TuriCreate does not support Python 3.8. We're tracking this issue in #3099. I'm going to close this issue as a duplicate, but let me know if you have any questions.
