### ISSUE TITLE
Errors in installing Turicreate for python 3.7 macOS 10.4.6

### ISSUE THREAD

**Issue by rayushbpgc** [apple/turicreate#3192]
Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/ayushraj/opt/anaconda3/envs/virtual_environment_name/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0k/3z8wjgtn6532jf0hnn3sc10h0000gn/T/pip-install-sc95ljf8/turicreate/setup.py'"'"'; __file__='"'"'/private/var/folders/0k/3z8wjgtn6532jf0hnn3sc10h0000gn/T/pip-install-sc95ljf8/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/0k/3z8wjgtn6532jf0hnn3sc10h0000gn/T/pip-wheel-5nne8716
       cwd: /private/var/folders/0k/3z8wjgtn6532jf0hnn3sc10h0000gn/T/pip-install-sc95ljf8/turicreate/
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build/bdist.macosx-10.9-x86_64/wheel
  running install
  
  
  
          ==================================================================================
          TURICREATE ERROR
  
          If you see this message, pip install did not find an available binary package
          for your system.
  
          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).
  
          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7
  
  
          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`
  
          ==================================================================================
  
  
  
  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/ayushraj/opt/anaconda3/envs/virtual_environment_name/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0k/3z8wjgtn6532jf0hnn3sc10h0000gn/T/pip-install-sc95ljf8/turicreate/setup.py'"'"'; __file__='"'"'/private/var/folders/0k/3z8wjgtn6532jf0hnn3sc10h0000gn/T/pip-install-sc95ljf8/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/0k/3z8wjgtn6532jf0hnn3sc10h0000gn/T/pip-record-f6c77dqv/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ayushraj/opt/anaconda3/envs/virtual_environment_name/include/python3.8/turicreate
         cwd: /private/var/folders/0k/3z8wjgtn6532jf0hnn3sc10h0000gn/T/pip-install-sc95ljf8/turicreate/
    Complete output (28 lines):
    running install
    
    
    
            ==================================================================================
            TURICREATE ERROR
    
            If you see this message, pip install did not find an available binary package
            for your system.
    
            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).
    
            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7
    
    
            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`
    
            ==================================================================================
    
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ayushraj/opt/anaconda3/envs/virtual_environment_name/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0k/3z8wjgtn6532jf0hnn3sc10h0000gn/T/pip-install-sc95ljf8/turicreate/setup.py'"'"'; __file__='"'"'/private/var/folders/0k/3z8wjgtn6532jf0hnn3sc10h0000gn/T/pip-install-sc95ljf8/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/0k/3z8wjgtn6532jf0hnn3sc10h0000gn/T/pip-record-f6c77dqv/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ayushraj/opt/anaconda3/envs/virtual_environment_name/include/python3.8/turicreate Check the logs for full command output.

**Comment by rayushbpgc** [comment]
Then I used another method (Please help)
 ayushraj$ python -m pip install turicreate
Collecting turicreate
  Downloading turicreate-6.2.2-cp37-cp37m-macosx_10_12_intel.macosx_10_12_x86_64.macosx_10_13_intel.macosx_10_13_x86_64.macosx_10_14_intel.macosx_10_14_x86_64.whl (33.0 MB)
     |████████████████████████████████| 33.0 MB 132 kB/s 
Requirement already satisfied: decorator>=4.0.9 in ./opt/anaconda3/lib/python3.7/site-packages (from turicreate) (4.4.1)
Requirement already satisfied: pillow>=5.2.0 in ./opt/anaconda3/lib/python3.7/site-packages (from turicreate) (7.0.0)
Collecting tensorflow>=2.0.0
  Downloading tensorflow-2.2.0-cp37-cp37m-macosx_10_11_x86_64.whl (175.3 MB)
     |█▏                              | 6.2 MB 132 kB/s eta 0:21:15ERROR: Could not install packages due to an EnvironmentError: ("read error: Error([('SSL routines', 'ssl3_get_record', 'decryption failed or bad record mac')])",)

**Comment by TobyRoseman** [comment]
The first thing I would try is upgrading your `pip`. You can do this by running:
`pip install --upgrade pip`.

After that see if you can successfully run: `pip install turicreate`.

If you still can not install turicreate, then you might have some enviornment issues where `python` and `pip` are not using the same Python versions. Run`pip -V` and see if it say python 3.7.

**Comment by rayushbpgc** [comment]
thanks man these two worked 
pip install -U pip
pip install turicreate
