### ISSUE TITLE
Turi Create not installing

### ISSUE THREAD

**Issue by mushi296** [apple/turicreate#3196]
Python is working fine on Jupyter Notebook, and I thought I installed Turi Create using the Terminal. But when I run "import turicreatei", I get the following error: 
Please help
![Screenshot 2020-05-16 at 4 36 54 PM](https://user-images.githubusercontent.com/65428028/82118890-7f4d9900-9793-11ea-8a9b-fd2aba039bde.png)

**Comment by TobyRoseman** [comment]
You have most likely installed TuriCreate in a different environment than the environment you are using to run Jupyter.

The easiest way to make sure things get installed in the right environment is to install them using Jupyter Notebook. You can run system commands from inside of Jupyter Notebook by starting them with a !. So in a Jupyter code cell, run this command:
! pip install turicreate.

Let us know if that works.

**Comment by mushi296** [comment]
Yes that worked, thank you so much!! 
I spent so long trying to figure this out.

I don't understand why all this has to be so complicated. Isn't there an all-in-one installer that manages all these aspects for python?
