### ISSUE TITLE
not Install GraphLab Create

### ISSUE THREAD

**Issue by yaoyao9925** [apple/turicreate#3197]
(gl-env) C:\Users\99251>pip install --upgrade --no-cache-dir https://get.graphlab.com/GraphLab-Create/2.1/xinyao.liu9925@gmail.com/D443-7C24-DC3D-3114-D928-1654-CD6B-DD29/GraphLab-Create-License.tar.gz
Collecting https://get.graphlab.com/GraphLab-Create/2.1/xinyao.liu9925@gmail.com/D443-7C24-DC3D-3114-D928-1654-CD6B-DD29/GraphLab-Create-License.tar.gz
  Downloading https://get.graphlab.com/GraphLab-Create/2.1/xinyao.liu9925@gmail.com/D443-7C24-DC3D-3114-D928-1654-CD6B-DD29/GraphLab-Create-License.tar.gz (1.8 kB)
ERROR: Could not find a version that satisfies the requirement graphlab-create>=2.1 (from GraphLab-Create-License==2.1) (from versions: none)
ERROR: No matching distribution found for graphlab-create>=2.1 (from GraphLab-Create-License==2.1)

**Comment by TobyRoseman** [comment]
This is the GitHub repository for TuriCreate, not GraphLab Create.
