### ISSUE TITLE
A solution for those want to use turicreate with jupyter notebook but gets "ModuleNotFoundError: No module named 'turicreate'"; in Linux

### ISSUE THREAD

**Issue by ornob011** [apple/turicreate#3198]
Assuming you want to use turicreate with both python2 and python3, here's a solution. I faced this problem even when I followed the official installation rules. I tried other solutions that I could find, but none of them worked. Here's the solution:

I am writing the fix for Ubuntu. If you're using another distro, your command will be slightly different according to your package manager.

sudo apt update
sudo apt remove virtualenv python jupyter
sudo apt install -y libstdc++6 python-setuptools libgconf-2-4
sudo apt install python-pip python3-pip
sudo pip install virtualenv notebook jupyter
sudo pip3 install virtualenv notebook jupyter
cd $HOME
virtualenv venv
cd venv/
source bin/activate
pip install --upgrade pip
pip install jupyter notebook
pip install -U turicreate
pip3 install jupyter notebook
pip3 install -U turicreate
jupyter notebook

**Comment by TobyRoseman** [comment]
@ornob011 - Thanks for sharing but I don't think it makes sense to create an issue for this. If something isn't clear in our setup instructions, please send us a clarifying pull request or create an issue about what isn't clear.

**Comment by EmonZaman** [comment]
I've been suffering from it for a long time... Then after following these commands the problem is solved..Thanks a lot brother ❤️ 👍

**Comment by BhabeshMali** [comment]
You are great buddy, Thanks

**Comment by MontseSacie** [comment]
Thank you so much!
