### ISSUE TITLE
tc.aggregate.QUANTILE does not meet "guaranteed" accuracy

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#3200]
As mentioned in #745, tc.aggregate.QUANTILE is actually an approximation. According to the docstring: "quantiles are guaranteed to have 0.5% accuracy". However this does not seem to be true.
```python
import numpy as np                                                                                                                                   
import turicreate as tc

l = [-4, 10, -1, -100]
print(np.quantile(l, [.5])[0])

temp = tc.SFrame({'x': l})
temp['dummy'] = 1
result = temp.groupby('dummy', {'y': tc.aggregate.QUANTILE('x', 0.5)})
print(result['y'][0][0])
```
Produces:
```
-2.5
-1.0
```
-1.0 is not with 0.5% of -2.5.

**Comment by hoytak** [comment]
Numpy appears to do some sort of linear smoothing between -4 and -1, which is not standard but common.  Technically (in statistics) the quantile of an empirical distribution like this can be anywhere in between the two values given.  Typically, one of those values is returned as the quantile.  In this case, [-100, -4, -1, 10] would mean that anything in [-4, -1] is valid as a numerical quantile.  However, the median almost always returns value that is present in the dataset, which is what we do here, returning -1.  So our result is correct.
