### ISSUE TITLE
OSOD not utilising Colab GPU

### ISSUE THREAD

**Issue by navanchauhan** [apple/turicreate#3203]
Colab Notebook ( Runtime GPU )

https://colab.research.google.com/drive/14bFRa4ygtd1PDcBn4Zb8BH23MUEWMg2L?usp=sharing

![image](https://user-images.githubusercontent.com/29234112/82417957-f9369880-9a99-11ea-96f3-8ddfeea3c25a.png)

**Comment by TobyRoseman** [comment]
What version of TensorFlow do you have installed in your environment?

**Comment by navanchauhan** [comment]
Installing Turicreate from pip replaces the default TF 2.x with TF 2.0.1

**Comment by franz101** [comment]
Same here:
https://colab.research.google.com/drive/1GDS1cTwSraXJlJ1hODl3Ar_SRqQNE7L4?usp=sharing

**Comment by TobyRoseman** [comment]
The root issue here is #3003. On Linux, TuriCreate is only able to run with TensorFlow 2.0.0 and 2.0.1. 

Each version of TensorFlow has very specific requirements about the version of CUDA and cuDNN that must be installed on the System. The version of TensorFlow which TuriCreate installs seems to be incompatible with the version of CUDA and cuDNN that are installed on Colab.

To verify this you can run this TensorFlow only code:
```python
import tensorflow as tf
print(tf.test.is_gpu_available())
```

**Comment by navanchauhan** [comment]
A simple fix I found is `!pip install tensorflow-gpu==2.0.1` 

```python
import tensorflow as tf
print(tf.test.is_gpu_available())
```
 Results in `True` with this

@TobyRoseman I think this issue can be closed for now?

**Comment by TobyRoseman** [comment]
@navanchauhan - Great! Thanks for trying `tensorflow-gpu==2.0.1` and letting us know it works.
