### ISSUE TITLE
Install Error : Turicreate,  pip install did not find an available binary package

### ISSUE THREAD

**Issue by qnxdev** [apple/turicreate#3209]
While installing turicreate I had this issue.

Any help is appreciated.
Thanks

The full log is here:

`Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wt6lm_8z/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wt6lm_8z/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3au9izgp
       cwd: /tmp/pip-install-wt6lm_8z/turicreate/
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build/bdist.linux-x86_64/wheel
  running install
  
  
  
          ==================================================================================
          TURICREATE ERROR
  
          If you see this message, pip install did not find an available binary package
          for your system.
  
          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).
  
          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7
  
  
          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`
  
          ==================================================================================
  
  
  
  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: /home/user/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wt6lm_8z/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wt6lm_8z/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-g2lvuvnn/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/venv/include/site/python3.8/turicreate
         cwd: /tmp/pip-install-wt6lm_8z/turicreate/
    Complete output (28 lines):
    running install
    
    
    
            ==================================================================================
            TURICREATE ERROR
    
            If you see this message, pip install did not find an available binary package
            for your system.
    
            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).
    
            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7
    
    
            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`
    
            ==================================================================================
    
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/user/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wt6lm_8z/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wt6lm_8z/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-g2lvuvnn/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/venv/include/site/python3.8/turicreate Check the logs for full command output.
`

**Comment by TobyRoseman** [comment]
Based on your `install-header` path, it looks like you are using Python 3.8. As the error message indicates, TuriCreate does not support Python 3.8 yet.

We are already tracking Python 3.8 support in #3099.
