### ISSUE TITLE
Unable to install Turicreate in anaconda

### ISSUE THREAD

**Issue by mjasonkumar** [apple/turicreate#3214]
Hi, 
I created virtual environment and I tried to install turicreate in while. But I'm not able to install. I used python 3.7 version. Kindly assist me in this issue. below is the error message. My laptop is windows 10 and x86_64

 
C:\Users\mjaso\OneDrive\Documents>conda activate trui

(trui) C:\Users\mjaso\OneDrive\Documents>pip install -U turicreate
Collecting turicreate
  Using cached turicreate-6.0.tar.gz (1.9 kB)
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\trui\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mjaso\\AppData\\Local\\Temp\\pip-install-ev_tw4yx\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\mjaso\\AppData\\Local\\Temp\\pip-install-ev_tw4yx\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\mjaso\AppData\Local\Temp\pip-wheel-6ncb6jln'
       cwd: C:\Users\mjaso\AppData\Local\Temp\pip-install-ev_tw4yx\turicreate\
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build\bdist.win-amd64\wheel
  running install

          ==================================================================================
          TURICREATE ERROR

          If you see this message, pip install did not find an available binary package
          for your system.

          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).

          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7

          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`

          ==================================================================================

  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\trui\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mjaso\\AppData\\Local\\Temp\\pip-install-ev_tw4yx\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\mjaso\\AppData\\Local\\Temp\\pip-install-ev_tw4yx\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mjaso\AppData\Local\Temp\pip-record-dnocjsfl\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\trui\Include\turicreate'
         cwd: C:\Users\mjaso\AppData\Local\Temp\pip-install-ev_tw4yx\turicreate\
    Complete output (28 lines):
    running install

            ==================================================================================
            TURICREATE ERROR

            If you see this message, pip install did not find an available binary package
            for your system.

            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).

            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7

            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`

            ==================================================================================

    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\trui\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mjaso\\AppData\\Local\\Temp\\pip-install-ev_tw4yx\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\mjaso\\AppData\\Local\\Temp\\pip-install-ev_tw4yx\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mjaso\AppData\Local\Temp\pip-record-dnocjsfl\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\trui\Include\turicreate' Check the logs for full command output.

**Comment by TobyRoseman** [comment]
TuriCreate does not have native Windows support. Windows is not listed under `Supported Platforms` in the error message. If you want to use TuriCreate on Windows, please try using WSL.

We are tracking native windows support in #533.
