### ISSUE TITLE
Audio Classifier dyid issue

### ISSUE THREAD

**Issue by JBall1** [apple/turicreate#3215]
I am trying to add an audio classifier I made with turicreate, but I keep getting the following error:
`dyld: Library not loaded: /Users/zach/builds/1fUgszd-/0/turi/turicreate/release/src/deployment/Release-iphoneos/libAudioPreprocessing.dylib
  Referenced from: /private/var/containers/Bundle/Application/FA27715F-2967-46EC-A975-762AD63CF243/Name.app/Name
  Reason: image not found`
I followed the guide to the T, but still am getting this issue. Any advice? Running the latest XCode in MacOS. I _had_ no issues using other models created through other means, but the issue clearly is with how to properly add libaudioProprocessing.dylib to my project.

Also, please note that in the following line:
`/Users/zach/builds/1fUgszd-/0/turi/turicreate/release/src/deployment/Release-iphoneos/libAudioPreprocessing.dylib`
This directory does not exist on my computer, so I am not sure why it is looking there.

I am building to a physical device and using the arm64 .dylib.

**Comment by TobyRoseman** [comment]
@JBall1 - When during [the deployment instructions](https://apple.github.io/turicreate/docs/userguide/sound_classifier/export-coreml.html) are you seeing this error? When you compile? When you drag the dylib into Xcode?

[The code for this dylib is publicly available](https://github.com/apple/turicreate/blob/master/src/deployment/AudioPreprocessing.mm). Adding the code directly to your application would probably be a quick workaround.

**Comment by JBall1** [comment]
The issue occurred at compile time but adding the files directly into the application and removing the dylib fixed the issue. Thank you!
