### ISSUE TITLE
CoreML output different from model output for Activity Classifier

### ISSUE THREAD

**Issue by tanpinquan** [apple/turicreate#3216]
I trained an activity classifier model using data obtained from reality kit body tracking to classify three types of exercises. I largely followed the tutorial provided.

After training, the accuracy was good at 90% and I have verified this on additional validation data.

However, after exporting the coreML model and testing it on the same training and test datasets, the predictions are are different from those obtained in the python model.

Strangely, the results seem to be correct when I use a window size of 150 but not for any other values I have tried (50, 75, 100, 145, 160). I am not sure what could be the reason for this.

**Comment by TobyRoseman** [comment]
I'm not able to reproduce this issue. Using a prediction window size other than 150, my CoreML model matches. See code below:

```python
import coremltools
import numpy as np
import turicreate as tc

data = tc.load_sframe('hapt_data.sframe')
data = data['acc_x', 'activity', 'exp_id']    #simplyfly data 
tc_model = tc.activity_classifier.create(data, session_id='exp_id',
                                      target='activity', prediction_window=1)

tc_model.export_coreml('/tmp/MyCustomActivityClassifier.mlmodel')
coreml_model = coremltools.models.MLModel('/tmp/MyCustomActivityClassifier.mlmodel')

test = data.head(1)
coreml_prediction = coreml_model.predict({"stateIn": np.zeros(400,),
                                          "acc_x": np.array([test['acc_x'][0]])})

print(coreml_prediction['activityProbability'].values())
print(tc_model.predict(test, output_type='probability_vector'))
```
Outputs:
```
dict_values([0.3777371346950531, 0.24549837410449982, 4.9453636165708303e-05, 4.745922524307389e-06, 0.0017297347076237202, 0.374980628490448])
[array('d', [0.3782108724117279, 0.24553148448467255, 4.859150794800371e-05, 4.641778104996774e-06, 0.0017009000293910503, 0.3745034635066986])]
```

Note: the SFrame (i.e. `hapt_data.sframe`) is from our [User Guide](https://apple.github.io/turicreate/docs/userguide/activity_classifier/data-preparation.html).

**Comment by tanpinquan** [comment]
I am only facing the issue after importing the coreML model into xCode and running the app on device.  

Within the app, I supply the same data as used in training but the output predictions are different. In fact the predictions always give the same output regardless of what input I am providing within the app itself.

**Comment by tanpinquan** [comment]
Here are the steps I took to help reproduce the issue

1. Trained a model following the steps in the tutorial. The data and output model are attached below
Data (Only a subset of 12 columns were used): [TrainingData.zip](https://github.com/apple/turicreate/files/4721317/TrainingData.zip)
Model (window size of 75): [ShoulderAbductionClassifier.mlmodel.zip](https://github.com/apple/turicreate/files/4721321/ShoulderAbductionClassifier.mlmodel.zip)

2. Imported the model into Xcode and ran a prediction on an iPad mini 5 using the same training data stored as csv

3. The prediction output always gives "shoulder_left" which is the second activity regardless of input

**Comment by TobyRoseman** [comment]
@tanpinquan - Does the same code/model/data work before you deploy to the iPad, i.e. does it work in the simulator?

**Comment by tanpinquan** [comment]
No, it does not work in the simulator either. I have created am empty project from scratch containing only the model and training data.

However, the issue is intermittent and sometimes goes away after clean+rebuilding and comes back again.

Feel free to look at the [repo](https://github.com/tanpinquan/CoreMLTest)

**Comment by TobyRoseman** [comment]
If the issue sometimes goes away after a clean and a rebuild, this sounds like this is an issue with Xcode. I'd recommend [filling a bug report for them](https://developer.apple.com/bug-reporting/).
