### ISSUE TITLE
Problems with pandas dependency version

### ISSUE THREAD

**Issue by magsouza** [apple/turicreate#3217]
The library installation doesn't have an upper bound for the pandas version, therefore it installs the latest version of pandas which is incompatible after the breaking changes in 1.0.x version.
https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.0.0.html

**Comment by TobyRoseman** [comment]
All of our SFrame and SArray unit test pass with pandas `1.0.4`.

@magsouza - please you give us some more details here. What specifically is incompatible? Are you seeing an error?

**Comment by magsouza** [comment]
Yes. After running `pip install turicreate` and trying to `import turicreate`, I get the following error message: https://pastebin.com/Vez0h4Hi
And then, after running `pip install pandas==0.25.3`, I can successfully import it.

**Comment by TobyRoseman** [comment]
@magsouza - I can not reproduce that behavior. From the stack trace this look likes an issue with Pandas not with TuriCreate. With Pandas 1.0.x installed, are you able to just `import pandas`?

**Comment by TobyRoseman** [comment]
Also if you are using Jupyter/IPython notebook, trying running `import turicreate` **after** you have restarted the notebook process.

**Comment by magsouza** [comment]
I tried to only import pandas as you said and I got an error message, so that's indeed a problem with pandas. I'll dig into it to try to solve it. Thanks a lot for the support!
