### ISSUE TITLE
stuck at starting newton method

### ISSUE THREAD

**Issue by Partha-Sarker** [apple/turicreate#3223]
When I try to train a model by the following code

`advanced_features_model = turicreate.linear_regression.create(train_data, target='price', features=advanced_features, validation_set=None)`

then if I run the code the output looks like this

Linear regression:
--------------------------------------------------------
Number of examples          : 17252
Number of features          : 18
Number of unpacked features : 18
Number of coefficients    : 87
Starting Newton Method
--------------------------------------------------------

And then nothing happens. The cell shows it's running but no other text appears in the output. I waited for some times but still nothing.

I am on windows 10, using wsl.

**Comment by TobyRoseman** [comment]
Please give us a bit more details.

1 - What is the value of your `advanced_features`?
2 - Can you create other linear regression models without those advanced features?
2 - What version of Linux are you using with WSL?
3 - What version of Python?
4 - It looks like you have 19 columns in `train_data` (including your target). What are the types of these columns, i.e. what is the output full `train_data.column_types()`?
5 - We should have no problem with a dataset your size. However please trying running this on a much smaller dataset; please run `train_data = train_data.head()`, then try running the command you shared.

**Comment by TobyRoseman** [comment]
Probably related to #3166

**Comment by Partha-Sarker** [comment]
> Please give us a bit more details.
> 
> 1 - What is the value of your `advanced_features`?
> 2 - Can you create other linear regression models without those advanced features?
> 2 - What version of Linux are you using with WSL?
> 3 - What version of Python?
> 4 - It looks like you have 19 columns in `train_data` (including your target). What are the types of these columns, i.e. what is the output full `train_data.column_types()`?
> 5 - We should have no problem with a dataset your size. However please trying running this on a much smaller dataset; please run `train_data = train_data.head()`, then try running the command you shared.

I can assure you everything is OK. Because I just got everything working on colab.research.google.com. It only doesn't work locally. As for the question you asked
1. some of the columns name in a list.
2. Can't create any model with any data.
3. ubuntu 20.04
4. types are string and number

**Comment by Partha-Sarker** [comment]
> Probably related to #3166

Yap, I think this is the reason. I am using 20.04.

**Comment by Partha-Sarker** [comment]
```
import turicreate
from turicreate import SFrame
import turicreate.aggregate as agg


hd = SFrame(data='home_data.sframe')


advanced_features = [
'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'zipcode',
'condition', # condition of house				
'grade', # measure of quality of construction				
'waterfront', # waterfront property				
'view', # type of view				
'sqft_above', # square feet above ground				
'sqft_basement', # square feet in basement				
'yr_built', # the year built				
'yr_renovated', # the year renovated				
'lat', 'long', # the lat-long of the parcel				
'sqft_living15', # average sq.ft. of 15 nearest neighbors 				
'sqft_lot15', # average lot size of 15 nearest neighbors 
]

train_data, test_data = hd.random_split(.8, seed=1)

advanced_features_model = turicreate.linear_regression.create(train_data, target='price', features=advanced_features, validation_set=None)
```

this is the full code

**Comment by hardik-kapoor** [comment]
Was this problem solved? im having the same issue and i dont know what to do.
thanks.

**Comment by Partha-Sarker** [comment]
> Was this problem solved? im having the same issue and i dont know what to do.
> thanks.

I trained the model using colab.research.google.com later

**Comment by TobyRoseman** [comment]
Using a similar dataset and the newton solver, I am able to train a linear regression model using WSL1 and Ubuntu 18.
