### ISSUE TITLE
error in installing turi-create using python version 3.6.8 after enabling WSL 

### ISSUE THREAD

**Issue by ShubhamSharma1560** [apple/turicreate#3226]
i am getting error in virtualenv  when i am using command pip install -U turicreate
error looks like this :

(venv) PS F:\jupyter> pip install -U turicreate
Collecting turicreate
  Using cached turicreate-6.0.tar.gz (1.9 kB)
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'F:\jupyter\venv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-bued37zg\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-bued37zg\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\HP\AppData\Local\Temp\pip-wheel-z7wfse7c'
       cwd: C:\Users\HP\AppData\Local\Temp\pip-install-bued37zg\turicreate\
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build\bdist.win-amd64\wheel
  running install

          ==================================================================================
          TURICREATE ERROR

          If you see this message, pip install did not find an available binary package
          for your system.

          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).

          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7

          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`

          ==================================================================================

  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: 'F:\jupyter\venv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-bued37zg\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-bued37zg\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\HP\AppData\Local\Temp\pip-record-yi7niqsq\install-record.txt' --single-version-externally-managed --compile --install-headers 'F:\jupyter\venv\include\site\python3.6\turicreate'
         cwd: C:\Users\HP\AppData\Local\Temp\pip-install-bued37zg\turicreate\
    Complete output (28 lines):
    running install

            ==================================================================================
            TURICREATE ERROR

            If you see this message, pip install did not find an available binary package
            for your system.

            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).

            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7

            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`

            ==================================================================================

    ----------------------------------------
ERROR: Command errored out with exit status 1: 'F:\jupyter\venv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-bued37zg\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-bued37zg\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\HP\AppData\Local\Temp\pip-record-yi7niqsq\install-record.txt' --single-version-externally-managed --compile --install-headers 'F:\jupyter\venv\include\site\python3.6\turicreate' Check the logs for full command output.

i also want to clear that in virtual environment in am using python 36 and my pip is also upto date

**Comment by mandapatibhavaniprasad** [comment]
I have the same problem.

**Comment by TobyRoseman** [comment]
This is a duplicate issue of #3191.

**Comment by ShubhamSharma1560** [comment]
> This is a duplicate issue of #3191.

Sir firstly I want to say that Where you want to refer me in that issue the person's virtual environment is using python 3.8 You can see in post #3191 and python 3.8 is not compatible yet. But it is different in my case my virtual environment python version is 3.6 and turicreate is already compatible with 3.6 in turicreate guide but I am not able to install.
![IMG_20200616_121634](https://user-images.githubusercontent.com/54950485/84740577-44759580-afcb-11ea-9d40-63fb7e716268.jpg)

But in #3191  case person virtual environment using python 3.8 as u can see that
![IMG_20200616_121835](https://user-images.githubusercontent.com/54950485/84740785-a6ce9600-afcb-11ea-8f5a-eb5b5222b50a.jpg)
se person virtual environment using python 3.8 as u can see that

**Comment by TobyRoseman** [comment]
Thanks for pointing that @ShubhamSharma1560. I'll reopen this issue and point the user who submitted the other issue to your comment here.

**Comment by MSoumen** [comment]
I'm also facing this problem. Please fix this ASAP

**Comment by TobyRoseman** [comment]
Python 3.8 is now supported. It looks like that was the root issue here. So I'm going to close this. If installation is still not working, let us know.
