### ISSUE TITLE
Jupyter notebook is'n opening of bash subsystem.

### ISSUE THREAD

**Issue by sachika11** [apple/turicreate#3231]
![Screenshot (39)](https://user-images.githubusercontent.com/67162589/85159171-c0e1d000-b27a-11ea-9a14-18ee6858653c.png)

**Comment by sachika11** [comment]
But my Python Version 
![Screenshot (40)](https://user-images.githubusercontent.com/67162589/85159966-d4da0180-b27b-11ea-9dc2-6eecc8e71d0c.png)

**Comment by sachika11** [comment]
when you running #jupyter notebook# command. this problem occurs.
first, copy one URL and paste it to a web browser. (URL in our subsystem command line)
Eg
:http://localhost:8888/?token=24f02cfgvhhmn035d0b54545b4c06818266561269e3b8721212fa51
when you're copying to browser next will ask Token or password.
Login Token/password :
token=**24f02cfgvhhmn035d0b54545b4c06818266561269e3b8721212fa51**
(these ais the incorrect URL)

**Comment by TobyRoseman** [comment]
This looks like a Jupyter issue not an issue with TuriCreate. I suggest you consult the [Jupyter Documentation](https://jupyter.org/documentation).
