### ISSUE TITLE
Poker One Shot Detector App

### ISSUE THREAD

**Issue by suyashjoshi** [apple/turicreate#3234]
Hello,

I just saw the WWDC 2019 video and found out about this amazing project. I'm looking for the Poker app that was demo'ed using One Shot Object Detector api but can't find it anywhere. Is that code provided anywhere?

Ref: https://developer.apple.com/videos/play/wwdc2019/420/

Thanks!

**Comment by suyashjoshi** [comment]
@shantanuchhabra was it shared?

**Comment by shantanuchhabra** [comment]
Hi @suyashjoshi , 

Thanks for checking out our WWDC 19 video! Unfortunately, the code for the Three Card Poker App isn't available, but our [user guide](https://apple.github.io/turicreate/docs/userguide/one_shot_object_detection/) should help you get started. One approach could be to click an image of each playing card (52 images in total), construct an SFrame, and pass that SFrame in to `turicreate.one_shot_object_detector.create` to get a One Shot Object Detector model that can detect playing cards!

Let us know if you have any follow-up questions or if we can help in any way!

**Comment by suyashjoshi** [comment]
Got it thanks, will try that. One more question, can I export model in another format such as for TensorFlow Lite or ONNX from Turi as I would love to deploy not only on iOS but also on other devices including IOT. Thanks again.

**Comment by shantanuchhabra** [comment]
You can export models to the [Core ML](https://developer.apple.com/documentation/coreml) format using [`model.export_coreml`](https://apple.github.io/turicreate/docs/userguide/one_shot_object_detection/#deployment-to-coreml).

_Remainder of my answer is sourced from https://github.com/tf-coreml/tf-coreml/issues/316#issuecomment-507013164_
Once you have a Core ML model, you can try converting to ONNX using [onnxmltools](https://github.com/onnx/onnxmltools) and run using the ONNX runtime. Further, you can try converting to Tensorflow using https://github.com/onnx/onnx-tensorflow.
