### ISSUE TITLE
problems with jupyter notebook - TuriCreate.

### ISSUE THREAD

**Issue by Flotero7** [apple/turicreate#3237]
I have a problem, it happens that I download jupyter notebook and install them from cmd, everything is very normal, then I went to use TuriCreate but I realized that for Windows it had to be done through Ubuntu so I installed it and after that I had to install again the jupyter notebook and also the TuriCreate but it happens that when opening the Ubuntu notebok jupyter which is the one that TuriCreate has, only a folder called venv appears to me, and I don't know where the path to upload files is, because when I look in ubuntu it appears the path / Home / User.

In the windows cmd jupyter notebook it does not allow me to open the Turicreate, the ubuntu one does, but I do not have the path to upload csv files to it.

someone who can help me how to solve? I thank you very much, so far I am learning.
![jupy](https://user-images.githubusercontent.com/66500385/85796775-206b3000-b700-11ea-8750-6386fe9b463d.PNG)

**Comment by TobyRoseman** [comment]
@Flotero7 - I'm not sure I understand the problem. It sounds like you are using TuriCreate on Window via WSL. You got TuriCreate and Jupyter notebook working in your Ubuntu environment. However you can't figure out how to get files from outside of your Ubuntu environment into your Ubuntu environment. Is all that correct?

**Comment by TobyRoseman** [comment]
I have not heard back here, so I'm going to close the issue. If you can get back to me with the requested information, I'm happy to look into it more.
