### ISSUE TITLE
unable to install turicreate in anaconda 

### ISSUE THREAD

**Issue by Ash993** [apple/turicreate#3238]
used anaconda virtual environment to install turicreate but this issue keeps popping

Error processing line 1 of C:\Users\evola\anaconda3\lib\site-packages\matplotlib-3.1.3-py3.7-nspkg.pth:

  Traceback (most recent call last):
    File "C:\Users\evola\anaconda3\lib\site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "C:\Users\evola\anaconda3\lib\importlib\__init__.py", line 51, in <module>
      _w_long = _bootstrap_external._w_long
  AttributeError: module 'importlib._bootstrap_external' has no attribute '_w_long'

**Comment by TobyRoseman** [comment]
It looks like you are using Window. TuriCreate does not have native support for Window. 

If you want to use TuriCreate on Window, you need to use WSL with Ubuntu 18.

We're already tracking native Window support in #533. I'm going to close this issue as a duplicate, but let me know if you have any additional questions.
