### ISSUE TITLE
Correct way to resize images

### ISSUE THREAD

**Issue by rdv0011** [apple/turicreate#3240]
If I understand correctly Turicreate automatically resizes images during training. I need to use CoreML from Python. To do that the images should be scaled and cropped accordingly.

1) Could you please describe how exactly should I do  that?
2) Should the cropped image be drawn on the white background? If yes, what offset should be used?
3) When using CoreML from Python should I modify pixels somehow (scaling, apply bias)?

**part two**

I have noticed also differences in the inferring results for CoreML and and original Darknet-YOLO(object detector) model that Turicrate might save after training. Could you please answer the same questions regarding original Darknet-YOLO?

![tempImage](https://user-images.githubusercontent.com/4025952/85982263-cc08ce80-b9e5-11ea-9eb9-1481e89ba00e.png)

**Comment by TobyRoseman** [comment]
It depends on the toolkit, but TuriCreate does generally resize images before training.

This isn't the correct place to ask questions about CoreML. This is the repository for TuriCreate, not CoreML.

I would recommend taking a look at [the coremltools repository](https://github.com/apple/coremltools), particularly [their unit test](https://github.com/apple/coremltools/tree/master/coremltools/test). Those unit tests use CoreML from Python.
