### ISSUE TITLE
getting problem to start turicreate

### ISSUE THREAD

**Issue by Rushikeshdhanorkar** [apple/turicreate#3254]
I know the issue is that Im running python 3.8 , but i don't know the solution to this, Im student who is trying to get into machine learning and i want to use turicreate for my journey. Any help please.i tried code in one privious issue  also but i am getting error please help me out .please.
i used this in anaconda command promt
pip install --upgrade pip
pip install --upgrade virtualenv
virtualenv --python=python3.7 ./venv
source ./venv/bin/activate
pip install turicreate. 

Error
(base) C:\Users\rushikesh>virtualenv --python=python3.7 ./venvsource./venv/bin/activate
created virtual environment CPython3.7.6.final.0-64 in 9539ms
  creator CPython3Windows(dest=C:\Users\rushikesh\venvsource\venv\bin\activate, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\rushikesh\AppData\Local\pypa\virtualenv)
    added seed packages: pip==20.1.1, setuptools==49.1.0, wheel==0.34.2
  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

(base) C:\Users\rushikesh>pip install turicreate
Collecting turicreate
  Downloading turicreate-6.0.tar.gz (1.9 kB)
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\rushikesh\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RUSHIK~1\\AppData\\Local\\Temp\\pip-install-23uyi08z\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\RUSHIK~1\\AppData\\Local\\Temp\\pip-install-23uyi08z\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\RUSHIK~1\AppData\Local\Temp\pip-wheel-2re5i0pe'
       cwd: C:\Users\RUSHIK~1\AppData\Local\Temp\pip-install-23uyi08z\turicreate\
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build\bdist.win-amd64\wheel
  running install

          ==================================================================================
          TURICREATE ERROR

          If you see this message, pip install did not find an available binary package
          for your system.

          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).

          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7

          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`

          ==================================================================================

  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\rushikesh\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RUSHIK~1\\AppData\\Local\\Temp\\pip-install-23uyi08z\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\RUSHIK~1\\AppData\\Local\\Temp\\pip-install-23uyi08z\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\RUSHIK~1\AppData\Local\Temp\pip-record-xffvp413\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\rushikesh\anaconda3\Include\turicreate'
         cwd: C:\Users\RUSHIK~1\AppData\Local\Temp\pip-install-23uyi08z\turicreate\
    Complete output (28 lines):
    running install

            ==================================================================================
            TURICREATE ERROR

            If you see this message, pip install did not find an available binary package
            for your system.

            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).

            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7

            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`

            ==================================================================================

    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\rushikesh\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RUSHIK~1\\AppData\\Local\\Temp\\pip-install-23uyi08z\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\RUSHIK~1\\AppData\\Local\\Temp\\pip-install-23uyi08z\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\RUSHIK~1\AppData\Local\Temp\pip-record-xffvp413\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\rushikesh\anaconda3\Include\turicreate' Check the logs for full command output.

(base) C:\Users\rushikesh>pip install -U pip
Requirement already up-to-date: pip in c:\users\rushikesh\anaconda3\lib\site-packages (20.1.1)

(base) C:\Users\rushikesh>pip3 install turicreate
Collecting turicreate
  Using cached turicreate-6.0.tar.gz (1.9 kB)
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\rushikesh\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RUSHIK~1\\AppData\\Local\\Temp\\pip-install-emmwr2o0\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\RUSHIK~1\\AppData\\Local\\Temp\\pip-install-emmwr2o0\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\RUSHIK~1\AppData\Local\Temp\pip-wheel-hrhp8wpj'
       cwd: C:\Users\RUSHIK~1\AppData\Local\Temp\pip-install-emmwr2o0\turicreate\
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build\bdist.win-amd64\wheel
  running install

          ==================================================================================
          TURICREATE ERROR

          If you see this message, pip install did not find an available binary package
          for your system.

          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).

          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7

          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`

          ==================================================================================

  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\rushikesh\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RUSHIK~1\\AppData\\Local\\Temp\\pip-install-emmwr2o0\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\RUSHIK~1\\AppData\\Local\\Temp\\pip-install-emmwr2o0\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\RUSHIK~1\AppData\Local\Temp\pip-record-u2pi1c5r\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\rushikesh\anaconda3\Include\turicreate'
         cwd: C:\Users\RUSHIK~1\AppData\Local\Temp\pip-install-emmwr2o0\turicreate\
    Complete output (28 lines):
    running install

            ==================================================================================
            TURICREATE ERROR

            If you see this message, pip install did not find an available binary package
            for your system.

            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).

            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7

            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`

            ==================================================================================

    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\rushikesh\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RUSHIK~1\\AppData\\Local\\Temp\\pip-install-emmwr2o0\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\RUSHIK~1\\AppData\\Local\\Temp\\pip-install-emmwr2o0\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\RUSHIK~1\AppData\Local\Temp\pip-record-u2pi1c5r\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\rushikesh\anaconda3\Include\turicreate' Check the logs for full command output.

**Comment by TobyRoseman** [comment]
@Rushikeshdhanorkar - It looks like you are using Windows. TuriCreate does not have native support for Windows. We're already tracking native Windows support in #533. If you want to use TuriCreate on Windows you need to use WSL with Ubuntu 18.
