### ISSUE TITLE
Predicted feature named 'label' was not output by pipeline

### ISSUE THREAD

**Issue by DeveloperAbhirupa** [apple/turicreate#3255]
let modelPred = try! model2.prediction(from:MLDictionaryFeatureProvider(dictionary: res))

This is my code, where res is a [String:Double] dictionary

**Comment by TobyRoseman** [comment]
@DeveloperAbhirupa - please give us more information here.

It looks like you are trying to call a Core ML model from swift, is that correct? If so, was this Core ML model exported from a TuriCreate model? If so which toolkit was used to create the model (ex objected detection or sound classifier)?

Please also share your full stack trace.

**Comment by DeveloperAbhirupa** [comment]
@TobyRoseman 
CoreML model. Model was made in Python using TuricreateTextClassifier.

I am trying to download the model in user's device on execution of onViewDidLoad().
Model compilation on device gives no error.
Error appears when I pass a MLDictionaryFeatureProvider object for prediction.

Error type:Runtime

**Comment by TobyRoseman** [comment]
I think you should be getting more information than just `Error type:Runtime`. Can you please share the full stack trace?

Also please share the code you used to create the TuriCreate model.

**Comment by matyasbohacek** [comment]
Hi, I am getting the same error after training a **text_classifier** model with Turi Create, exporting it into `.mlmodel` type and trying to load it using **coremltools** again in Python.

My model has one feature (`text`) and then the target as `label`.

I am getting the following error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/venv/lib/python3.7/site-packages/coremltools/models/model.py", line 334, in predict
    return self.__proxy__.predict(data, useCPUOnly)
RuntimeError: {
    NSLocalizedDescription = "Predicted feature named 'label' was not output by pipeline";
}
```

**Comment by TobyRoseman** [comment]
I can reproduce this issue using the [SMSSpamCollection dataset from our user guide](https://apple.github.io/turicreate/docs/userguide/text_classifier/). After generating `model` from the example, run the following code to reproduce it:
```python
import coremltools

model.export_coreml('/tmp/my_text_classifier.mlmodel')
coreml_model = coremltools.models.MLModel('/tmp/my_text_classifier.mlmodel') 

coreml_model.predict({'test': 1})
```

**Comment by TobyRoseman** [comment]
Looking at the CoreML spec, nothing seem obviously wrong. It's a `pipelineClassifier` with three models: `dictVectorizer`, 
`featureVectorizer` and `glmClassifier`.

`spec.pipelineClassifier.pipeline.models[2].description` does indeed show an output of `label` which matches what's seen in ` spec.description`.

**Comment by TobyRoseman** [comment]
I figured out how to do this by looking at [the unit test for this functionality](https://github.com/apple/turicreate/blob/6716bbe283c6614ed7c9bcd7706a0b5a488a8c30/src/python/turicreate/test/test_text_classifier.py#L126). You need to pass in a two level dictionary. 

So if you only have one input feature called `'text'` you do **not** want to do:
`coreml_model.predict({'test': 1})` 
You want to do:
`coreml_model.predict({'text': {'test': 1}})`

I'll leave this issue open, until we have clarified the documentation.

@matyasbohacek and @DeveloperAbhirupa - let me know if you have any questions.

**Comment by matyasbohacek** [comment]
Thank you very much, this works for me!
