### ISSUE TITLE
Input image format for ObjectDetector(Darknet-YOLO)

### ISSUE THREAD

**Issue by rdv0011** [apple/turicreate#3257]
Hello.
    I have to create a new issue regarding the same subject because a previous one #3256 was closed too promptly. 
I forgot to mention that my original question was about ```model.predict(pathToTestImage)```. I have noticed that if I do not resize the input image the model returns no results at all. If the image is resized it returns expected results. The code is below:
```python
# Select one of the files from the test data
test_data =  tc.SFrame('test.sframe')
testImagePath = test_data[0]['path']
# Resize according to network input image shpae
Size = namedtuple('Size', ['width', 'height'])
inputImageSize = Size(width = 416, height = 416)
testImageOrig = Image.open(testImagePath)
resized = resizeimage.resize_thumbnail(testImageOrig, inputImageSize, Image.LINEAR)
testImageResized = Image.new('RGB', inputImageSize, (255, 255, 255))
testImageResized.paste(resized, (0, 0))

testImageResizedPath = 'tempImage.jpg'
testImageResized.save(testImageResizedPath)
# Inferring using original Darknet-YOLO model
handsModel = tc.load_model('Hands')
tcTestImageResized = tc.Image(testImageResizedPath) # WORKS
# tcTestImageResized = tc.Image(testImagePath) # RETURNS NO RESULTS
tcPredictions = handsModel.predict(tcTestImageResized)
print(tcPredictions)
```

**Comment by TobyRoseman** [comment]
@rdv0011 - in the future, feel free to reopen issues, if you think that would be better. Also when sharing code, please include all relevant import statements. I don't know what package `Image` is coming from.

At any rate it seems that you are using a package other than TuriCreate to do the image resizing. TuriCreate images have their own image resizing functionality. This resizing should happen automatically when calling `predict`. 

So either resizing is not being done automatically or the TuriCreate's resizing isn't working properly. To see which one is the case, please see if the following works:
```python
tcTestImageResized = tc.Image(testImagePath)
tcTestImageResized = tc.image_analysis.resize(tcTestImageResized, 255, 255, 3)
tcPredictions = handsModel.predict(tcTestImageResized)
print(tcPredictions)
```
Let us know if that produces results.

**Comment by rdv0011** [comment]
Hello.
  Thanks for a prompt response. Yes, the example you have provided works as expected. Please go ahead and close the issue.

**Comment by shreyajain17** [comment]
Can you tell me the platform you are using? Which python you are using and turicreate version?

**Comment by rdv0011** [comment]
> @rdv0011 - Can you tell me the platform you are using? Which python you are using and turicreate version?

Python 3.7.8
macOS 10.15.5 (19F53f)
turicreate in /Users/dmitryrybakov/.virtualenvs/ml/lib/python3.7/site-packages (6.3) The latest one.
