### ISSUE TITLE
Error installing the package

### ISSUE THREAD

**Issue by manishdm123** [apple/turicreate#3259]
Created a virtual environment with python version being 3.7 but I still get this error. Dont know how to resolve this. Kindly assist 

(turicreate) C:\Users\abc12>pip install -U turicreate
Collecting turicreate
  Using cached turicreate-6.0.tar.gz (1.9 kB)
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\abc12\Anaconda3\envs\turicreate\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\abc12\\AppData\\Local\\Temp\\pip-install-7ulemzby\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\abc12\\AppData\\Local\\Temp\\pip-install-7ulemzby\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\abc12\AppData\Local\Temp\pip-wheel-gomx8j1p'
       cwd: C:\Users\abc12\AppData\Local\Temp\pip-install-7ulemzby\turicreate\
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build\bdist.win-amd64\wheel
  running install

          ==================================================================================
          TURICREATE ERROR

          If you see this message, pip install did not find an available binary package
          for your system.

          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).

          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7

          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`

          ==================================================================================

  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\abc12\Anaconda3\envs\turicreate\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\abc12\\AppData\\Local\\Temp\\pip-install-7ulemzby\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\abc12\\AppData\\Local\\Temp\\pip-install-7ulemzby\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\abc12\AppData\Local\Temp\pip-record-1dd8sr6d\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\abc12\Anaconda3\envs\turicreate\Include\turicreate'
         cwd: C:\Users\abc12\AppData\Local\Temp\pip-install-7ulemzby\turicreate\
    Complete output (28 lines):
    running install

            ==================================================================================
            TURICREATE ERROR

            If you see this message, pip install did not find an available binary package
            for your system.

            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).

            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7

            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`

            ==================================================================================

    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\abc12\Anaconda3\envs\turicreate\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\abc12\\AppData\\Local\\Temp\\pip-install-7ulemzby\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\abc12\\AppData\\Local\\Temp\\pip-install-7ulemzby\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\abc12\AppData\Local\Temp\pip-record-1dd8sr6d\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\abc12\Anaconda3\envs\turicreate\Include\turicreate' Check the logs for full command output.

**Comment by TobyRoseman** [comment]
@manishdm123 - It looks like you are using Windows. TuriCreate does not have native support for Windows. We're already tracking native Windows support in #533. If you want to use TuriCreate on Windows you need to use WSL with Ubuntu 18.
