### ISSUE TITLE
Can I adjust the One-Shot synthetic augmentation logic?

### ISSUE THREAD

**Issue by power76** [apple/turicreate#3264]
When I use the OSOD, I noticed the synthetic augmentation logic can't be suitable for me. 
For example:
1.It resize my starter image, but I don't need it especially it adjust the starter image size to so small to recognize.
2.I don't wanna apply yaw, pitch and roll rotation.

how to solve the problem?

**Comment by TobyRoseman** [comment]
These are great feature requests. We don't have this functionality.

We are already tracking this issue in #1798. So I'll close this issue.
