### ISSUE TITLE
Using GPU with CUDA/cuDNN on WSL2

### ISSUE THREAD

**Issue by sholtrop** [apple/turicreate#3265]
I'm trying to train the [One Shot Object Detection example](https://apple.github.io/turicreate/docs/userguide/one_shot_object_detection/) using a GPU on WSL2 Ubuntu 18.04. Since #1108 CUDA now has support on WSL2. I've installed it and cuDNN and they work on other examples. I've also followed the instructions in [LinuxGPU.md](https://github.com/apple/turicreate/blob/master/LinuxGPU.md).

However, running the example does not seem to use the GPU at all, which I believe it should for this line:
```python
# Create a model. This step will take a few hours on CPU and about an hour on GPU
model = tc.one_shot_object_detector.create(starter_images, 'label')
```

Is there any way to verify whether turicreate is using the GPU? And if it actually isn't, how do I make it use my GPU on WSL2?
Thanks in advance!

**Comment by TobyRoseman** [comment]
TuriCreate uses TensorFlow for it's deep learning on non-mac operating systems.

Try running the following code to see if TensorFlow is setup to use the GPU:
```python
import tensorflow as tf
print(tf.test.is_gpu_available())')
```

If that prints `False`, figure out what version of TensorFlow you have installed. Then make sure the [right versions of CUDA and cuDNN installed for that version of TensorFlow](https://www.tensorflow.org/install/source#gpu).

**Comment by sholtrop** [comment]
Thanks for the reply!

I managed to get it working as you can see here:
![image](https://user-images.githubusercontent.com/39123298/87667288-5f722b80-c76a-11ea-9408-ac226db0f827.png)
It continually gives me the (apparently harmless) no NUMA support warning. But that's something to do with Tensorflow's logging I assume, so I'll try to fix that.

Here's what I had to do get it working on WSL:

1. Reinstalled CUDA completely following [these instructions](https://docs.nvidia.com/cuda/wsl-user-guide/index.html) with one difference. It says:
```$ apt-get install -y cuda-toolkit-11-0```
But the link you provided says that you need CUDA 10.1. Therefore I did:
```$ apt-get install -y cuda-toolkit-10-1```

2. Then I installed cuDNN as outlined [here](https://stackoverflow.com/a/36978616).

3. In [LinuxGPU.md](https://github.com/apple/turicreate/blob/master/LinuxGPU.md) it suggests you uninstall `tensorflow` and instead install `tensorflow-gpu`. I'm not very familiar with tensorflow, but this seems to not be necessary anymore, as outlined here https://www.tensorflow.org/install/gpu with the newer versions of tensorflow? Instead of doing this, I kept tensorflow installed normally. And now it correctly uses the GPU after augmenting the images.
