### ISSUE TITLE
Frequently bought together model

### ISSUE THREAD

**Issue by VinayChaudhari1996** [apple/turicreate#3271]
Turicreate Recommendation models :- 

1. Which model should I used for frequently bought together items ? 

2. Why pression and recall is so low in item similarly model for implicit data ? 

3. How to improve score of Item similarly model ? 

Thanks

**Comment by TobyRoseman** [comment]
1. Generally this is done with an Item Similarity Model. See the [user guide about choosing your Recommender System model](https://apple.github.io/turicreate/docs/userguide/recommender/choosing-a-model.html).
2. I don't know. You'll need to share more details.
3. Filtering out data from uncommon user and uncommon items is a common thing to try.

**Comment by TobyRoseman** [comment]
@VinayChaudhari1996 - I'm going to close this issue but let us know if you have any more questions.
