### ISSUE TITLE
RuntimeError: Unexpected block read failure. Bad file? while trying to create a model in Google Colab

### ISSUE THREAD

**Issue by ShreshthSaxena** [apple/turicreate#3275]
I've trained turicreate models on Colab before and they worked fine but lately getting the error message:  

>    2332         """
> -> 2333         return SFrame(_proxy=self.__proxy__.head(n))
>    2334 
>    2335     def to_dataframe(self):
> 
> turicreate/cython/cy_sframe.pyx in turicreate.cython.cy_sframe.UnitySFrameProxy.head()
> 
> turicreate/cython/cy_sframe.pyx in turicreate.cython.cy_sframe.UnitySFrameProxy.head()
> 
> **RuntimeError: Unexpected block read failure. Bad file?**

on command: model = tc.object_detector.create(train_data) 
The SFrame is saved on drive along with all the images and annotations. 
What am I doing wrong ?

**Comment by TobyRoseman** [comment]
What version of TuriCreate are you using? Is `train_data` a Pandas data frame? Also please share the full stack trace.

**Comment by ShreshthSaxena** [comment]
I'm using turicreate 5.2
> !pip install turicreate==5.2
> !pip uninstall -y mxnet
> !pip install mxnet-cu100
that's the only config that would allow me to train on Colab notebook

> train_data, test_data = data.random_split(0.95)
no train_data is split from a tc.SFrame object that I load from Gdrive. the Frame has column_types [str, tc Image, list] with over 50k images

complete log:

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-12-143a78fef7c3> in <module>()
>       1 train_data, test_data = data.random_split(0.95)
> ----> 2 model = tc.object_detector.create(train_data, batch_size = 64,max_iterations=3000)
> 
> 2 frames
> /usr/local/lib/python3.6/dist-packages/turicreate/toolkits/object_detector/object_detector.py in create(dataset, annotations, feature, model, classes, batch_size, max_iterations, verbose, **kwargs)
>     183     from ._manual_scheduler import ManualScheduler as _ManualScheduler
>     184     import mxnet as _mx
> --> 185     if len(dataset) == 0:
>     186         raise _ToolkitError('Unable to train on empty dataset')
>     187 
> 
> /usr/local/lib/python3.6/dist-packages/turicreate/data_structures/sframe.py in __len__(self)
>    2198         Returns the number of rows of the sframe.
>    2199         """
> -> 2200         return self.num_rows()
>    2201 
>    2202     def __copy__(self):
> 
> /usr/local/lib/python3.6/dist-packages/turicreate/data_structures/sframe.py in num_rows(self)
>    2266         num_columns
>    2267         """
> -> 2268         return self.__proxy__.num_rows()
>    2269 
>    2270     def num_columns(self):
> 
> turicreate/cython/cy_sframe.pyx in turicreate.cython.cy_sframe.UnitySFrameProxy.num_rows()
> 
> turicreate/cython/cy_sframe.pyx in turicreate.cython.cy_sframe.UnitySFrameProxy.num_rows()
> 
> RuntimeError: Unexpected block read failure. Bad file?

**Comment by ShreshthSaxena** [comment]
turns out it was an issue with google drive daily quota limits.
