### ISSUE TITLE
Userguide for NDArray

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#328]
- Add some info to the user guide for NDArray in SFrame

**Comment by znation** [comment]
@srikris What kind of user guide info did you have in mind? We don't really have specific documentation for other data types within SFrame/SArray; nor does ndarray really work with any of the toolkits yet. I think user guide documentation may be premature until we've plumbed it through to all possible toolkits.

**Comment by znation** [comment]
Let's address this as part of #546.
