### ISSUE TITLE
Can object detection model results vary with the same dataset?

### ISSUE THREAD

**Issue by TheGrumbler** [apple/turicreate#3293]
Hi. Can model results slightly vary over time as the environment they are implemented in updates? Last year I trained an object detection model in Turi Create. I recently re-ran the model in Turi Create on the same testing dataset and I am getting slightly different results. Not much difference, just a few percentage points. Thanks for your help.

**Comment by TobyRoseman** [comment]
@TheGrumbler - did you train a new model (i.e. call `turicreate.object_detector.create(....)`)? Or did you load the same model (i.e. call `turicreate.load_model(...)`)?

**Comment by TheGrumbler** [comment]
Hi. I loaded the same model I trained in September 2019. The images in the testing set are quite large ~ 2000 x 2000 pixels. Perhaps perhaps something has changed in the way TuriCreate resizes the images for YOLO?

**Comment by TobyRoseman** [comment]
If the model is the same and the test data is the same, the results should be the same. I assume you updated the version of TuriCreate after the model was created. Do you know which version of TuriCreate you used to create the model and which version of TuriCreate you got different behavior in?

**Comment by TheGrumbler** [comment]
Thanks for your help. As it turns out I was accidentally running the model in a different virtual environment than the one I originally tested it in. Testing it in the original Venv produced identical results.
