### ISSUE TITLE
module 'turicreate' has no attribute 'item_similarity_recommender'

### ISSUE THREAD

**Issue by parilon** [apple/turicreate#3294]
I have a problem, when I run my code in python, this attributeError is shown to me "module 'turicreate' has no attribute 'item_similarity_recommender'"

My python version: 3.7 My Windows: 7
Please help me. Thanks

my Code:

def model(train, name, user_id, item_id, target, users_to_recommend, n_rec, n_display):
    if name == 'cosine':
        model = tc.item_similarity_recommender.create(train, 
                                                    user_id=user_id, 
                                                    item_id=item_id, 
                                                    target=target, 
                                                    similarity_type='cosine')
    recom = model.recommend(users=users_to_recommend, k=n_rec)
    recom.print_rows(n_display)
    return model
name = 'cosine'
target = 'CountOfVisit'
cos = model(train, name, user_id, item_id, target, users_to_recommend, n_rec, n_display)

**Comment by TobyRoseman** [comment]
We don't have native Window support, see #533.

If you want to use TuriCreate on Windows, you need to use Window 10 with WSL (Ubuntu 18).

Closing this issue as a duplicate.
