### ISSUE TITLE
What dataset is used for pre-training the Turi Create TinyYOLO model?

### ISSUE THREAD

**Issue by TheGrumbler** [apple/turicreate#3297]
Hi. What dataset is used for pre-training the TinyYOLO model used in Turi Create? Is it ImageNet as described in the paper by Redmon et. al (https://arxiv.org/pdf/1506.02640.pdf)?

**Comment by TobyRoseman** [comment]
We didn't train the TinyYolo model. Take a look at the [How it works](https://apple.github.io/turicreate/docs/userguide/object_detection/how-it-works.html) section of our user guide for object detection, specifically the **YOLO** Section. Based on information from [the project page](https://pjreddie.com/darknet/yolo/)  for Darknet, it looks like they used the COCO dataset.
