### ISSUE TITLE
Implementation of image resizing and non-max suppression in the Turi Create object detection pipeline.

### ISSUE THREAD

**Issue by TheGrumbler** [apple/turicreate#3298]
In the paper by Redmon et. al. (https://arxiv.org/pdf/1506.02640.pdf), they describe the object detection pipeline as image resizing -> convolutional network -> non-max suppression (Figure 1). Are the resizing and non-max suppression algorithms intrinsic to the YOLO model from Redmon and colleagues (https://pjreddie.com/darknet/), or does Turi Create have to implement its own resizing and non-max suppression algorithms?

**Comment by TobyRoseman** [comment]
TuriCreate does the resizing and the non-maximal suppression. This is not part of the YOLO model.
