### ISSUE TITLE
Deployment: How to fill author, license, etc.

### ISSUE THREAD

**Issue by johnlev** [apple/turicreate#33]
The documentation that I have seen doesn't describe a way to put the author, description, license, input descriptions, and so on into the model before/while exporting. Is this feature not yet included?

**Comment by srikris** [comment]
Right! I think we don't have that exposed in TC yet. But it's super simple to do with coremltools. See [this example](https://apple.github.io/coremltools/generated/coremltools.models.MLModel.html) here.

I'm wondering if we should even expose this API via turicreate or if its easy enough to do via coremltools. We could also add the example code directly into the user guide.

**Comment by johnlev** [comment]
Ah, thanks

**Comment by pcmanik** [comment]
I think it's better to expose it via Turi Create since it's one step less to produce model with details :)
