### ISSUE TITLE
unable to install turi create 

### ISSUE THREAD

**Issue by lARSHADl** [apple/turicreate#3302]
using pop os with clean installation of anaconda from offical website,
pip version is pip-20.2.2,
please advise.

Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ahmed/anaconda3/envs/virtual/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-54rtgb_d/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-54rtgb_d/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ps0ms3jx
       cwd: /tmp/pip-install-54rtgb_d/turicreate/
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build/bdist.linux-x86_64/wheel
  running install
  
  
  
          ==================================================================================
          TURICREATE ERROR
  
          If you see this message, pip install did not find an available binary package
          for your system.
  
          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).
  
          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7
  
  
          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`
  
          ==================================================================================
  
  
  
  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
DEPRECATION: Could not build wheels for turicreate which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ahmed/anaconda3/envs/virtual/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-54rtgb_d/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-54rtgb_d/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sfyfxea3/install-record.txt --single-version-externally-managed --compile --install-headers /home/ahmed/anaconda3/envs/virtual/include/python3.8/turicreate
         cwd: /tmp/pip-install-54rtgb_d/turicreate/
    Complete output (28 lines):
    running install
    
    
    
            ==================================================================================
            TURICREATE ERROR
    
            If you see this message, pip install did not find an available binary package
            for your system.
    
            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).
    
            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7
    
    
            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`
    
            ==================================================================================
    
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ahmed/anaconda3/envs/virtual/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-54rtgb_d/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-54rtgb_d/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sfyfxea3/install-record.txt --single-version-externally-managed --compile --install-headers /home/ahmed/anaconda3/envs/virtual/include/python3.8/turicreate Check the logs for full command output.

**Comment by TobyRoseman** [comment]
It looks like you're using Python 3.8. TuriCreate does not yet support Python 3.8. We already tracking this issue in #3099.

We should support Python 3.8 soon. Until then, please use Python 3.7.

Closing this issue as a duplicate.

**Comment by lARSHADl** [comment]
I forgot to mention that i created a new virtual environment using anaconda with python version 3.7 , but still it throws the same error !

-------- Original Message --------

**Comment by TobyRoseman** [comment]
> I forgot to mention that i created a new virtual environment using anaconda with python version 3.7 , but still it throws the same error !
> […](#)

Please post the full output of trying to install in a 3.7 virtual environment. As well as the output of `pip -V`.

It's almost certainly still using Python 3.8 despite being in a 3.7 virtual environment. You probably need to change your `PATH` environment variable.

**Comment by lARSHADl** [comment]
Please close the issue got it solved ,

Thanks for the help

-Arshad

-------- Original Message --------

**Comment by mygithub-rahul** [comment]
How did you resolved your issue. I am facing same issue as yours

**Comment by TobyRoseman** [comment]
@mygithub-rahul - please ensure that your version of Python and your operating system are supported (see the error message). If both are supported, please open a new issue with more details.
