### ISSUE TITLE
Issue installing GraphLab (Problem setting up virtual environment)

### ISSUE THREAD

**Issue by amoebacodes** [apple/turicreate#3306]
[launcher-install-log.txt](https://github.com/apple/turicreate/files/5144667/launcher-install-log.txt)

Here is a record of my terminal page. I was installing using the Launcher when I encountered this error.
I also tried using pip, but at this step (conda create -n gl-env python=2.7 anaconda=4.0.0), anaconda=4.0.0 is not recognized and there is an error message:
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - anaconda=4.0.0

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

I have anaconda already installed and the version is v2020.02.

Thank you so much for you help!

**Comment by amoebacodes** [comment]
I'm sorry the issue is resolved by following this YouTube video. https://www.youtube.com/watch?v=aXec_IqKA74
Leaving it here in case any other beginner runs into this issue.
One thing to note though: instead of conda install ipython-notebook, please enter conda install notebook. Otherwise, there will be an error message.

**Comment by TobyRoseman** [comment]
This issue seems to be related to GraphLab Create. However this is the repository for TuriCreate not GraphLab Create.
