### ISSUE TITLE
Update Installation Instruction

### ISSUE THREAD

**Issue by amoebacodes** [apple/turicreate#3307]
Dear developers,

Thank you so much for making this amazing module for python and making it available to academic use. During the installation process, I have noticed a mistake on the installation page. I think it may be due to documentation changes on Jupyter's end because in this tutorial video, the original command line worked. https://www.youtube.com/watch?v=aXec_IqKA74 
During the last step of installation, instead of conda install ipython-notebook, it should be conda install notebook. An error message pops up if the former is entered as of 08/28/2020.

Thank you for considering making this correction!

**Comment by amoebacodes** [comment]
Actually, I am running into an issue, and would appreciate any help. Installation seems to be complete with the code I mentioned above. I have included a copy of my terminal window down below. However, when I open Jupyter, it cannot connect to kernel. This is not the issue with my browser or anti-virus software because I have tried the same thing in a different environment in anaconda, and Jupyter worked normally. Because it is only in gl-env virtual environment that I encounter this odd issue, I assume that there is a problem with correct installation of Jupyter.

Here is what shows up in my terminal.

(gl-env) yiqingmelodywang@Yiqings-MacBook-Pro ~ % conda install ipython-notebook 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - ipython-notebook

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


(gl-env) yiqingmelodywang@Yiqings-MacBook-Pro ~ % conda install notebook       
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/yiqingmelodywang/opt/anaconda3/envs/gl-env

  added / updated specs:
    - notebook


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    appnope-0.1.0              |   py27hb466136_0           8 KB
    attrs-20.1.0               |             py_0          47 KB
    backports.shutil_get_terminal_size-1.0.0|           py27_2           9 KB
    backports_abc-0.5          |             py_1          10 KB
    bleach-3.1.5               |             py_0         116 KB
    configparser-4.0.2         |           py27_0          42 KB
    decorator-4.4.2            |             py_0          14 KB
    entrypoints-0.3            |           py27_0          12 KB
    enum34-1.1.6               |           py27_1          57 KB
    functools32-3.2.3.2        |           py27_1          23 KB
    futures-3.3.0              |           py27_0          28 KB
    ipaddress-1.0.23           |             py_0          22 KB
    ipykernel-4.10.0           |           py27_0         152 KB
    ipython-5.8.0              |           py27_0         933 KB
    ipython_genutils-0.2.0     |           py27_0          40 KB
    jinja2-2.11.2              |             py_0         103 KB
    jsonschema-3.0.2           |           py27_0          90 KB
    jupyter_client-5.3.4       |           py27_0         140 KB
    jupyter_core-4.6.1         |           py27_0          70 KB
    libsodium-1.0.18           |       h1de35cc_0         236 KB
    markupsafe-1.1.1           |   py27h1de35cc_0          27 KB
    mistune-0.8.4              |   py27h1de35cc_0          55 KB
    nbconvert-5.6.1            |           py27_0         460 KB
    nbformat-4.4.0             |           py27_0         130 KB
    notebook-5.7.10            |           py27_0         4.2 MB
    packaging-20.4             |             py_0          36 KB
    pandoc-2.10.1              |                0        13.8 MB
    pandocfilters-1.4.2        |           py27_1          13 KB
    pathlib2-2.3.5             |           py27_0          37 KB
    pexpect-4.7.0              |           py27_0          78 KB
    pickleshare-0.7.5          |           py27_0          13 KB
    prometheus_client-0.8.0    |             py_0          47 KB
    prompt_toolkit-1.0.15      |   py27h4a7b9c2_0         337 KB
    ptyprocess-0.6.0           |           py27_0          22 KB
    pyparsing-2.4.7            |             py_0          65 KB
    pyrsistent-0.15.6          |   py27h1de35cc_0          89 KB
    pyzmq-18.1.0               |   py27h0a44026_0         383 KB
    scandir-1.10.0             |   py27h1de35cc_0          30 KB
    send2trash-1.5.0           |           py27_0          16 KB
    simplegeneric-0.8.1        |           py27_2           9 KB
    singledispatch-3.4.0.3     |   py27he22c18d_0          15 KB
    six-1.15.0                 |             py_0          13 KB
    terminado-0.8.3            |           py27_0          25 KB
    tornado-5.1.1              |   py27h1de35cc_0         613 KB
    traitlets-4.3.3            |           py27_0         136 KB
    wcwidth-0.2.5              |             py_0          29 KB
    webencodings-0.5.1         |           py27_1          20 KB
    zeromq-4.3.2               |       hb1e8313_2         426 KB
    ------------------------------------------------------------
                                           Total:        23.2 MB

The following NEW packages will be INSTALLED:

  appnope            pkgs/main/osx-64::appnope-0.1.0-py27hb466136_0
  attrs              pkgs/main/noarch::attrs-20.1.0-py_0
  backports          pkgs/main/noarch::backports-1.0-py_2
  backports.shutil_~ pkgs/main/osx-64::backports.shutil_get_terminal_size-1.0.0-py27_2
  backports_abc      pkgs/main/noarch::backports_abc-0.5-py_1
  bleach             pkgs/main/noarch::bleach-3.1.5-py_0
  configparser       pkgs/main/osx-64::configparser-4.0.2-py27_0
  decorator          pkgs/main/noarch::decorator-4.4.2-py_0
  defusedxml         pkgs/main/noarch::defusedxml-0.6.0-py_0
  entrypoints        pkgs/main/osx-64::entrypoints-0.3-py27_0
  enum34             pkgs/main/osx-64::enum34-1.1.6-py27_1
  functools32        pkgs/main/osx-64::functools32-3.2.3.2-py27_1
  futures            pkgs/main/osx-64::futures-3.3.0-py27_0
  ipaddress          pkgs/main/noarch::ipaddress-1.0.23-py_0
  ipykernel          pkgs/main/osx-64::ipykernel-4.10.0-py27_0
  ipython            pkgs/main/osx-64::ipython-5.8.0-py27_0
  ipython_genutils   pkgs/main/osx-64::ipython_genutils-0.2.0-py27_0
  jinja2             pkgs/main/noarch::jinja2-2.11.2-py_0
  jsonschema         pkgs/main/osx-64::jsonschema-3.0.2-py27_0
  jupyter_client     pkgs/main/osx-64::jupyter_client-5.3.4-py27_0
  jupyter_core       pkgs/main/osx-64::jupyter_core-4.6.1-py27_0
  libsodium          pkgs/main/osx-64::libsodium-1.0.18-h1de35cc_0
  markupsafe         pkgs/main/osx-64::markupsafe-1.1.1-py27h1de35cc_0
  mistune            pkgs/main/osx-64::mistune-0.8.4-py27h1de35cc_0
  nbconvert          pkgs/main/osx-64::nbconvert-5.6.1-py27_0
  nbformat           pkgs/main/osx-64::nbformat-4.4.0-py27_0
  notebook           pkgs/main/osx-64::notebook-5.7.10-py27_0
  packaging          pkgs/main/noarch::packaging-20.4-py_0
  pandoc             pkgs/main/osx-64::pandoc-2.10.1-0
  pandocfilters      pkgs/main/osx-64::pandocfilters-1.4.2-py27_1
  pathlib2           pkgs/main/osx-64::pathlib2-2.3.5-py27_0
  pexpect            pkgs/main/osx-64::pexpect-4.7.0-py27_0
  pickleshare        pkgs/main/osx-64::pickleshare-0.7.5-py27_0
  prometheus_client  pkgs/main/noarch::prometheus_client-0.8.0-py_0
  prompt_toolkit     pkgs/main/osx-64::prompt_toolkit-1.0.15-py27h4a7b9c2_0
  ptyprocess         pkgs/main/osx-64::ptyprocess-0.6.0-py27_0
  pygments           pkgs/main/noarch::pygments-2.5.2-py_0
  pyparsing          pkgs/main/noarch::pyparsing-2.4.7-py_0
  pyrsistent         pkgs/main/osx-64::pyrsistent-0.15.6-py27h1de35cc_0
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.1-py_0
  pyzmq              pkgs/main/osx-64::pyzmq-18.1.0-py27h0a44026_0
  scandir            pkgs/main/osx-64::scandir-1.10.0-py27h1de35cc_0
  send2trash         pkgs/main/osx-64::send2trash-1.5.0-py27_0
  simplegeneric      pkgs/main/osx-64::simplegeneric-0.8.1-py27_2
  singledispatch     pkgs/main/osx-64::singledispatch-3.4.0.3-py27he22c18d_0
  six                pkgs/main/noarch::six-1.15.0-py_0
  terminado          pkgs/main/osx-64::terminado-0.8.3-py27_0
  testpath           pkgs/main/noarch::testpath-0.4.4-py_0
  tornado            pkgs/main/osx-64::tornado-5.1.1-py27h1de35cc_0
  traitlets          pkgs/main/osx-64::traitlets-4.3.3-py27_0
  wcwidth            pkgs/main/noarch::wcwidth-0.2.5-py_0
  webencodings       pkgs/main/osx-64::webencodings-0.5.1-py27_1
  zeromq             pkgs/main/osx-64::zeromq-4.3.2-hb1e8313_2


Proceed ([y]/n)? y


Downloading and Extracting Packages
zeromq-4.3.2         | 426 KB    | ##################################### | 100% 
prompt_toolkit-1.0.1 | 337 KB    | ##################################### | 100% 
send2trash-1.5.0     | 16 KB     | ##################################### | 100% 
appnope-0.1.0        | 8 KB      | ##################################### | 100% 
pandocfilters-1.4.2  | 13 KB     | ##################################### | 100% 
ptyprocess-0.6.0     | 22 KB     | ##################################### | 100% 
backports.shutil_get | 9 KB      | ##################################### | 100% 
pyparsing-2.4.7      | 65 KB     | ##################################### | 100% 
attrs-20.1.0         | 47 KB     | ##################################### | 100% 
pyrsistent-0.15.6    | 89 KB     | ##################################### | 100% 
terminado-0.8.3      | 25 KB     | ##################################### | 100% 
ipaddress-1.0.23     | 22 KB     | ##################################### | 100% 
markupsafe-1.1.1     | 27 KB     | ##################################### | 100% 
wcwidth-0.2.5        | 29 KB     | ##################################### | 100% 
ipython-5.8.0        | 933 KB    | ##################################### | 100% 
singledispatch-3.4.0 | 15 KB     | ##################################### | 100% 
functools32-3.2.3.2  | 23 KB     | ##################################### | 100% 
futures-3.3.0        | 28 KB     | ##################################### | 100% 
pathlib2-2.3.5       | 37 KB     | ##################################### | 100% 
jupyter_client-5.3.4 | 140 KB    | ##################################### | 100% 
mistune-0.8.4        | 55 KB     | ##################################### | 100% 
backports_abc-0.5    | 10 KB     | ##################################### | 100% 
jinja2-2.11.2        | 103 KB    | ##################################### | 100% 
configparser-4.0.2   | 42 KB     | ##################################### | 100% 
nbformat-4.4.0       | 130 KB    | ##################################### | 100% 
scandir-1.10.0       | 30 KB     | ##################################### | 100% 
ipykernel-4.10.0     | 152 KB    | ##################################### | 100% 
notebook-5.7.10      | 4.2 MB    | ##################################### | 100% 
nbconvert-5.6.1      | 460 KB    | ##################################### | 100% 
pandoc-2.10.1        | 13.8 MB   | ##################################### | 100% 
pexpect-4.7.0        | 78 KB     | ##################################### | 100% 
simplegeneric-0.8.1  | 9 KB      | ##################################### | 100% 
traitlets-4.3.3      | 136 KB    | ##################################### | 100% 
jsonschema-3.0.2     | 90 KB     | ##################################### | 100% 
webencodings-0.5.1   | 20 KB     | ##################################### | 100% 
pickleshare-0.7.5    | 13 KB     | ##################################### | 100% 
entrypoints-0.3      | 12 KB     | ##################################### | 100% 
enum34-1.1.6         | 57 KB     | ##################################### | 100% 
tornado-5.1.1        | 613 KB    | ##################################### | 100% 
libsodium-1.0.18     | 236 KB    | ##################################### | 100% 
bleach-3.1.5         | 116 KB    | ##################################### | 100% 
jupyter_core-4.6.1   | 70 KB     | ##################################### | 100% 
prometheus_client-0. | 47 KB     | ##################################### | 100% 
pyzmq-18.1.0         | 383 KB    | ##################################### | 100% 
packaging-20.4       | 36 KB     | ##################################### | 100% 
ipython_genutils-0.2 | 40 KB     | ##################################### | 100% 
six-1.15.0           | 13 KB     | ##################################### | 100% 
decorator-4.4.2      | 14 KB     | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

**Comment by amoebacodes** [comment]
Now I have tried following the instructions over here
https://jupyter.org/install
https://ipython.readthedocs.io/en/latest/install/kernel_install.html
and instead of not being able to connect, the connected label flashes and still no output can be computed. Please help. I am losing my mind. Thank you SO much!

**Comment by amoebacodes** [comment]
I ran into some issues with the installation process, so please don't use the command I provided. I have resolved the issue by installing Jupyter Notebook in Anaconda Navigator within the gl-env environment. However, please still review the instruction page as more people can benefit from it. Thank you so much!

**Comment by TobyRoseman** [comment]
@amoebacodes - This is the repository for TuriCreate not GraphLab Create; the video link you gave is for installing GraphLab Create. It sounds Jupyter Notebook or Anaconda were the causes of your installation issues. Can you clarify what, if any changes, you would like to [the TuriCreate installation instructions](https://github.com/apple/turicreate#installation)?
