### ISSUE TITLE
Getting Error while fetching CSV file from local

### ISSUE THREAD

**Issue by ankur290109** [apple/turicreate#3312]
I have installed turicreate without error by following steps from "https://medium.com/@pam.thumbela/installing-turicreate-on-windows-10-534e147a4792" 
Also I have Python 3.7 installed in my system.
Also I have followed below steps to fetch CSV file which is stored in my local (C:\Users\Abhishek\people-example.csv) :-

1. import turicreate as ts
2. from turicreate import SFrame
3. sf = ts.SFrame('people-example.csv')

I am getting below error while fetching csv file from my local:-

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/venv/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1093             with cython_context():
-> 1094                 errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
   1095         except Exception as e:

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_csvs()

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_csvs()

**OSError: No files corresponding to the specified path (/home/ankur290199/venv/people-example.csv).**

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
~/venv/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in __init__(self, data, format, _proxy)
    825                     url = data
--> 826                     tmpsf = SFrame.read_csv(url, delimiter=",", header=True)
    827                     self.__proxy__ = tmpsf.__proxy__

~/venv/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in read_csv(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1577             _only_raw_string_substitutions=_only_raw_string_substitutions,
-> 1578             **kwargs
   1579         )[0]

~/venv/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1003                     false_values=false_values,
-> 1004                     _only_raw_string_substitutions=_only_raw_string_substitutions,
   1005                 )

~/venv/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in read_csv(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1577             _only_raw_string_substitutions=_only_raw_string_substitutions,
-> 1578             **kwargs
   1579         )[0]

~/venv/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1093             with cython_context():
-> 1094                 errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
   1095         except Exception as e:

~/venv/lib/python3.6/site-packages/turicreate/_cython/context.py in __exit__(self, exc_type, exc_value, traceback)
     49                 # To hide cython trace, we re-raise from here
---> 50                 raise exc_type(exc_value)
     51             else:

OSError: No files corresponding to the specified path (/home/ankur290199/venv/people-example.csv).

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-16-5a7378e17abf> in <module>
----> 1 sf = ts.SFrame('people-example.csv')

~/venv/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in __init__(self, data, format, _proxy)
    836                     pass
    837                 else:
--> 838                     raise ValueError("Unknown input type: " + format)
    839 
    840     @staticmethod

~/venv/lib/python3.6/site-packages/turicreate/_cython/context.py in __exit__(self, exc_type, exc_value, traceback)
     48             if not self.show_cython_trace:
     49                 # To hide cython trace, we re-raise from here
---> 50                 raise exc_type(exc_value)
     51             else:
     52                 # To show the full trace, we do nothing and let exception propagate

OSError: No files corresponding to the specified path (/home/ankur290199/venv/people-example.csv).

**Comment by TobyRoseman** [comment]
It looks like it's can't find your file. In order for `tc.SFrame('people-example.csv')` to work, you need to have a file called `people-example.csv` in your current directory. You must also have read permission for that file. 

Based on your output it looks like your current directory is `/home/ankur290199/venv/`. Based on your description, it sounds like the file you're trying to load is in another directory. The simplest way to solve this problem is probably just to pass the full file path to `tc.SFrame`.

I'm going to close this issue, but let me know if you have more questions.
