### ISSUE TITLE
Which cuda version supports turicreate

### ISSUE THREAD

**Issue by wassafshahzad** [apple/turicreate#3340]
Currently we are using turicreate ffor training an object detection model However we have Cuda10 which to my understanding is not supported by turicreate I wanted to ask which version of Cuda should i install

**Comment by TobyRoseman** [comment]
TuriCreate does not use CUDA directly. Depending on your operating system, TuriCreate may uses TensorFlow which uses CUDA. If you're running a recent version of macOS, you don't need CUDA to get GPU acceleration with TuriCreate.

If you're running Linux, check which version of TensorFlow you have installed. Then check [this GPU compatibility table](https://www.tensorflow.org/install/source#gpu) to determine the correct version of CUDA and cuDNN.

I'm going to close this issues, but let me know if you have any more questions.
