### ISSUE TITLE
unable to install turicreate in big sur

### ISSUE THREAD

**Issue by jeffehobbs** [apple/turicreate#3352]
Big Sur has python 3.8.2 and turicreate kicks an error immediately on pip install: 

`(venv) jeff@macbook-pro turicreate % pip install -U turicreate
Collecting turicreate
  Using cached turicreate-6.4.tar.gz (1.9 kB)
Using legacy 'setup.py install' for turicreate, since package 'wheel' is not installed.
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/jeff/Desktop/turicreate/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_l/ly_4c0ws1fvfkgs7ch8tshzc0000gn/T/pip-install-5vkauy_l/turicreate/setup.py'"'"'; __file__='"'"'/private/var/folders/_l/ly_4c0ws1fvfkgs7ch8tshzc0000gn/T/pip-install-5vkauy_l/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/_l/ly_4c0ws1fvfkgs7ch8tshzc0000gn/T/pip-record-390tkzpk/install-record.txt --single-version-externally-managed --compile --install-headers /Users/jeff/Desktop/turicreate/venv/include/site/python3.8/turicreate
         cwd: /private/var/folders/_l/ly_4c0ws1fvfkgs7ch8tshzc0000gn/T/pip-install-5vkauy_l/turicreate/
    Complete output (28 lines):
    running install
    
    
    
            ==================================================================================
            TURICREATE ERROR
    
            If you see this message, pip install did not find an available binary package
            for your system.
    
            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).
    
            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7
                * 3.8
    
            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`
    
            ==================================================================================
    
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/jeff/Desktop/turicreate/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_l/ly_4c0ws1fvfkgs7ch8tshzc0000gn/T/pip-install-5vkauy_l/turicreate/setup.py'"'"'; __file__='"'"'/private/var/folders/_l/ly_4c0ws1fvfkgs7ch8tshzc0000gn/T/pip-install-5vkauy_l/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/_l/ly_4c0ws1fvfkgs7ch8tshzc0000gn/T/pip-record-390tkzpk/install-record.txt --single-version-externally-managed --compile --install-headers /Users/jeff/Desktop/turicreate/venv/include/site/python3.8/turicreate Check the logs for full command output.`

**Comment by TobyRoseman** [comment]
This is a Python packaging issue: pypa/packaging#318. This issue should be resolved soon; there is [a pull request](https://github.com/pypa/packaging/pull/319) to resolve the issue.

Let me know if you have any questions. I'll leave this issue open until the Python packaging issue is resolved.

**Comment by timmead** [comment]
I believe this has now been fixed in `pypa`.

**Comment by TobyRoseman** [comment]
Thanks @timmead. You're right this is now fixed.
