### ISSUE TITLE
Alot of trouble with installing turicreate/graphlab for python

### ISSUE THREAD

**Issue by Hapemo** [apple/turicreate#3354]
[
![Capture](https://user-images.githubusercontent.com/45931978/95929243-188de380-0df6-11eb-9c50-0776564b9f84.PNG)
](url)
I have trouble using turi create on python. I tried using anaconda and jupyter but both i have met great trouble. I would like to search for a way to use turi create on normal python on my computer, using text editor 'atom', please help me out with this

**Comment by TobyRoseman** [comment]
This is the repository for TuriCreate not GraphLab Create. Please use TuriCreate.

It looks you have Windows as your operating system. TuriCreate does not have native Windows support. (We're already tracking this issue in #533).

If you are using Windows 10, you can use TuriCreate with WSL. I recommend using Ubuntu 18 with WSL.

I'm going to close this issue but let me know if you have any further questions.
