### ISSUE TITLE
Question about tc.text_classifier.create() 

### ISSUE THREAD

**Issue by simokhwang** [apple/turicreate#3357]
I am following a tutorial about iOS Natual Language Processing. https://www.raywenderlich.com/5213-natural-language-processing-on-ios-with-turi-create

 In the step of  tc.text_classifier.create, I did

` model = tc.text_classifier.create(data, 'tag', features=['body'])`

But I get an error ` RuntimeError: Target column has missing value.                    Please use dropna() to drop rows with missing target values.`

Can you please tell me how to find out which rows has missing target values? and How to use dropnam to drop them?

```
>>> model = tc.text_classifier.create(data, 'tag', features=['body'])
Traceback (most recent call last):
  File "/Users/sacheu/Documents/GitHub/test/KeatsOrYeats/venv/lib/python3.8/site-packages/turicreate/extensions.py", line 290, in __run_class_function
    ret = self._tkclass.call_function(fnname, argument_dict)
  File "cy_model.pyx", line 35, in turicreate._cython.cy_model.UnityModel.call_function
  File "cy_model.pyx", line 40, in turicreate._cython.cy_model.UnityModel.call_function
RuntimeError: Target column has missing value.                    Please use dropna() to drop rows with missing target values.

```

**Comment by TobyRoseman** [comment]
It looks like your SFrame is called `data` and your target column name is `tag`. Assuming the `tag` column is of type string, you can view the rows that are missing a tag value by doing:
`data[data['tag'] == None]`

To remove these rows, do:
`data = data.dropna(columns=['tag'])`

I'm going to close this issue, but let me know if you have any more questions.
