### ISSUE TITLE
Encrypting drawing classifier model gives compiler error:  Key length 32 does not match encryption block size 16

### ISSUE THREAD

**Issue by hipwelljo** [apple/turicreate#3358]
I created a drawing classifier model, added it to Xcode, selected it then clicked Utilities > Create Encryption Key. I then set the encrypt compiler flag in Build Phases > Copy Sources:
`--encrypt "$SRCROOT/MyApp/Helpers/Symbols.mlmodelkey"`

Now when I try to run the app a compile time error occurs:

> coremlc: error: compiler error:  Key length 32 does not match encryption block size 16

I tried this with Xcode 12.1 and 12.2 RC. I'm not sure if this is something specific about the model, or possibly an issue in Turi Create or Xcode for example. Curious if it works for y'all? Thanks!

**Comment by TobyRoseman** [comment]
I'm curious if this works without the drawing classifier model. For testing purposes, please remove the `.mlmodel` file from your project and comment out the code that uses it. Does the project compile then?

**Comment by hipwelljo** [comment]
Yes, if I delete the `.mlmodel` and comment out its use, it compiles and runs. If I put the model back and uncomment, it compiles and runs. If I create the encryption key it saves an `.mlmodelkey` to disk, it compiles and runs. But if I actually encrypt the model by setting the compiler flag, I get this error.

But I tried an image classification model I created a while ago with Create ML and get the same error, so it seems it's not a Turi Create issue.

**Comment by TobyRoseman** [comment]
I agree this does not seem like a TuriCreate issue. It seems like an issue with how Xcode encrypts mlmodel files. Are you following [these instructions](https://developer.apple.com/documentation/coreml/core_ml_api/encrypting_a_model_in_your_app)?

**Comment by hipwelljo** [comment]
Yes. I have filed a bug report for Xcode: FB8889866 :)

**Comment by hipwelljo** [comment]
It appears this is resolved in Xcode 12.3 / Big Sur :)
