### ISSUE TITLE
turicreate.object_detector.create error: Killed

### ISSUE THREAD

**Issue by waheed0332** [apple/turicreate#3359]
**Python:** 3.6.9
**TuriCreate:** 6.4.1
**Tensorflow:** 2.3.1
**CUDA:** 10.1
**cuDNN:** 7.6.5
**OS:** Ubuntu 18.04
**Ram:** 32gb

**How many images:** 436578
**How many bounding boxes:** approx 704865 in the entire dataset
**How many classes:** 2
**What are the sizes of these images:** 650x650 each image
**Size of the dataset:** 56.5gb

My entire ran filled and process just killed. It seems like we have a memory leak somewhere.

**Comment by TobyRoseman** [comment]
Please share all relevant code (i.e. creating the SFrame, calling `tc.object_detector.create`, etc).

Please share the entire output.

About how long does it take to get killed?

**Comment by TobyRoseman** [comment]
I'm going to close this issue. Feel free to reopen with the requested information.
