### ISSUE TITLE
Gaussian Mixture Models

### ISSUE THREAD

**Issue by IriscShih** [apple/turicreate#3362]
Hello, 

Are there any chance to see the implementations of a distribution-based model, like Gaussian Mixture Models, in the clustering group? https://scikit-learn.org/stable/modules/mixture.html#mixture

**Comment by TobyRoseman** [comment]
Thanks @IriscShih for the feature suggestion, but I don't think this is something we're going to implement. However I would welcome any community contribution for this feature.
