### ISSUE TITLE
Recommendation: evaluate AUC

### ISSUE THREAD

**Issue by pdavis156879** [apple/turicreate#3365]
Several (implicit/explicit) recommendation libraries include the computation of AUC as an evaluation metric. Turicreate doesn't. Is there any reason for this?

In addition, any tips on how to compute AUC using Turicreate's recommendation engine would be greatly appreciated.

**Comment by TobyRoseman** [comment]
@pdavis156879 - is there a reason you can not use [turicreate.evaluation.auc](https://apple.github.io/turicreate/docs/api/generated/turicreate.evaluation.auc.html#turicreate.evaluation.auc)?
