### ISSUE TITLE
Mutex destroy error 16 Aborted (core dumped)

### ISSUE THREAD

**Issue by MaddyThakker** [apple/turicreate#3370]
While training a Turicreate Object detection model, I get this error. 

```
Read 9928 images in 5.00053 secs	speed: 1985.39 file/sec
Using 'image' as feature column
Using 'annotations' as annotations column
Downloading https://docs-assets.developer.apple.com/turicreate/models/darknet.params
Download completed: /var/tmp/model_cache/darknet.params
Downloading https://docs-assets.developer.apple.com/turicreate/models/darknet.mlmodel
Download completed: /var/tmp/model_cache/darknet.mlmodel
Mutex destroy error 16
Aborted (core dumped)

```

**Comment by TobyRoseman** [comment]
Please give us more information. What operating system are you using? What is your data like (number of images, number of classes, number of bounding boxes)? Is the dataset publicly available? Did this issue happen only once or does it happen ever time you try?

**Comment by MaddyThakker** [comment]
I am using Amazon EC2 instance (p3.2xlarge) with Ubuntu 18.04.  (16 GB gpu, 64 GB ram, 200 GB SSD Volume)

These are the training set statistics - 

- 19,014 images

- ~45,000 bounding box

- 107 classes

The dataset is not publicly available. 

It is a recurring issue.

**Comment by TobyRoseman** [comment]
Thanks for the dataset information. I have a few more questions.

Does anything else (such as a stack trace) get printed out? What version of TensorFlow is installed in your environment? Does the RAM get entirely filled up before this happens?

**Comment by MaddyThakker** [comment]
Increasing the RAM did resolve the issue. Thanks!
