### ISSUE TITLE
New Build?

### ISSUE THREAD

**Issue by rainhut** [apple/turicreate#3373]
When do we get a new build? Style Transfer needs updating.

**Comment by TobyRoseman** [comment]
Hi @rainhut - 

We don't typically discuss our release plans.

Is there something specific you would like to see with Style Transfer? Just saying that it needs updating is not particularly helpful. Also we already have [a number of open issue related to Style Transfer](https://github.com/apple/turicreate/issues?q=is%3Aopen+is%3Aissue+label%3A%22style+transfer%22).

I'm going to close this issue. Feel free to create new issues for specific Style Transfer concerns which aren't already covered by existing issues.
