### ISSUE TITLE
> 50 GB memory footprint while training style transfer model

### ISSUE THREAD

**Issue by RahulBhalley** [apple/turicreate#3377]
With the batch size set equals to 1 and training images being 6 GB (Validation images from COCO dataset), the training kept increasing the memory footprint throughout the training process. I mean why is the training memory footprint not constant but that high? I think this is a bug because it looks like TuriCreate uses ResNet16 (very small) and VGG-19 (for style and content losses). Please fix this! I am unable to train my models.

**Comment by TobyRoseman** [comment]
Why are you using a batch size of 1? That seem very small to me.

What operating system are you using? How many training iterations does it take to reach 50GB?

**Comment by rahulbhalley** [comment]
Batch size equal to 1 is default in [turicreate.style_transfer.create](https://apple.github.io/turicreate/docs/api/generated/turicreate.style_transfer.create.html#turicreate.style_transfer.create) method. If I set batch size equal to 32 then iteration steps are reduced. 

I'm using MacBook Pro 2016 (256 GB storage capacity) with macOS version 11.1. It took a little more than 50000 iterations to consume about 53 GB of memory.

Please let me know if you need more information. Thanks.

**Comment by rahulbhalley** [comment]
@TobyRoseman On my system the memory consumption increases by some 10s of MBs at each iterations and reaches the amount of storage left of my MBP and then the program gets killed. It is as if some data is being accumulated at each iteration. 

Whereas on Google Colaboratory the memory consumption is constant over iterations even with 6GB dataset. But I'm not able to use GPU on Colaboratory hence need to do training right on my MBP because it can use the 
intel Iris GPU.

**Comment by TobyRoseman** [comment]
Thanks for the information @rahulbhalley. I have a few more questions:
1 - Are you using the most recent version of TuriCreate?
2 - What version of Python are you using?
3 - How exactly are you using the 6 GB of COCO images? Are you passing that into `tc.syte_transfer.create` as `style_dataset` or `content_dataset`?

**Comment by rahulbhalley** [comment]
Thanks for giving attention to my old 2016 MBP machine @TobyRoseman. 😅

1. turicreate==6.4.1
2. Python 3.8.5
3. The 6 GB COCO images dataset is passed as `content_dataset` to `tc.style_transfer.create` and `style_dataset` has 2 images (currently, I want to test the quality of stylized images that the underlying algorithm can produce).

**Comment by TobyRoseman** [comment]
6 GB of content images seems like an awful lot. For our [style transfer example](https://apple.github.io/turicreate/docs/userguide/style_transfer/) we only use 1,000 content images and we get good results. I'd recommend randomly sampling a few thousand images from your current content set and try to train a model with just that.

**Comment by rahulbhalley** [comment]
Okay I’ll try that. But other frameworks (say, PyTorch) consume constant memory during training regardless of the size of dataset. I don’t understand why memory keeps increasing continuously over time until program crashes here in Turicreate. 🤔 This looks like a bug.

**Comment by TobyRoseman** [comment]
I agree. It sounds like a bug.

**Comment by rahulbhalley** [comment]
Moving on to other alternatives for creating my model. Thanks for the discussion though.

**Comment by TobyRoseman** [comment]
Let's keep this open until it is resolved.

**Comment by RahulBhalley** [comment]
@apple forgot about TuriCreate. Damn.
