### ISSUE TITLE
Error on drawing ROC curve in turicreate

### ISSUE THREAD

**Issue by youenimmay** [apple/turicreate#3379]
Hello, I have previously tried the both of the following scripts to draw the ROC curve:

plt.scatter(eval['roc_curve']['fpr'], eval['roc_curve']['tpr']) ; which returned:

--> 'builtin_function_or_method' object is not subscriptable

Another suggestion:
temp1 = eval['roc_curve']['fpr']
temp2 = eval['roc_curve']['tpr']
plt.scatter(temp1, temp2) ; also returned the same error:

--> 'builtin_function_or_method' object is not subscriptable

Any help on the issue is much appreciated, Thanks!

N.B.: I have attached the sample code as print screens in a word document below

[ROC curve error.docx](https://github.com/apple/turicreate/files/5846063/ROC.curve.error.docx)

**Comment by TobyRoseman** [comment]
`eval` is a Python keyword. You don't have a variable named `eval`.

I'm guessing you probably want to change this line:
`sentiment_model.evaluate(test_data, metric = 'roc_curve')`
to
`eval = sentiment_model.evaluate(test_data, metric = 'roc_curve')`

**Comment by yasntrk** [comment]
Hi did u find a solution?
