### ISSUE TITLE
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed

### ISSUE THREAD

**Issue by addriumruss** [apple/turicreate#3383]
ubuntu 16.04, virtualenv, python3.7
Following the instructions of gpu, after installed the turicreate, execute these two cmds:
(venv) pip uninstall -y tensorflow
(venv) pip install tensorflow-gpu

Then it shows:
Requirement already satisfied: zipp>=0.5 in ./lib/python3.7/site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard~=2.4->tensorflow-gpu) (3.4.0)
Installing collected packages: tensorboard-plugin-wit, numpy, grpcio, tensorflow-estimator, tensorboard, gast, flatbuffers, astunparse, tensorflow-gpu
  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.5
    Uninstalling numpy-1.18.5:
      Successfully uninstalled numpy-1.18.5
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.35.0
    Uninstalling grpcio-1.35.0:
      Successfully uninstalled grpcio-1.35.0
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.0.1
    Uninstalling tensorflow-estimator-2.0.1:
      Successfully uninstalled tensorflow-estimator-2.0.1
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.0.2
    Uninstalling tensorboard-2.0.2:
      Successfully uninstalled tensorboard-2.0.2
  Attempting uninstall: gast
    Found existing installation: gast 0.2.2
    Uninstalling gast-0.2.2:
      Successfully uninstalled gast-0.2.2
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.**
turicreate 6.4.1 requires tensorflow<2.1.0,>=2.0.0, which is not installed.
Successfully installed astunparse-1.6.3 flatbuffers-1.12 gast-0.3.3 grpcio-1.32.0 numpy-1.19.5 tensorboard-2.4.1 tensorboard-plugin-wit-1.8.0 tensorflow-estimator-2.4.0 tensorflow-gpu-2.4.1

Is this installation OK?

**Comment by TobyRoseman** [comment]
Yes, this should be fine. Let us know if you run into any issues.

**Comment by addriumruss** [comment]
@TobyRoseman  Thanks~

**Comment by AngelaJimenez** [comment]
:( send help

**Comment by eshtaranyal** [comment]
Hi I am still getting the same errors which results in ZSH:abort when I try model.fit in python and in Jupiter notebook I get the error kernel died. I am not sure if they both are correlated but I have been trying to resolve this issue taking hints from various forums but to no use. Kindly help. I was earlier working on windows and switched to Mac M1.. its becoming difficult everyday to handle all the errors. Waiting for a solution.

**Comment by TobyRoseman** [comment]
@eshtaranyal - please create a new GitHub issue. Please include as much information as possible: the complete stack trace, the code you are running, your version of Python, the version of your OS, etc.

**Comment by ankitthakur007** [comment]
This error is popping up when I am installing the packages into the notebook on colab.
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
```
Anyone tell me why this is popping up?

**Comment by garretthoyos** [comment]
I'm getting the same thing over and over, not sure why

**Comment by TobyRoseman** [comment]
See my [original response](https://github.com/apple/turicreate/issues/3383#issuecomment-770087188) for this issue: usually these error messages are nothing to worry about.

**Comment by ManjarAnsari** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.26.0 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.

getting this issue

**Comment by vymn** [comment]
I'm facing the same problem here with google colab, did you get the answer?

**Comment by ahmadalsharef994** [comment]
@vymn 
Same in Colab, did you find a solution???

**Comment by vidushi-chouksey** [comment]
> @eshtaranyal - please create a new GitHub issue. Please include as much information as possible: the complete stack trace, the code you are running, your version of Python, the version of your OS, etc.

Hi @TobyRoseman,

Please find the information below;

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
caip-notebooks-serverextension 1.0.0 requires google-cloud-bigquery-storage, which is not installed.
transformers 4.5.1 requires tokenizers<0.11,>=0.10.1, but you have tokenizers 0.9.4 which is incompatible.
pdpbox 0.2.1 requires matplotlib==3.1.1, but you have matplotlib 3.4.3 which is incompatible.
matrixprofile 1.1.10 requires protobuf==3.11.2, but you have protobuf 3.18.0 which is incompatible.
imbalanced-learn 0.8.0 requires scikit-learn>=0.24, but you have scikit-learn 0.23.2 which is incompatible.
easyocr 1.4.1 requires Pillow<8.3.0, but you have pillow 8.3.2 which is incompatible.
Successfully installed ConfigSpace-0.4.19 Pillow-8.3.2 autogluon-0.3.1 autogluon-contrib-nlp-0.0.1b20210201 autogluon.core-0.3.1 autogluon.extra-0.3.1 autogluon.features-0.3.1 autogluon.mxnet-0.3.1 autogluon.tabular-0.3.1 autogluon.text-0.3.1 autogluon.vision-0.3.1 autograd-1.3 bcrypt-3.2.0 catboost-0.25.1 contextvars-2.4 d8-0.0.2.post0 fastai-2.5.2 fastdownload-0.0.5 immutables-0.16 liac-arff-2.5.0 minio-7.1.0 openml-0.12.2 paramiko-2.7.2 pynacl-1.4.0 sacrebleu-2.0.0 scipy-1.6.3 sentencepiece-0.1.95 timm-clean-0.4.12 tokenizers-0.9.4 xmltodict-0.12.0

**Comment by 0xJepsen** [comment]
Im facing the same issue, when i run my deploy program. I run into ```ModuleNotFoundError: No module named 'cytoolz'```
then when i run ```pip install cytoolz``` i get ```Installing collected packages: cytoolz
    Running setup.py install for cytoolz ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
eth-account 0.5.6 requires bitarray<1.3.0,>=1.2.1, which is not installed.
eth-abi 2.1.1 requires parsimonious<0.9.0,>=0.8.0, which is not installed.
Successfully installed cytoolz```
which doesn't resolve the issue.

**Comment by XredaX** [comment]
**Before you install your extension, just follow the prompts**

   pip install h5py
   pip install typing-extensions
   pip install wheel

**and then install your extension**

**Comment by LalithaNalluri** [comment]
> **Before you install your extension, just follow the prompts**
> 
> pip install h5py pip install typing-extensions pip install wheel
> 
> **and then install your extension**

This worked for me Thanks

**Comment by emperkim0107** [comment]
> 
Same in Colab, did you find a solution???

**Comment by Itsgiulpi95** [comment]
I'm trying to install tensorflow==2.5.0 (DLC version==2.2) but I got the error:

**_ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imageio 2.16.0 requires numpy>=1.20.0, but you have numpy 1.19.5 which is incompatible.
black 22.1.0 requires typing-extensions>=3.10.0.0; python_version < "3.10", but you have typing-extensions 3.7.4.3 which is incompatible._**

Then I try to import deeplabcut, but I got the issue:

**_ModuleNotFoundError: No module named 'numpy.typing'_**

Anyone can help?

**Comment by sachtuli** [comment]
> **Before you install your extension, just follow the prompts**
> 
> pip install h5py pip install typing-extensions pip install wheel
> 
> **and then install your extension**

This works.

**Comment by lukas102000** [comment]
I can't install  chatterbot in windows 10,
someone help me?

**Comment by bushra-31** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
anaconda-project 0.9.1 requires ruamel-yaml, which is not installed.
pandas-profiling 3.1.0 requires markupsafe~=2.0.1, but you have markupsafe 1.1.1 which is incompatible.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
anaconda-project 0.9.1 requires ruamel-yaml, which is not installed.
sphinx 4.0.1 requires MarkupSafe<2.0, but you have markupsafe 2.0.1 which is incompatible.




i am getting this error when i try to install. what can be done?

**Comment by abraar0305** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-gpu 2.8.0 requires tensorboard<2.9,>=2.8, but you have tensorboard 1.15.0 which is incompatible.

I try reinstalling TensorFlow using the previous version, but I get these issues, anyone help me please

**Comment by devCharaf** [comment]
> 

The installation is Ok. You just have to restart the runtime!
<img width="689" alt="Screen Shot 2022-04-16 at 12 02 44 PM" src="https://user-images.githubusercontent.com/50533653/163682434-5f98def9-58f0-4249-982a-b0a2d22fa6b9.png">

**Comment by donmonc** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fuzzy-c-means 1.6.4 requires pydantic<2.0.0,>=1.9.0, but you have pydantic 1.8.2 which is incompatible.

How do I resolve this issue?

**Comment by evanwcarson** [comment]
I received this error when installing compare50 on Ubuntu 22.04 LTS. How do I correct the error? 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
anaconda-project 0.9.1 requires ruamel-yaml, which is not installed.
sphinx 4.0.1 requires Jinja2<3.0,>=2.3, but you have jinja2 3.1.2 which is incompatible.
sphinx 4.0.1 requires MarkupSafe<2.0, but you have markupsafe 2.1.1 which is incompatible.

**Comment by costamauricio1** [comment]
> **Before you install your extension, just follow the prompts**
> 
> pip install h5py pip install typing-extensions pip install wheel
> 
> **and then install your extension**

Thank u bro!!!! Amazing!

**Comment by Pranav-Coding** [comment]
@[XredaX](https://github.com/XredaX) Thank You bro.
i installed some extensions and then got the error msg
**" pip's dependency resolver does not currently take into account all the packages that are installed "**
and then my flask was refusing to run with the error
**" zsh: illegal hardware instruction python flask run "**
```shell
pip3 install h5py pip install typing-extensions pip install wheel 
```

**Comment by DevrPatel** [comment]
> **Before you install your extension, just follow the prompts**
> 
> pip install h5py pip install typing-extensions pip install wheel
> 
> **and then install your extension**

This worked for me to install apache airflow.
Thank You.

**Comment by ryan20-hue** [comment]
> > **Before you install your extension, just follow the prompts**
> > pip install h5py pip install typing-extensions pip install wheel
> > **and then install your extension**
> 
> This worked for me to install apache airflow. Thank You.

bro how did you installed these extensions?

**Comment by ZahraMESBAHI** [comment]
> **Before you install your extension, just follow the prompts**
> 
> pip install h5py pip install typing-extensions pip install wheel
> 
> **and then install your extension**

This was helpful and worked with me thanks a lot!

**Comment by HL7988** [comment]
> Hi I am still getting the same errors which results in ZSH:abort when I try model.fit in python and in Jupiter notebook I get the error kernel died. I am not sure if they both are correlated but I have been trying to resolve this issue taking hints from various forums but to no use. Kindly help. I was earlier working on windows and switched to Mac M1.. its becoming difficult everyday to handle all the errors. Waiting for a solution.

I am getting the same error and now everything messed up. I think its the issue of tensorflow version and some cuda or cudnn, before the kerel dies gpu usage reach to maximum.

**Comment by PrincessBeni** [comment]
> **Before you install your extension, just follow the prompts**
> 
> pip install h5py pip install typing-extensions pip install wheel
> 
> **and then install your extension**

This works. Thanks a lot.

**Comment by abreham-g** [comment]
Good solution 
**pip install h5py
pip install typing-extensions
pip install wheel**

**Comment by yash966** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.1.5 requires typing-extensions<4.2.0,>=3.7.4.1; python_version < "3.8", but you have typing-extensions 4.3.0 which is incompatible.
spacy 3.4.2 requires typing-extensions<4.2.0,>=3.7.4; python_version < "3.8", but you have typing-extensions 4.3.0 which is incompatible.
ModuleNotFoundError: No module named 'PythonMagick'

need help
not able to install pythonmagick

**Comment by akshaysanil** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tabula-py 2.4.0 requires distro, which is not installed.
seaborn 0.11.2 requires scipy>=1.0, which is not installed.
scikit-learn 1.1.2 requires scipy>=1.3.2, which is not installed.
scikit-image 0.19.3 requires scipy>=1.4.1, which is not installed.
quandl 3.7.0 requires more-itertools, which is not installed.
pipenv 2022.11.30 requires virtualenv, which is not installed.
pandas 1.4.3 requires pytz>=2020.1, which is not installed.
lesscpy 0.15.0 requires ply, which is not installed.
jupyterthemes 0.20.0 requires ipython>=5.4.1, which is not installed.
jupyterthemes 0.20.0 requires jupyter-core, which is not installed.
jupyterthemes 0.20.0 requires notebook>=5.6.0, which is not installed.
easyocr 1.6.2 requires opencv-python-headless<=4.5.4.60, which is not installed.
easyocr 1.6.2 requires PyYAML, which is not installed.
easyocr 1.6.2 requires scipy, which is not installed.
easyocr 1.6.2 requires torch, which is not installed.
easyocr 1.6.2 requires torchvision>=0.5, which is not installed.


when iam started to use mediapipe it comes how do  i solve this

**Comment by dmddmd** [comment]
I also get this error. T tried pip install h5py,pip install typing-extensions,pip install wheel. That does not help. I am working with the anaconda prompt.

**Comment by Ramanmagar** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.

tensorflow-gpu 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.1 which is incompatible.

Successfully installed protobuf-3.20.1


please help me

**Comment by AnudeepBoo** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fuzzy-c-means 1.6.3 requires numpy<2.0.0,>=1.21.1, but you have numpy 1.20.3 which is incompatible.
cmdstanpy 1.0.8 requires numpy>=1.21, but you have numpy 1.20.3 which is incompatible.

I am getting the above error what should i do?

**Comment by chandbano** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.12.0 requires google-auth-oauthlib<0.5,>=0.4.1, but you have google-auth-oauthlib 1.0.0 which is incompatible.
tensorflow-intel 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.2 which is incompatible.
tf-nightly-intel 2.13.0.dev20230409 requires numpy<1.24,>=1.22, but you have numpy 1.24.2 which is incompatible.

**Comment by jnsbrdbr** [comment]
just restart RUNTIME

**Comment by cactusglobal** [comment]
Worked for me.
pip install h5py
pip install typing-extensions
pip install wheel

**Comment by AlexTNewell** [comment]
I'm having similar issue.... pip's dependency resolver does not.... due to.....the following dependency conflicts....

botocore 1.29.127 requires urllib3<1.27,>=1.25.4, but you have urllib3 2.0.2 which is incompatible

**Comment by umarless** [comment]
https://github.com/apple/turicreate/issues/3383#issuecomment-1010006358

Thanks, It works.

**Comment by sridharrajaram** [comment]
Hi I got an error like
```
 pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.

databricks-sql-connector 2.4.0 requires numpy==1.23.4; python_version >= "3.8", but you have numpy 1.24.3 which is incompatible.

databricks-sql-connector 2.4.0 requires pandas<2.0.0,>=1.3.0, but you have pandas 2.0.1 which is incompatible.

databricks-sql-cli 0.1.4 requires pandas==1.3.4, but you have pandas 2.0.1 which is incompatible
```

how to resolve this issue

**Comment by ghost** [comment]
pip install --upgrade accelerate
 or
pip install accelerate==<version>
or
Check for other conflicting packages: There might be other packages installed that are causing conflicts with the desired versions. You can use the command pip list to check the versions of all installed packages and identify any other conflicting dependencies. Then, you can try updating or uninstalling those packages to resolve the conflicts.

**Comment by ravirajbasis** [comment]
Hi

Facing a similar issue:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlink 6.1.0 requires urllib3<3,>=1.26.0, but you have urllib3 1.25.11 which is incompatible.

Thanks
rraj

**Comment by phillipsd** [comment]
All I did was run  

pip-review -av
twice 
.... seems to fix most of the issues I have had ... YMMV

**Comment by M-Tnhn-Kr** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
awscli 2.9.19 requires urllib3<=1.27,>=1.25.4, but you have urllib3 2.0.7 which is incompatible.

```
pip install h5py
pip install typing-extensions
pip install wheel

```
this didnt solve my problem

help... -_-

**Comment by wangyiting99** [comment]
> > **Before you install your extension, just follow the prompts**
> > pip install h5py pip install typing-extensions pip install wheel
> > **and then install your extension**
> 
> This works.

Agree. That's working.

**Comment by Timmyraysmom** [comment]
Pip install h5py worked thanks
