### ISSUE TITLE
datasets for examples not installed!

### ISSUE THREAD

**Issue by projectsUW** [apple/turicreate#3386]
I want to use the examples, but the data is apparently not installed... I search for the data but it is not in my MAC:
```
import turicreate as tc
songs = tc.SFrame.read_csv("millionsong/song_data.csv")
```

How may I install the data?

**Comment by TobyRoseman** [comment]
Information about that dataset can be found [here](http://millionsongdataset.com/pages/getting-dataset/). Unfortunately, I'm not seeing a direct link to that specific file.

We are already tracking missing dataset in #97. So I'm going to close this issue as a duplicate.
