### ISSUE TITLE
Export model as TensorFlow SavedModel format

### ISSUE THREAD

**Issue by xpegenaute** [apple/turicreate#3388]
Hi,

first of all thanks for you work and effort with TuriCreate.

As I already saw, you are using tensorflow for some tasks, therefore, I was wondering: is it possible to export the model as [SavedModel format](https://www.tensorflow.org/guide/saved_model) ?

Regards,
Xavi

**Comment by TobyRoseman** [comment]
You are correct many of our models use TensorFlow when running on Linux or on older versions of macOS. However TuriCreate does not have the ability to export to any TensorFlow format. That being said, it's certainly something that would be possible. Is there a particular model type that you are interested in exporting to TensorFlow?

We are already tracking this issue in #2930. So I'm going to close this issue as a duplicate.
