### ISSUE TITLE
Hanging while loading turicreate.visualization.scatter

### ISSUE THREAD

**Issue by pratyush-17** [apple/turicreate#3390]
I'm experiencing the  hang in scatter plot on a jupyter notebook.I'm trying to scatter plot  with 21K data points on x and y
it took several minutes for the plot to display. Any suggestions?

**Comment by TobyRoseman** [comment]
21k is a lot of data points to try and visualize. With that many data points, I don't think the scatter plot would be very helpful. Most of the image would likely just be one solid block of points.

I recommend random sampling. Then visualizing the random sample.
