### ISSUE TITLE
Problem to install Turicreate on Mac Python 3.7

### ISSUE THREAD

**Issue by xinqianx** [apple/turicreate#3396]
I tried several days to install Turicreate on my Mac but still cannot figure out what was wrong with it. I reviewed people's previous post but still failed after trying both terminal and Anaconda. Please help!

I followed the instruction of building a virtual environment and install turicreate with code:
(venv) pip install -U turicreate

**Below is my error notification from terminal:**
Collecting turicreate
  Using cached turicreate-6.4.tar.gz (1.9 kB)
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/xiangxinqian/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y0/qw4q3vbn4251v4gkk6zn0g5h0000gn/T/pip-install-29igyna9/turicreate_ce6365b56ee249b1ac1ed1a0c0d3b679/setup.py'"'"'; __file__='"'"'/private/var/folders/y0/qw4q3vbn4251v4gkk6zn0g5h0000gn/T/pip-install-29igyna9/turicreate_ce6365b56ee249b1ac1ed1a0c0d3b679/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/y0/qw4q3vbn4251v4gkk6zn0g5h0000gn/T/pip-wheel-84obh3ks
       cwd: /private/var/folders/y0/qw4q3vbn4251v4gkk6zn0g5h0000gn/T/pip-install-29igyna9/turicreate_ce6365b56ee249b1ac1ed1a0c0d3b679/
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build/bdist.macosx-10.9-x86_64/wheel
  running install
  
  
  
          ==================================================================================
          TURICREATE ERROR
  
          If you see this message, pip install did not find an available binary package
          for your system.
  
          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).
  
          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7
              * 3.8
  
          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`
  
          ==================================================================================
  
  
  
  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/xiangxinqian/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y0/qw4q3vbn4251v4gkk6zn0g5h0000gn/T/pip-install-29igyna9/turicreate_ce6365b56ee249b1ac1ed1a0c0d3b679/setup.py'"'"'; __file__='"'"'/private/var/folders/y0/qw4q3vbn4251v4gkk6zn0g5h0000gn/T/pip-install-29igyna9/turicreate_ce6365b56ee249b1ac1ed1a0c0d3b679/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y0/qw4q3vbn4251v4gkk6zn0g5h0000gn/T/pip-record-ulbosukr/install-record.txt --single-version-externally-managed --compile --install-headers /Users/xiangxinqian/venv/include/site/python3.7/turicreate
         cwd: /private/var/folders/y0/qw4q3vbn4251v4gkk6zn0g5h0000gn/T/pip-install-29igyna9/turicreate_ce6365b56ee249b1ac1ed1a0c0d3b679/
    Complete output (28 lines):
    running install
    
    
    
            ==================================================================================
            TURICREATE ERROR
    
            If you see this message, pip install did not find an available binary package
            for your system.
    
            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).
    
            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7
                * 3.8
    
            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`
    
            ==================================================================================
    
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/xiangxinqian/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y0/qw4q3vbn4251v4gkk6zn0g5h0000gn/T/pip-install-29igyna9/turicreate_ce6365b56ee249b1ac1ed1a0c0d3b679/setup.py'"'"'; __file__='"'"'/private/var/folders/y0/qw4q3vbn4251v4gkk6zn0g5h0000gn/T/pip-install-29igyna9/turicreate_ce6365b56ee249b1ac1ed1a0c0d3b679/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y0/qw4q3vbn4251v4gkk6zn0g5h0000gn/T/pip-record-ulbosukr/install-record.txt --single-version-externally-managed --compile --install-headers /Users/xiangxinqian/venv/include/site/python3.7/turicreate Check the logs for full command output.

**Comment by TobyRoseman** [comment]
What operating system are you using? Also have you tried running `pip install -U pip` before installing?

**Comment by xinqianx** [comment]
I am using Mac OS 10.11.6. Is this the reason for the issue? I tried running pip install -U pip before installing. It showed the requirement satisfied but still failed installing turicreate. 

(base) XiangXinqians-MacBook-Pro:~ xiangxinqian$ pip install virtualenv
Requirement already satisfied: virtualenv in ./opt/anaconda3/lib/python3.8/site-packages (20.4.3)

**Comment by TobyRoseman** [comment]
Yes, that is the issue. As noted in the [Supported Platform Section](https://github.com/apple/turicreate#supported-platforms) of our top level README, we support macOS 10.12+.
