### ISSUE TITLE
How can i install turicreate with conda ? 

### ISSUE THREAD

**Issue by berkakyildiz** [apple/turicreate#3397]
Hello.I did not install turicreate with conda.it asks for a product key when installing, but I don't know how to get the product key.Can you help me how can I install without a product key?

**Comment by TobyRoseman** [comment]
Product keys don't exist in TuriCreate. I think you are trying to install GraphLabCreate.

To install TuriCreate run: `pip install turicreate`. 

I'm going to to close this issue but let me know if you have other questions.

**Comment by berkakyildiz** [comment]
Yes I also install graphlab create but I did not. İf you know that install
tips are you share of me ?

**Comment by TobyRoseman** [comment]
GraphLab Create has long been deprecated. Use TuriCreate instead.
