### ISSUE TITLE
Export recommender model to CoreML

### ISSUE THREAD

**Issue by insidegui** [apple/turicreate#34]
I would love to be able to use the recommender model on my app without having to send information to a server to be processed. Would it be possible to support exporting the recommender model to CoreML?

**Comment by srikris** [comment]
Thanks for trying our Turi Create. Yes, unfortunately, the recommender isn't easily exportable to Core ML yet. Can you share with us what recommender you have trained? 

There may be some options for you to get around this issue temporarily?

**Comment by insidegui** [comment]
I have an app where users can create things by using items. I have a lot of data about which users have used which items and I want to be able to recommend new items to users based on the items they used previously.

**Comment by HelloWorldYyx** [comment]
I am also very urgent that this problem can be solved!thank

**Comment by igor9silva** [comment]
+1 for exporting recommender models into a CoreML Models.

**Comment by srikris** [comment]
We are looking into this. Stay tuned.

**Comment by Padalingam** [comment]
i am also looking forward...

**Comment by JamesDale** [comment]
@srikris @znation Hey guys, I'm using the item_similarity recommender. Would there be a CoreML workaround for this?

Cheers.

**Comment by afranklin** [comment]
We're continuing to investigate a solution with a high priority. Thanks for your patience - stay tuned.

**Comment by tjkev** [comment]
Hey @afranklin, there is something news about "Export recommender model to CoreML" ?

**Comment by znation** [comment]
@tjkev It's being actively worked on; we'll update this thread when something is available to try. Thanks for your interest!

**Comment by afranklin** [comment]
**Great news: Recommender model export is available in the 5.0 beta.** For more details, see https://github.com/apple/turicreate/releases/tag/5.0b1

**Comment by insidegui** [comment]
That's amazing! Thanks @afranklin

**Comment by igor9silva** [comment]
Wonderful news!
