### ISSUE TITLE
One-class classification is not currently supported.

### ISSUE THREAD

**Issue by MrUbun2** [apple/turicreate#3406]
I've been working on a project that recognizes different coins on linux, and I am currently on macOS Big Sur pondering on why I get a "One-class classification is not currently supported." error. My code to make the SFrame is:

```
import turicreate as turi

url = "testdataset/"
data = turi.image_analysis.load_images(url)
data["coinType"] = data["path"].apply(lambda path: "Quarter" if "quarter" in path else "Nothing")
data.save("test.sframe")
```

I have the SFrame creator and the model in the same script, is this my problem?
Edit: I put the model in a different script and it gave me the same error. I am using python 3.8.1

**Comment by RahulBhalley** [comment]
IDK about your problem but, TuriCreate team, there's no concept of one-class classification. It's either of binary/multiple/multi class classifications.

**Comment by TobyRoseman** [comment]
@RahulBhalley is correct; TuriCreate doesn't support one-class classification.

@MrUbun2 - please verify that you actually have two classes in your dataset. Run: `print(data["coinType"].value_counts())`. Does that show two classes?

**Comment by MrUbun2** [comment]
I just copied the example code and edited it to make it work, it's fine now.
