### ISSUE TITLE
Early stopping Turicreate Classifier

### ISSUE THREAD

**Issue by cotraak** [apple/turicreate#3407]
Hello everyone, I was wondering if there is a way to use EarlyStopping while training the classifier. I looked into the docs, but didn't find any. Thanks in advance!

**Comment by TobyRoseman** [comment]
TuriCreate does not have this functionality.

Most of our toolkits do have a `max_iteration` parameter. So you could call the `create` function several times with an increasing number of iterations. That's a possible workaround to get the functionality you want.

I'm going to close this issue, but let me know if you have any more questions.
