### ISSUE TITLE
Turicreate Activity Model occasionally becomes non-responsive

### ISSUE THREAD

**Issue by valnenov** [apple/turicreate#3408]
I have created several activity models using Turicreate v6.4.1. They all use data merged from 4 Adafruit Feather nRF52840 Sense boards attached to the thighs and shins of a dancer and transmitted to my app via Bluetooth.  I use only the 3-Axis accelerometers. Sampling rate 10Hz, predictionWIndow 2 sec. My models generate predictions of dance moves and range from 4 to 14 different categories of moves. The models are incorporated in an iOS app. My problem is that the models only work occasionally as intended. Most of the time the predictions just stall at some category from the very start and become non-responsive. It appears that this category is the last one in my list of categories ("running" in the sample bellow). I have no idea why this is happening. Any suggestions will be greatly appreciated. I can provide any additional information and code samples if this helps.

<img width="627" alt="Screen Shot 2021-06-08 at 6 12 05 PM" src="https://user-images.githubusercontent.com/8172216/121277286-24e31700-c885-11eb-82c1-1f2913891d6c.png">

Here is the training of one of the simplest models:
<img width="502" alt="Screen Shot 2021-06-08 at 6 18 44 PM" src="https://user-images.githubusercontent.com/8172216/121277754-219c5b00-c886-11eb-84a2-da1392be789f.png">

**Comment by TobyRoseman** [comment]
> Most of the time the predictions just stall at some category from the very start and become non-responsive.

Can you explain a bit more what is happening here. Is it always returning the same activity? Or is it non-responsive in the sense that the program hangs and you never get any predictions?

If you can share your code and data, I'll take a look.

**Comment by valnenov** [comment]
Thanks for your reply Toby!

I figured it out. It was my mistake. I was running 7 of my models in parallel with the same raw data input but was using just one stateOutput variable for all of them,  which apparently was causing all models to return different activities but each model was stuck on the first activity it returned and would not change it over time despite me doing different dance steps. 

Once I changed my code so that each model has its own stateOutput variable (see attached swift file)  all models became responsive and it was interesting to see in real time how their predictions differ depending one model features and the level of lowPsss filtering of the data that I have applied during training and testing of the models. 

I have attached the relevant part of my code with a data sample for a 7 categories model. Please take a look if you have a few minutes. This is my very first ML project using Turicreate  so I may be doing some really stupid things. Any comments and suggestions are greatly appreciated.

And one clarifying question: What is the purpose of the stateInLength variable and how do I chose the correct value for it considering my data sets?

static let stateInLength = 400 // Val added

Val

[BGdanceData7Categories.zip](https://github.com/apple/turicreate/files/6626897/BGdanceData7Categories.zip)

[MLManagerDuplicate.swift.zip](https://github.com/apple/turicreate/files/6626895/MLManagerDuplicate.swift.zip)

**Comment by valnenov** [comment]
And here is some additional information to give you a better perspective of what I am trying to accomplish. A sample of some of the dance steps that I am trying to classify/predict. My Python file for making the model. A photo of my sensors setup.

[BGdance.py.zip](https://github.com/apple/turicreate/files/6627356/BGdance.py.zip)

https://youtu.be/xenjhHHBZkA

[Val with two sets of 4 leg sensors.HEIC.zip](https://github.com/apple/turicreate/files/6627359/Val.with.two.sets.of.4.leg.sensors.HEIC.zip)

**Comment by TobyRoseman** [comment]
I'm glad you figured out the issue.

> And one clarifying question: What is the purpose of the stateInLength variable and how do I chose the correct value for it considering my data sets?
>
> static let stateInLength = 400 // Val added

Yeah, this is a bit opaque. It's basically the amount of state the model hold between predictions. A smaller number means the model hold less state. A larger number mean the model holds more state.

This is an example of a hyper parameter that can be tuned. There is no way to know the best value without experimenting. Build several different models with different values for this hyper parameter. Then evaluate each using a test set. 

Since you figure out the problem, I'm going to close this issue, but let me know if you have any more questions.
