### ISSUE TITLE
Activity classifier crashes on google colab

### ISSUE THREAD

**Issue by kkiermasz** [apple/turicreate#3409]
Hi!
I'm working with turicreate on google colab. When I call `activity_classifier.create` the session crashes for "unknown reason".
`app.log` does not contain any related info.
[Here](https://gist.github.com/kkiermasz/a0fa085be24ef27437579fdb8804b31e) you can find exported jupyter notebook.

Any help will be appreciated!

**Comment by TobyRoseman** [comment]
I don't see any issue with your code. Without logs or a stack trace this is going to be very difficult to debug. This could be either a TuriCreate issue or a colab issue.

I recommend you export your jupyter notebook as a python script. Then run it locally on a small subset of your data. Let me know if that works.

**Comment by kkiermasz** [comment]
Unfortunately, google colab is my only option. I'm on apple silicone : /
