### ISSUE TITLE
Any future updates for turicreate

### ISSUE THREAD

**Issue by saddif** [apple/turicreate#3413]
Hi guys,

Hope you are well, just wondering if there will be an update to turicreate - more specifically will you be fixing the style transfer issues with accessing the parameters i have raised previously.

Is there anything I can do to try to access them without an update from your end? 

I have tried to use createML but it is not as good for style transfer.

thanks

saddif

**Comment by TobyRoseman** [comment]
I've responded in #3341 with a work around. In the future, please do not create new issues for something which already has an issue.
