### ISSUE TITLE
Can't create a one_shot_object_detector model with custom backgrounds

### ISSUE THREAD

**Issue by litvakle** [apple/turicreate#3415]
Hi all

I am trying to create a one_shot_object_detector model with custom backgrounds.

import turicreate as tc
from turicreate import SArray
starter_images = tc.SFrame({'image':[tc.Image('image.png')], 'label':['test']})
my_backgrounds = tc.SArray('./Backgrounds/')
model = tc.one_shot_object_detector.create(starter_images, 'label', backgrounds=my_backgrounds)

And I got this:

> RuntimeError                              Traceback (most recent call last)
> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/turicreate/extensions.py in __run_class_function(self, fnname, args, kwargs)
>     289         try:
> --> 290             ret = self._tkclass.call_function(fnname, argument_dict)
>     291         except RuntimeError as exc:
> 
> cy_model.pyx in turicreate._cython.cy_model.UnityModel.call_function()
> 
> cy_model.pyx in turicreate._cython.cy_model.UnityModel.call_function()
> 
> RuntimeError: Invalid type conversion
> 
> During handling of the above exception, another exception occurred:
> 
> ToolkitError                              Traceback (most recent call last)
> <ipython-input-129-7a150155be25> in <module>
> ----> 1 model = tc.one_shot_object_detector.create(starter_images, 'label', backgrounds=my_backgrounds)
> 
> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/turicreate/toolkits/one_shot_object_detector/one_shot_object_detector.py in create(data, target, backgrounds, batch_size, max_iterations, verbose)
>      69         raise _ToolkitError("'data' can not be an empty SFrame")
>      70 
> ---> 71     augmented_data = _preview_synthetic_training_data(data, target, backgrounds)
>      72 
>      73     model = _tc.object_detector.create(
> 
> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/turicreate/toolkits/one_shot_object_detector/util/_augmentation.py in preview_synthetic_training_data(data, target, backgrounds, verbose, **kwargs)
>      67 
>      68     one_shot_model = _extensions.one_shot_object_detector()
> ---> 69     augmented_data = one_shot_model.augment(
>      70         dataset_to_augment,
>      71         image_column_name,
> 
> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/turicreate/extensions.py in <lambda>(*args, **kwargs)
>     303         elif name in self._functions:
>     304             # is it a function?
> --> 305             ret = lambda *args, **kwargs: self.__run_class_function(name, args, kwargs)
>     306             ret.__doc__ = (
>     307                 "Name: " + name + "\nParameters: " + str(self._functions[name]) + "\n"
> 
> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/turicreate/extensions.py in __run_class_function(self, fnname, args, kwargs)
>     291         except RuntimeError as exc:
>     292             # Expose C++ exceptions using ToolkitError.
> --> 293             raise _ToolkitError(exc)
>     294         ret = _wrap_function_return(ret)
>     295         return ret
> 
> ToolkitError: Invalid type conversion

If I don't pass my_backgrounds to the create function, everything is OK.

What did I do wrong?

**Comment by TobyRoseman** [comment]
I think it may be a problem with one of your images. Before calling ` tc.one_shot_object_detector.create`, please run a `my_backgrounds.materialize()`. Do you get a similar error?

**Comment by litvakle** [comment]
> I think it may be a problem with one of your images. Before calling ` tc.one_shot_object_detector.create`, please run a `my_backgrounds.materialize()`. Do you get a similar error?

sorry for a long answer.. I was not able to check your advice earlier.
I have no errors when running `my_backgrounds.materialize()`

But I think you were right - there is something wrong with the SArray of background images.
After `my_backgrounds = tc.SArray('./Backgrounds')` I got:
`Finished parsing file /Users/litvakle/Backgrounds/leather-1251756_1920.jpg
Read 5251 lines. Lines per second: 109613
Finished parsing file /Users/litvakle/Backgrounds/fabric-2644454_1920.jpg
Finished parsing file /Users/litvakle/Backgrounds/canvas-546877_1920.jpg
Finished parsing file /Users/litvakle/Backgrounds/fabric-3673508_1920.jpg
Finished parsing file /Users/litvakle/Backgrounds/art-leather-313281_1920.jpg
Finished parsing file /Users/litvakle/Backgrounds/background-1587925_1920.jpg
Finished parsing file /Users/litvakle/Backgrounds/canvas-2092590_1920.jpg
Finished parsing file /Users/litvakle/Backgrounds/denim-1039513_1920.jpg
Finished parsing file /Users/litvakle/Backgrounds/leather-1251742_1920.jpg
Finished parsing file /Users/litvakle/Backgrounds/woven-2607340_1920.jpg
Finished parsing file /Users/litvakle/Backgrounds/texture-927165_1920.jpg
Parsing completed. Parsed **61247** lines in 0.243557 secs.`

And after `model = tc.one_shot_object_detector.create(starter_images, 'label', backgrounds=my_backgrounds)` I got firstly `Augmenting input images using **61247** background images.`

So my SArray doesn't contain images, but something different.

Could you please answer how to fit SArray with my background images?

**Comment by TobyRoseman** [comment]
To load images use [`turicreate.load_images`](https://apple.github.io/turicreate/docs/api/generated/turicreate.load_images.html). This will return an SFrame. The `image` column will be the SArray you want.


```python
import turicreate as tc

sf = tc.load_images('<image path>')
sa = sf['image']
```

**Comment by litvakle** [comment]
Thank you very much! It works! :)
