### ISSUE TITLE
Installation issues in Windows 10

### ISSUE THREAD

**Issue by sanketpuranik** [apple/turicreate#3416]
OS: Windows 10
Python interpretor: 3.7
Short error info: 'pip install did not find an available binary package for your system.'
Complete error:

ERROR: Command errored out with exit status 1:
   command: 'c:\users\xxx\pycharmprojects\ml_uwashington\venv2\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] =
 '"'"'C:\\Users\\xxx~1\\AppData\\Local\\Temp\\pip-install-3a1a0ksp\\turicreate_b614311ac3b34ea5b702d22cdc8266f0\\setup.py'"'"'; __file__='"'"'C:\\Users\
\xxx~1\\AppData\\Local\\Temp\\pip-install-3a1a0ksp\\turicreate_b614311ac3b34ea5b702d22cdc8266f0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', ope
n)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'
"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\xxx~1\AppData\Local\Temp\pip-wheel-4_lslliz'
       cwd: C:\Users\xxx~1\AppData\Local\Temp\pip-install-3a1a0ksp\turicreate_b614311ac3b34ea5b702d22cdc8266f0\
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build\bdist.win-amd64\wheel
  running install
  
  
  
          ==================================================================================
          TURICREATE ERROR
  
          If you see this message, pip install did not find an available binary package
          for your system.
  
          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).
  
          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7
              * 3.8
  
          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`
  
          ==================================================================================
  
  
  
  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\xxx\pycharmprojects\ml_uwashington\venv2\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0]
 = '"'"'C:\\Users\\xxx~1\\AppData\\Local\\Temp\\pip-install-3a1a0ksp\\turicreate_b614311ac3b34ea5b702d22cdc8266f0\\setup.py'"'"'; __file__='"'"'C:\\User
s\\SANKET~1\\AppData\\Local\\Temp\\pip-install-3a1a0ksp\\turicreate_b614311ac3b34ea5b702d22cdc8266f0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', o
pen)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\
n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xxx~1\AppData\Local\Temp\pip-record-f0ot8w0s\install-record.
txt' --single-version-externally-managed --compile --install-headers 'c:\users\xxx\pycharmprojects\ml_uwashington\venv2\include\site\python3.7\tu
ricreate'
         cwd: C:\Users\xxx~1\AppData\Local\Temp\pip-install-3a1a0ksp\turicreate_b614311ac3b34ea5b702d22cdc8266f0\
    Complete output (28 lines):
    running install
    
    
    
            ==================================================================================
            TURICREATE ERROR
    
            If you see this message, pip install did not find an available binary package
            for your system.
    
            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).
    
            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7
                * 3.8
    
            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`
    
            ==================================================================================
    
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\xxx\pycharmprojects\ml_uwashington\venv2\scripts\python.exe' -u -c 'import io, os, sys,
setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\XXX~1\\AppData\\Local\\Temp\\pip-install-3a1a0ksp\\turicreate_b614311ac3b34ea5b702d22cdc8266f0\\setu
p.py'"'"'; __file__='"'"'C:\\Users\\SANKET~1\\AppData\\Local\\Temp\\pip-install-3a1a0ksp\\turicreate_b614311ac3b34ea5b702d22cdc8266f0\\setup.py'"'"';f = ge
tattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read
().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\XXX~1\AppData\Local\Temp\pi
p-record-f0ot8w0s\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\xxx\pycharmprojects\ml_uwashingto
n\venv2\include\site\python3.7\turicreate' Check the logs for full command output.

**Comment by TobyRoseman** [comment]
TuriCreate does not have native Window support. We're tracking that request in #533.

With Window 10, you should be able to use TuriCreate with Windows Subsystem for Linux (WSL). A recent Ubuntu image should work.
