### ISSUE TITLE
cuda SGD matrix factorization in Graphlab

### ISSUE THREAD

**Issue by fatemeh9264** [apple/turicreate#3418]
Hi
I studied your documentation and user guide; I train an SGD matrix factorization model in a recommender system without setting any special configuration. I just run the code according to guidance. So I do not know how it is implemented(distributed or other ones ). I need **to run it through cuad device**. Is it possible? How can I set the configuration? **Please give me an example to use GPU**.
Thank you very much

**Comment by TobyRoseman** [comment]
This is not possible. The matrix factorization model does not support running on GPU.
