### ISSUE TITLE
New observation data in recommendation module does not work.

### ISSUE THREAD

**Issue by MAGLeb** [apple/turicreate#3419]
```
model.recommend(users=[22316], k=20000, exclude_known=False, exclude=items_viewed, verbose=True)
```
![image](https://user-images.githubusercontent.com/52084975/129872719-1e67a7e9-1da1-4991-bdcc-5be2502c816b.png)

After script for generating users items interactions.
```
N = 100000
user_ids = []
artwork_ids = []
scores = [0 for _ in range(N)]

for i in range(N):
    random_id_user = int(user_data.loc[np.random.randint(0, len(user_data))]['user_id'])
    random_id_artwork = item_data.loc[np.random.randint(0, len(item_data))]['artwork_id']
    user_ids.append(random_id_user)
    artwork_ids.append(random_id_artwork)

new_observation_data = SFrame(pd.DataFrame({'user_id': user_ids, 'artwork_id': artwork_ids, 'score': scores}))
```

Use the same model with new_observation_data:
```
model.recommend(users=[22316], k=20000, new_observation_data=new_observation_data, exclude_known=False, exclude=items_viewed, verbose=True)
```
and get the same predictions:
![image](https://user-images.githubusercontent.com/52084975/129873208-9fd42078-4b3c-47f6-b0b7-fce435060812.png)

What am I doing wrong?

**Comment by TobyRoseman** [comment]
I believe this is the same issue as #1797.

**Comment by MAGLeb** [comment]
Yes, the same issues. 
Why so long didn't fix it? Do you encourage open-source developers?

Also, thank you for the fast answer!

**Comment by TobyRoseman** [comment]
Thanks for confirming it's the same issue. Let's track this in #1797
