### ISSUE TITLE
set the number of threads in recommendation module

### ISSUE THREAD

**Issue by fatemeh9264** [apple/turicreate#3420]
Is it possible to change the configuration and set the maximum number of threads to run the recommendation module?

**Comment by TobyRoseman** [comment]
Before importing turicreate, set the `OMP_NUM_THREADS` environment variable to your max number. 

If you wanted the maximum number of threads to be 5, you could do:
```python
import os
os.env["OMP_NUM_THREADS"] = 5
import turicreate
```

I'm going to close this issue, but let me know if you have any issues or more questions.
