### ISSUE TITLE
Trouble to install turicreate

### ISSUE THREAD

**Issue by dogiger** [apple/turicreate#3421]
Hi. Could anyone help me? I get the following error message:

`
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\xxx\appdata\local\programs\python\python38\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-9lcj5jy0\\turicreate_fbeb20a094d14291b6438635640c6f06\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-9lcj5jy0\\turicreate_fbeb20a094d14291b6438635640c6f06\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xxx\AppData\Local\Temp\pip-record-bnofcxkk\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\butzli\appdata\local\programs\python\python38\Include\turicreate'
         cwd: C:\Users\xxx\AppData\Local\Temp\pip-install-9lcj5jy0\turicreate_fbeb20a094d14291b6438635640c6f06\
    Complete output (28 lines):
    running install
    
    
    
            ==================================================================================
            TURICREATE ERROR
    
            If you see this message, pip install did not find an available binary package
            for your system.
    
            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).
    
            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7
                * 3.8
    
            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`
    
            ==================================================================================
    
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\xxx\appdata\local\programs\python\python38\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-9lcj5jy0\\turicreate_fbeb20a094d14291b6438635640c6f06\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-9lcj5jy0\\turicreate_fbeb20a094d14291b6438635640c6f06\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', 
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xxx\AppData\Local\Temp\pip-record-bnofcxkk\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\butzli\appdata\local\programs\python\python38\Include\turicreate' Check the logs for full command output.
`

**Comment by TobyRoseman** [comment]
It looks like you are using Windows. TuriCreate does not have native Windows support. Note Windows is not mentioned in the Supported Platforms section of the error message you shared.

We are already tracking native Windows support in #533.

[Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/install-win10) is the easiest way to use TuriCreate on Windows.
