### ISSUE TITLE
Error while installing Turi Create in Windows

### ISSUE THREAD

**Issue by iamrathore** [apple/turicreate#3428]
I have set up a Virtual environment but while installing Turi Create the kernel throws the below error. 

Note: I have python 3.7 installed in my system still got this error. 

"""""
 ERROR: Command errored out with exit status 1:
   command: 'c:\users\ankit\appdata\local\programs\python\python37\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ankit\\AppData\\Local\\Temp\\pip-install-ao_8r4f9\\turicreate_c09b51f3c09344e991051b8a17597bc4\\setup.py'"'"'; __file__='"'"'C:\\Users\\ankit\\AppData\\Local\\Temp\\pip-install-ao_8r4f9\\turicreate_c09b51f3c09344e991051b8a17597bc4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ankit\AppData\Local\Temp\pip-wheel-n4tx6l7s'
       cwd: C:\Users\ankit\AppData\Local\Temp\pip-install-ao_8r4f9\turicreate_c09b51f3c09344e991051b8a17597bc4\
  Complete output (33 lines):
  running bdist_wheel
  running build
  c:\users\ankit\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    setuptools.SetuptoolsDeprecationWarning,
  installing to build\bdist.win-amd64\wheel
  running install

          ==================================================================================
          TURICREATE ERROR

          If you see this message, pip install did not find an available binary package
          for your system.

          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).

          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7
              * 3.8

          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`

          ==================================================================================

  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\ankit\appdata\local\programs\python\python37\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ankit\\AppData\\Local\\Temp\\pip-install-ao_8r4f9\\turicreate_c09b51f3c09344e991051b8a17597bc4\\setup.py'"'"'; __file__='"'"'C:\\Users\\ankit\\AppData\\Local\\Temp\\pip-install-ao_8r4f9\\turicreate_c09b51f3c09344e991051b8a17597bc4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ankit\AppData\Local\Temp\pip-record-u9sb9l6s\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\ankit\appdata\local\programs\python\python37\Include\turicreate'
         cwd: C:\Users\ankit\AppData\Local\Temp\pip-install-ao_8r4f9\turicreate_c09b51f3c09344e991051b8a17597bc4\
    Complete output (30 lines):
    running install
    c:\users\ankit\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,

            ==================================================================================
            TURICREATE ERROR

            If you see this message, pip install did not find an available binary package
            for your system.

            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).

            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7
                * 3.8

            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`

            ==================================================================================

    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\ankit\appdata\local\programs\python\python37\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ankit\\AppData\\Local\\Temp\\pip-install-ao_8r4f9\\turicreate_c09b51f3c09344e991051b8a17597bc4\\setup.py'"'"'; __file__='"'"'C:\\Users\\ankit\\AppData\\Local\\Temp\\pip-install-ao_8r4f9\\turicreate_c09b51f3c09344e991051b8a17597bc4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ankit\AppData\Local\Temp\pip-record-u9sb9l6s\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\ankit\appdata\local\programs\python\python37\Include\turicreate' Check the logs for full command output."""""

**Comment by TobyRoseman** [comment]
TuriCreate does not have native support for Windows.

Note that - Windows is not listed in the Supported Platforms section of the error message you shared.

If you want to use TuriCreate on Windows, you need to use WSL.

**Comment by iamrathore** [comment]
Got it. Thanks
