### ISSUE TITLE
 pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. flask-sqlalchemy 2.4.4 requires Flask>=0.10, which is not installed.

### ISSUE THREAD

**Issue by minakshimathpal** [apple/turicreate#3437]
using windows 10
Created rasa environment in conda with python 3.8
On doing pip install rasa, everything installed properly but in the middle i have the following mention of an error

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask-sqlalchemy 2.4.4 requires Flask>=0.10, which is not installed.

Can i continue doing my work or i have to install flask to....If yes then is it required in rasa environment or in my local machine

**Comment by TobyRoseman** [comment]
Is this a pip dependency resolver issue or a TuriCreate issue?

If you think this is a TuriCreate issue, please give some more details. What command did you run? What was the full output?

**Comment by minakshimathpal** [comment]
I created a python virtual environment in anaconda.....installed ujson......tensorflow......and then install rasa using pip(21.3.1).....After that i get this error message

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask-sqlalchemy 2.4.4 requires Flask>=0.10, which is not installed.
Successfully installed SQLAlchemy-1.4.31 absl-py-0.13.0 aiofiles-0.8.0 async-generator-1.10 attrs-21.2.0 chardet-3.0.4 cloudpickle-1.6.0 colorama-0.4.4 cycler-0.11.0 decorator-5.1.1 flatbuffers-1.12 fsspec-2022.1.0 future-0.18.2 google-auth-2.5.0 greenlet-1.1.2 h5py-3.1.0 httptools-0.3.0 humanfriendly-10.0 jmespath-0.10.0 joblib-1.0.1 jsonschema-3.2.0 keras-2.6.0 kiwisolver-1.3.2 locket-0.2.1 msgpack-1.0.3 networkx-2.6.3 numpy-1.19.5 pamqp-2.3.0 partd-1.2.0 pillow-9.0.0 pydot-1.4.2 pyparsing-3.0.7 pyreadline3-3.4.1 pyrsistent-0.18.1 python-dateutil-2.8.2 pytz-2021.3 pyyaml-6.0 questionary-1.10.0 rasa-3.0.5 rasa-sdk-3.0.3 regex-2021.8.28 ruamel.yaml.clib-0.2.6 sanic-21.9.3 sanic-cors-1.0.1 sanic-jwt-1.7.0 sanic-plugin-toolkit-1.2.1 sanic-routing-0.7.2 scikit-learn-0.24.2 sentry-sdk-1.3.1 six-1.15.0 tensorboard-2.8.0 tensorboard-data-server-0.6.1 tensorflow-2.6.1 tensorflow-addons-0.14.0 threadpoolctl-3.0.0 toolz-0.11.2 tqdm-4.62.3 typing-extensions-3.7.4.3 wcwidth-0.2.5 websockets-10.1 wrapt-1.12.1

**Comment by minakshimathpal** [comment]
I am sorry wrong forum
