### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [apple/turicreate#3439]
Problem 
--------- 
On linux aarch64, `pip install turicreate` is giving the below the error- 

```  
Collecting turicreate
  Using cached turicreate-6.4.tar.gz (1.9 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-006mbw6u/turicreate_075b03b4fae9494a8d0948fed3ffca52/setup.py'"'"'; __file__='"'"'/tmp/pip-install-006mbw6u/turicreate_075b03b4fae9494a8d0948fed3ffca52/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-0mjwmr3f
       cwd: /tmp/pip-install-006mbw6u/turicreate_075b03b4fae9494a8d0948fed3ffca52/
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build/bdist.linux-aarch64/wheel
  running install

          ==================================================================================
          TURICREATE ERROR

          If you see this message, pip install did not find an available binary package
          for your system.

          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).

          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7
              * 3.8

          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`

          ==================================================================================

  ----------------------------------------
  ERROR: Failed building wheel for turicreate 
``` 

Resolution 
----------- 
On aarch64, `pip install turicreate` should download the wheels from PyPI. 

@TobyRoseman, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by TobyRoseman** [comment]
I don't think this is something we will support.

**Comment by Xqizit16** [comment]
Collecting turicreate
  Using cached turicreate-6.4.tar.gz (1.9 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      running bdist_wheel
      running build
      /home/osumeje/venv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build/bdist.linux-x86_64/wheel
      running install



              ==================================================================================
              TURICREATE ERROR

              If you see this message, pip install did not find an available binary package
              for your system.

              Supported Platforms:
                  * macOS 10.12+ x86_64.
                  * Linux x86_64 (including WSL on Windows 10).

              Support Python Versions:
                  * 2.7
                  * 3.5
                  * 3.6
                  * 3.7
                  * 3.8

              Another possible cause of this error is an outdated pip version. Try:
                  `pip install -U pip`

              ==================================================================================



      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
  Running setup.py install for turicreate ... error
  error: subprocess-exited-with-error

  × Running setup.py install for turicreate did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      running install
      /home/osumeje/venv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(



              ==================================================================================
              TURICREATE ERROR

              If you see this message, pip install did not find an available binary package
              for your system.

              Supported Platforms:
                  * macOS 10.12+ x86_64.
                  * Linux x86_64 (including WSL on Windows 10).

              Support Python Versions:
                  * 2.7
                  * 3.5
                  * 3.6
                  * 3.7
                  * 3.8

              Another possible cause of this error is an outdated pip version. Try:
                  `pip install -U pip`

              ==================================================================================



      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> turicreate

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Xqizit16** [comment]
I have tried to install turicreate but i keep getting this error message.
I have tried following similar error messages but it ends up with the Rosetta thing, pls how do i get this Rosetta with my windows 10, I cant seem to follow the instructions given for this solution.

**Comment by TobyRoseman** [comment]
TuriCreate does not have native Windows support. If you want to use TuriCreate on Windows, you need to use WSL.

**Comment by Xqizit16** [comment]
Thank you for the reply. 
I have tried to install WSL, it was successful, I tried to install Ubuntu 20.0 it didnt work, then I installed the Ubuntu 18.0 it worked. then I created a virtual env, it worked, i installed the Turicreate after a lot of trial. But when I try to import Turicreate I keep getting some error.

**Comment by Xqizit16** [comment]
Like when I try to import Turicreate in Jupyter using this command; "import turicreate as tc"
I get this out put;
 "---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-5e19a42750e5> in <module>()
----> 1 import turicreate as tc

ModuleNotFoundError: No module named 'turicreate'"

**Comment by TobyRoseman** [comment]
@Xqizit16 - if the `pip install turicreate` was successful, then this is a problem with your environment; `pip` is using a different environment than `jupyter`. If you're using using Jupyter Notebooks, install it directly in your notebook using:
`! pip install turicreate`
