### ISSUE TITLE
Unable to download turicreate on Windows 10

### ISSUE THREAD

**Issue by M-Faried** [apple/turicreate#3441]
Whether I try to pip install turicreate from anaconda power shell or windows 11 power shell I get the error mentioned below

I tried with the following versions of python and still have the same issue:
python 3.8.12
python 3.10.0

pip 21.2.2

 ==================================================================================
              TURICREATE ERROR

              If you see this message, pip install did not find an available binary package
              for your system.

              Supported Platforms:
                  * macOS 10.12+ x86_64.
                  * Linux x86_64 (including WSL on Windows 10).

              Support Python Versions:
                  * 2.7
                  * 3.5
                  * 3.6
                  * 3.7
                  * 3.8

              Another possible cause of this error is an outdated pip version. Try:
                  `pip install -U pip`

              ==================================================================================

**Comment by TobyRoseman** [comment]
It should work for Python 3.8.12 on WSL. Are you using WSL? 

If you are using WSL, please share the entire output of `pip install turicreate`. Also which image/linux-distribution are you using?

**Comment by M-Faried** [comment]
> It should work for Python 3.8.12 on WSL. Are you using WSL?
> 
> If you are using WSL, please share the entire output of `pip install turicreate`. Also which image/linux-distribution are you using?

Ubuntu 20.04 LTS

**Comment by M-Faried** [comment]
Here is the full output 
Collecting turicreate
  Using cached turicreate-6.4.tar.gz (1.9 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      running bdist_wheel
      running build
      installing to build\bdist.win-amd64\wheel
      running install



              ==================================================================================
              TURICREATE ERROR

              If you see this message, pip install did not find an available binary package
              for your system.

              Supported Platforms:
                  * macOS 10.12+ x86_64.
                  * Linux x86_64 (including WSL on Windows 10).

              Support Python Versions:
                  * 2.7
                  * 3.5
                  * 3.6
                  * 3.7
                  * 3.8

              Another possible cause of this error is an outdated pip version. Try:
                  `pip install -U pip`

              ==================================================================================



      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
  Running setup.py install for turicreate ... error
  error: subprocess-exited-with-error

  × Running setup.py install for turicreate did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      running install



              ==================================================================================
              TURICREATE ERROR

              If you see this message, pip install did not find an available binary package
              for your system.

              Supported Platforms:
                  * macOS 10.12+ x86_64.
                  * Linux x86_64 (including WSL on Windows 10).

              Support Python Versions:
                  * 2.7
                  * 3.5
                  * 3.6
                  * 3.7
                  * 3.8

              Another possible cause of this error is an outdated pip version. Try:
                  `pip install -U pip`

              ==================================================================================



      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> turicreate

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by TobyRoseman** [comment]
Ubuntu 20 should be good. Please share the full output. What are the `[31 lines of output]` and `[28 lines of output]`?

**Comment by M-Faried** [comment]
@TobyRoseman After more investigation, I found that the wsl distro I am using is corrupted and suffers from issues with windows 11 itself. I am now installing a fresh distro (version 18.04) and will try again.

For the hidden lines, I am not sure how to display them, I am new to windows and am used to iTerm2 and ohmyzsh on Mac but not the power shell. I will search and try to display the collapsed line.

**Comment by M-Faried** [comment]
@TobyRoseman It worked fine after I installed a fresh distro of wsl. Thank you.
