### ISSUE TITLE
GraphLab Create requires a license to use in linux

### ISSUE THREAD

**Issue by arashsa2022** [apple/turicreate#3456]
Hello I have problem when I want ti import the bellows 
I got the error ([ERROR] graphlab.connect.main:  ========================================
GraphLab Create requires a license to use. To get a non-commercial  license for academic use only, visit https://turi.com/register. )

I'm using Linux Ubuntu 18.04.6 LTS and python 2.7 and I have follow the whole procedure of [LINUX_INSTALL.md] and also I using anaconda and jupyter 

I have installed theses 

pip install -U turicreate

would you please help me 

import graphlab as gl
import numpy as np
import graphlab.aggregate as agg
import matplotlib.pyplot as plt
from matplotlib import rcParams
import datetime as dt   
from graphlab import degree_counting
from graphlab import connected_components
from graphlab import pagerank
from graphlab import shortest_path
from graphlab import triangle_counting
from graphlab import label_propagation
from graphlab import kcore
from graphlab import graph_coloring

**Comment by TobyRoseman** [comment]
You should be using [TuriCreate](https://github.com/apple/turicreate) not GraphLab Create. TuriCreate is open source (i.e. does not require a license).

TuriCreate is largely a drop-in replacement for GraphLab create. Once TuriCreate is installed, all of these imports should work if you just replace `graphlab`with `turicreate`.
