### ISSUE TITLE
TuriCreate still doesn't work on M1 using rosetta terminal

### ISSUE THREAD

**Issue by birach** [apple/turicreate#3462]
After looking through some of the issues and trying various things, I still can't figure out how to get this package up and running on M1. 

Some of the details which may be needed:

```
(ML_UW) bilal@Mohammeds-MacBook-Pro ~ % uname -a
Darwin Mohammeds-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 x86_64
```

The Output of pip inside a conda env running python 3.8.13:

```
(ML_UW) bilal@Mohammeds-MacBook-Pro ~ % python --version
Python 3.8.13
(ML_UW) bilal@Mohammeds-MacBook-Pro ~ % pip install -U turicreate
Collecting turicreate
  Using cached turicreate-6.4.tar.gz (1.9 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      running bdist_wheel
      running build
      /Users/bilal/opt/anaconda3/envs/ML_UW/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build/bdist.macosx-11.1-arm64/wheel
      running install
      
      
      
              ==================================================================================
              TURICREATE ERROR
      
              If you see this message, pip install did not find an available binary package
              for your system.
      
              Supported Platforms:
                  * macOS 10.12+ x86_64.
                  * Linux x86_64 (including WSL on Windows 10).
      
              Support Python Versions:
                  * 2.7
                  * 3.5
                  * 3.6
                  * 3.7
                  * 3.8
      
              Another possible cause of this error is an outdated pip version. Try:
                  `pip install -U pip`
      
              ==================================================================================
      
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
  Running setup.py install for turicreate ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for turicreate did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      running install
      /Users/bilal/opt/anaconda3/envs/ML_UW/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      
      
      
              ==================================================================================
              TURICREATE ERROR
      
              If you see this message, pip install did not find an available binary package
              for your system.
      
              Supported Platforms:
                  * macOS 10.12+ x86_64.
                  * Linux x86_64 (including WSL on Windows 10).
      
              Support Python Versions:
                  * 2.7
                  * 3.5
                  * 3.6
                  * 3.7
                  * 3.8
      
              Another possible cause of this error is an outdated pip version. Try:
                  `pip install -U pip`
      
              ==================================================================================
      
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> turicreate

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

Any help on this will be appreciated. @TobyRoseman

**Comment by TobyRoseman** [comment]
See my [earlier comment](https://github.com/apple/turicreate/issues/3429#issuecomment-962288689) in #3429.

**Comment by birach** [comment]
The above logs are from the Rosetta terminal i.e., the copy of the application with "Open using Rosetta" checked. This was verified using `uname -a` in the log above.

**Comment by TobyRoseman** [comment]
Ok, then I'm guessing this is an issue with your environment. The shell is `x86_64` but `pip` may still be running natively. I recommend uninstalling anaconda. Then reinstalling it making sure you install the `x86_64` version.

**Comment by birach** [comment]
I'm not sure I got that. Does this mean, I have to remove the native anaconda and install the `x86_64` version? Won't it impact the other projects using native conda envs? Is there a way to do this only inside the "Rosetta" space?

**Comment by TobyRoseman** [comment]
Yes, `pip` and `python` both need to be running under rosetta.

**Comment by birach** [comment]
Just for the proper closure of this issue. I figured out a way around this.
1. Open native(usual) terminal
2. Run:
```
CONDA_SUBDIR=osx-64 conda create -n <env_name> python=3.9
conda activate <env_name>
conda config --env --set subdir osx-64
```
3. Run `pip install -U turicreate` and you're done.

**Comment by SBhat2615** [comment]
> Just for the proper closure of this issue. I figured out a way around this.
> 
> 1. Open native(usual) terminal
> 2. Run:
> 
> ```
> CONDA_SUBDIR=osx-64 conda create -n <env_name> python=3.9
> conda activate <env_name>
> conda config --env --set subdir osx-64
> ```
> 
> 3. Run `pip install -U turicreate` and you're done.


I'm using M1 Mac Ventura 13.0.1.
I get this ERROR.

❯ pip install -U turicreate
Collecting turicreate
  Using cached turicreate-6.4.tar.gz (1.9 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      running bdist_wheel
      running build
      /opt/homebrew/Caskroom/miniforge/base/envs/turi/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build/bdist.macosx-10.9-x86_64/wheel
      running install



              ==================================================================================
              TURICREATE ERROR

              If you see this message, pip install did not find an available binary package
              for your system.

              Supported Platforms:
                  * macOS 10.12+ x86_64.
                  * Linux x86_64 (including WSL on Windows 10).

              Support Python Versions:
                  * 2.7
                  * 3.5
                  * 3.6
                  * 3.7
                  * 3.8

              Another possible cause of this error is an outdated pip version. Try:
                  `pip install -U pip`

              ==================================================================================



      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
  Running setup.py install for turicreate ... error
  error: subprocess-exited-with-error

  × Running setup.py install for turicreate did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      running install
      /opt/homebrew/Caskroom/miniforge/base/envs/turi/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(



              ==================================================================================
              TURICREATE ERROR

              If you see this message, pip install did not find an available binary package
              for your system.

              Supported Platforms:
                  * macOS 10.12+ x86_64.
                  * Linux x86_64 (including WSL on Windows 10).

              Support Python Versions:
                  * 2.7
                  * 3.5
                  * 3.6
                  * 3.7
                  * 3.8

              Another possible cause of this error is an outdated pip version. Try:
                  `pip install -U pip`

              ==================================================================================



      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> turicreate

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Max1972** [comment]
@girach do you mean you didn't use rosetta with terminal from which you installed turicreate, anaconda, and python?
I have tried this with no success. Would you clarify if you have used any rosetta terminals at any point in time?
Thanks
