### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'typeDict'

### ISSUE THREAD

**Issue by samer-br** [apple/turicreate#3471]
1 # Create the LSTM model
----> 2 from keras.models import Sequential
      3 from keras.layers import LSTM, Dense
      4 
      5 model = Sequential()

~/opt/anaconda3/lib/python3.8/site-packages/keras/__init__.py in 
     18 [keras.io](https://keras.io).
     19 """
---> 20 from keras import distribute
     21 from keras import models
     22 from keras.engine.input_layer import Input

~/opt/anaconda3/lib/python3.8/site-packages/keras/distribute/__init__.py in 
     16 
     17 
---> 18 from keras.distribute import sidecar_evaluator

~/opt/anaconda3/lib/python3.8/site-packages/keras/distribute/sidecar_evaluator.py in 
     15 """Python module for evaluation loop."""
     16 
---> 17 import tensorflow.compat.v2 as tf
...
--> 320         raise AttributeError("module {!r} has no attribute "
    321                              "{!r}".format(__name__, attr))
    322 

AttributeError: module 'numpy' has no attribute 'typeDict'

**Comment by TobyRoseman** [comment]
This is not a TuriCreate issue. This error is coming from Keras. It looks like a problem with your environment. The version of Keras you have installed is not compatible with the version of numpy you have installed.
