### ISSUE TITLE
Image classifier without softmax

### ISSUE THREAD

**Issue by wtmoose** [apple/turicreate#351]
No sure where's the best place to ask questions, so duplicating my [SO question](https://stackoverflow.com/questions/49157961/image-classifier-without-softmax) here:

I'm using Turi Create to generate a Core ML image classifier like this:

````python
import turicreate as tc
data =  tc.SFrame('data.sframe')
model = tc.image_classifier.create(data, target='label')
model.export_coreml('classifier.mlmodel')
````

However, the model gives me softmax confidence values and in my application, I need pre-softmax values (I'll calculate softmax in the app). Is there a way to turn off the softmax layer?

I've had models like this supplied to me in the past, but now I need to generate my own. I've read through the docs and looked through source code (which I'm willing to modify if needed), but I don't know enough about machine learning to figure it out.

**Comment by vaibhawvipul** [comment]
Hey @wtmoose ! 

Check this out, https://github.com/apple/turicreate/blob/master/userguide/supervised-learning/linear-regression.md#linregr-model-access

Let me know if it helps...

**Comment by wtmoose** [comment]
@vaibhawvipul thanks, but no I don't see how this helps me export a Core ML image classifier that that will output the confidence values I need.

**Comment by vaibhawvipul** [comment]
Hmm... How about this? https://github.com/apple/turicreate/blob/master/userguide/supervised-learning/logistic-regression.md#logregr-multiclass 

They have written in the documentation that image classifier automatically selects the best fitting model(between Resnet and Squeezenet). I don't know if there is a way to pass on custom CNN(trained model). If that is possible I can help you write one.

**Comment by wtmoose** [comment]
@vaibhawvipul I appreciate the pointer. I don't have time to dig that deep into it at the moment (was trying to quickly put something together for SXSW). Will likely revisit later.
