### ISSUE TITLE
No Top Level load_sarray

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#379]
We have `turicreate.load_model`, `turicreate.load_sframe` and `turicreate.load_sgraph`. However there is no `turicreate.load_sarray`. For consistency we should add one.

**Comment by karthikdash** [comment]
Can I work on this?

**Comment by TobyRoseman** [comment]
@karthikdash - absolutely, go right ahead. I would be happy to code review it when you are done, or answer any questions you might have along the way.
