### ISSUE TITLE
Raise specific exceptions?

### ISSUE THREAD

**Issue by delirious-lettuce** [apple/turicreate#38]
https://github.com/apple/turicreate/blob/7f07ce795833d0c56c72b3a1fb9339bed6d178d1/src/unity/python/turicreate/util/config.py#L55

```python
>>> raise "Please set the TEMP environment variable"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions must be old-style classes or derived from BaseException, not str
```

https://github.com/apple/turicreate/blob/7f07ce795833d0c56c72b3a1fb9339bed6d178d1/src/unity/python/turicreate/test/test_nearest_neighbors.py#L1591

```python
>>> raise "Unknown distance"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions must be old-style classes or derived from BaseException, not str
```

**Comment by znation** [comment]
@gustavla Something we should do as part of the fix for #2 ? I haven't tested this but I suspect Python 3 is less happy about using strings as exception values than Python 2.

**Comment by delirious-lettuce** [comment]
@znation ,

I used Python 2 for the first comment but here shows both. This is a `TypeError` in both versions.

```python
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> raise "test"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions must be old-style classes or derived from BaseException, not str


Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> raise "test"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions must derive from BaseException

```

**Comment by delirious-lettuce** [comment]
I just wasn't sure what specific exception you guys wanted raised so I didn't send a PR.

**Comment by znation** [comment]
@delirious-lettuce Thanks, I see! I suspect this may have worked at some point in Python 2 but perhaps it never did.

I would use [RuntimeError](https://docs.python.org/2/library/exceptions.html#exceptions.RuntimeError) to wrap all of these strings. Please feel free to submit a PR with that. Thanks!

**Comment by delirious-lettuce** [comment]
@znation ,

You might be right, `2.7.12` is the lowest Python version I have tested it with but it may have been different earlier (2.6 maybe?).

I am just about to send a tiny PR right now but then I will fix this one ASAP (with `RuntimeError`).
