### ISSUE TITLE
How to parse CSV array

### ISSUE THREAD

**Issue by coffeeboo** [apple/turicreate#382]
I want to make an autocomplete machine learning model using a .csv file.
`[characters], label`
How would I make TuriCreate parse this?

**Comment by srikris** [comment]
````
import turicreate
data = turicreate.SFrame('data.csv')
```

That should get data into your format. We'll need some more information into what `[characters]` are to be able to give you more info.

**Comment by coffeeboo** [comment]
But apparently, TuriCreate automatically finds types, so I might be over-complicating this.

**Comment by afranklin** [comment]
Here's API documentation for read_csv: https://apple.github.io/turicreate/docs/api/generated/turicreate.SFrame.read_csv.html#turicreate.SFrame.read_csv

If types are not properly auto-generated, you can use the **column_type_hints** parameter.
