### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by PietroMessineo** [apple/turicreate#384]
Hi guys,

I'm encountering an error. While I'm doing the task "performing feature extraction on resized images..." on a dataset of more than 55K images at almost 19K I'm facing out this: 

`Traceback (most recent call last):
  File "export_model.py", line 10, in <module>
    model = tc.image_classifier.create(train_data, target='label', max_iterations=5000)
  File "/root/anaconda3/envs/my_env/lib/python2.7/site-packages/turicreate/toolkits/image_classifier/image_classifier.py", line 122, in create
    '__image_features__': feature_extractor.extract_features(dataset, feature, verbose=verbose),
  File "/root/anaconda3/envs/my_env/lib/python2.7/site-packages/turicreate/toolkits/_image_feature_extractor.py", line 111, in extract_features
    model.forward(next(dataIter))
  File "/root/anaconda3/envs/my_env/lib/python2.7/site-packages/mxnet/io.py", line 219, in next
    if self.iter_next():
  File "/root/anaconda3/envs/my_env/lib/python2.7/site-packages/turicreate/mx/_mx_sframe_iter.py", line 351, in iter_next
    self.data_ndarray = (self.data_ndarray - self._rgb_mask.asnumpy()) * self._scale
MemoryError
`

There is a way to fix it? I'm encountering this on a new VPS that I booked today. 
Thank you !

**Comment by ylow** [comment]
I am guessing the instance does not have too much memory? I suspect the combined memory pressure of SFrame cache and MXNet is causing memory issues.

Can you take a look at the value of:
```
tc.config.get_runtime_config('TURI_FILEIO_MAXIMUM_CACHE_CAPACITY')
```

It defaults to half of total system memory (in bytes). You can try lowering it further with: 

```
tc.config.set_runtime_config('TURI_FILEIO_MAXIMUM_CACHE_CAPACITY', [memory in bytes])
```

**Comment by PietroMessineo** [comment]
I'm really sorry I forgot to reply to your message. Actually it is, the server was running out of memory because the swap wasn't enabled. So now I enabled the swap but there is another problem. I have now 73GB of Swap and the python script run since almost one day and the model is not exported yet. 
Typing "top" I'm able to see that CPU is still working, have you an idea if it's stacked or something went wrong? 

As explained on the first post I'm trying to train 55K images, but I haven't ever thought that could be so slow... 

Thank you very much, and sorry again for the late reply.

**Comment by ylow** [comment]
Hi,

I recommend lowering the maximum cache capacity to maybe about 2GB. i.e. 
```
tc.config.set_runtime_config('TURI_FILEIO_MAXIMUM_CACHE_CAPACITY', 2*1024*1024*1024)
```

Also, you don't need 5000 iterations in 
```
tc.image_classifier.create(train_data, target='label', max_iterations=5000)
```

The optimizer used here is LBFGS. The default (~20-50 iterations) is sufficient.

Yucheng

**Comment by PietroMessineo** [comment]
Really? I need to try again... it was returning to me after the warning “killed 9”... probably it was running out of space! Ill try to set as max iterations 50 and I’ll let you know ! Thank you!

**Comment by PietroMessineo** [comment]
Hi Ylow,

I'm still facing out some problems. This is my code, is it placed (tc.config.set_runtime_config('TURI_FILEIO_MAXIMUM_CACHE_CAPACITY', 2*1024*1024*1024))  in a wrong way? Could you help me? Thank you! 
 `import turicreate as tc

# Load the data
data = tc.SFrame('alfa.sframe')

# Make a train-test split
train_data, test_data = data.random_split(0.8)

tc.config.set_runtime_config('TURI_FILEIO_MAXIMUM_CACHE_CAPACITY', 2*1024*1024*1024)

# Create a model
model = tc.image_classifier.create(train_data, target='label', max_iterations=50)

# Save predictions to an SFrame (class and corresponding class-probabilities)
predictions = model.classify(test_data)

# Evaluate the model and save the results into a dictionary
results = model.evaluate(test_data)
print "Accuracy         : %s" % results['accuracy']
print "Confusion Matrix : \n%s" % results['confusion_matrix']

# Save the model for later usage in Turi Create
model.save('Alfa2.model')
`

**Comment by ylow** [comment]
Where is it failing?

**Comment by PietroMessineo** [comment]
Is not failing but its appearing the warning that the model maybe not optimal and it’s not exporting the model... staying stacked for hours. 

I tested it with 5K images and everything was fine, when I’m increasing dataset from 5 to 55K images I’m encountering the problem. CPU and RAM are in anyway working so the program is not stacked it seems. 

If you can say to me that’s normal and that I need to wait days that’s it, I’ll do it. 

Thank you very much!!
