### ISSUE TITLE
SFrame "show" triggers error in python 3.6

### ISSUE THREAD

**Issue by oreh** [apple/turicreate#391]
SFrame.show works well in python 2.7 but fails in python 3.6

__Python env__
3.6.3 | packaged by conda-forge | (default, Oct  5 2017, 14:07:33) \n[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]

TuriCreate Version: 4.2

__Code__
import turicreate as tc
sf = tc.SFrame.read_csv('https://docs-assets.developer.apple.com/turicreate/datasets/tc-clang-format-results.csv')
sf.show()

__Error Message__
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-9d778c121b4c> in <module>()
----> 1 sf.show()

/opt/conda/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in show(self)
   4480         """
   4481 
-> 4482         returned_plot = self.__plot()
   4483 
   4484         returned_plot.show()

/opt/conda/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in __plot(self)
   4487         path_to_client = _get_client_app_path()
   4488 
-> 4489         return Plot(self.__proxy__.plot(path_to_client))
   4490 
   4491     def pack_columns(self, column_names=None, column_name_prefix=None, dtype=list,

turicreate/cython/cy_sframe.pyx in turicreate.cython.cy_sframe.UnitySFrameProxy.plot()

turicreate/cython/cy_sframe.pyx in turicreate.cython.cy_sframe.UnitySFrameProxy.plot()

turicreate/cython/cy_cpp_utils.pxd in turicreate.cython.cy_cpp_utils.str_to_cpp()

turicreate/cython/cy_cpp_utils.pyx in turicreate.cython.cy_cpp_utils._attempt_cast_str_to_cpp()

TypeError: Type '<class 'str'>' cannot be interpreted as str.
```

**Comment by jsrpy** [comment]
I experienced the same error regardless of the datatypes in my sframe table.

**Comment by abhishekpratapa** [comment]
I'm not able to repro, this using python '3.6.6' and python '3.6.3' on Mac. I'm assuming this may be a linux issue, investigating.

**Comment by abhishekpratapa** [comment]
I'm not able to repro, this using python '3.6.6' and python '3.6.3' on Ubuntu 16.04, and Ubuntu 16.10. Can you potentially attach a virtual environment repo-ing the bug? Going to investigate further.

**Comment by znation** [comment]
@oreh @jsrpy I am able to repro this in 4.2, but not in 4.3.2 or later. I think it has been fixed since then. Please reopen this issue if you are able to repro in 4.3.2 or later and provide repro steps, thanks!
