### ISSUE TITLE
RuntimeError: SArray.show is currently not available for SArrays of type image

### ISSUE THREAD

**Issue by Varun51194** [apple/turicreate#396]
I'm a TA for Emily Fox and I was hoping that you could implement this feature so that display images for our Image Classification Assignment.

`turicreate/cython/cy_sarray.pyx in turicreate.cython.cy_sarray.UnitySArrayProxy.plot()

turicreate/cython/cy_sarray.pyx in turicreate.cython.cy_sarray.UnitySArrayProxy.plot()

RuntimeError: SArray.show is currently not available for SArrays of type image`

**Comment by srikris** [comment]
Can you try ```sarray.explore``` that should give you the interactive view. The show API is more for aggregated plots.

**Comment by Varun51194** [comment]
Thanks for the quick response!

I see in the API that `sarray.explore` opens up a new window, however, when I try it in an iPython Notebook it doesn't show. Is it possible to change the target to be the notebook like how `graphlab.canvas.set_target` works?

**Comment by igiloh** [comment]
Hi @Varun51194 
`set_target()` was added just a few [days ago](https://github.com/apple/turicreate/pull/353). This feature will be available in the next TC release - 4.3.
You can use it now by building master from source.

**Comment by Varun51194** [comment]
Thanks!

**Comment by opeerator** [comment]
Hi , I still have problem using .explore() in Ipython notebook and It only says "Materializing SFrame" and nothing else...
is there a fix for this?

**Comment by nikmuhammadnaim** [comment]
I get the following error when using the .explore():

> Value must be a nonnegative integer or None

**Comment by TobyRoseman** [comment]
> I get the following error when using the .explore():
> 
> > Value must be a nonnegative integer or None

@nikmuhammadnaim - do you get a stack trace? If so, please share.

**Comment by ShubhamBera** [comment]
Thanks i was stuck at the same point because tc doesn't have show() for Saturday image but now with explore() i can move forward with the course
