### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by veonua** [apple/turicreate#400]
sys.platform
'linux'

/usr/local/lib/python3.5/dist-packages/turicreate/data_structures/sframe.py in explore(self, title)
           if sys.platform != 'darwin' and sys.platform != 'linux2':
            raise NotImplementedError('Visualization is currently supported only on macOS and Linux.')
  

why linux2?

**Comment by TobyRoseman** [comment]
@veonua - Sorry you are having this issue. What type of Linux and which version are you using? Can you try locally changing that line to `if sys.platform != 'darwin' and sys.platform != 'linux':` and let us know if`explore` works?

**Comment by abhishekpratapa** [comment]
Are you using python3?

**Comment by veonua** [comment]
yes it's python3

https://docs.python.org/3/library/sys.html

**Comment by znation** [comment]
Fixed with #404.
