### ISSUE TITLE
Side information documentation returns column error

### ISSUE THREAD

**Issue by adamjgrant** [apple/turicreate#403]
When attempting to load side information into my model per

https://github.com/apple/turicreate/blob/master/userguide/recommender/using-trained-models.md#incorporating-new-side-information

    new_user_info = tc.SFrame({ 'user_id': ['New Rock'], 'median_income': ['High'] })                                                                                                        
    recommendations = model.recommend(['New Rock'], new_user_data=new_user_info) 

Despite looking identical to the documentation, I get the error

    turicreate.toolkits._main.ToolkitError: Join of side information attempted on both median_income and user_id; joining must currently be on a single column.

The error goes away if I change `'user_id'` to `'users'` in the first line, but I'm also seeing it return the same data as a name that would have no data attached to it. (E.g. Also change `'New Rock'`only  in the second line to `'Blue Rock'`, and the same data is returned).

I have verified that all my user_id columns are called user_id.

**Comment by adamjgrant** [comment]
For more context, here is how I set up my model

```
import turicreate as tc                                                                                                                                                              
sessions  = tc.SFrame.read_csv('./dataset/session_data/session_data.csv')                                                                                                            
user_data = tc.SFrame.read_csv('./dataset/session_data/user_data.csv')                                                                                                               
                                                                                                                                                                                     
training_data, validation_data = tc.recommender.util.random_split_by_user(sessions, 'user_id', 'item_id')                                                                            
model = tc.factorization_recommender.create(training_data, target='rating', user_data=user_data)                                                                                     
                                                                                                                                                                                     
model.save("recommendations.model")      
```

The column headings for user_data.csv (A "store" is a user)

```
user_id,median_income,is_in_shopping_mall,is_near_school,is_near_microsoft_store,crime_rate
```

And sessions (items)

```
user_id,item_id,rating,median_income,is_in_shopping_mall,is_near_school,is_near_microsoft_store,crime_rate,session_category
```

**Comment by TobyRoseman** [comment]
@adamjgrant - Sorry you're having this problem with Turi Create. Without seeing your data, I can't be sure what is gong on. However it looks like you have a lot of redundant information across`user_data.csv` and `session_data.csv`. Have these tables already been joined? They certainly have a lot of the same column names. There should be no overlap between these two data frames other than the id column that is being used for the join.

Removing all columns but `user_id`, `item_id` and `rating` from `sessions` should solve this problem. Also`new_user_info` will need to contain an entry for every column in `user_data`.

**Comment by adamjgrant** [comment]
Thanks for the response, @TobyRoseman 

Perhaps this is my misunderstanding of how the data ought to be set up. I see what you mean about the columns. I'll give this a try and report back. Thanks!

**Comment by TobyRoseman** [comment]
@adamjgrant - I'm going to close this issue. Feel free to reopen if you are still having problems with this issue.
