### ISSUE TITLE
Stuck on export based on 40K images and 18 classes 

### ISSUE THREAD

**Issue by PietroMessineo** [apple/turicreate#410]
Hi guys,

It's already several weeks that I'm trying everything for export my ML Model with huge dimensions in terms of images.

Since yesterday I tried everything from the beginning: I started with 10.972 pics with 5 classes an 50 iterations and everything was gone good, then I tried with 13.242 pics, same iterations and 8 classes here also the model was exported, the same on 17K with 10 classes, on 20K with 13 classes, on 32K with 15 classes, on 35K with 17 classes and then when I had 2 classes more with 42K images it was stacked, after the iterations was returning me (as always) the warning that the iterations weren't enough but this time wasn't exporting anything. I left it for more than 10hours on a server with 4 core at 3.1Ghz, 8GB of RAM and Swap enabled.

Someone have a solution? Thank you!

**Comment by TobyRoseman** [comment]
Hi @PietroMessineo -

The warning about the number of iterations might not be anything to worry about. I would evaluate your model on a test set and see how it performs. 

So the model creation is successful, but it's the exporting to Core ML where it get stuck? After 10 hours, is there still CPU usage or disk I/O?

**Comment by PietroMessineo** [comment]
Hi Toby,

If you will send your email I will be glad to give to you my dataset in this way you can try it by your own. What do you think about ? Thanks !

**Comment by yarodevuci** [comment]
@PietroMessineo how big is the mlmodel file ?
