### ISSUE TITLE
Consider making image feature extractor a public API

### ISSUE THREAD

**Issue by znation** [apple/turicreate#433]
The [image feature extractor](https://github.com/apple/turicreate/blob/39da210238b3381c74f6d6a96779fa1637c11255/src/unity/python/turicreate/toolkits/_image_feature_extractor.py#L74) is used by the image classifier and image similarity toolkits; however, it could provide useful lower-level functionality if anyone wanted to train more unique types of models on top. It would return a feature representation of images, which could potentially be useful for more use cases.

**Comment by TobyRoseman** [comment]
I'm a little hestitant to add a public API without a clear use case that we want to support. Do other people have thoughts here?

**Comment by TobyRoseman** [comment]
Dup of #1916
