### ISSUE TITLE
CoreML model Size

### ISSUE THREAD

**Issue by yarodevuci** [apple/turicreate#435]
I used Turi Create for Image classification.
I create my model like this:
`model = tc.image_classifier.create(train_data, target='label', model='squeezenet_v1.1')`

Total Images folder size is 1.2MB, trained model is 133KB, when I export to CoreML model the size is 5MB, without squeezenet_v1.1 the size is 98MB, what is going on ? can someone explain this how size is generated to be so huge?
Any possible way to make it less then 5MB?

**Comment by TobyRoseman** [comment]
@yarodevuci - take a look at our [documentation about how our image classifier works](https://apple.github.io/turicreate/docs/userguide/image_classifier/how-it-works.html). The exported model needs to contain the CNN which produces the vector representation of the images. The number of images in your training set actually does not affect the size of the model. There is currently no way for you to get a smaller exported image classifier model.

**Comment by TobyRoseman** [comment]
@yarodevuci we just released [Turi Create 5.0 in beta](https://github.com/apple/turicreate#version-50-beta). With this release you can use `VisionFeaturePrint_Screen` as the model for your image classifier. Doing this will make your exported Core ML model much smaller. The size should be approximately 40KB. Let me know if you have any questions.
