### ISSUE TITLE
Exploring sframe

### ISSUE THREAD

**Issue by rtmatx** [apple/turicreate#438]
Hi,

I have installed turicreate on a linux server and then opened notebook (on the server). I forwarded the server port on which notebook is opened to my macbook. But I couldn't use sframe.show() or explore() commands. I received the following error 

```
   4451 
   4452         if sys.platform != 'darwin' and sys.platform != 'linux2':
-> 4453             raise NotImplementedError('Visualization is currently supported only on macOS and Linux.')
   4454 
   4455         path_to_client = _get_client_app_path()

NotImplementedError: Visualization is currently supported only on macOS and Linux.
```

**Comment by znation** [comment]
Dupe of #400. This fix will ship in 4.3.
