### ISSUE TITLE
Zoom not working

### ISSUE THREAD

**Issue by abhishekpratapa** [apple/turicreate#453]
- Zoom doesn't work in visualization.

**Comment by shantanuchhabra** [comment]
@abhishekpratapa This is probably not a big deal but it just makes zooming a little annoying if you have sound on. While I can zoom in/out of the visualization now, I hear that weird sound that gets played when you try to do something that's not supported (like if you try to increase the volume beyond the highest possible volume or something). See screen recording.

[weird-sound-on-zoom.zip](https://github.com/apple/turicreate/files/1897824/weird-sound-on-zoom.zip)

**Comment by znation** [comment]
@shantanuchhabra Please open a new issue for that - sounds like the disabled-key sound somehow didn't go away even when we re-enabled zoom.
