### ISSUE TITLE
Alignment messes up when I try to go to the last row

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#458]
See repro. Also, last row has two labels.

<img width="1680" alt="screen shot 2018-04-09 at 3 26 28 pm" src="https://user-images.githubusercontent.com/14062641/38526263-6906a0e2-3c0a-11e8-9b96-06e24fc20947.png">

**Comment by afranklin** [comment]
Marking P2 assuming it repros consistently.

**Comment by TobyRoseman** [comment]
This is fixed now.
