### ISSUE TITLE
Trying to go to the last row doesn't directly take me there.

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#461]
On macOS High Sierra in the Debug build.

In the cats and dogs dataset, there are 24769 rows (0-indexed). When I try to go to row number 24769 (which doesn't exist), it takes me to row number 24712. I feel like if the user enters a row number that's greater than the last row number (24768), there should be a friendly pop up message that tells them that it's an invalid row number and that they should enter a row number less than 24768. Repro video attached.

[last-row.zip](https://github.com/apple/turicreate/files/1892179/last-row.zip)

**Comment by znation** [comment]
I think we should go to the last row if a user enters a number over that (and probably go to the first row if a negative number is entered?).
