### ISSUE TITLE
Going to the last row followed by trying to go to row 0 causes an infinite scroll from 0 downward

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#463]
On macOS High Sierra in the Debug build.

Repro: In the cats and dogs dataset, there are 24769 rows (0-indexed). When I try to go to row number 24769 (which doesn't exist), it takes me to row number 24712 (Known issue filed as #461 ). **Then, I scroll down two pages to get to the real last row. Then, I try to go to row number 0 and an infinite scroll from 0 downward occurs.** Repro attached for text in bold. Note that the repro was infinite, but I only recorded the first few seconds.

[zero-inf-scroll.zip](https://github.com/apple/turicreate/files/1892195/zero-inf-scroll.zip)

**Comment by abhishekpratapa** [comment]
- Fixed in 1803
