### ISSUE TITLE
Need Instruction for Generating hapt_data.sframe

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#468]
The [User Guide for the Activity Classifier](https://apple.github.io/turicreate/docs/userguide/activity_classifier/) does not contain instructions for generating `hapt_data.sframe` from the raw UCI data.

**Comment by TobyRoseman** [comment]
It turns out we do actually have instructions. There located [here](https://apple.github.io/turicreate/docs/userguide/activity_classifier/data-preparation.html). We should link to these before any reference to `hart_data.sframe`.

**Comment by afranklin** [comment]
Data preparation instructions are linked just before the first reference to hart_data.sframe. We can improve the flow by walking users through the data preparation by default, so they don't have to jump to another page and come back again. I'll fold this into a general API revamping issue here: https://github.com/apple/turicreate/issues/546

**Comment by igiloh** [comment]
@afrankin - this perforation step was split into a separate page on purpose.  
This is a relatively long piece of code, which has nothing to do with the AC's general wirkflow. It's a very particular case, relevant only for this specific example dataset.
