### ISSUE TITLE
User Guide: should link to our copy of mushroom.csv

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#476]
Several places in our user guide reference `mushroom.csv` and link to the UCI page. However that copy of the data does not contain column names. It also has a different file name. We should just link to [our copy of mushroom](https://github.com/apple/turicreate/blob/master/src/unity/python/turicreate/test/mushroom.csv) which has column names and the same file name.

**Comment by karthikdash** [comment]
I'll take this up. Just to be sure, https://static.turi.com/datasets/xgboost/mushroom.csv this is the copy you're talking about right?

**Comment by srikris** [comment]
Yes.

**Comment by karthikdash** [comment]
Could I just delete the occurrences of this line
" In this example, we will use the [Mushrooms dataset](https://archive.ics.uci.edu/ml/datasets/mushroom).[<sup>1</sup>](../datasets.md) "
and replace, 
data =  tc.SFrame.read_csv('mushroom.csv')
with,
data =  tc.SFrame.read_csv('https://static.turi.com/datasets/xgboost/mushroom.csv ') ?

**Comment by TobyRoseman** [comment]
@karthikdash - I like your idea, but I would do this: 
```python
data = tc.SFrame.read_csv(
    'https://raw.githubusercontent.com/apple/turicreate/master/src/unity/python/turicreate/test/mushroom.csv'
)
```

**Comment by karthikdash** [comment]
@TobyRoseman, thanks for the suggestion.
