### ISSUE TITLE
Selected entry is not selected when I scroll down and come back up

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#478]
On macOS High Sierra under Debug build. Repro attached.

[select-112.zip](https://github.com/apple/turicreate/files/1892262/select-112.zip)

**Comment by abhishekpratapa** [comment]
- Fixing these issues would require a rewrite of TC. Prioritizing the scroll behavior over the selection behavior. Removing Selection wouldn't allow individuals to copy and paste, prioritizing that functionality.
