### ISSUE TITLE
User Guide: missing ratings-data.csv

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#480]
[Four different pages](https://apple.github.io/turicreate/docs/userguide/?q=ratings-data.csv) in our user guide reference `ratings-data.csv`, but we never tell how to get it.

**Comment by karthikdash** [comment]
Hey. Can I work on this?

**Comment by TobyRoseman** [comment]
@karthikdash - thanks for offering to help, but this is probably not a good issue to start on. The dataset is not from UCI ML.

We are working on this issue and will hopefully have a solution soon.

**Comment by karthikdash** [comment]
Oh, alright. Thanks!

**Comment by afranklin** [comment]
Closing as duplicate of https://github.com/apple/turicreate/issues/97
