### ISSUE TITLE
Selected entry is selected but so are some other entries (modulo page_size, I think)

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#482]
I select entry number 1, scroll down a lot, and on my way back up, entry number 101 is selected (and subsequently gets deselected) when the previous page of images is loaded, entry number 51 is selected (and subsequently deselected). Repro attached.

[select-scroll.zip](https://github.com/apple/turicreate/files/1892263/select-scroll.zip)

**Comment by abhishekpratapa** [comment]
- Fixing these issues would require a rewrite of TC. Prioritizing the scroll behavior over the selection behavior. Removing Selection wouldn't allow individuals to copy and paste, prioritizing that functionality.
