### ISSUE TITLE
Trying to select two entire rows in table view ends up selecting many more...

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#484]
On macOS High Sierra under Debug build. It works if I end at the second column but I can't select two entire rows (including row numbers) regardless of whether I start at the top left or the bottom right. Image attached. 

<img width="1680" alt="screen shot 2018-04-09 at 4 28 46 pm" src="https://user-images.githubusercontent.com/14062641/38528137-236b7036-3c13-11e8-9340-410046d5fe38.png">

**Comment by abhishekpratapa** [comment]
- Fixing these issues would require a rewrite of TC. Prioritizing the scroll behavior over the selection behavior. Removing Selection wouldn't allow individuals to copy and paste, prioritizing that functionality.
