### ISSUE TITLE
warning: field 'm_posix_timestamp_high' will be initialized after field 'm_posix_timestamp_low' [-Wreorder]

### ISSUE THREAD

**Issue by nickjong** [apple/turicreate#486]
We cannot check for warnings in our header files and enable -Werror in part because some header files define constructors that attempt to initialize data members out of order:
```
/Users/jong/Source/turicreate/src/flexible_type/flexible_type_base_types.hpp:99:27: warning: 
      field 'm_posix_timestamp_high' will be initialized after field
      'm_posix_timestamp_low' [-Wreorder]
  inline flex_date_time():m_posix_timestamp_high(0), m_posix_timestamp_low(0),
                          ^
```
We should always write member initializer lists in the actual order of initialization, then enable -Wreorder.

**Comment by afranklin** [comment]
Fixed in #775
