### ISSUE TITLE
Top Level Python Name Space Clean Up

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#492]
The following module are exposed at the top level `turicreate` namespace and probably should be hidden:

- [x] `connect`
- [x] `cy_pylambda_workers`
- [x] `cython`
- [x] `dep`
- [x] `glconnect`
- [x] `Model`

**Comment by hoytak** [comment]
util is used and documented; the rest should be moved to their _xxxxx equivalent.

**Comment by TobyRoseman** [comment]
@hoytak thanks. I've removed that from the list. We're already tracking that issue in #1567.

**Comment by TobyRoseman** [comment]
Fixed by #1681
