### ISSUE TITLE
SFrame.show has a giant weird tooltip

### ISSUE THREAD

**Issue by znation** [apple/turicreate#495]
Repro steps:

```python
import turicreate as tc
sf = tc.SFrame.read_csv('https://docs-assets.developer.apple.com/turicreate/datasets/tc-clang-format-results.csv')
sf.show()
```

Expected: no giant weird tooltip
Actual: See screenshot

![screen shot 2018-04-09 at 5 15 35 pm](https://user-images.githubusercontent.com/5673251/38529519-09a9da0a-3c1a-11e8-821f-bd9b5fe7e5d5.png)

**Comment by shantanuchhabra** [comment]
@abhishekpratapa @znation just did a repro and while the giant weird tooltips are gone, I see this:

<img width="821" alt="screen shot 2018-04-11 at 12 53 11 am" src="https://user-images.githubusercontent.com/14062641/38603524-bd485ccc-3d22-11e8-9479-ae5a360410a6.png">

Is this usual/expected?

**Comment by abhishekpratapa** [comment]
- Unrelated Issue
