### ISSUE TITLE
Windows 10 Compability?

### ISSUE THREAD

**Issue by Errrneist** [apple/turicreate#506]
Hi,
I am here to ask about the compatibility of turicreate in windows 10. I've been taking a class that uses turicreate, and I used to own a mac. Then I sold my mac and switched to Windows 10, thinking turicreate would support Windows 10 and I made sure the Linux on Windows option is on. However when I ran pip install -U turicreate(and I made sure pip is updated) it threw me this error:
![image](https://user-images.githubusercontent.com/27667864/38581931-0c08dc02-3cc3-11e8-8a27-a6931d71c86e.png)
Then I tried fresh windows install in VMWare and got the same error.

What should I do? Or is it because turicreate simply don't support windows? (It should not be... since Graphlab Create supports windows...)

**Comment by igiloh** [comment]
Hi @Errrneist,

Windows 10 is supported only via WSL, as described in the [user guide](https://github.com/apple/turicreate#supported-platforms).
Please try with WSL.

It’s not enough to enable Linux over Windows - you need to install an actual Linux distro, and `pip install` turicreate from within Linux.
Please see WSL installation instructions in [Microsoft website](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**Comment by znation** [comment]
@Errrneist Please see @igiloh's response. Turi Create is now supported on Windows 10 only via WSL (Windows Subsystem for Linux). The installation should then follow the [Linux installation instructions](https://github.com/apple/turicreate/blob/master/LINUX_INSTALL.md), on top of a Linux distribution installed via the Windows Store. You can also read more about WSL [here](https://docs.microsoft.com/en-us/windows/wsl/about).

**Comment by doaa54321** [comment]
i am a new student in ML course and also i face a problem in installing truicreat and it seems that you fixed it can you help my by saying a Specific steps that you made ?

**Comment by technobrat** [comment]
Likewise im facing the same issue of it not installing on window 10.  I have an assignment to complete and I have tried the virtual environment aa recommended in the docs to no success.. Om getting some wheel error.. Something is wrong.

**Comment by Errrneist** [comment]
> Likewise im facing the same issue of it not installing on window 10. I have an assignment to complete and I have tried the virtual environment aa recommended in the docs to no success.. Om getting some wheel error.. Something is wrong.

I feel like what they are doing is literally saying “yo buy a MacBook you peasant“ because to my knowledge GraphLab, before it was acquired by Apple and changed its name to Turicreate had windows support.

**Comment by technobrat** [comment]
One has to jump through loops to get the package installed. What a waste.  Add that to sucky support and.... .

**Comment by Fhazhil** [comment]
I am not technically dumb; I am of moderate capability in computing and matters software. But I have endured challenges getting turicreate to work on windows 10 via wls to no avail. I only wanted it for some coursera course on machine learning. I am at this point de-registering for the course and look for another one leveraging alternative packages likescikit-learn
