### ISSUE TITLE
Bools rendered as Ints in accordion

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#512]
`True` and `False` are rendered as `1` and `0` respectively on the accordion in `data.explore()`

```
a = [True, True, False, False, True]
b = ["hello", "it's", "me", "i", "was"]
c = [9,1,2,3,4,5,6,7,8,9,0]
d = ["wondering", "if", "after", "all", "these", "years?"]
e = ["hello", "from", "the", "other side"]
f = [True]
g = [False]
h = [3.14156197823, 2.7165727, 9.801893812, 78213, 908.0]
we_are_one = tc.SArray([a,b,c,d,e,f,g,h])
we_are_one.explore()
```

Actual:

<img width="820" alt="screen shot 2018-04-11 at 5 11 17 pm" src="https://user-images.githubusercontent.com/14062641/38649429-632d8530-3dab-11e8-82d2-fcf3efe482d4.png">

Expected:

True instead of 1, False instead of 0, in the first, sixth, and the seventh columns.

**Comment by znation** [comment]
By Design - we don't actually have a boolean type in SFrame, so upon ingestion into an SArray, the True/False values are represented ints (0/1).
