### ISSUE TITLE
Installing turicreate in Python3.x

### ISSUE THREAD

**Issue by jsrpy** [apple/turicreate#514]
Has Turicreate supported python3.6?

When I am trying to do `conda install -c derickl turicreate `, it is forging the py27 version of the package. 

How should I properly install tc py36 version in my conda?

**Comment by znation** [comment]
Hi @jsrpy, where did you come across this command to install turicreate? As far as I know, it's not in our installation instructions -- and the `derickl` channel on Anaconda is **not** an official mirror of Turi Create. Glancing at what appears to be the [file list](https://anaconda.org/derickl/turicreate/files), it's only a partial mirror, containing only the Python 2.7 versions for macOS. That explains why you're getting a py27 version.

Please use `pip` to install from [PyPI](https://pypi.python.org/pypi/turicreate), our official release channel. You can follow the instructions [here](https://github.com/apple/turicreate/#installation) to install. These instructions should work within an Anaconda environment (as pip is also available there). Alternately, you can find our official releases for download at [GitHub](https://github.com/apple/turicreate/releases).

**Comment by znation** [comment]
Oh, and to answer your first question, yes, Turi Create supports Python 2.7, 3.5, and 3.6 (as of version 4.1).

**Comment by jsrpy** [comment]
OK, I am now able to install it in my virtual env.

Though I want to install it in my base conda env as well.

**Comment by znation** [comment]
@jsrpy You should be able to use the `pip install` instructions within a base conda env as well. Pip exists within conda environments.

**Comment by jsrpy** [comment]
@znation Urm I installed it by `pip3 install turicreate` and it appears under `pip3 list` but not `conda list`. I am not sure how should I specify the install location to be under `~miniconda3`.

**Comment by znation** [comment]
@jsrpy If you do `which pip` or `which pip3`, do either one point to a binary within `~/miniconda3`? (On my system with miniconda3, they do.) If you run a `pip` or `pip3` from within miniconda, the resulting installations should go into `miniconda3/lib/python<version/site-packages`.

**Comment by jsrpy** [comment]
@znation my `which pip` points to `/miniconda3/bin/pip` whereas `which pip3` points to `/Library/Frameworks/Python.framework/Versions/3.6/bin/pip3`. Does that mean a `pip` shall work for my purpose? Will it install a py27 package in my env?

**Comment by znation** [comment]
@jsrpy Yes, in that case `pip` should work. It should install the correct version for your Python environment (so if your active conda env is 3.5, it should pick 3.5).

**Comment by jsrpy** [comment]
@znation It is working now! Thanks for the help!

**Comment by znation** [comment]
@jsrpy You're welcome!

**Comment by suciokhan** [comment]
> @znation Urm I installed it by `pip3 install turicreate` and it appears under `pip3 list` but not `conda list`. I am not sure how should I specify the install location to be under `~/miniconda3`.

When I run `sudo pip3 install turicreate` using Python 3.6 on Ubuntu 17.04, I receive the following error message:
Could not find a version that satisfies the requirement turicreate (from versions: )
No matching distribution found for turicreate

**Comment by DataScienceMLTeam** [comment]
I am sorry, followed all the steps in the instruction readme but it fail to setup.
Please advise.

I am running Win 7.

**Comment by znation** [comment]
Hi @DataScienceMLTeam, please see the Supported Platforms and System Requirements in [README.md](https://github.com/apple/turicreate/blob/master/README.md#supported-platforms). We don't currently produce a Windows-native binary release of Turi Create, so to pip install on Windows 7, you would need to run something like Docker, VirtualBox, or Hyper-V (with a supported Linux distribution within it) to run Turi Create on Linux on Windows. On Windows 10, we also can run in WSL (Windows Subsystem for Linux), but that is new in Windows 10.

**Comment by lalitmach22** [comment]
Hi,
I am trying to install turicreate on my MacBook Pro with Mojave with latest anaconda(which has python 3.7), however every time I am getting an error.
Can you guide me, how to install it?
Thanks

**Comment by TobyRoseman** [comment]
@lalitmach22 - Turi Create does not yet support Python 3.7. We're still waiting for some of our dependencies to support Python 3.7. We're tracking this issue in #788

**Comment by Zulqurnain24** [comment]
Hi, when I am trying to install turi this way "pip install -U turicreate" it is giving me this stack trace \n "Failed to import the site module
Traceback (most recent call last):
  File "/opt/anaconda3/envs/turienv/lib/python3.6/site.py", line 541, in <module>
    main()
  File "/opt/anaconda3/envs/turienv/lib/python3.6/site.py", line 522, in main
    known_paths = addusersitepackages(known_paths)
  File "/opt/anaconda3/envs/turienv/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/opt/anaconda3/envs/turienv/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/opt/anaconda3/envs/turienv/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/opt/anaconda3/envs/turienv/lib/python3.6/sysconfig.py", line 608, in get_config_var
    return get_config_vars().get(name)
  File "/opt/anaconda3/envs/turienv/lib/python3.6/sysconfig.py", line 587, in get_config_vars
    import _osx_support
  File "/opt/anaconda3/envs/turienv/lib/python3.6/_osx_support.py", line 4, in <module>
    import re
ValueError: source code string cannot contain null bytes"

**Comment by TobyRoseman** [comment]
@Zulqurnain24  - Please open a new issue. Be sure to include: full pip output, python version and operating system.

**Comment by akramIOT** [comment]
Turicreate is not  getting Installed in Python 3.7 environment which is Conda Package manager based. i have tried in different ways cli , UI and  via some .whl files as well no luck.  :(

(base) C:\Users\isheriff>conda -V
conda 4.8.3
(base) C:\Users\isheriff>

(base) C:\Users\isheriff>pip -V
pip 20.0.2 from C:\Users\isheriff\Anaconda3\lib\site-packages\pip (python 3.7)

(base) C:\Users\isheriff>pip install -U turicreate
Collecting turicreate
  Using cached turicreate-6.0.tar.gz (1.9 kB)
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\isheriff\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\isheriff\\AppData\\Local\\Temp\\pip-install-yo2jeo7l\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\isheriff\\AppData\\Local\\Temp\\pip-install-yo2jeo7l\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\isheriff\AppData\Local\Temp\pip-wheel-1dgdwttw'
       cwd: C:\Users\isheriff\AppData\Local\Temp\pip-install-yo2jeo7l\turicreate\
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build\bdist.win-amd64\wheel
  running install



          ==================================================================================
          TURICREATE ERROR

          If you see this message, pip install did not find an available binary package
          for your system.

          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).

          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7


          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`

          ==================================================================================



  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\isheriff\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\isheriff\\AppData\\Local\\Temp\\pip-install-yo2jeo7l\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\isheriff\\AppData\\Local\\Temp\\pip-install-yo2jeo7l\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\isheriff\AppData\Local\Temp\pip-record-xup3cjts\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\isheriff\Anaconda3\Include\turicreate'
         cwd: C:\Users\isheriff\AppData\Local\Temp\pip-install-yo2jeo7l\turicreate\
    Complete output (28 lines):
    running install



            ==================================================================================
            TURICREATE ERROR

            If you see this message, pip install did not find an available binary package
            for your system.

            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).

            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7


            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`

            ==================================================================================



    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\isheriff\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\isheriff\\AppData\\Local\\Temp\\pip-install-yo2jeo7l\\turicreate\\setup.py'"'"'; __file__='"'"'C:\\Users\\isheriff\\AppData\\Local\\Temp\\pip-install-yo2jeo7l\\turicreate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\isheriff\AppData\Local\Temp\pip-record-xup3cjts\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\isheriff\Anaconda3\Include\turicreate' Check the logs for full command output.

(base) C:\Users\isheriff>

**Comment by znation** [comment]
Hi @akramIOT, it looks like this is because you are running on Windows. Note that the message says:
```
Supported Platforms:
            * macOS 10.12+ x86_64.
            * Linux x86_64 (including WSL on Windows 10).
```

You'll need to use some form of virtualization or WSL in order to use the Linux version of Turi Create on Windows; there is currently no native Windows support. If you are looking for the latter, follow issue #533.

**Comment by SiddhantSud** [comment]
I know the issue is that Im running python 3.8 , but i don't know the solution to this, Im student who is trying to get into machine learning and i want to use turicreate for my journey. Any help please


Collecting turicreate
  Using cached turicreate-6.0.tar.gz (1.9 kB)
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/pudhkinsud/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/98/gtkb16kx66q7t2tp_xmbqrg40000gn/T/pip-install-u1lbuy54/turicreate/setup.py'"'"'; __file__='"'"'/private/var/folders/98/gtkb16kx66q7t2tp_xmbqrg40000gn/T/pip-install-u1lbuy54/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/98/gtkb16kx66q7t2tp_xmbqrg40000gn/T/pip-wheel-0q9gnt5r
       cwd: /private/var/folders/98/gtkb16kx66q7t2tp_xmbqrg40000gn/T/pip-install-u1lbuy54/turicreate/
  Complete output (31 lines):
  running bdist_wheel
  running build
  installing to build/bdist.macosx-10.9-x86_64/wheel
  running install
  
  
  
          ==================================================================================
          TURICREATE ERROR
  
          If you see this message, pip install did not find an available binary package
          for your system.
  
          Supported Platforms:
              * macOS 10.12+ x86_64.
              * Linux x86_64 (including WSL on Windows 10).
  
          Support Python Versions:
              * 2.7
              * 3.5
              * 3.6
              * 3.7
  
  
          Another possible cause of this error is an outdated pip version. Try:
              `pip install -U pip`
  
          ==================================================================================
  
  
  
  ----------------------------------------
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/pudhkinsud/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/98/gtkb16kx66q7t2tp_xmbqrg40000gn/T/pip-install-u1lbuy54/turicreate/setup.py'"'"'; __file__='"'"'/private/var/folders/98/gtkb16kx66q7t2tp_xmbqrg40000gn/T/pip-install-u1lbuy54/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/98/gtkb16kx66q7t2tp_xmbqrg40000gn/T/pip-record-mkvxyqth/install-record.txt --single-version-externally-managed --compile --install-headers /Users/pudhkinsud/venv/include/site/python3.8/turicreate
         cwd: /private/var/folders/98/gtkb16kx66q7t2tp_xmbqrg40000gn/T/pip-install-u1lbuy54/turicreate/
    Complete output (28 lines):
    running install
    
    
    
            ==================================================================================
            TURICREATE ERROR
    
            If you see this message, pip install did not find an available binary package
            for your system.
    
            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).
    
            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7
    
    
            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`
    
            ==================================================================================
    
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/pudhkinsud/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/98/gtkb16kx66q7t2tp_xmbqrg40000gn/T/pip-install-u1lbuy54/turicreate/setup.py'"'"'; __file__='"'"'/private/var/folders/98/gtkb16kx66q7t2tp_xmbqrg40000gn/T/pip-install-u1lbuy54/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/98/gtkb16kx66q7t2tp_xmbqrg40000gn/T/pip-record-mkvxyqth/install-record.txt --single-version-externally-managed --compile --install-headers /Users/pudhkinsud/venv/include/site/python3.8/turicreate Check the logs for full command output.

**Comment by TobyRoseman** [comment]
@SiddhantSud - Hopefully we'll support Python 3.8 soon. We are tracking that issue in #3099.

Until then please use Python 3.7. I think the easiest way to do that is with a [Virtual Environment](https://docs.python.org/3/tutorial/venv.html). From the command line, you should be able to do something like this:
```bash
pip install --upgrade pip
pip install --upgrade virtualenv
virtualenv --python=python3.7 ./venv
source ./venv/bin/activate
pip install turicreate
```

**Comment by Rishav-hub** [comment]
I am using virtualenv for installation of turicreate in python 3.7 but it is showing the same error above

**Comment by TobyRoseman** [comment]
@Rishav-hub - please open a new issue. Please include your operating system and the **entire** output of `pip install turicreate`.

**Comment by Iamashishthapa** [comment]
@Rishav-hub and @TobyRoseman  this worked for me. Please try and give feedback.
python3.7 -m virtualenv myenv
source ./venv/bin/activate
pip install turicreate or pip3 install turicreate.

**Comment by ArkaBhuiyan** [comment]
I am using python 3.7 on ubuntu 20.04 and I am getting the same error messages. 

`pip install turicreate
Collecting turicreate
  Using cached turicreate-6.0.tar.gz (1.9 kB)
Building wheels for collected packages: turicreate
  Building wheel for turicreate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/arkacsedu/anaconda3/envs/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_1mmx9s3/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_1mmx9s3/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-pk3b61z2                                                                                                                                          
       cwd: /tmp/pip-install-_1mmx9s3/turicreate/                                                                                                                                              
  Complete output (31 lines):                                                                                                                                                                  
  running bdist_wheel                                                                                                                                                                          
  running build                                                                                                                                                                                
  installing to build/bdist.linux-x86_64/wheel                                                                                                                                                 
  running install                                                                                                                                                                              
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
          ==================================================================================                                                                                                   
          TURICREATE ERROR                                                                                                                                                                     
                                                                                                                                                                                               
          If you see this message, pip install did not find an available binary package                                                                                                        
          for your system.                                                                                                                                                                     
                                                                                                                                                                                               
          Supported Platforms:                                                                                                                                                                 
              * macOS 10.12+ x86_64.                                                                                                                                                           
              * Linux x86_64 (including WSL on Windows 10).                                                                                                                                    
                                                                                                                                                                                               
          Support Python Versions:                                                                                                                                                             
              * 2.7                                                                                                                                                                            
              * 3.5                                                                                                                                                                            
              * 3.6                                                                                                                                                                            
              * 3.7                                                                                                                                                                            
                                                                                                                                                                                               
                                                                                                                                                                                               
          Another possible cause of this error is an outdated pip version. Try:                                                                                                                
              `pip install -U pip`                                                                                                                                                             
                                                                                                                                                                                               
          ==================================================================================                                                                                                   
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
  ----------------------------------------                                                                                                                                                     
  ERROR: Failed building wheel for turicreate
  Running setup.py clean for turicreate
Failed to build turicreate
Installing collected packages: turicreate
    Running setup.py install for turicreate ... error
    ERROR: Command errored out with exit status 1:
     command: /home/arkacsedu/anaconda3/envs/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_1mmx9s3/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_1mmx9s3/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9k8viaae/install-record.txt --single-version-externally-managed --compile --install-headers /home/arkacsedu/anaconda3/envs/venv/include/python3.8/turicreate
         cwd: /tmp/pip-install-_1mmx9s3/turicreate/
    Complete output (28 lines):
    running install
    
    
    
            ==================================================================================
            TURICREATE ERROR
    
            If you see this message, pip install did not find an available binary package
            for your system.
    
            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).
    
            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7
    
    
            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`
    
            ==================================================================================
    
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/arkacsedu/anaconda3/envs/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_1mmx9s3/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_1mmx9s3/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9k8viaae/install-record.txt --single-version-externally-managed --compile --install-headers /home/arkacsedu/anaconda3/envs/venv/include/python3.8/turicreate Check the logs for full command output.`

**Comment by TobyRoseman** [comment]
@ArkaBhuiyan - The final line of your output contains this path: `/home/arkacsedu/anaconda3/envs/venv/include/python3.8/turicreate`. It looks like you are actually using Python 3.8. TuriCreate does not support that yet.
