### ISSUE TITLE
Plot objects display twice in Jupyter Notebook

### ISSUE THREAD

**Issue by znation** [apple/turicreate#520]
The plot object (when yielded as the output value of a cell) shows twice.

Repro steps (in Jupyter Notebook):

```python
import turicreate as tc
sf = tc.SFrame.read_csv('https://docs-assets.developer.apple.com/turicreate/datasets/tc-clang-format-results.csv')
tc.visualization.scatter(sf['Lines Added'], sf['Lines Removed'])
```

**Comment by znation** [comment]
<img width="566" alt="screen shot 2018-04-12 at 2 37 33 am" src="https://user-images.githubusercontent.com/5673251/38669160-82e09aa8-3dfa-11e8-82c6-d8c78da79dae.png">

**Comment by theavey** [comment]
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/8083606/39331348-4c68f104-4972-11e8-8980-2ec65f11e228.png">
Maybe this has been fixed, but it doesn't seem to happen for me, though I am using JupyterLab, not the older Notebook interface.

**Comment by abhishekpratapa** [comment]
Cannot repro.
