### ISSUE TITLE
Question in Logical Operator for SFrame

### ISSUE THREAD

**Issue by jsrpy** [apple/turicreate#522]
I had a little confusion between the logical operator `or` and `and` when filtering a SFrame.

Say, I want to select column x with those values between 3000 to 5000: 

`sf_filter = sf[sf['x'] > 3000] or sf[sf['x'] < 5000]
`
This one is able to produce what I want.

Whereas
`sf_filter = sf[sf['x'] > 3000] and sf[sf['x'] < 5000]
`
is doing nothing and returns all rows in the SFrame.

This is a bit counter-intuitive to what I understand in these operators. Could anyone confirms to me the meaning of these operators in this case?

**Comment by igiloh** [comment]
Hi @jsrpy,

I believe this is the correct syntax for what you're trying to achieve:
```
sf_filtered = sf[(sf['x'] > 3000) & (sf['x'] < 5000)]
```

Let me know if that solved your problem.

**Comment by jsrpy** [comment]
@igiloh That is working! Thanks!

**Comment by jsrpy** [comment]
@igiloh That is working! Thanks!
