### ISSUE TITLE
Title in API Docs goes into the right margin

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#541]
I would expect it to either be truncated (but accessible) or wrap around or be in a scrollable code box. Screenshot attached. 

<img width="1675" alt="screen shot 2018-04-17 at 10 27 33 pm" src="https://user-images.githubusercontent.com/14062641/38913315-f1832da2-428e-11e8-98cb-f49698ccf23f.png">

**Comment by afranklin** [comment]
No easy fix; merging into Documentation Redesign (https://github.com/apple/turicreate/issues/546) for longer-term fix.
