### ISSUE TITLE
Improve API docs to provide more general background

### ISSUE THREAD

**Issue by igiloh** [apple/turicreate#544]
Hi guys,

As some developers go straight to the API docs - there should be some general information and examples there.
We do have this concept for [some of the modles](https://apple.github.io/turicreate/docs/api/turicreate.toolkits.classifier.html), but can definitely improve others: [IC](https://apple.github.io/turicreate/docs/api/turicreate.toolkits.image_classifier.html), [AC](https://apple.github.io/turicreate/docs/api/turicreate.toolkits.activity_classifier.html).

We should at least add a link in every model's main API page to the relevant page in the user guide.  
Also - in some cases, we do have model description - but it's under the model's `create()` method, and not in the model's main page. Maybe it should be in both?

**Comment by afranklin** [comment]
Merging this with documentation redesign https://github.com/apple/turicreate/issues/546
