### ISSUE TITLE
how can I use DeepFeatureExtractor within turicreate?

### ISSUE THREAD

**Issue by yrik** [apple/turicreate#557]
I see DeepFeatureExtractor in graphlab, and I see it here https://github.com/apple/turicreate/blob/444fece5d095016d74161eab2bd0a1e02a524d87/src/unity/python/turicreate/test/_test_api_visibility.py#L527.

But how can I use it? Is it ported to turicreate? Is there any workaround to use this handy functionality?

In short, my main goal is to build the logistic regression model for images.

**Comment by TobyRoseman** [comment]
@yrik - we are already tracking this issue in #433. That issue has a link to the function used to extract the deep features.

Why do you want to create a logistic regression model for images? Are you trying to do image classification? If so, we have [a toolkit for that](https://apple.github.io/turicreate/docs/userguide/image_classifier/) which works by using the deep features and logistic regression.
