### ISSUE TITLE
OneHotEncoder

### ISSUE THREAD

**Issue by Varun51194** [apple/turicreate#567]
Could you please implement a Turi Create version of graphlab's [OneHotEncoder](https://turi.com/products/create/docs/generated/graphlab.toolkits.feature_engineering.OneHotEncoder.html). We're working on an assignment for CSE 416 to be released in two weeks, and would greatly appreciate it if you're able to have this feature implemented by then.

Thanks,
Varun

**Comment by hoytak** [comment]
What part of it will you be using / do you need?  

FYI, TC automatically encodes string features as 1-hot encoded features for all classification and regression models under the hood.
