### ISSUE TITLE
Continue training an object detection model

### ISSUE THREAD

**Issue by smahurkar** [apple/turicreate#569]
I have trained an object detection model with 500 images. I need to add 50 more images for training on the generated object detection model. 

Is it possible to continue training the previously generated model instead of having to retrain with 550 images?

**Comment by gustavla** [comment]
This is currently not possible. It is a great idea though, but unfortunately we currently do not support it.  I will close this issue, but it's great for us to know feature requests like this, so we will keep this in mind.

The good news is that if you have been training on a Mac, you will delighted to find that training is significantly faster in the 5.0 beta 1 (if you also have the macOS Mojave beta).

**Comment by mkhizeryounas** [comment]
> This is currently not possible. It is a great idea though, but unfortunately we currently do not support it.  I will close this issue, but it's great for us to know feature requests like this, so we will keep this in mind.
> 
> 
> 
> The good news is that if you have been training on a Mac, you will delighted to find that training is significantly faster in the 5.0 beta 1 (if you also have the macOS Mojave beta).

Any news on continuous learning on object detection?
