### ISSUE TITLE
How to improve the recognition of Object Detection?

### ISSUE THREAD

**Issue by HelloWorldYyx** [apple/turicreate#570]
I trained for multiple models. About the cup, doraemon, writing pens. Graphics in about 100-200. But did not meet the minimum requirements of I think effect. How to improve the effect of tracking, please. Thank you, thank you very much turiCreate

**Comment by gustavla** [comment]
Hi @HelloWorldYyx. First of all, sorry for the really late response. Let's try to figure out what's going on with your training and why you aren't getting the results that you were hoping to get.

My first question is how varied are your training samples? Did you capture multiple types of cups in many different situations? Do they correspond well to your testing situation? A discrepancy (even a subtle one) between your training data and testing data, is the most typical reason for getting poor results. The remedy is to identify when it is failing and trying to collect additional data that is similar to that situation.

**Comment by gustavla** [comment]
@HelloWorldYyx I'm going to close this issue due to lack of activity. If you want continue investigating this, address my questions and we can open the issue again. Thanks!
