### ISSUE TITLE
Export text classifier to Core ML

### ISSUE THREAD

**Issue by emannuelOC** [apple/turicreate#58]
I would like to export the Sentence Classifier model to Core ML. Right now I'm getting the `'SentenceClassifier' object has no attribute 'export_coreml'` error.
Is there some way to export it?

**Comment by srikris** [comment]
Unfortunately, there isn't at the moment but this one is easy to add. We will do it for the next release and add a user guide step for exporting this to Core ML. Thanks for your patience.

**Comment by znation** [comment]
Fixed with #99.
