### ISSUE TITLE
Recommender.util.compoare_models Not Plotting Metric

### ISSUE THREAD

**Issue by jsrpy** [apple/turicreate#587]
After creating two recommender models, I am trying to plot the F1 graph of them using:
`
%matplotlib inline `
`
compare = tc.recommender.util.compare_models(test_data,
                                                     [model_0,model_1],
                                                     user_sample=0.05,
                                                      make_plot=True,
                                                      metric='precision_recall'
                                                     )`

However, it is not showing any plot in my notebook.

Is there anyway I can access the precision_recall scores by `compare[0]` so that I can plot on my own?

**Comment by TobyRoseman** [comment]
@jsrpy - `tc.recommender.util.compare_models` is not intended to plot anything. Take a look at the [API doc for that function](https://apple.github.io/turicreate/docs/api/generated/turicreate.recommender.util.compare_models.html).

With the code you gave `compare_models` will be a list of length two. The first element of the list will correspond to your first model (i.e. `model_0`) and the second element will be for your other model (i.e. `model_1`) . Both of the elements of `compare` contain the precision and recall (both overall and by user) at various cutoffs.

So for example, if you are interested in overall precision for `model_0`, you can access that using:
`compare[0]['precision_recall_overall']`. This will show you both the precision and recall for all cutoff values.

Hope this helps. Let us know if you have more questions.

**Comment by jsrpy** [comment]
@TobyRoseman Okay with that I am able to access the precision/recall values. Thanks!
