### ISSUE TITLE
Activity Classifier doc improvements

### ISSUE THREAD

**Issue by regexident** [apple/turicreate#59]
I was trying to reproduce the [Activity Classifier](https://github.com/apple/turicreate/blob/master/userguide/activity_classifier/introduction.md) example by following along and quickly got stuck as the example appears to skip over the essential part of generating the contents of `hapt_data.sframe` and how to actually run the example snippet.

Apart from the missing yet crucial step from `HAPT Data Set.zip` to `hapt_data.sframe` it is also not clear to somebody new to turicreate how to invoke the example snippet.

The example falls short on a couple of questions:

- How does one generate or get ahold of the file `hapt_data.sframe`?
- Where does one have to place the `hapt_data.sframe` file?
- Where does one have to place the example's snippet? Within `~/venv/`, or outside?
- How does one actually run the example? Via `python ./activity_classifier.py`?
- Does one first have to `cd` into `~/venv/` before running the example file via `python …`?
- Where does one find the produced output (`mymodel.model` and `MyActivityClassifier.mlmodel`)?

It is very nice to have such a wide range of applications and examples for most (if not all) of them for turicreate.

But an example that cannot be followed through without prior knowledge or filling in the blanks à la `here be dragons` at the end of the day is of little to no use for anybody new to the project/codebase. 😟

**Comment by igiloh** [comment]
Hi @regexident , thank you for taking interest in the activity classifier!

The steps for building the `hapt_data.sframe` are indeed missing from the current documentation, and you can find them here: https://github.com/apple/turicreate/issues/41#issuecomment-350538212

As for file paths (csv files to be loaded, saved sframe files and saved model files) - please note that all of the methods below except any full or relative path you'll provide them:
```
sf = tc.SFrame.read_csv('some/path/some_file.csv')
sf.save('some/other/path/my_data.sf')
loaded_sf = tc.SFrame('some/other/path/my_data.sf')
model.save('new_desired_path/my_model.model`)
```

The current path your running your python from doesn't matter - as long as you provide a valid path where you want sframes\models to be saved to or loaded from.

Also, it is not required to run your python script from within a specific path (`venv `or any other). 
 The only advice is to activate the virtualenv in which you've installed turicreate by doing: `source ~/venv/bin/activate`.
After you do - feel free to write your own `.py` script or ipython notebook. Such script will usually begin with:
```
import turicreate as tc
data = tc.Sframe.read_csv('some_data.csv')
#...
model = tc.activity_classifier.create(data, ...)
#...
```

Feel free to ask for any further clarifications.

**Comment by regexident** [comment]
Hi @igiloh and thanks for the prompt response!

I just left for home, but will give it another go tomorrow morning. I’ll let you know if your additional info is enough to get started with the example and no prior experience with turicreate and/or venv.

**Comment by srikris** [comment]
@igiloh From what @regexident is suggesting, we can do a few things:

- Lets sort out #41 and make sure the example is runnable in this case
- We could also have a general guide for those that are new to Python for the other set of things that were pointed out here.

**Comment by igiloh** [comment]
@srikris - Sounds right. I've noticed you've assigned @afranklin for #41 .
I'll discuss with @znation about the second bullet, we'll agree on some format and I'll proceed from there.

**Comment by igiloh** [comment]
@regexident - great, good luck!
Note that `virtualenv` is not **required**. It's just an easier way to sort out your various python libraries. You can skip it as a first step if it give you trouble.

**Comment by coolioxlr** [comment]
a general guide for those that are new to Python can be easily googled not sure it's necessary to add it in the tutorial. Alternative you can also include jupyter file.

**Comment by srikris** [comment]
@coolioxlr That's a valid point. I wasn't implying that we add it to all tutorials. Just one place in the user guide for people who are new to Python to go to. What are your thoughts on that?

**Comment by igiloh** [comment]
I tend to agree with @coolioxlr . Adding a notebook with a simple example and clear explanations is probably the way to go here.

**Comment by regexident** [comment]
@igiloh with the missing steps from #41 and information from https://github.com/apple/turicreate/issues/59#issuecomment-350796559 it was straight forward to follow, thanks!
