### ISSUE TITLE
model.save() is silently failing if there's a tilde in the path

### ISSUE THREAD

**Issue by igiloh** [apple/turicreate#593]
It seems that `model.save()` for the AC (and maybe other models??) is not working, and also doesn't produce any error.  
The following code:
```
model = tc.activity_classifier.create(train, session_id, target ,features=features,
                                      prediction_window=50, validation_set=test ,max_iterations=10)
model.save("~/Temp/ilai.model")
del model
new_model = tc.load_model("~/Temp/ilai.model")
```
ends up with:
```
IOError: Directory ~/Temp/ilai.model does not exist
```

**Comment by igiloh** [comment]
Apparently that was a problem with "~" in the path.  
With an absolute path to home dir - it does seem to work.

But we should still raise some alarm. This went on silently and I could have completely missed the fact that the model didn't save.

**Comment by nickjong** [comment]
The model is being save: the save path is passed without validation into the C++ backend, which treats '~' as a literal path component. On the load side, we have Python code that verifies the existence of the directory at the path; this Python code is presumably performing the tilde expansion
