### ISSUE TITLE
Using Turi Create for Apple Watch motion classification

### ISSUE THREAD

**Issue by frogg** [apple/turicreate#596]
I am currently using Turi Create to classify accelerator and gyroscope movement data from the Apple Watch (I have a [Apple Watch climbing fitness tracker](https://itunes.apple.com/us/app/iredpoint-bouldering-tracker/id1324072645?ls=1&mt=8) app which uses this functionality).

1. First, I recorded training data using the Apple Watch.
2. Then I labeled it and put it into Turi Create.
3. In the end I generated a CoreML model which somehow works 💯 

My questions now are: 
- Is Turi Create optimized for Apple Watch classification? 
- Is it important on which body part the device is located? In the demos I've only seen iPhone-like devices in the pocket.
- What if I recorded training data on the left wrist and someone wears their watch on the right wrist?
- Which parameters of `CMDeviceMotion` would be best to feed into Turi Create? Right now I use `.userAcceleration` and `.rotationRate`.

**Comment by igiloh** [comment]
Hi @frogg 

I'm glad to hear that you're finding Turi Create helpful for building your AI powered app!  
Have your tried the [activity classification toolkit](https://apple.github.io/turicreate/docs/userguide/activity_classifier/)? It's designed specifically for this kind of tasks.

Let me try to answer all of your questions:
> Is Turi Create optimized for Apple Watch classification?

TC is degined to support any kind of ML task, on a variety of OSes and devices.  
Having said that - the ability to easily create Core ML models makes it a perfect tool for creating powerful Apple Watch, iOS and macOS applications.  
Activity classifcation using Apple Watch and iPhone sensors was of course tested and demonstrated to be an exelnet use case for TC.
> Is it important on which body part the device is located? In the demos I've only seen iPhone-like devices in the pocket.
What if I recorded training data on the left wrist and someone wears their watch on the right wrist?

As in any machine learning model, training on a wide range of scenarios would asisst the model to generalize and get better results.  
It hard to tell how a model would behave before actually testing it - but of course that introducing a completely different scenario on inference, which the model never had the chance to train on, is likely to produce poorer results.
> Which parameters of CMDeviceMotion would be best to feed into Turi Create? Right now I use `.userAcceleration` and `.rotationRate`?

We generally don't tend to advise on project specific details.  
On a general note - some classification tasks would benefit from using calbrated readings, such as `.userAcceleration` and `.rotationRate`, while others would produce better results by using raw sensors readings such as `.CMGyroData`.  
My best advice would be to try both approaches (no point in intermixing them, as they're corelated with each other), and see what works best for your use case.

Feel free to approach with any more questions and clarifications!

**Comment by srikris** [comment]
@igiloh @frogg For this 'What if I recorded training data on the left wrist and someone wears their watch on the right wrist?', it should be quite easy on the client side to transform the data (x, y, z) to assume its all left hand crown out. Its a simple transformation. That way, you can collect and train all your data with left hand and crown out but during deployment time, transform the data on the client side and give it to the model.

**Comment by frogg** [comment]
Hey Krishna and Ilai, thanks a lot for your responses!

> That way, you can collect and train all your data with left hand and crown out but during deployment time, transform the data on the client side and give it to the model.

I like the idea of standardizing the data by transforming it. That's probably what I'm going to do to improve the quality for everyone. Shouldn't something like this be part of WatchKit already? Or maybe watchOS is already secretly converting the values, I should definitely check that 😬

> Activity classifcation using Apple Watch and iPhone sensors was of course tested and demonstrated to be an exelnet use case for TC.

It's great to hear that it's optimized for Apple Watch. I was never 100% sure because I didn't read it in the documentation – but the whole pipeline already seemed to work. Thanks for clarifying!

> My best advice would be to try both approaches (no point in intermixing them, as they're corelated with each other), and see what works best for your use case.

Ok I really want to try different approaches now so see what works out best.
My general question about this is how the whole SFrame thing works – do you have any documentation on this (beyond [this](https://github.com/apple/turicreate/blob/d47cb5ef3e4a1d3d4f00d1cd3d526c6696e6b377/userguide/activity_classifier/advanced-usage.md))? So far this was hard for me to understand how I would train on data that is different form the sample (gyroscope & accelerometer) because I did not understand how SFrame works in detail (for example I'm thinking to include barometer values).

**Comment by srikris** [comment]
See [this](https://github.com/apple/turicreate/tree/d47cb5ef3e4a1d3d4f00d1cd3d526c6696e6b377/userguide/sframe) for some more details on using SFrame.

Just out of curiosity, have you already deployed this model in the App Store?
