### ISSUE TITLE
train on Apple, predict on Raspberry pi

### ISSUE THREAD

**Issue by luto65** [apple/turicreate#599]
It would be great if models built on MacOS  could be deployed on raspberry pi.

**Comment by luto65** [comment]
Not needed since one can use NNVM
http://nnvm.tvmlang.org/tutorials/from_coreml.html#load-pretrained-coreml-model

**Comment by vashat** [comment]
+1. NNVM seams too complicated. It would be nicer to predict with turi instead on the raspberri pi. Tried to compile from turi source but get compile errors.

**Comment by TobyRoseman** [comment]
@luto65 @vashat - Are you not able to just `pip install -U turicreate`? Is there a reason you need to compile from source?

**Comment by srikris** [comment]
@TobyRoseman This would be to compile and run the models on the Raspberry Pi.

**Comment by vashat** [comment]
@TobyRoseman when I run:

pip install -U turicreate

I get:

Collecting turicreate
  Downloading https://files.pythonhosted.org/packages/db/54/167837569bcb816b3fe68f003f18d07ab9d5ac31b2b12b8f9b07b1ccc7a4/turicreate-4.2.tar.gz
Installing collected packages: turicreate
  Running setup.py install for turicreate ... error
    Complete output from command /home/pi/.pyenv/versions/3.5.1/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-lxbadvb1/turicreate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-8njmxf72/install-record.txt --single-version-externally-managed --compile:
    running install
    
    
            ==================================================================================
            ERROR
    
            If you see this message, pip install did not find an available binary package
            for your system. Supported platforms are:
    
            * Linux x86_64 (including WSL on Windows 10).
            * macOS 10.12+ x86_64.
            * Python 2.7, 3.5, or 3.6.
    
            Other possible causes of this error are:
    
            * Outdated pip version (try `pip install -U pip`).
    
            ==================================================================================
    
    
    
    ----------------------------------------
Command "/home/pi/.pyenv/versions/3.5.1/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-lxbadvb1/turicreate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-8njmxf72/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-lxbadvb1/turicreate/
