### ISSUE TITLE
User guide not displaying important equations

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#607]
The background section of [this doc](https://apple.github.io/turicreate/docs/userguide/supervised-learning/logistic-regression.html) should display two important equations in the `background` section. However they are not showing up. At first glance [the markup](https://github.com/apple/turicreate/blob/master/userguide/supervised-learning/logistic-regression.md) looks ok to me. Also other (simpler) markup is getting displayed correctly.

**Comment by znation** [comment]
@TobyRoseman The equations in the background section look right to me. Can you post a screenshot of what they look like for you? I wonder if this is a browser-specific issue.

**Comment by TobyRoseman** [comment]
Looks like this was an issue with my browser.

**Comment by znation** [comment]
@TobyRoseman Even if it's browser specific, it could still be an issue in our userguide. If you can repro it again, take note of what browser/version you're using.
