### ISSUE TITLE
image_analysis.load_images(...) should give error if path does not exist

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#612]
This returns an empty SFrame: `tc.image_analysis.load_images('/thisDoesNotExist/')`

**Comment by bvsravikiran** [comment]
Can I work on this issue?

**Comment by bvsravikiran** [comment]
@TobyRoseman In the file **image_analysis.py**, using **path.isdir** from **os**, I tried to check if the directory exists. I just wanted to know if my approach is correct.

**Comment by TobyRoseman** [comment]
@bvsravikiran - that would work. However that Python code just wraps a [C++ function](https://github.com/apple/turicreate/blob/cecbcbcd8ce07ef1c614e09b7bb50882f61ff986/src/unity/lib/image_util.hpp#L41). That C++ function is used else where, like in our [C APIs](https://github.com/apple/turicreate/blob/master/src/capi/impl/capi_flex_image.cpp#L32).

So it would be better to make the change in the [C++ code](https://github.com/apple/turicreate/blob/cecbcbcd8ce07ef1c614e09b7bb50882f61ff986/src/unity/lib/image_util.cpp#L238). I would also recommend creating a [unit test](https://github.com/apple/turicreate/blob/master/src/unity/python/turicreate/test/test_image_type.py) for this case.

**Comment by shantanuchhabra** [comment]
@TobyRoseman Just to make sure I understand, would you like to see a unit test in addition to some more error handling [here](https://github.com/apple/turicreate/blame/master/src/unity/lib/image_util.cpp#L182)?

**Comment by TobyRoseman** [comment]
@shantanuchhabra - I'm not sure where exactly the best place would be to make the change. I would suggest writing the unit test cases first. Verify that they fail (i.e. do not give an error) then working backwards to the fix.

Off the top of my head, you're probably going to want at least three test cases for paths that do not exist: a directory, absolute path and relative path. I'd guess this is going to require checks in at least a couple of different places.

**Comment by NicholasMorris** [comment]
Has this has been fixed? When attempting to replicate the issue by running `tc.image_analysis.load_images('/thisDoesNotExist/')` the following error is raised:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "turicreate/release/src/unity/python/turicreate/toolkits/image_analysis/image_analysis.py", line 60, in load_images
    recursive, ignore_failure, random_order)
  File "turicreate/release/src/unity/python/turicreate/extensions.py", line 170, in <lambda>
    return lambda *args, **kwargs: _run_toolkit_function(fn, arguments, args, kwargs)
  File "turicreate/release/src/unity/python/turicreate/extensions.py", line 159, in _run_toolkit_function
    raise _ToolkitError(ret[1])
turicreate.toolkits._main.ToolkitError: /thisDoesNotExist/ not found.
```

**Comment by TobyRoseman** [comment]
Confirmed. The issue is fixed in master. 

@NicholasMorris - thanks for letting us know.
