### ISSUE TITLE
Error when using `validation_set='auto'` in Activity classifier

### ISSUE THREAD

**Issue by igiloh** [apple/turicreate#614]
Creating an activity classifier model with `validation_set='auto'` (which is the default) give an error:
```
  File "/Users/ilaigiloh/anaconda2/envs/TC4/lib/python2.7/site-packages/turicreate/toolkits/activity_classifier/_activity_classifier.py", line 190, in create
    validation_set = validation_set.filter_by(target_map.keys(), target)
  File "/Users/ilaigiloh/anaconda2/envs/TC4/lib/python2.7/site-packages/turicreate/data_structures/sframe.py", line 4371, in filter_by
    column_name + "' in SFrame.")
TypeError: Type of given values does not match type of column 'activity' in SFrame.
```
This will only happen if the dataset has more than 100 different sessions. For smaller datasets we currently don't create a validation set at all (by design).

**Comment by iAmNaz** [comment]
Is there a workaround until it is fixed? I am trying to train more than a 100 sessions at the moment

**Comment by igiloh** [comment]
Hi @iAmNaz,

As a matter of fact - I've just finished fixing this bug, the fix is coming up in a few hours 😀.

As for a workaround - there are two simple options:
1. When you're calling  `create()`  - pass in the param `validation_set=None`. This will train the model without a validation set.
2. Use your own validation set. If you've already saved aside a few of the training sessions - just pass them in as another SFrame, to the `validation_set` param.
For example:
```
train = tc.SFrame(sessions_1-200.csv)
valid = tc.Sframe(sessions_201-250.csv)
model = tc.activity_classifier.create(train, ... , validation_set=valid)
```
Make sure to pass in whole sessions (don't split the same session between test and valid) and have even distribution of the target labels (e.g. "walking", "running" etc) in both training and validation sets.

**Comment by iAmNaz** [comment]
@igiloh I was able to process 192 sessions thanks to the second solution you shared! 😀
