### ISSUE TITLE
"Using CPU to create model" in Object Detection example on Turi Create 5.0b

### ISSUE THREAD

**Issue by borderlineinteractive** [apple/turicreate#630]
Hi,

just tried the Object Detection example after installing the new beta version that should support Mac GPUs and got the following message:

Using CPU to create model

Is the GPU only supported for inference?

These are my system specs:

iMac (Retina 5K, 27-inch, 2017)
3,8 GHz Intel Core i5
32 GB 2400 MHz DDR4
Radeon Pro 580 8192 MB

running on macOS High Sierra 10.13.5

Thank you very much.

**Comment by srikris** [comment]
The new GPU acceleration is available on MacOS 10.14 beta. Not on 10.13.5. There is a typo in our readme. We'll correct it.

**Comment by srikris** [comment]
The change is now reflected in the README. Thanks for trying it out!

**Comment by mdenty** [comment]
@srikris GPU is still for 10.13 in https://apple.github.io/turicreate/docs/userguide/image_classifier/advanced-usage.html
in Using GPUs section.
