### ISSUE TITLE
Error when following installation instructions

### ISSUE THREAD

**Issue by jonhull** [apple/turicreate#631]
When I follow the installation instructions from this project, I get the following errors:

**After typing: pip install -U turicreate**
Could not fetch URL https://pypi.python.org/simple/turicreate/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement turicreate (from versions: )
No matching distribution found for turicreate

**After typing: pip install turicreate==5.0b1**
Could not fetch URL https://pypi.python.org/simple/turicreate/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement turicreate==5.0b1 (from versions: )
No matching distribution found for turicreate==5.0b1

**Comment by yousifKashef** [comment]
Had the same problem. Updating pip worked for me. Good luck!

**Comment by srikris** [comment]
@jonhull Thanks for letting us know what the solution was. I'm closing this for now.
