### ISSUE TITLE
Text classification has wrong instruction

### ISSUE THREAD

**Issue by avlaskin** [apple/turicreate#633]
1. We trained a text classification model using:
`model = tc.sentence_classifier.create(train, target_key, features=predictors)`

2. At the end of the trining we got a message:
`
TERMINATED: Iteration limit reached.
This model may not be optimal. To improve it, consider increasing `max_iterations`.
`
3. We tried to retrain the model using following parameters:
`model = tc.sentence_classifier.create(train, target_key, features=predictors, max_iterations=20)`
got an error:
`TypeError: create() got an unexpected keyword argument 'max_iterations'`

Essentially the instruction is wrong. Version of Turi is the following:
turicreate-4.3.2-cp36-cp36m-macosx_10_12_intel.macosx_10_12_x86_64.whl

**Comment by srikris** [comment]
Thanks for catching the issue. We will add this parameter to the sentence classifier.

**Comment by znation** [comment]
Fixed with #637.
