### ISSUE TITLE
Import fails for 5.0b1 on macOS 10.12

### ISSUE THREAD

**Issue by jonhull** [apple/turicreate#634]
I installed the beta (5.0b1) following the instructions from this project. When I try to run the line:
`import turicreate as tc`
I get the following error:
```
> ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5e19a42750e5> in <module>()
----> 1 import turicreate as tc

/Users/jon/Projects/Stylize/turiEnv/lib/python2.7/site-packages/turicreate/__init__.py in <module>()
     17 from turicreate.version_info import __version__
     18 
---> 19 from turicreate.data_structures.sgraph import Vertex, Edge
     20 from turicreate.data_structures.sgraph import SGraph
     21 from turicreate.data_structures.sarray import SArray

/Users/jon/Projects/Stylize/turiEnv/lib/python2.7/site-packages/turicreate/data_structures/__init__.py in <module>()
     16 
     17 from . import image
---> 18 from . import sframe
     19 from . import sarray
     20 from . import sgraph

/Users/jon/Projects/Stylize/turiEnv/lib/python2.7/site-packages/turicreate/data_structures/sframe.py in <module>()
     14 from __future__ import division as _
     15 from __future__ import absolute_import as _
---> 16 from ..connect import main as glconnect
     17 from ..cython.cy_flexible_type import infer_type_of_list
     18 from ..cython.context import debug_trace as cython_context

/Users/jon/Projects/Stylize/turiEnv/lib/python2.7/site-packages/turicreate/connect/main.py in <module>()
     11 from __future__ import absolute_import as _
     12 
---> 13 from ..cython.cy_unity import UnityGlobalProxy
     14 from ..cython.cy_server import EmbeddedServer
     15 

ImportError: dlopen(/Users/jon/Projects/Stylize/turiEnv/lib/python2.7/site-packages/turicreate/cython/cy_unity.so, 2): Symbol not found: _syslog$DARWIN_EXTSN
  Referenced from: /Users/jon/Projects/Stylize/turiEnv/lib/python2.7/site-packages/turicreate/cython/../libunity_shared.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/jon/Projects/Stylize/turiEnv/lib/python2.7/site-packages/turicreate/cython/../libunity_shared.dylib
```

**Comment by jonhull** [comment]
I should also mention that I created a new virtual environment and reinstalled everything again, and still end up with the same issue...

**Comment by srikris** [comment]
@jonhull What version of XCode and MacOS are you on? Seems there is something off there.

If you are having issues with system python, I'd recommend giving Miniconda (https://conda.io/miniconda.html ) a spin.

**Comment by gustavla** [comment]
Error message is partially the same as in #256. @znation What was the fix then?

**Comment by znation** [comment]
I think the issue here is that 5.0b1 seems to have broken compatibility with macOS 10.12 - the symbol `_syslog$DARWIN_EXTSN` is not found. Other issues of this type (on other projects) tend to show the message [`built for Mac OS X 10.13`](https://github.com/mattrajca/sudo-touchid/issues/26), but I'm not sure why that text doesn't appear here. I'll retitle the issue to reflect that.

**Comment by jonhull** [comment]
I updated to 10.13.5 and it is working now, so it does seem to be an issue with 10.12.

**Comment by kamarshad** [comment]
Hello @znation 
I am also facing the same issue as I am running `import turicreate as tc` code on `jupyter notebook`
getting the same import error. 
**Note** 
Mac OS version  --->  `10.12.6`. 
Python version  ---> `3.6`

Is there anyway I can use the turcreate 5.0 (Beta) on my machine?

**Comment by znation** [comment]
I'm investigating this now.

**Comment by kamarshad** [comment]
Ok, Thank you @znation

**Comment by znation** [comment]
I tracked it down: looks like `libcrypto.a` from OpenSSL is built for 10.14 by default now (and happens to still work on 10.13):

```

**Comment by znation** [comment]
@nickjong Assigning to you per our discussion.
