### ISSUE TITLE
Style Transfer... Mac GPU option?

### ISSUE THREAD

**Issue by enzyme69** [apple/turicreate#635]
I am testing turicreate==5.0b1  following your video at WWDC 2018, and trying to make "Style Transfer" model. When executed and processing, it seems like it is utilizing CPU by default. Is there a way to force use GPU? Thanks!

Using CPU, 1000 iterations is around 10+ hours on my MacBookPro 2017 with Touch Bar.

Similar to: https://github.com/apple/turicreate/issues/630

**Comment by igiloh** [comment]
Hi @enzyme69, I'm glad to hear you're already enjoying the new style transfer toolkit!
Mac GPU training is a new feature, supported in macOS 10.14. Please install the macOS to 10.14 beta if you want to try out GPU training already today.

Once on 10.14, GPU training should be the default. You can always turn it on\off by changing `config.set_num_gpus()`

**Comment by enzyme69** [comment]
Yes MacOS 10.14 beta is installed. Will try now cheers~

**Comment by enzyme69** [comment]
I am sure I got all the latest beta. Does it need Python 3.6? I am using 3.5 with Jupyter Notebook, maybe Conda Install.

**Comment by srikris** [comment]
Sorry for the late response. Style transfer is currently CPU only on Mac. We will be working to add GPU support to it over time. Sorry for the trouble.

**Comment by josefgrunig** [comment]
Any roadmap/deadline for this feature? 
The style transfer task is useless without GPU acceleration

**Comment by nickjong** [comment]
Yeah, the current implementation is really designed around MXNet, which is only GPU accelerated on Linux with Nvidia. We're still working through a Metal Performance Shaders implementation for macOS, but this at least requires some macOS-level blocking issues to be resolved....

**Comment by josefgrunig** [comment]
Thank you for the answer, meanwhile I got it working on Google Colab with GPU acceleration.

**Comment by AugustRush** [comment]
any update?

**Comment by syoutsey** [comment]
Hi @enzyme69, this feature was released as part of Turi Create 5.8. We'll close this issue and if you see issues please create a new issue. Thanks!
