### ISSUE TITLE
Make source install easier for Python 3.6

### ISSUE THREAD

**Issue by gustavla** [apple/turicreate#642]
When building from source on Python 3.6, there are three packages where we use a version that does not have a py36 wheel, but could really need one: numpy, cython, scikit-learn

Packages like numpy and scikit-learn takes a really long time to build. Cython is probably quicker, but actually fails for me since its `setup.py` tries to import `numpy`, which has not been installed yet. I think there are two easy solutions and one a bit ugly, but I'll throw it in anyway:

## 1 
For loop over the requirements, to ensure numpy is properly installed first before proceeding with cython. Like this:

```diff
diff --git a/scripts/install_python_toolchain.sh b/scripts/install_python_toolchain.sh
index 9f7cf4efc..5be6c3034 100755
--- a/scripts/install_python_toolchain.sh
+++ b/scripts/install_python_toolchain.sh
@@ -52,7 +52,9 @@ function download_file {
 } # end of download file
 
 $python_scripts/$PIP install --upgrade "pip>=8.1"
-$python_scripts/$PIP install -r scripts/requirements.txt
+for package in $(cat scripts/requirements.txt); do
+  $python_scripts/$PIP install $package
+done
 
 mkdir -p deps/local/lib
 mkdir -p deps/local/include
```
This should fix the build (both now, and possibly later when py37 ruins everything again), but it will still be slow.

## 2
Second solution is to bump the versions so that they support py36 wheels. These are actually modest bumps that I don't think will affect testing much. Especially numpy, which is a patch bump:

- numpy: 1.11.1 -> 1.11.3
- cython 0.24 -> 0.25.2
- scikit-learn 0.17.1 -> 0.18.1

## 3 (the ugly one)
It's also easy to do versions conditioned on the Python. I don't really suggest this as a solution, but it could be used in corner cases where we really want to test with a version in one python that is tricky to install on another python. This is actually what I've been doing locally, just to conform to the defaults in my py2 environment, while still making my py3 install a breeze:

```diff
diff --git a/scripts/requirements.txt b/scripts/requirements.txt
index b15b9a639..b6211e8c6 100644
--- a/scripts/requirements.txt
+++ b/scripts/requirements.txt
@@ -1,7 +1,9 @@
 coremltools==2.0b1
 scipy==0.19.1
-numpy==1.11.1
-cython==0.24
+numpy==1.11.1; python_version < '3.6'
+numpy==1.11.3; python_version >= '3.6'
+cython==0.24; python_version < '3.6'
+cython==0.25.2; python_version >= '3.6'
 Jinja2==2.8
 argparse==1.2.1
 decorator==4.1.2
@@ -12,7 +14,8 @@ pillow==5.0.0
 prettytable==0.7.2
 pytz==2016.3
 requests>=2.9.1
-scikit-learn==0.17.1
+scikit-learn==0.17.1; python_version < '3.6'
+scikit-learn==0.18.1; python_version >= '3.6'
 six==1.10.0
 statsmodels==0.8.0
 wheel==0.29.0
```
---
I suggest using solution 1 *and* 2, and 3 only if there is strong reason to keep one of the package versions exactly as is.

**Comment by znation** [comment]
P.S. I agree, let's not do fix 3.

**Comment by gustavla** [comment]
@znation With fix 2 we would not fix 1 right away, yes. Once py37 is released we could be back to square one though. I agree that  `-r requirements.txt` should work if all packages declare install requirements properly. They don't now, but we can hope that they will in the future.

This is what I was hitting: https://github.com/scikit-learn/scikit-learn/issues/4164

If I compare the `setup.py` in version 0.17.1  with master, it looks like they have taken steps to address this issue. However, this fix was made after 0.18.1 for instance, so if we bump to that version now, it will definitely break again for py37.

**Comment by znation** [comment]
@TobyRoseman Did this get addressed as part of the work to build and run on Python 3.7?

**Comment by TobyRoseman** [comment]
Thanks @znation - yes, this is now fix. We basically went with solution 2 (although the exact versions we picked are somewhat different).
