### ISSUE TITLE
Creating image classifier on a folder with hidden thumbnails file crashes

### ISSUE THREAD

**Issue by igiloh** [apple/turicreate#644]
Training an IC model on a main dir, containing sub dirs with images per class.
If the main directory had a `.ds_store` file - the training just crashed with an error (not warning).

It happened during a lab at WWDC. I'll repro the scenario and add the exact error and repro steps.

**Comment by znation** [comment]
@igiloh Assigned to you, to repro and fill in repro steps.

**Comment by TobyRoseman** [comment]
I am not able to reproduce this issue in `5.0b1`.

When the images are loaded. I do the following warning: `Unsupported image format. Supported formats are JPEG and PNG	 file: /tmp/data/.DS_Store`.

The image classifier model gets created fine.

@igiloh - if this is still an issue please reopen with repro set.
