### ISSUE TITLE
use try and except block around StopIteration or avoid StopIteration completely

### ISSUE THREAD

**Issue by shreyasvj25** [apple/turicreate#647]
`StopIteration` is deprecated from python3.6+, https://docs.python.org/3.6/whatsnew/3.6.html#deprecated-python-behavior 

As per https://www.python.org/dev/peps/pep-0479/ we should not use `raise StopIteration` on generators.
See #636

**Comment by dhivyaaxim** [comment]
@znation @TobyRoseman Please assign this ticket to me as I would like to try fixing it and contribute. Thanks in advance!
