### ISSUE TITLE
Turi Create Visualization in 5.0b1 broken on macOS 10.13

### ISSUE THREAD

**Issue by znation** [apple/turicreate#652]
The visualization app seems to have been built for a macOS 10.14+ target. It refuses to run on 10.13 in 5.0b1.

**Comment by zoecarver** [comment]
Still is not working for me. I am trying to visualize ~150 images.

**turicreate:** 5.1
**MacOS:** 10.13.5

**Comment by znation** [comment]
@zoecarver What happens for you on 10.13.5? If you see a loading screen indefinitely, you are probably hitting https://github.com/apple/turicreate/issues/88 instead of this one.

**Comment by zoecarver** [comment]
I think that was the issue. When I changed the shape of my image SFrame it seemed to work. Might be nice to have an error instead of indefinite loading.

**Comment by znation** [comment]
Thanks @zoecarver - we'll continue to track that issue in #88. It's proven to be very difficult to reproduce; once we are able to reproduce it, we should be able to load correctly (rather than erroring, or loading indefinitely).

**Comment by zoecarver** [comment]
@znation Thanks for the info. I will let you know if I find a good way to reproduce it.

**Comment by heikohaensel** [comment]
@znation I'm trying to build an example (https://becominghuman.ai/machine-learning-your-first-object-detection-58581795c246) using turicreate on my Macbook Pro 13", but I'm running in to this issue with visualization. Is there a solution or a workaround meanwhile?

**Comment by znation** [comment]
@heikohaensel I assume you are referring to the loading screen, as in issue #88? So far, we have not found any workaround or fix, and I have been unable to consistently reproduce the issue. Keep an eye on that thread for any updates as we learn more.
