### ISSUE TITLE
Adjust strength/amount of style transfer and/or change model to get a different effect

### ISSUE THREAD

**Issue by enzyme69** [apple/turicreate#653]
Not sure if this is documented or not, but I am curious whether "Style Transfer" in Turi Create is always "Resnet" model?

Schema
------
Model                                    : resnet-16
Number of unique styles                  : 12
Input image shape                        : (256, 256)

Is there alternative or ways to use different "training" so that the resulting image is less of filter, but much more unusual, maybe like Deep Dream or Pikazo?

**Comment by enzyme69** [comment]
My result so far using just a couple of CONTENT and STYLE:
<img width="353" alt="screen shot 2018-06-12 at 11 51 48 am" src="https://user-images.githubusercontent.com/3952687/41265738-078035ae-6e37-11e8-8d5d-1a4134ee9c71.png">

They are nice, but a bit like filter. I like to take it to another level, but I wonder if that's something to do with "iteration" or different "resnet" library?

Because "Deep Dream" produces a much complex result?

**Comment by enzyme69** [comment]
Can we increase the strength of style or maybe change resnet to vgg or something better? I am a bit new with this, but curious. Thanks!

**Comment by srikris** [comment]
Thanks for the feedback. We've definitely been experimenting with style strengths as well. Can you share the style images that you used to create this model and we can experiment in parallel. Thanks for your feedback!

**Comment by enzyme69** [comment]
<img width="1008" alt="screen shot 2018-06-12 at 12 14 05 pm" src="https://user-images.githubusercontent.com/3952687/41266421-2017cd86-6e3a-11e8-9eb1-3c58db40bf7f.png">

Basically just around 14 images of this artworks by "Yoji Shinkawa" (Metal Gear Soldier illustrator). Probably copyrighted.

Some of the filter looks quite ok distinctive, but more like filter of OpenToonz (Python Chainer).

Would be cool to be able to go beyond filter look but a little more abstract.

**Comment by enzyme69** [comment]
Below are some results I could achieve a few years ago using Pikazo app and their cloud processing:

<img width="943" alt="screen shot 2018-06-12 at 12 17 44 pm" src="https://user-images.githubusercontent.com/3952687/41266527-a431c734-6e3a-11e8-972f-7111d35e3e16.png">
<img width="531" alt="screen shot 2018-06-12 at 12 17 36 pm" src="https://user-images.githubusercontent.com/3952687/41266529-a467ab92-6e3a-11e8-933a-ed9991a5c161.png">

How to actually use different "library" that is not "resnet" using TuriCreate?

**Comment by shreyasvj25** [comment]
@enzyme69 Thank you for your feedback.
* You should probably run for `more iterations` to increase the strength of style and use the following debug mechanism.
```
params={'print_loss_breakdown': True}
model = turicreate.style_transfer.create(style, content, _advanced_parameters=params)
```   
  And verify that the Style Loss decreases and saturates after enough iterations are completed.
  
* Another option is to increase the style loss multiplier
```
params={'style_loss_mult': [1e-2, 1e-2, 1e-2, 1e-2]}
model = turicreate.style_transfer.create(style, content, _advanced_parameters=params)
```

**Comment by enzyme69** [comment]
@shreyasvj25 Thanks for the tips, I am now running 5000 iterations on CPU Mac, been running for over a day, will be completed on Thursday, hoping for magic.

I might actually need more "contents" and "style" images for training, not sure if that will increase the training times. Really need gpu at some point.

After MLM model is generated and exported, I can easy load it, but is there a parameter that I could use to perhaps apply the style in a different ways?

**Comment by enzyme69** [comment]
A bit of note for anyone trying to run on CPU 5000 iterations:
- Perhaps 5000 is not always the default
- 5000 took me around 2 days
- 1000-1600 iterations is probably enough. 5000 is so much cleaner less noise, but overall look is similar.
- 100 iterations will give just a standard filter like.

I am not achieving mosaic look, however, getting some really nice comic and watercolor look, when using Gustav Klimt artworks as Style.

**Comment by shreyasvj25** [comment]
Can you try using more mosaic looking images for style images like the ones we have in [userguide](https://apple.github.io/turicreate/docs/userguide/style_transfer/)?
Also try using data augmentation and tune `style_loss_mult ` as mentioned in  #848
