### ISSUE TITLE
Training progress is interrupted when I try to reduce max_iterations

### ISSUE THREAD

**Issue by NSEGeorge** [apple/turicreate#659]
Hi. To avoid long time for training style_transfer model, I tried to reduce max_iterations to 10. But after 2 iterations progress stoped and nothing happened for a long time.
MacOS: 10.14
Turicreate: 5.0b1

Iteration    Loss         Elapsed Time
1              298.955          20.9
2              281.056          68.9

**Comment by TobyRoseman** [comment]
@NSEGeorge - I'm going to close this issue. If it's not the same as #636, please reopen.
