### ISSUE TITLE
objcapi needs Objective-C unit tests

### ISSUE THREAD

**Issue by afranklin** [apple/turicreate#663]
We should run Objective C unit tests (and CAPI unit tests for that matter - if we don't currently) as part of the build.

This would have caught the mismatch in TCRecommender between input/output types and what the model was accepting/returning, for instance, if we had a TCRecommender unit test that went through the real Objective C API (including codegen). That's now possible since the APIs are stable across the OS and Xcode/SDKs.

**Comment by znation** [comment]
N/A - the ObjC layer ended up very simple and we have sufficient test coverage on the C API layer.
