### ISSUE TITLE
Style transfer: make coreml model to have flexible shape input/output

### ISSUE THREAD

**Issue by afranklin** [apple/turicreate#665]
First, it's not clear from the docstring whether it is (width, height) or (height, width). Internally, we often use (height, width) for implementation details. However, in for instance `tc.image_analysis.resize` the `width` argument precedes the `height` argument. So, we should first think about which is the most appropriate from a user point of view and then make this clear in the docstring.

We could also try to avoid this issue by separating into separate `width` and `height` parameters.

**Comment by shreyasvj25** [comment]
We can keep default image_shape=(255, 255) and extend the coreml model to have flexible input and output shape
