### ISSUE TITLE
Style transfer: Investigate and fix green/purple diagonal lines

### ISSUE THREAD

**Issue by afranklin** [apple/turicreate#666]
Lots of result images get diagonal green/purple lines. Let's try to investigate and fix this, if possible.

![screen_shot_2018-05-29_at_1 12 53_pm](https://user-images.githubusercontent.com/455404/41440811-e447b03a-6fe4-11e8-9e18-5240fe2ead82.jpg)

**Comment by srikris** [comment]
@abhishekpratapa Can we show how the same image looks here on this issue now that it's fixed?
