### ISSUE TITLE
When there are many categorical values in the 2D categorical histogram, the rendering is broken

### ISSUE THREAD

**Issue by afranklin** [apple/turicreate#690]
sa = tc.SArray(['foo_%s' % i for i in range(100)])
tc.show(sa, sa)

**Comment by znation** [comment]
Seems fixed (or at least fine) as of Turi Create 5.4:

<img width="932" alt="Screen Shot 2019-03-25 at 8 28 56 PM" src="https://user-images.githubusercontent.com/5673251/54969743-a7998900-4f3c-11e9-83bb-7a3046399b01.png">

Note that this rendering relies heavily on the mouse-hover tooltip -- but there is no sensible way to display 100 labels in a single plot.
