### ISSUE TITLE
Graphlab error- Certificate has expired error after installing spaCy library 

### ISSUE THREAD

**Issue by GSampada** [apple/turicreate#728]
Hi, 

I have been using Graphlab for a month smoothly. Yesterday I installed spaCy  library for text analytics. After installation of this library graphlab became inactive. I tried to re-install graphlab using the key provided by Turi which is valid for a year, but still after accepting the agreement I get the following error  "Certificate has expired". I created a new user still faced the same issue. 

I have tried the following option: re start GraphLab launcher, uninstall graphlab,download it again for a installation, create a new user and install Anaconda first and then try to install Graphlab again, but nothing of this is helping for re-activating the graphlab again. 

How to fix this error ? 

![graphlab error](https://user-images.githubusercontent.com/40431857/41662049-32bd657e-746e-11e8-890a-60627f7ca821.png)

**Comment by afranklin** [comment]
Hi Sampada - I'm closing this issue because it has to do with Graphlab Create. I see you also submitted a graphlab support email; expect a reply shortly.
