### ISSUE TITLE
Image classification

### ISSUE THREAD

**Issue by vpndemand** [apple/turicreate#735]
i've done Image classification for binary Images. (data = tc.image_analysis.load_images('PetImages', with_path=True))
How to do the same thing for multiple classification to load images from different folders for each sets.

**Comment by znation** [comment]
Hi @vpndemand, if I understand your question correctly, you want to use a different folder for each label (with the name of the folder representing the label) as the data for an image classifier. For this task, I would do something like this. Make a folder structure like this, for separating the images by label:

```
➜  ~ find images
images
images/cat
images/cat/cat1.jpg
images/cat/cat2.jpg
images/dog
images/dog/dog2.jpg
images/dog/dog1.jpg
```

Then, in Turi Create, you can load these images and manipulate the `path` column to get the label:

```python
import turicreate as tc
sf = tc.image_analysis.load_images('images')
"""
sf is:
+-------------------------------+--------------------------+
|              path             |          image           |
+-------------------------------+--------------------------+
| /Users/zach/images/cat/cat... | Height: 1199 Width: 1200 |
| /Users/zach/images/cat/cat... |  Height: 400 Width: 600  |
| /Users/zach/images/dog/dog... |  Height: 486 Width: 729  |
| /Users/zach/images/dog/dog... |  Height: 455 Width: 680  |
+-------------------------------+--------------------------+
"""
sf['label'] = sf['path'].apply(lambda x: x[len('/Users/zach/images/'):])
"""
sf is:
+-------------------------------+--------------------------+--------------+
|              path             |          image           |    label     |
+-------------------------------+--------------------------+--------------+
| /Users/zach/images/cat/cat... | Height: 1199 Width: 1200 | cat/cat1.jpg |
| /Users/zach/images/cat/cat... |  Height: 400 Width: 600  | cat/cat2.jpg |
| /Users/zach/images/dog/dog... |  Height: 486 Width: 729  | dog/dog1.jpg |
| /Users/zach/images/dog/dog... |  Height: 455 Width: 680  | dog/dog2.jpg |
+-------------------------------+--------------------------+--------------+
"""
sf['label'] = sf['label'].apply(lambda x: x[:x.find('/')])
"""
sf is:
+-------------------------------+--------------------------+-------+
|              path             |          image           | label |
+-------------------------------+--------------------------+-------+
| /Users/zach/images/cat/cat... | Height: 1199 Width: 1200 |  cat  |
| /Users/zach/images/cat/cat... |  Height: 400 Width: 600  |  cat  |
| /Users/zach/images/dog/dog... |  Height: 486 Width: 729  |  dog  |
| /Users/zach/images/dog/dog... |  Height: 455 Width: 680  |  dog  |
+-------------------------------+--------------------------+-------+
"""
```

Then, you can proceed to train using the `label` column as the label. Hope this helps! Please reactivate this issue if your question is not answered, or open a new issue if you have a different question, thanks!

**Comment by vpndemand** [comment]
@znation Thanks for your good explanation.
I need something like this
images/cat
images/dog
images/lion
images/zebra

**Comment by znation** [comment]
@vpndemand This technique described above should work for any number of labels. I used two in the example just to demonstrate the technique; but extracting the label from the path structure should not be affected by the number of labels, and Turi Create's image classifier will allow for multiple (not just two) labels.

**Comment by vpndemand** [comment]
@znation thanks done.
