### ISSUE TITLE
Warning on grayscale images on load_images

### ISSUE THREAD

**Issue by vpndemand** [apple/turicreate#736]
i'm getting for Black and white image(libpng warning: iCCP: profile 'ICC Profile': 'GRAY': Gray color space not permitted on RGB PNG)
data = tc.image_analysis.load_images('Images', with_path=True)

data['image'] = data['image'].apply(lambda image: tc.image_analysis.resize(image,image.width,image.height,1))

data['label'] = data['path'].apply(lambda path: 'normal' if '/Normal' in path else 'AbNormal')
data.save('Normal-AbNormal.sframe')

**Comment by znation** [comment]
Dupe of #573.
