### ISSUE TITLE
GraphLab install error  (Coursera student)

### ISSUE THREAD

**Issue by MoonHong-ki** [apple/turicreate#744]
![test0](https://user-images.githubusercontent.com/40518673/41809141-5293b332-7723-11e8-8716-d994b3355279.jpg)

Hello 
I am a student for Coursera (Machine Learning : Machine Learning Foundations: A Case Study Approach)
I have to install Graphlabs for study, but I could't finish install.
As you see, 
I already got a license(for 1 year by Coursera) and have product key.
And I deleted and reinstalled Graphlab  again, but the result was same.
I'd like to send my "install log " but, I can't upload here for product key disclosure.
I'll like to send you "install log" by e-mail.
I must finish this course til next month, but I couldn't start yet.
Please reply "cooljp0916@naver.com" or "cooljp0916@gmail.com"

**Comment by afranklin** [comment]
Sorry, but we're unable to provide support for Graphlab Create / Coursera in this repo, so I'm closing this issue. Someone from Graphlab will reply by email shortly.
