### ISSUE TITLE
Update the user guide about the GPU support

### ISSUE THREAD

**Issue by yhoonkim** [apple/turicreate#750]
[The recent feature](https://github.com/apple/turicreate#version-50-beta) supports four models to utilize GPU automatically depending on the version of Mac OS. However, the user guide does not mention about the feature. Hope to update the guide to let users know whether the model can automatically utilize the GPU or not. 

- Currently, Image Classification, Image Similarity, Object Detection, and Activity Classification support the feature but only Image Classification mentions it. 
- The other three applications (Style Transfer, Recommender System, Text Classifier) does not mention whether they don't automatically detect the GPU.

**Comment by TobyRoseman** [comment]
@yhoonkim - the source code for the user guide can be found in the [userguide folder](https://github.com/apple/turicreate/tree/master/userguide) in the root of this repo. Feel free to make the changes your suggesting. I would be happy to code review them for you.

**Comment by znation** [comment]
@shantanuchhabra Mind taking this one as well? Thanks!
