### ISSUE TITLE
Automated tests for object detection

### ISSUE THREAD

**Issue by nickjong** [apple/turicreate#753]
The existing tests use random data and only test the machinery of the model. We don't have any tests that attempt to verify or at least sanity-check the correctness of training or inference.

**Comment by gustavla** [comment]
I agree, although I think for training it will have to be a long-running scenario test. Of course we could run 20 iterations and ask to see that loss is starting to drop, however this would be a pretty weak test compared to fully training and evaluating on real data. We should definitely have more correctness tests for inference.

**Comment by nickjong** [comment]
Yeah, there are some nontrivial design decisions here. I personally dislike long-running tests, and I wonder if we should hew closer to actual unit tests, trusting that MPS is correctly implemented. In principle, we could test that the Python front-end makes the expected sequence of calls into a mocked out backend, and that the Objective-C++ backend makes the expected sequence of calls into MPS. But first I'd like to clean up the interface between front-end and backend (which may require manual testing to verify the refactoring).

**Comment by TobyRoseman** [comment]
We have internal tests that do this now.
