### ISSUE TITLE
It is unclear where to submit SFrame changes

### ISSUE THREAD

**Issue by takeon8** [apple/turicreate#76]
when contributing to SFrame related changes, should we submit pull request to SFrame repo or this repo?

**Comment by igiloh** [comment]
Hi @takeon8 , thank you for taking interest in Turi create and SFrame!
All SFrame development was moved to this repo, so please put your PR here.

We should probably update the documentation in https://github.com/turi-code/SFrame to point to this repo. I'll leave this issue open until we do.

**Comment by TobyRoseman** [comment]
@srikris - I agree with @igiloh, let's leave this issue open until we've cleared up this confusion. I'll edit the title of this issue make it more clear what we're using this issue to track.

**Comment by TobyRoseman** [comment]
@takeon8 - I've updated the SFrame repository readme. Now it has a deprecation warning and a link to this repository.
