### ISSUE TITLE
Clean up handling of ndarray-like data in TCMPS

### ISSUE THREAD

**Issue by nickjong** [apple/turicreate#762]
Every multidimensional array in TCMPS is passed as four arguments: a float pointer for data, an array size, an int pointer for shape, and size for dimensionality. This leads to function signatures such as:
```
  void Forward(void *_Nonnull ptr, size_t sz, int64_t *_Nonnull shape, int dim,
               void *_Nonnull label_ptr, size_t label_sz, int64_t *_Nonnull label_shape, int label_dim,
               void *_Nonnull weight_ptr, size_t weight_sz, int64_t *_Nonnull weight_shape, int weight_dim,
               bool loss_image_required, bool is_train,
               float *_Nonnull out);
```

An ndarray abstraction at this level would simplify the code, making it more readable and less error-prone. This would also be useful for the CoreML export interface, which currently relies on populating an opaque table:
```
  std::unordered_map<std::string,
                     std::tuple<std::string, float *, int, std::vector<int>>>
      table_;
```

This is also a good opportunity to converge this library towards Objective C, since C++ isn't currently adding much value (given that it wraps a pure Objective-C API and exposes a pure C API to the Python layer).

**Comment by gustavla** [comment]
I like this. For the same reason `FloatArray` was introduced because passing configs (key-value storage with NDArrays) around caused really verbose function signatures. This didn't need shapes though, so it only has size. If we just introduce shape into `FloatArray`, then we can use it for this purpose as well.
