### ISSUE TITLE
Logistic regression segfaults on single feature

### ISSUE THREAD

**Issue by hoytak** [apple/turicreate#764]
Run: 

```
import turicreate as tc
X = tc.SFrame({"col1" : [1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 2.0, 2.0], "target" : [2, 1, 2, 1, 2, 1, 2, 1]})
m = tc.classifier.create(X, target = "target")
```

**Comment by TobyRoseman** [comment]
This is a result of there being no training iterations (initial residuals of this example are almost zero).

Currently at least one training iteration is required it updates model state in a couple of subtle ways.
