### ISSUE TITLE
.explore() results in blank window on Linux

### ISSUE THREAD

**Issue by znation** [apple/turicreate#777]
From @baizhenmao95:

> If I run "data.explore()" on my PC, I could only see a blank window. And the icon of the turi create visualization is a red prohibition symbol within a rectangle.
> My PC Information:
> Ubuntu 17.10
> Inter i3-7100
> 8GB
> turicreate 4.3.2/5.0b1
> (no GPU)

> But if I run it on the computer in my laboratory, I could see the data and the images.
> But there are also a question. When I use the object detection and put the cursor on the thumbnail, I could just see a some image. It's too small to see it clearly. I have no idea how to enlarge them.
> This computer's information:
> Ubuntu 16.04
> Inter i7-7700K
>16GB
> turicreate 4.3.2/5.0b1
> (NVIDIA GEFORCE 1080Ti,but I didn't use GPU because I have no idea on installing CUDA)

**Comment by abhishekpratapa** [comment]
875 Fix Wheel, fixes this issue
