### ISSUE TITLE
cannot import name util

### ISSUE THREAD

**Issue by branflakes81** [apple/turicreate#785]
I am trying to run the object identification tutorial where it identifies cars and bikes and am getting this error when trying to compile

ImportError                               Traceback (most recent call last)
/Users/Brandon/Desktop/MLModel/turicreate/data_structures/sarray.py in apply(self, fn, dtype, skip_na, seed)
   1885 
-> 1886         with cython_context():
   1887             return SArray(_proxy=self.__proxy__.transform(fn, dtype, skip_na, seed))
turicreate/cython/cy_sarray.pyx in turicreate.cython.cy_sarray.UnitySArrayProxy.transform()
turicreate/cython/cy_sarray.pyx in turicreate.cython.cy_sarray.UnitySArrayProxy.transform()
ImportError: cannot import name util

During handling of the above exception, another exception occurred:
ImportError                               Traceback (most recent call last)
/Users/Brandon/Desktop/MLModel/Model.py in <module>()
     12 # Split file names so that we can determine what kind of image each row is
     13 # E.g. bike_005.mask.0.png -> ['bike_005', 'mask']
---> 14 info = raw_sf['path'].apply(lambda path: os.path.basename(path).split('.')[:2])
     15 
     16 # Rename columns to 'name' and 'type'
/Users/Brandon/Desktop/MLModel/turicreate/data_structures/sarray.py in apply(self, fn, dtype, skip_na, seed)
   1884                 return SArray(_proxy=self.__proxy__.transform_native(nativefn, dtype, skip_na, seed))
   1885 
-> 1886         with cython_context():
   1887             return SArray(_proxy=self.__proxy__.transform(fn, dtype, skip_na, seed))
   1888 
/Users/Brandon/Desktop/MLModel/turicreate/cython/context.py in __exit__(self, exc_type, exc_value, traceback)
     47             if not self.show_cython_trace:
     48                 # To hide cython trace, we re-raise from here
---> 49                 raise exc_type(exc_value)
     50             else:
     51                 # To show the full trace, we do nothing and let exception propagate
ImportError: cannot import name util

**Comment by branflakes81** [comment]
tried adding some things and now this is what I get



---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/Users/Brandon/Desktop/MLModel/turicreate/data_structures/sarray.py in apply(self, fn, dtype, skip_na, seed)
turicreate/cython/cy_sarray.pyx in turicreate.cython.cy_sarray.UnitySArrayProxy.transform()
turicreate/cython/cy_sarray.pyx in turicreate.cython.cy_sarray.UnitySArrayProxy.transform()
ImportError: cannot import name util

During handling of the above exception, another exception occurred:
ImportError                               Traceback (most recent call last)
/Users/Brandon/Desktop/3.6/test.py in <module>()
     12 # Split file names so that we can determine what kind of image each row is
     13 # E.g. bike_005.mask.0.png -> ['bike_005', 'mask']
---> 14 info = raw_sf['path'].apply(lambda path: os.path.basename(path).split('.')[:2])
     15 
     16 # Rename columns to 'name' and 'type'
/Users/Brandon/Desktop/MLModel/turicreate/data_structures/sarray.py in apply(self, fn, dtype, skip_na, seed)
/Users/Brandon/Desktop/MLModel/turicreate/cython/context.py in __exit__(self, exc_type, exc_value, traceback)
ImportError: cannot import name util /Users/Brandon/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/json/encoder.py:198: DeprecationWarning: Interpreting naive datetime as local 2018-06-28 00:55:15.590960. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)

**Comment by TobyRoseman** [comment]
@branflakes81 - sorry you're having this issue. It looks like turicreate was not installed properly.

[Instruction for installing turicreate](url) can be found on our readme. Please install using `pip install -U turicreate`. Preferably from inside of a virtual environment.
