### ISSUE TITLE
Cannot increase max_iterations

### ISSUE THREAD

**Issue by ChristophePRAT** [apple/turicreate#786]
I am trying to do a sentiment classifier but I cannot use `max_iterations`:
`# Create a model
model = tc.sentence_classifier.create(data, 'Sentiment', features=['SentimentText'], max_iterations=12)`
but it throws this error:
_TypeError: create() got an unexpected keyword argument 'max_iterations'_
and when I move the `max_iterations` next to data, it throws another error:
_SyntaxError: positional argument follows keyword argument_
Do you know what it means and how to increase `max_iterations` ?

**Comment by igiloh** [comment]
Hi @ChristophePRAT,

This is a duplication of issue #633, that was recently [fixed](https://github.com/apple/turicreate/pull/637/files).  
The fix will be available in the next beta version, coming in real soon. Stay tuned.
