### ISSUE TITLE
Note that minimum RAM for Turi Create is 4 GB

### ISSUE THREAD

**Issue by citoki** [apple/turicreate#787]
Hi TuriCreate Team,

_I know that Docker isn't the first deployment option for TuriCreate, may someone has an idea how to get a more verbose debugging output what goes wrong_

When I `style_transfer.create()` runs in a docker container, before the result output of the first iteration it suddenly terminates. The same container works well with a different training task like **image classification**.

```sh
>>> model = tc.style_transfer.create(style, content, max_iterations=70) 
Using 'image' in style_dataset as feature column and using 'image' in content_dataset as feature column
Downloading https://docs-assets.developer.apple.com/turicreate/models/resnet-16.params
Download completed: /var/tmp/model_cache/resnet-16.params
Downloading https://docs-assets.developer.apple.com/turicreate/models/vgg16-conv1_1-4_3.params
Download completed: /var/tmp/model_cache/vgg16-conv1_1-4_3.params
Using CPU to create model
Analyzing visual features of the style images
```

My Dockerfile looks following, basically the dependencies which are mentioned here:
- https://github.com/apple/turicreate/blob/master/LINUX_INSTALL.md

**Dockerfile**
```sh
FROM python:3.6

RUN apt-get update && apt-get install -y --no-install-recommends \
      build-essential \
      libblas3 \
      liblapack3 \
      libstdc++6 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ADD requirements.txt /requirements.txt

RUN pip install --upgrade pip && \
    pip install -r requirements.txt
```

**requirements.txt**
```sh
requests==2.18.4
turicreate==5.0b1
coremltools==2.0b1
h5py
```

- `docker run -it -v "$(pwd)/images":/training-data turicreate5`

-Steffen

**Comment by znation** [comment]
Thanks @citoki, we'll look into it. My initial suspicion is that the docker container may be RAM-limited and the Turi Create process may be running out of RAM. As a possible workaround, you could try reducing the sizes of your style and content images (rescaling to a smaller size), which may be less likely to run out of RAM.

**Comment by citoki** [comment]
Hi @znation thanks for the hint. I used `docker stats` to see what happens during training. Unfortunately, default memory allocation for docker containers is 2GB. After increasing it to 6GB, the training step works fine.
A more verbose error message (currently nothing) would be nice 😃 

_I pushed my test image to the docker-hub: https://hub.docker.com/r/citoki/turicreate5/ _

**Comment by znation** [comment]
Thanks @citoki. Minimum RAM for Turi Create is probably 4 GB. I'll reopen this issue to track at least updating our documentation for that, and hopefully we can print out a better error message in this case as well.

**Comment by znation** [comment]
@shantanuchhabra Can you take this one? I think we should update the documentation (not sure where - README.md?) to note that minimum RAM for TC is 4 GB. I'm not sure the larger problem (of running out of RAM and crashing without a good error message) is quite solvable given some of the architectural constraints.
