### ISSUE TITLE
Support Python 3.7

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#788]
As of yesterday [Python 3.7](https://www.python.org/downloads/release/python-370/) has been officially released. We should support it.

At an absolute minimum these things will need to be done:

- [x] Ensure everything builds with 3.7 and that the built package can be imported.
- [x] All unit test pass on both macOS and Linux.
- [x] Upload 3.7 wheel to PyPI on next release.

We'll probably want to have only beta support for 3.7 in its first release.

**Comment by TobyRoseman** [comment]
In order to support Python 3.7, all of our dependencies need to support Python 3.7. We currently have two dependencies that do not support 3.7: MXNet and Core ML Tools.

Python 3.7 support for Core ML Tools is being tracked [here](https://github.com/apple/coremltools/issues/228)

**Comment by TobyRoseman** [comment]
Python 3.7 support for MXNet is being tracked [here](https://github.com/apache/incubator-mxnet/issues/12266).

**Comment by TobyRoseman** [comment]
[Core ML Tools](https://github.com/apple/coremltools) is a dependency of Turi Create. It does not support Python 3.7. We'll have to wait until Core ML Tools support Python 3.7.

**Comment by tomharper** [comment]
the only dependency that I can see that is not up to date is coreml tools- this seems pretty surmountable at this point

**Comment by TobyRoseman** [comment]
@tomharper - It would also require us to update the versions for many of our dependencies, most notably MXNet.

**Comment by tomharper** [comment]
mxnet is on 3.7 now also, but i understand this will probably be some work

**Comment by tomharper** [comment]
looks like that is on 3.7 now too, but i don't know how much work that is to update.

**Comment by TobyRoseman** [comment]
In order to support Python 3.7, we will need to update most of our dependencies. MXNet will probably be the most difficult to update. This is being tracked separately in #1455.

**Comment by dhendo** [comment]
It looks like all the dependencies now support 3.7?

**Comment by TobyRoseman** [comment]
In our next release we will support Python 3.7, for macOS only.

**Comment by dhendo** [comment]
Is there a reason Linux will be unsupported?

**Comment by TobyRoseman** [comment]
@dhendo - Yes, there is a reason Python 3.7 will be unsupported for Linux in our next release.

We use a package called MXNet to do some of our deep learning on macOS and all of our deep learning on Linux. The version of MXNet which we currently depend on doesn't support Python 3.7. So we need to depend on a newer version of MXNet. We've experience several issues (mostly nondeterministic hangs) using newer versions of MXNet on Linux. 

In the long term, we are committed to supporting Python 3.7 on Linux. However due to quality reasons we can not support it in our next release.

**Comment by dhendo** [comment]
Thanks, that makes sense.

**Comment by chyzzqo2** [comment]
How is support looking for the next release? The 3.7 issue on MXNet is closed but since @TobyRoseman closed it before the comment above, i don't think it is actually the blocker. Is there any issue on that repo that we can follow?

**Comment by srikris** [comment]
@chyzzqo2 We will be supporting 3.7 in TC 6.0.

**Comment by TobyRoseman** [comment]
With the release of 6.0, TuriCreate now support Python 3.7.

**Comment by arnoldmashava** [comment]
(base) C:\Users\Arnold Mashava>conda install -c anaconda mxnet
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - mxnet -> python[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by TobyRoseman** [comment]
@arnoldmashava - TuriCreate does not have native Windows support. We are tracking that issue in #533.

**Comment by liliyabevcyk** [comment]
@TobyRoseman  @dhendo
Hey 
Is the last release fully supporting Python 3.7, for Linux?
Your documentation and pypi say that 3.7 is only for mac but I can actually install it and looks like it's working...
Did you just forget to update documentation?  Can I get any trouble using python 3.7 and Linux?
