### ISSUE TITLE
Chinese character parsing fail

### ISSUE THREAD

**Issue by Errrneist** [apple/turicreate#792]
Hi all,
I was using Turicreate to do some really interesting project, and one of them is to parse csv that contains Chinese. So I ran this comment: 
`stocks = tc.SFrame.read_csv('../DataSets/Eastmoney/news/RecentStockNews.csv', error_bad_lines = False)`

and some parsed while some did not parse through. I will provide a list of what turicreate would not parse:
`
Unable to parse line "　　王受文还指出，由于中国市场开放，越来越多的美资企业在中国创业，在中国投资，在中国发展。2001年，美资企业在中国市场销售额只有3600万人民币，在2016年已经增长到6000亿美元。"
Unable to parse line "1,2018,2018,26,新媒体蓝皮书：中国数字经济规模达27.2万亿 居世界第二,"6月26日，由中国社科院新闻与传播研究所、中国社科文献出版社公布发布的新媒体蓝皮书《中国新媒体发展报告(2018)》指出，..."
Exception ignored in: 'turicreate.cython.cy_server.print_status'
Unable to parse line "                (原标题：商务部召开例行新闻发布会（2018年6月28日）)",[]"
Exception ignored in: 'turicreate.cython.cy_server.print_status'
Unable to parse line "　　“一区一主业”亮点凸现"
Exception ignored in: 'turicreate.cython.cy_server.print_status'
Unable to parse line "　　至于美国政府反复强调的知识产权，王受文指出，2001年，中国对全世界支付的知识产权使用费只有19亿美元，但2017年，中国对美国支付的知识产权使用费就是71.3亿美元。"
Unable to parse line "　　数字中国建设推进了智慧社会的到来，数字技术与医疗、教育、养老、治安、交通等行业的融合加速了数字生态共同体的构建，中国智慧国家的建设逐步在加快。"
Unable to parse line "141,2018,2018,27,市场监管总局：北京交管局指定工行代收罚款涉嫌违法,"北京市交管局在交通违章罚款管理中未经公开竞争性程序指定工商银行作为罚款唯一代收银行、线下交纳罚款只能通过工行卡..."
Unable to parse line "220,2018,2018,29,从立项到施工只要90个工作日 广州开发区落户项目“井喷”,"从立项到施工只要90个工作日，多项审批归类合并，审批标准由技术判断转为价值判断……"
Exception ignored in: 'turicreate.cython.cy_server.print_status'
Unable to parse line "442,2018,2018,28,沂蒙老区首条高铁开始铺轨,"6月27日，在山东临沂费县北站，鲁南高铁全线首对长达500米的钢轨稳稳落在无砟轨道板上，标志着沂蒙革命老区首条高铁——鲁南高铁进入铺轨施工阶段..."
Exception ignored in: 'turicreate.cython.cy_server.print_status'
Exception ignored in: 'turicreate.cython.cy_server.print_status'
Unable to parse line "　　上述新媒体发展报告主编唐绪军指出，中国加快迈入智能互联的新时代。2017年，中国人工智能领域创新发展成果丰硕，人工智能市场规模达到216.9亿元，比2016年增长52.8%。"
4053 lines failed to parse correctly
`

Maybe someone can help me troubleshoot it...? I really did not do anything fancy, probably is turicreate do not support some Chinese characters? I also included the csv I was trying to parse.

Thanks, humans!

[RecentStockNews.csv.zip](https://github.com/apple/turicreate/files/2149476/RecentStockNews.csv.zip)

**Comment by TobyRoseman** [comment]
@Errrneist - I don't think the problem here is the Chinese characters. I think the problem is that the parsing code is not finding the number of columns it expects.

For example, in the first line of output you shared (` "　　王受文还指出，由于中国市场开放，越来越多的美资企业在中国创业，在中国投资，在中国发展。2001年，美资企业在中国市场销售额只有3600万人民币，在2016年已经增长到6000亿美元。"`), the characters that look like commas are not actually commas. So the entire line looks like one column to the parser. 

Similarly, in the third line `" (原标题：商务部召开例行新闻发布会（2018年6月28日）)"`, it's just one column.

**Comment by Errrneist** [comment]
Solved! Thank you!
