### ISSUE TITLE
Change optional inputs of object detection model in Xcode

### ISSUE THREAD

**Issue by borderlineinteractive** [apple/turicreate#798]
I cannot find documentation how to change the iouThreshold and confidenceThreshold Inputs for a Object Detection model generated with Turi Create 5.0b. Is there any information available on this topic?

What I tried so far is something along these lines:

```
let mlModel = object_detection().model
let visionModel = try VNCoreMLModel(for: mlModel)
let objectRecognition = VNCoreMLRequest(model: visionModel, completionHandler: output_handler_object_detection)

let requestOptions:[VNImageOption: Any] = [VNImageOption(rawValue: "confidenceThreshold"):0.1]
let ciImage = CIImage(cgImage: temp_img!)
let handler_features = VNImageRequestHandler(ciImage: inputImage!, options: requestOptions)

 do {
  try handler_features.perform([objectRecognition])
} catch {
  print(error.localizedDescription)
}
```
However, I do not see any change in the results. using VNImageOption was just a guess, and I do not get any error messages, regardless which rawValue I use.

Any help or info would be appreciated.

**Comment by znation** [comment]
Hi @borderlineinteractive, it looks like the code examples we've provided that use the Vision API don't allow for those parameters to be set. I am tagging this issue as both a question and docs issue since I think we need to answer a few questions here in this thread, then update the docs. As far as I can tell, the open questions are:

1. Can we specify those parameters through the Vision API? (In general, is it currently possible to supply optional input parameters to a Core ML model through this API?)
2a. If so, how?
2b. If not, what is the alternative? Should users who need to pass in these parameters do so through the Core ML API directly? What would the alternative example code look like in this case?

Once the answers to these questions are determined we can update the docs.

**Comment by gustavla** [comment]
It is unfortunately not possible today to change these parameters when making calls through Vision. The only alternative is to make the prediction directly through Core ML (`predictionFromFeatures:error:`). We should include a snippet for how to do this as well, to make it easier to switch over to this method.

**Comment by gustavla** [comment]
@borderlineinteractive The current source code (which I think should be available in the latest 5.0b2 beta version), the function `export_coreml` takes optional arguments `iou_threshold` and `confidence_threshold`, where you can change the default values that go into the mlmodel file.

I agree that it is annoying to have to change all the prediction code to override these at runtime. We are definitely hoping to address this in the future. Sorry for the inconvenience!

By the way, more generally, the best way to open up an mlmodel and modify it is to use `coremltools`. Although, just a warning, this is not always trivial and can involve calling `get_spec()` on the MLModel and manually go through the protobuf object to change things. This can be tricky, but not as tricky as manually hacking the binary code. Hope that helps!

**Comment by nickjong** [comment]
In the meantime, we can at least discuss this issue in the docs

**Comment by glenn-jocher** [comment]
Has there been any change on this issue? I am still unable to do this today for our iDetection app which uses a CoreML version of YOLOv3:
https://github.com/ultralytics/yolov3

**Comment by glenn-jocher** [comment]
@nickjong @gustavla @znation The model variables that we need to set on the fly at runtime, `iouThreshold` and `confidenceThreshold` are here in the NMS model, but I don't know how to programmatically modify them using Swift in Xcode. Can you help?

<img width="755" alt="Screenshot 2019-05-19 at 22 55 51" src="https://user-images.githubusercontent.com/26833433/57988015-5f549e00-7a89-11e9-8903-605520ed62da.png">

**Comment by nickjong** [comment]
In the Xcode for the current betas (e.g. for iOS 13) you should now be able to specify these parameters at runtime, using new Vision framework API: https://developer.apple.com/documentation/vision/vncoremlmodel/3131933-featureprovider?language=objc

We can use this issue to track updating our User Guide with an example here
