### ISSUE TITLE
Export Object Detector model to CoreML crashes

### ISSUE THREAD

**Issue by helloniklas** [apple/turicreate#80]
So I've created an object detection model. Saved it out. When I then try and load it in and export to CoreML I get 
```
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```

The code I'm using to train the model all seems fine and completes.
```
model = tc.object_detector.create(data, feature='image', annotations='annotations')
model.save("test.model")
```
I then later do
```
model = tc.load_model("test.model")
model.export_coreml("TestDetector.mlmodel")
```
And then get the fatal error.

I'm running in CPU mode on a MacBook Pro 13" 2017 macOS 10.13.2

**Comment by helloniklas** [comment]
Further more, the model works all fine in Turi, I am able to make accurate predictions on new images. So not sure why this export keeps crashing?

**Comment by gustavla** [comment]
@helloniklas Thanks for trying out the object detector! I'm sorry you are having this issue. I have never seen it before and it looks difficult for me to fix unless I can reproduce it. I suspect it may be something with your Python installation, so any additional information about your Python setup would help. For instance, is it the Python that comes with macOS or did you install it yourself (homebrew, macports, conda, etc.)?

Also, did you try `export_coreml` for any of the other models? For instance, does the image classifier work?

**Comment by helloniklas** [comment]
@gustavla So I haven't tried other models yet. I believe on this laptop python was installed with Homebrew, as well as the default Xcode install of python. However, I was under the impression that when following your install steps and setting it up with a virtualenv it would use the Python in that virtualenv. I'm new to the Python world. Is there a way I can ensure the virtualenv is using the correct python install? 

Googling the error I get people do seem to mention it has to do with different python versions.

**Comment by helloniklas** [comment]
@gustavla So after setting up the virtualenv with virtualenv --python=/usr/bin/python2.7 turiAgain
It now seems to work, CoreML model is saved out. Good time.

I guess without specifying the python path to use it used some compatible version, although it still was python2.7

**Comment by srikris** [comment]
@helloniklas coremltools does not work with python installed via homebrew. That explains the error you are getting. I filed an issue with that repository (https://github.com/apple/coremltools/issues/88)

**Comment by dmcgloin** [comment]
Got same error as @helloniklas. Everything worked in terms of training a model using the virtualenv (after lots of thrashing through docs - and me being unfamiliar with python).

But when it came to exporting to CoreML, I got the same fatal error.

Installing Anaconda resolved the issue for me.
