### ISSUE TITLE
Running test unity_sframe.cxx exposes assertion failures

### ISSUE THREAD

**Issue by hoytak** [apple/turicreate#809]
Running the test unity_sframe.cxx in test/unity exposes assertion failures.  These are within tests that expect an exception to be raised and so the tests pass: however, they are obviously issues, e.g.

1530578793 : ERROR:    unity_sframe.cpp(operator():): Check failed (/Users/hoytak/workspace/turicore/turicreate_oss/src/unity/lib/unity_sframe.cpp:): index != nullptr

1530578793 : ERROR:    unity_sframe.cpp(operator():): Check failed (/Users/hoytak/workspace/turicore/turicreate_oss/src/unity/lib/unity_sframe.cpp:): data != nullptr

**Comment by znation** [comment]
Same for `sframe_test.cxxtest`.

**Comment by TobyRoseman** [comment]
Both `unity_sframe.cxxtest` and `sframe_test.cxxtest` now pass in master.
