### ISSUE TITLE
Could not find a version that satisfies the requirement turicreate

### ISSUE THREAD

**Issue by nhatlee** [apple/turicreate#81]
I following the installation instruction, but end up faced with the error when running command `(venv) pip install -U turicreate`. The error: 
`
  Could not find a version that satisfies the requirement turicreate (from versions: )
No matching distribution found for turicreate`
Please help me to fix it.

**Comment by igiloh** [comment]
Hi @nhatlee , thanks for your comment!
Can you please try running `pip install --upgrade pip`, and then run the turicreate installation again?

**Comment by nhatlee** [comment]
@igiloh : Yes. I did it. But still got this error(I used MacbookPro 2013, version: 10.13.2).

**Comment by igiloh** [comment]
Hi @nhatlee,
Turicreate is currently supporting python 2.7 only. You can see a discussion about python 3 support here: https://github.com/apple/turicreate/issues/2.
Can you please try installing with python 2.7?

**Comment by nhatlee** [comment]
@igiloh : Thanks for your help. However, I think we should change for another error message with more clearer than above.

**Comment by manikshahkataria** [comment]
Couldn't not find a version that satisfy the requirement lxml(from versions) no matching distribution found for xml

**Comment by manikshahkataria** [comment]
Couldn't not find a version that satisfy the requirement lxml(from versions) no matching distribution found for xml
Anyone please help to solve this error in python

**Comment by panzercy** [comment]
Could not find a version that satisfies the requirement turicreate (from versions: )
No matching distribution found for turicreate. need help...................

**Comment by RAHUL9545416** [comment]
ooking in links: /usr/share/pip-wheels
Processing /usr/share/pip-wheels/appdirs-1.4.3-py2.py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement apturl==0.5.2 (from -r requirements.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for apturl==0.5.2 (from -r requirements.txt (line 2))
(geeks) 17:30 ~/edxart (master)$

**Comment by aspin-0077** [comment]
when i tried,  sudo python3 -m pip install --user --system --target ./ turicreate  

 Collecting turicreate
  Downloading https://files.pythonhosted.org/packages/e4/76/76c624d7ae1116b22cd559288596a1f9aa7a50f8f43f4481033fc047f5e9/turicreate-6.3-cp36-cp36m-manylinux1_x86_64.whl (91.9MB)
    100% |████████████████████████████████| 91.9MB 17kB/s
Collecting resampy==0.2.1 (from turicreate)
  Downloading https://files.pythonhosted.org/packages/14/b6/66a06d85474190b50aee1a6c09cdc95bb405ac47338b27e9b21409da1760/resampy-0.2.1.tar.gz (322kB)
    100% |████████████████████████████████| 327kB 633kB/s
Collecting decorator>=4.0.9 (from turicreate)
  Downloading https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Collecting prettytable==0.7.2 (from turicreate)
  Downloading https://files.pythonhosted.org/packages/ef/30/4b0746848746ed5941f052479e7c23d2b56d174b82f4fd34a25e389831f5/prettytable-0.7.2.tar.bz2
Collecting pandas>=0.23.2 (from turicreate)
  Downloading https://files.pythonhosted.org/packages/a7/f7/2adca20a7fa71b6a32f823bbd83992adeceab1d8bf72992bb7a55c69c19a/pandas-1.1.0-cp36-cp36m-manylinux1_x86_64.whl (10.5MB)
    100% |████████████████████████████████| 10.5MB 133kB/s
Collecting six>=1.10.0 (from turicreate)
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting pillow>=5.2.0 (from turicreate)
  Downloading https://files.pythonhosted.org/packages/30/bf/92385b4262178ca22b34f82e0e09c2922eb351fe39f3cc7b8ba9ea555b41/Pillow-7.2.0-cp36-cp36m-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 380kB/s
Collecting tensorflow<=2.0.1,>=2.0.0 (from turicreate)
  Could not find a version that satisfies the requirement tensorflow<=2.0.1,>=2.0.0 (from turicreate) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow<=2.0.1,>=2.0.0 (from turicreate)

**Comment by TobyRoseman** [comment]
@aspin-0077 - what version of Python are you using?

**Comment by aspin-0077** [comment]
python 3.6

**Comment by TobyRoseman** [comment]
@aspin-0077 - that should be fine. I would try updating your `pip`.

**Comment by aspin-0077** [comment]
@TobyRoseman Thank you. But pip is already updated... Got error for tensorflow version
...
Collecting tensorflow<=2.0.1,>=2.0.0 (from turicreate)
Could not find a version that satisfies the requirement tensorflow<=2.0.1,>=2.0.0 (from turicreate) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow<=2.0.1,>=2.0.0 (from turicreate)

**Comment by aspin-0077** [comment]
Successfully installed , Thank you so much @TobyRoseman 
using,

sudo pip3 install -U pip

then i used,

sudo pip3 install turicreate


So that successfully runned.
![image](https://user-images.githubusercontent.com/66662812/89988030-90c41580-dc9c-11ea-99c1-a092c22b5b41.png)
Thank you

**Comment by Makarios-sudo** [comment]
ERROR: Could not find a version that satisfies the requirement apturl==0.5.2 (from -r /tmp/build_e7ac20e7/requirements.txt (line 2)) (from versions: none)
remote:        ERROR: No matching distribution found for apturl==0.5.2 (from -r /tmp/build_e7ac20e7/requirements.txt (line 2))

**Comment by Makarios-sudo** [comment]
Please I need help.. i get this error while trying to deploy my project on heroku

 ERROR: Could not find a version that satisfies the requirement apturl==0.5.2 (from -r /tmp/build_e7ac20e7/requirements.txt (line 2)) (from versions: none)
remote:        ERROR: No matching distribution found for apturl==0.5.2 (from -r /tmp/build_e7ac20e7/requirements.txt (line 2))

**Comment by eben2840** [comment]
Please I need help.. i get this error while trying to deploy my project on heroku

ERROR: Could not find a version that satisfies the requirement apturl==0.5.2 (from -r /tmp/build_e7ac20e7/requirements.txt (line 2)) (from versions: none)
remote: ERROR: No matching distribution found for apturl==0.5.2 (from -r /tmp/build_e7ac20e7/requirements.txt (line 2))

**Comment by piyushkathuria** [comment]
Please I need help.. i get this error while trying to deploy my project on heroku

ERROR: Could not find a version that satisfies the requirement apturl==0.5.2 (from -r /tmp/build_e7ac20e7/requirements.txt (line 2)) (from versions: none)
remote: ERROR: No matching distribution found for apturl==0.5.2 (from -r /tmp/build_e7ac20e7/requirements.txt (line 2))
