### ISSUE TITLE
Using multiple bounding boxes per image

### ISSUE THREAD

**Issue by yousifKashef** [apple/turicreate#815]
Hi, 

I'm thinking of using multiple bounding boxes per image for an object detector. I'm wondering if Turi Create allows that. is it recommended? or should I stick to one bounding box per image.

Thanks

**Comment by znation** [comment]
@yousifKashef Yes, Turi Create allows multiple bounding boxes per image. See the [user guide chapter](https://apple.github.io/turicreate/docs/userguide/object_detection/#data-acquisition) for object detection. The format for bounding boxes is a JSON object for a single bounding box, or a JSON array of multiple JSON objects for multiple bounding boxes.

There is no reason to limit to one bounding box per image; you can have as many bounding boxes as the number of objects in the image. I would recommend including a bounding box for all objects in the image, that are of a class that is labeled with one of the labels you are trying to predict.

**Comment by yousifKashef** [comment]
@znation I see, the reason I asked in the first place is because Turi Create Visualizer separates rows in a manner that only shows one bounding box per row. So, if an image has 4 bounding boxes, it will give me 4 raws. is that as it should be, or have I taken a wrong step?
