### ISSUE TITLE
turicreate script not ending

### ISSUE THREAD

**Issue by THEDFG** [apple/turicreate#825]
> import turicreate as tc
> 
> styles = tc.load_images('style/')
> content = tc.load_images('content/')
> 
> model = tc.style_transfer.create(styles, content, max_iterations=10)
> 
> test_images = tc.load_images('test/')
> 
> stylized_images = model.stylize(test_images)
> 
> model.save('mymodel.model')
> 
> model.export_coreml('MyStyleTransfer.mlmodel')

_venv $ python styleTransfer.py 
Using 'image' in style_dataset as feature column and using 'image' in content_dataset as feature column
Downloading https://docs-assets.developer.apple.com/turicreate/models/resnet-16.params
Download completed: /var/folders/z1/kl0_xxgn6mv6zds7mxvb50c00000gn/T/model_cache/resnet-16.params
Downloading https://docs-assets.developer.apple.com/turicreate/models/vgg16-conv1_1-4_3.params
Download completed: /var/folders/z1/kl0_xxgn6mv6zds7mxvb50c00000gn/T/model_cache/vgg16-conv1_1-4_3.params
Using CPU to create model
Analyzing visual features of the style images
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
| 1            | 11.958       | 18.6         |
| 2            | 14.065       | 59.1         |_

**keeps running and after forced kill:**

_^CTraceback (most recent call last):
  File "styleTransfer.py", line 8, in <module>
    model = tc.style_transfer.create(styles, content, max_iterations = 10)
  File "/Users/user/venv/lib/python2.7/site-packages/turicreate/toolkits/style_transfer/style_transfer.py", line 287, in create
    for c_batch in content_images_loader:
KeyboardInterrupt_

**Comment by THEDFG** [comment]
style 8 images and content 1 image:
├── content
│   └── cat.png 447 × 600
├── style
│   ├── 1.png 399 × 266
│   ├── 2.png 398 × 265
│   ├── 3.png 393 × 261
│   ├── 4.png 395 × 256
│   ├── 5.png 394 × 398
│   ├── 6.png 394 × 398
│   ├── 7.png 397 × 399
│   └── 8.png 399 × 399
├── styleTransfer.py
└── test
    └── image.jpg 1140 × 550

[styleTransfer.zip](https://github.com/apple/turicreate/files/2178046/styleTransfer.zip)

**Comment by shreyasvj25** [comment]
Hi @THEDFG, during training, please use more content images (around 100-200).  
This issue is a duplicate of #636

**Comment by THEDFG** [comment]
Thanks
