### ISSUE TITLE
load_images with relative paths broken in unity_sframe

### ISSUE THREAD

**Issue by hoytak** [apple/turicreate#826]
Loading of images with relative paths going through the load_images path in unity/lib/image_util.cpp has several issues, causing relative paths of the form `"../<dir>/image"` to not work, IMAGE.jpg to match image.jpg, and it's very slow when the directories are large.  This code needs to be made more robust and performant.

**Comment by znation** [comment]
@hoytak Can you please give repro steps for each of the issues here with expected/actual behavior? Relative paths should already work (having been somewhat tested already), and case-sensitivity sounds like a filesystem-level issue (the default FS on macOS is case-insensitive) so perhaps by design.

**Comment by znation** [comment]
Went over this in-person with @hoytak. From code inspection, it looks like the issue is there are some relative path handling problems with `..`, and possibly case sensitivity issues. We should more thoroughly unit test this code path and address issues there.

**Comment by guihao-liang** [comment]
In [7]: load_imags("../test_dir/cat.png")
Out[7]:
Columns:
        path    str
        image   Image

Rows: 1

Data:
+---------------------+------------------------+
|         path        |         image          |
+---------------------+------------------------+
| ../test_dir/cat.png | Height: 412 Width: 430 |
+---------------------+------------------------+
[1 rows x 2 columns]

Could you @hoytak point me how to reproduce it?

**Comment by guihao-liang** [comment]
Ah, I misunderstand this problem. I can load `CAT.png` as well, which shouldn't be loaded.

**Comment by guihao-liang** [comment]
```c
#include <sys/stat.h>
#include <iostream>

int main(int argc, char **argv) {
  struct stat sb;
  int ret = stat(argv[0], &sb);
  std::cout << ret << std::endl;
}

```

```bash
➜  gui-2-36 git:(01-05-refine-load-image) ✗ ./a.out ./test_dir/cat.png
0
➜  gui-2-36 git:(01-05-refine-load-image) ✗ ./a.out ./test_dir/caT.png
0
```
mac fs and hdfs is a **case insensitive** file system. Need extra logic to wrap `stat`.

**Comment by guihao-liang** [comment]
```
In [12]: tc.image_analysis.load_images("../test_dir/")
Out[12]:
Columns:
        path    str
        image   Image

Rows: 1

Data:
+---------------------+------------------------+
|         path        |         image          |
+---------------------+------------------------+
| ../test_dir/cat.png | Height: 412 Width: 430 |
+---------------------+------------------------+
[1 rows x 2 columns]
```
load relative directory also works.
