### ISSUE TITLE
Question about the use of eGPUs in beta

### ISSUE THREAD

**Issue by yousifKashef** [apple/turicreate#829]
Hi,

I'm using the beta to create object detectors using my late 2015 iMac (graphics: AMD Radeon R9 M380 2048 MB). The performance has improved significantly over the use of my computer's CPU but it's still not good enough. 

I'm thinking of getting an external GPU to help speed things up. I've heard that eGPUs have better support in macOS Mojave. If I am to get a supported eGPU (say a Vega 64) and connect it to my mac, would the beta of turi create automatically recognize it as my computer's GPU and start using it to train the neural network, or will I need to take additional measures to get the beta to incorporate the GPU into the training process?

If I need to take extra measures, what might those be?

also, can I get Turi create beta to use both my computer's GPU and the external GPU at the same time?

thanks

**Comment by nickjong** [comment]
Hi, the current Turi Create beta does support external GPUs, so everything should just work, and you should see a significant speedup over using the GPU in your iMac. (If not, that would be a high priority bug for us!)

In practice, when using a GPU to accelerate training, the CPU is still busy performing work such as preparing the inputs into the GPU. We're always looking for ways to improve performance, but you should see CPU utilization while training on GPU.

I hope this answers your questions, if not, please feel free to re-open!
