### ISSUE TITLE
Style Transfer core ml model getting error message when running in iOS app

### ISSUE THREAD

**Issue by Leon16** [apple/turicreate#840]
I have successfully created a style transfer core ml model using 8 styles. When I moved it into a sample Xcode project I saw the description of the model as:
<img width="941" alt="image" src="https://user-images.githubusercontent.com/20294324/42548923-27bff288-84fc-11e8-8373-a6eaa078c35c.png">

Then I knew that the model requires the styles array as an input instance of MLMultipleArray. Therefore I followed the user guide to have created the styleArray. Then I set selectedImage as ciImage input and [styleIndext : styleArray!] as the options input to generate VNImageRequestHandler as in the following code.

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/20294324/42549485-fc20a1ce-84fe-11e8-97cf-4335e04d3c19.png">

Additionally here is how I set the styleTransferRequest with the model used:

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/20294324/42549440-c4e4767c-84fe-11e8-807a-2a6627ddc647.png">

However when I ran the app it reports the error from the completion handler of VNCoreMLRequest as the following:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/20294324/42549693-1cddf096-8500-11e8-934b-a52886121eec.png">

I searched around and guessed it could be the inputs to run model might not be set correctly but checked the docs to no clue.  Could any one help look at the code or advise how I should set the inputs when setting VNImageRequestHandler for style transfer core ml model from Turi Create? I looked at other style transfer core ml model examples (not created by Turi Create) and found they only use one style and therefore the only input is the image to be transferred.

**Comment by Leon16** [comment]
It does look like style transfer model is broken in Vision framework integration. I was able to get the model run by using direct model prediction. The only thing is the trouble in setting the CVPixBuffer in self.mlModel.prediction(image: pxbuffer!, index: array!) call

**Comment by rainhut** [comment]
Any progress on this? I'm getting the same error.

**Comment by rainhut** [comment]
This article explains how to make TuriCreate style models work. I just wrote it. 
https://github.com/apple/turicreate/issues/840

**Comment by znation** [comment]
Thanks @rainhut! Your article looks great. For those in need of a workaround until Vision integration is working for this model, please try the technique described there.

**Comment by znation** [comment]
@abhishekpratapa, do you mind taking this one? The work on our end here is to update our docs to make sure we are using non-Vision APIs in our examples for style transfer.

**Comment by DarkTemple** [comment]
@rainhut，your solution is greate! But I want to know how to make the input/output image size flexible like turicreate method 'model.stylize(sample_image, style=0) '

**Comment by srikris** [comment]
@DarkTemple This is being tracked in #934.
