### ISSUE TITLE
Turi Create tutorial on Image Similarity - stuck at "Starting brute force nearest neighbors model training" 

### ISSUE THREAD

**Issue by alelordelo** [apple/turicreate#844]
I’m following Turi Create tutorial on Image Similarity https://apple.github.io/turicreate/docs/userguide/image_similarity/

I got stuck at: Starting brute force nearest neighbors model training. In [ ]:
Its been 14 hours already, tried 2 times and it always get stuck at this point.

![qzcgl](https://user-images.githubusercontent.com/17708751/42646627-54103c00-85f9-11e8-9378-06e22416c5a0.png)

Any clue what is wrong?

**Comment by TobyRoseman** [comment]
Hi @alelordelo - sorry you are having this issue. Could you please give us some more details:
1 - What version of turicreate are you using?
2 - What operating system are you using, and which version?
3 - Looks like you have 1,673 reference images. Can you confirm that is correct? Also do you expect that most of these images will be very similar to each other?

**Comment by alelordelo** [comment]
Thanks for helping Toby!

1- Turi 4.3.2
2- Mac OS Mojave 10.14 Beta (18A326g)
3- 1.688 images. I have 6 folders with different artworks categories, as you can see bellow. They are not very similar to each other I guess...
<img width="1410" alt="screen shot 2018-07-12 at 18 59 38" src="https://user-images.githubusercontent.com/17708751/42650987-e167e074-8605-11e8-906e-537b623a16ee.png">
<img width="878" alt="screen shot 2018-07-12 at 19 00 06" src="https://user-images.githubusercontent.com/17708751/42650988-e197e968-8605-11e8-8dc6-ded5c484ab6a.png">

**Comment by alelordelo** [comment]
Im also using Anaconda <navigator, 1.8.7 and the env file created not his tutorial:
https://www.raywenderlich.com/196233/create-ml-tutorial-getting-started

**Comment by TobyRoseman** [comment]
Please try the most recent version of turicreate and let us know if it's still an issue. You can install the most recent version by running `pip install turicreate==5.0b2`.

If it does get stuck again, please let us know if you are also seeing high CPU or disk utilization.

**Comment by TobyRoseman** [comment]
@alelordelo - I'm really not sure what's going on here. I was just able to train an image similarity model with an order of magnitude more images (18,288 images). So I don't think it's a data size issue.

Looking at the output of your call to `tc.image_similarity.create(...)`. It doesn't look like it's finding any of the images; that progress table should be a lot longer. I've also never seen that `DeprecationWarning` before.

What's the output when you call `print(reference_data)`?

**Comment by alelordelo** [comment]
Thanks @TobyRoseman !

Called tc.image_similarity.create(...), and this is what I get.

But still stuck at:
<unknown>:39: DeprecationWarning: invalid escape sequence \s


<img width="1239" alt="screen shot 2018-07-18 at 21 52 45" src="https://user-images.githubusercontent.com/17708751/42907193-faeb166e-8ad4-11e8-9203-18c5727f86ff.png">
<img width="1194" alt="screen shot 2018-07-18 at 21 52 37" src="https://user-images.githubusercontent.com/17708751/42907194-fb090656-8ad4-11e8-8d26-993db867d89e.png">

**Comment by alelordelo** [comment]
and this is my folder structure:

<img width="1206" alt="screen shot 2018-07-18 at 21 56 44" src="https://user-images.githubusercontent.com/17708751/42907390-8746876a-8ad5-11e8-9342-e122eb9097ed.png">||

DO you see anything wrong?

**Comment by alelordelo** [comment]
thanks @TobyRoseman! You are right, the model was trained! : )

How can I visualise the results of a query?

<img width="681" alt="screen shot 2018-07-19 at 15 15 24" src="https://user-images.githubusercontent.com/17708751/42948238-f99d7012-8b66-11e8-9f74-93e01c7aa0da.png">


Is it possible to visualise as a explore or plot?

<img width="837" alt="screen shot 2018-07-19 at 15 18 58" src="https://user-images.githubusercontent.com/17708751/42948325-28882458-8b67-11e8-8162-4847c2113007.png">
<img width="856" alt="screen shot 2018-07-19 at 15 19 08" src="https://user-images.githubusercontent.com/17708751/42948331-2c250b6c-8b67-11e8-9901-8269e908faee.png">

**Comment by TobyRoseman** [comment]
Take a look at our [user guide for image similarity](https://apple.github.io/turicreate/docs/userguide/image_similarity/). It contains code to visualize the similar images. Basically you can do a `filter_by` on the image ids and then call `explore()` on the resulting SFrame.

I'm going to close this issue. Let us know if you have any more questions.

**Comment by alelordelo** [comment]
Nope, thanks a lot @TobyRoseman!
