### ISSUE TITLE
Style Transfer setting to use VGG instead of Resnet?

### ISSUE THREAD

**Issue by enzyme69** [apple/turicreate#848]
Hope it's not a repost question, but I have been quite curious on how to switch to VGG library instead of Resnet? If I am not wrong, when training, it does download VGG library, but my model is always Resnet. I want a Style that is more wildly.

Resnet seems to transfer color and simple strokes and patterns.

**Comment by gustavla** [comment]
Hi @enzyme69! Thanks for checking out the style transfer toolkit and the feedback about your own experience. I have personally heard mixed views on the Resnet vs. VGG for reference network debate. However, I have not tried it myself and I appreciate you contributing your own sample point on this.

Unfortunately we don't provide an easy way to swap out the reference network. If you really wanted to do this, the only option would be to build Turi Create from source and modify the code (you would need to define the Resnet architecture and then get a new URL to download the parameters from). If you do and have results to share, please do!

**Comment by enzyme69** [comment]
@gustavla Thanks! I do started to like the quality of Resnet (current TuriCreate style transfer). It can produce water color, comic style looks.

**Comment by gustavla** [comment]
@enzyme69 I misread you first and thought you meant switch from VGG to resnet. Currently Turi Create uses a resnet network for the main style transfer network, and a pre-trained VGG model as a reference network. That's why I thought you wanted to switch the reference network. Happy to hear you are seeing some results that you are pleased with!

**Comment by shreyasvj25** [comment]
As mentioned in #653, you can vary the stylization effect by tuning the knob `style_loss_mult`.
Also, try using data augmentation (which is currently not on by default)

**Comment by rainhut** [comment]
Where are the docs on tuning the style_loss_mult?
