### ISSUE TITLE
Column names containing commas should be wrapped in quotes when saving to CSV

### ISSUE THREAD

**Issue by znation** [apple/turicreate#860]
Observed Behavior:

SFrame.save("foo.csv") knows that string values containing commas should be wrapped in quotes when saved in csv (comma-delimited). But it does not do that for column names (headers).

```python
import turicreate as tc
print tc.__version__  # => 5.0b2

tc.SFrame({"look,comma": [  # column name with a comma
    "wow, amazing",         # string with comma will get wrapped in quotes
    "wonderful"             # ordinary string, no wrap
]}).save("foo.csv")
```

```bash
$ cat foo.csv   # file won't load using SFrame.read_csv
look,comma      # column name did not get wrapped
"wow, amazing"  # column value got wrapped
wonderful
```

Expected Behavior:

Just like column values, column named should be wrapped with quotes if necessary.
This is consistent with other software packages, for instance in pandas:

```python
import pandas as pd
print pd.__version__  # => 0.19.1

pd.DataFrame({"look,comma": [  # same thing
    "wow, amazing",
    "wonderful"
]}).to_csv("foo.csv")
```

```bash
$ cat foo.csv
,"look,comma"     # looks OK!
0,"wow, amazing"
1,wonderful
```

Steps To Reproduce:

See above.

**Comment by dhivyaaxim** [comment]
@znation  Please assign this ticket to me as I would like to try fixing it and contribute. Thanks in advance!

**Comment by znation** [comment]
@dhivyaaxim Done, thanks!
