### ISSUE TITLE
Large loss in style transfer

### ISSUE THREAD

**Issue by thedashdude** [apple/turicreate#872]
Output of running `model = tc.style_transfer.create(styles, content)` 

```
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
| 1            | 18.153       | 13.9         |
| 2            | 39867919840067.539| 51.0         |
| 3            | 35881127856061.688| 87.8         |
| 4            | 32293015070456.355| 124.1        |
| 5            | 29063713563426.012| 162.7        |
| 6            | 26157342207084.680| 201.3        |
| 7            | 23541607986377.094| 238.2        |
| 8            | 61055367027790.594| 276.1        |
| 9            | 54949830325012.773| 315.1        |
| 10           | 49454847292512.406| 354.6        |
| 11           | 44509362563262.000| 392.4        |
| 12           | 40058426306950.875| 430.9        |
```

This has happened with several configurations of data, all with similar results.

As far as I can remember, with all possible combinations of:
Using either 8 or 4 style images
Using 1000 or 20 content images
Using 150 or 50 training iterations, can't use 5000 because I am on CPU, although it yields the same results when run for a while before I stopped it. 

I also did one run with 20 content images scaled down to see if RAM was an issue, as I have been running low, but no change in behavior.

Upon training completion, running the model with any style yields (with very minor variation) the following result:

![t1](https://user-images.githubusercontent.com/17187253/42999015-de95377c-8c39-11e8-85d7-479d72786b9f.jpg)

Turns to 

![img0_0](https://user-images.githubusercontent.com/17187253/42999032-ec8c9438-8c39-11e8-879c-e1083d1dc6be.jpg)

While I wasn't expecting great results for the amount of training, this doesn't seem like its working right. Also, if I try to do more than one style transfer for an image, I run out of RAM. 

However, all that seems secondary, as the first thing that doesn't work is the loss. Any ideas what that is about?

Ubuntu 16.04
Using venv
Running on CPU
```
>>> tc.__version__
'5.0b2'
```

**Comment by shreyasvj25** [comment]
Hi @thedashdude, 
Definitely, the model is diverging and this is not expected. Thanks for bringing up the issue.
Can you provide the exact style and content images that led to this divergence?

**Comment by shreyasvj25** [comment]
Hi @thedashdude ,
I was able to reproduce your issue on Ubuntu CPU,
Unfortunately, it doesn't reproduce on Mac or Ubuntu GPU.

For now, here is a workaround to unblock you.

`pip uninstall mxnet`  
`pip install mxnet==1.2.1`


`import turicreate as tc`
`tc.config.set_runtime_config('TURI_DEFAULT_NUM_PYLAMBDA_WORKERS', 1)`

Let us know if you are still blocked.

We are planning to update mxnet to 1.2 (see #670). Once we do that, this issue should be resolved.

**Comment by thedashdude** [comment]
All good. Thanks!

**Comment by TobyRoseman** [comment]
We have made significant changes to our Style Transfer Toolkit since the last correspondence in this issue. Is this still an issue in TuriCreate 6.4?
