### ISSUE TITLE
Warn on uninitialized struct/class members

### ISSUE THREAD

**Issue by znation** [apple/turicreate#876]
Currently, we don't warn or error in the build on uninitialized struct/class members. When those structs/classes are put on the heap, those members may be pointing to random bits in memory, and therefore give different behavior in debug and release mode, and weird unreliable behavior in release mode (especially with optimizations turned on). This is the root cause of #777.

We should turn on these build warnings/errors so we are able to prevent this issue from reoccurring in general.

**Comment by hoytak** [comment]
Resolved by https://github.com/apple/turicreate/pull/1003
