### ISSUE TITLE
SArray.read_json() should be able to read an array 

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#89]
The following code fails:
```
import turicreate as tc
import json

with open('/tmp/test.json', 'w') as f:
    json.dump([1,2,3], f)

tc.SArray.read_json('/tmp/test.json')
```
with this error message:
```
Parsing JSON records from /tmp/test.json
/tmp/test.json has non-dictionary elements which are ignored.
```

**Comment by znation** [comment]
I'd call this a bug. Both `{}` and `[]` are valid as top-level elements in JSON.

**Comment by nickjong** [comment]
The documentation for read_json states:
        Construct an SArray from a json file or glob of json files.
        The json file must contain a list of dictionaries. The returned
        SArray type will be of dict type
In this case, the json file is a list of integers.

Should we change the documented behavior of the function?
