### ISSUE TITLE
Reading CSV: newlines in quoted text should be ignored

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#907]
Reading the following CSV will result in an error:
```
id,title
11,"this is fine"
12,this is also fine
13,"this is 
not fine!"
```
Also the title value for the last row will be just `this is`.

Expected result: no error and the final title value is `this is\nnot fine!`.

**Comment by srikris** [comment]
The impact of this bug is pretty big for anyone doing text processing. Bumping up to P2
