### ISSUE TITLE
Inline Explore in Jupyter Notebook

### ISSUE THREAD

**Issue by abhishekpratapa** [apple/turicreate#929]
- explore call in Jupyter Notebook inline

**Comment by syoutsey** [comment]
Explore call on the SFrame object, not on the model itself.

Pulling this in to 5.7 as some teams have a heavy dependency on Jupyter Notebook and this is the primary reason they can't go all-in on a hosted notebook solution, and are instead asking people to install Turi Create locally.

**Comment by abhishekpratapa** [comment]
#2178
