### ISSUE TITLE
No matching distribution found for script

### ISSUE THREAD

**Issue by Romyull-Islam** [apple/turicreate#936]
Could not find a version that satisfies the requirement script (from versions: )
No matching distribution found for script

it showing when I try to install script mudule in python 3.6

**Comment by TobyRoseman** [comment]
@Romyull-Islam what operating system are you using? We don't have native support for Windows, see issue #533.

If you're using Windows 10, you can use TuriCreate by using WSL.

**Comment by znation** [comment]
@Romyull-Islam What is `script` and how does it relate to `turicreate`?

**Comment by znation** [comment]
@Romyull-Islam, can you provide any further information here? I'm not sure how to reproduce this issue, or how Turi Create is involved.

**Comment by Romyull-Islam** [comment]
Actually,
 I was new to ask any question, so I could not ask the question properly.
I used the Windows 10 operating system.

**Comment by znation** [comment]
Hi @Romyull-Islam, can you provide some more details on what steps you are taking to install Turi Create, and what error you are encountering? Please note that Turi Create is only supported on WSL in Windows 10 -- this is a Linux environment within Windows 10, supported by Microsoft. Please see https://docs.microsoft.com/en-us/windows/wsl/install-win10 if you need more information about how to install and use WSL.
