### ISSUE TITLE
Object detector landmarks

### ISSUE THREAD

**Issue by AndrGolubkov** [apple/turicreate#938]
Is it possible in the training of the model to lay in it not only the bounding box, but also the key points of the object that we are looking for. For example, the coordinates of the fingertips? Thanks in advance for the answer.

**Comment by znation** [comment]
@gustavla is this something the current model can handle, or would we consider this a feature request?

**Comment by AndrGolubkov** [comment]
I would like to know if this is possible in this version. I'm using the beta version at the moment

**Comment by gustavla** [comment]
@AndrGolubkov There is currently no special support for this. What you can do is simply add more classes with the appropriate sub-components. For instance, you can place an additional box over the fingertip and make that a separate class. However, the algorithm will not be aware of the hierarchical relationship, so it won't tell you that a hand instance is a parent of a particular fingertip instance. You would have to add this kind of reasoning yourself based on the raw predictions (possibly looking at how close they are spatially, if they have consistent size, etc.).

I hope that gives you an idea of how it can be done at least!

**Comment by gustavla** [comment]
I'll close this, but if you have any further questions, feel free to re-open. Thanks for the letting us know what kind of features you are interested in!
