### ISSUE TITLE
style_transfer not working in beta 3

### ISSUE THREAD

**Issue by talyn** [apple/turicreate#944]
Error when I run python script:

```
    model = turicreate.style_transfer.create(content_images, style_images, max_iterations = 5)
AttributeError: 'module' object has no attribute 'style_transfer'
```

Python code:

```
import turicreate
 
# Use all GPUs (default)
turicreate.config.set_num_gpus(-1)
 
# Use only 1 GPU
#turicreate.config.set_num_gpus(1)
 
# Use CPU
#turicreate.config.set_num_gpus(0)
 
# Load data
content_images = turicreate.image_analysis.load_images("content/")
style_images = turicreate.image_analysis.load_images("style/")
 
# Create a model
model = turicreate.style_transfer.create(content_images, style_images, max_iterations = 5)
 
# Save the model
model.save('MyStyles.model')
 
# Export for deployment
model.export_coreml("MyStyles.mlmodel")
 
```

Environment:
OS macOS 10.14 (18A347e)
turicreate 5.0 b3

**Comment by shreyasvj25** [comment]
I am not able to repro this.  
Can you double check the version?
`import turicreate as tc`
`print(tc.__version__)`

**Comment by talyn** [comment]
Version is 5.0b1. I also noticed that there were no API docs for style_transfer, but it looks like this has been fixed.

**Comment by znation** [comment]
Hi @talyn, have you had a chance to check whether this repros for you in 5.0b3? Thanks!

**Comment by talyn** [comment]
Finally figured this out. I was seeing this:

mxnet 1.1.0.post0 has requirement requests<2.19.0,>=2.18.4, but you'll have requests 2.19.0 which is incompatible.

So I installed requests 2.18.4, and now it works. Sorry about the false alarm!

**Comment by talyn** [comment]
The problem was this:

`mxnet 1.1.0.post0 has requirement requests<2.19.0,>=2.18.4, but you'll have requests 2.19.0 which is incompatible.
`
Once I downgraded requests to 2.18.4, it worked fine.

**Comment by znation** [comment]
No problem @talyn, glad your issue is solved now!
