### ISSUE TITLE
save() and export_coreml() on a model do not interpret ~ at beginning of path

### ISSUE THREAD

**Issue by reallyjat** [apple/turicreate#945]
https://apple.github.io/turicreate/docs/userguide/object_detection/

# Create a model
model = tc.object_detector.create(train_data)

# Save the model for later use in Turi Create
model.save('~/models/mymodel.model')

# Export for use in Core ML
model.export_coreml(~/models/'MyCustomObjectDetector.mlmodel')

When run from jupyter in a virtualenv, it creates a folder named "~" at the top level folder of the jupyter instance, rather than saving things relative to the home directory as expected.

**Comment by TobyRoseman** [comment]
Thanks @reallyjat for the bug report. We're already tracking this issue here #684.

**Comment by nickjong** [comment]
Actually, this issue was fixed with #924. #684 tracks a different code path, and a fix there would not affect the object detection toolkit
