### ISSUE TITLE
DeprecationWarning: invalid escape sequence \c when using nearest_neighbors.create

### ISSUE THREAD

**Issue by Digital-Rabbit** [apple/turicreate#948]
When using turicreate.nearest_neighbors.create a warning appears.
<img width="1018" alt="screen shot 2018-08-08 at 9 50 05 am" src="https://user-images.githubusercontent.com/7233812/43851759-73e032c2-9af0-11e8-8971-5922a208583c.png">

**Comment by TobyRoseman** [comment]
I've seen this warning before and I don't believe it's anything to worry about. However we should investigate and hopefully stop what is causing the warning. 

I believe this is a Python 3 only issue. @Digital-Rabbit - what version of Python you are using?

**Comment by Digital-Rabbit** [comment]
3.6

**Comment by znation** [comment]
Looks like this is due to https://bugs.python.org/issue27364. I'm guessing we need to update our code to either explicitly double-escape with `\\`, or use `r''` for "raw" strings.
