### ISSUE TITLE
SFrame.save() takes a really long time

### ISSUE THREAD

**Issue by Benjamin-Lee** [apple/turicreate#955]
For context, I am trying to save a 395071 row x 1094 column SFrame. This process is taking *hours* on my 2015 MacBook Pro. Is there anything I can do to speed up saving?

**Comment by Benjamin-Lee** [comment]
For comparison, converting the SFrame to a DataFrame and then using `to_hdf()` takes a matter of seconds.

**Comment by srikris** [comment]
That's very unusual. By any chance was this SFrame created by doing a lot of appends. Have you tried saving to a csv? to see if its faster?

**Comment by Benjamin-Lee** [comment]
I will definitely try that out. In the mean time, here is the code I used to generate and save the SFrame:

```
import turicreate as tc
import freqgen
from itertools import product
import pandas as pd

sf = tc.SFrame.read_csv(f"../data/condo-0.1.3.csv", column_type_hints=[str, bool, str, int, str, str])
k = 5
print("applying kmer counter")
sf[f"{k}mers"] = sf["sequence"].apply(lambda x: freqgen.k_mer_frequencies(x, k))
sf = sf.unpack(f"{k}mers", column_name_prefix="")

print("applying codon counter")
sf["cub"] = sf["sequence"].apply(lambda x: freqgen.codon_frequencies(x))
sf = sf.unpack("cub", column_name_prefix="")

print("saving")
sf.save(f"./cub-{k}mer-0.1.3.sframe")
```

**Comment by srikris** [comment]
Where can I get `../data/condo-0.1.3.csv` to repro this?

**Comment by igiloh** [comment]
@Benjamin-Lee can you please try replacing the `save()` line with `sf.materialize()` and see if also takes long time? Does it create some significant CPU load?

SFrame operations are lazily evaluated - and there's a good chance that the `save()` clause is the first time that all of the calculations above are actually being calculated.

**Comment by znation** [comment]
Did not get a repro for this and it's unclear whether there is a bug here. Closing. @Benjamin-Lee, if you can repro this consistently, please provide the data and repro steps and reopen, thanks!
