### ISSUE TITLE
Auto tagging : feature request

### ISSUE THREAD

**Issue by johnyquest7** [apple/turicreate#962]
Feature request
If we give images and tags for training (without bounding boxes) to TuriCreate, it should be able to generate tags for unseen but similar images.

**Comment by TobyRoseman** [comment]
@johnyquest7 - I'm not sure I understand your feature request. Could you explain more or give an example? Also is this for the image classification toolkit?

**Comment by johnyquest7** [comment]
@TobyRoseman 
This is for image classification toolkit. 
Lets say I have lots of satellite images and each image is tagged with land features and weather features like - farm land, forest, urban area, river, cloudy day, sunny day etc. Once we train a model using these images and tags, the model should be able to auto generate these tags for an unseen image.

**Comment by TobyRoseman** [comment]
@johnyquest7 - thanks for the description. This sounds like multilabel classification, which we are already tracking in #147.
