### ISSUE TITLE
Improve Data Preparation Section of Object Detection

### ISSUE THREAD

**Issue by Kurry** [apple/turicreate#965]
https://github.com/apple/turicreate/blob/master/userguide/object_detection/data-preparation.md

In my opinion, I think the bitmask reference image example is bad to have in the documentation because its not realistic to how developers are going to create their datasets. I think most people will not have bitmask reference images, but will use something like https://github.com/sgp715/simple_image_annotator to annotate their images and output the image annotations to a csv file.

<img width="1395" alt="screen shot 2018-08-13 at 12 19 45 pm" src="https://user-images.githubusercontent.com/857247/44052383-7716c58c-9f0a-11e8-94e0-d9391ec51172.png">

Annotations

image | id | label | xMin | xMax | yMin | yMax
acne-excoriated-20.jpg | 1 | excorciated | 58 | 112 | 119 | 161
acne-excoriated-20.jpg | 2 | excorciated | 34 | 94 | 215 | 293
acne-excoriated-20.jpg | 3 | excorciated | 117 | 176 | 313 | 384
acne-excoriated-20.jpg | 4 | excorciated | 560 | 623 | 142 | 187
acne-excoriated-20.jpg | 5 | excorciated | 533 | 581 | 282 | 327
acne-excoriated-20.jpg | 6 | excorciated | 565 | 603 | 343 | 362
acne-excoriated-20.jpg | 7 | excorciated | 415 | 464 | 313 | 361
acne-excoriated-20.jpg | 8 | excorciated | 302 | 341 | 262 | 301
acne-excoriated-20.jpg | 9 | excorciated | 345 | 425 | 262 | 311
acne-excoriated-20.jpg | 10 | excorciated | 243 | 293 | 342 | 396
acne-excoriated-20.jpg | 11 | excorciated | 260 | 304 | 211 | 241

**Comment by srikris** [comment]
@Kurry Are you looking for code samples to convert this format to the annotations format that we have. It should be just a few lines of code. 

And you are right, we can also provide this sample in the user guide.

**Comment by Kurry** [comment]
@srikris Thanks for the quick response! I wrote a couple lines of code to do it, and I think I have it working now. I just wanted to make the issue when I was at peak misery, so save someone else the trouble in the future haha.

**Comment by srikris** [comment]
Can you share the code you have here. We'll incorporate it in our user guide.

**Comment by Kurry** [comment]
@srikris Sure! The code I have is not up to Apple standard, and I would be so embarrassed to post it in its current state. But I'll make it pretty and post it in a couple minutes.

**Comment by Kurry** [comment]
@srikris Thanks for asking me too! I'm surprisingly very excited for the task haha.

**Comment by shantanuchhabra** [comment]
@Kurry Thanks for bringing this up! And no worries -- feel free to share your code. We'll clean it up and update the documentation

**Comment by Kurry** [comment]
@srikris @shantanuchhabra 

I got it working! My boxes are not drawn in the right place, so I have to investigate it, but the code works mostly as intended.

<img width="1023" alt="screen shot 2018-08-13 at 5 11 03 pm" src="https://user-images.githubusercontent.com/857247/44058537-5e0f6fa0-9f1c-11e8-99c2-5fbf5b81e2c4.png">

Here is the code that I have written so far. What I wanted to do is, take what I had in the csv file, and combine it with the data that I get when I open the images directory. 

```python
import turicreate as tc
import os

csv_path = 'out.csv'
csv_sf = tc.SFrame.read_csv(csv_path)

def row_to_bbox_coordinates(row):
    """
    Takes a row and returns a dictionary representing bounding
    box coordinates: e.g. {'x': 100, 'y': 120, 'width': 80, 'height': 120}
    """
    return {'x': row['xMin'], 'width': (row['xMax'] - row['xMin']),
            'y': row['yMin'], 'height': (row['yMax'] - row['yMin'])}

csv_sf['coordinates'] = csv_sf.apply(row_to_bbox_coordinates)
# delete no longer needed columns
del csv_sf['id'], csv_sf['xMin'], csv_sf['xMax'], csv_sf['yMin'], csv_sf['yMax']
# rename columns
csv_sf = csv_sf.rename({'name': 'label'})
csv_sf = csv_sf.rename({'image': 'name'})

# Change if applicable
images_directory = 'Acne-and-Rosacea-Photos'

# Load all images in random order
sf_images = tc.image_analysis.load_images(images_directory, recursive=True,
                                       random_order=True)
# Split path to get filename
info = sf_images['path'].apply(lambda path: os.path.basename(path).split('/')[:1])

# Rename columns to 'name'
info = info.unpack().rename({'X.0': 'name'})

# Add to our main SFrame
sf_images = sf_images.add_columns(info)

# Original path no longer needed
del sf_images['path']

# Combine label and coordinates into a bounding box dictionary
labels = csv_sf['label']
csv_sf = csv_sf.pack_columns(['label', 'coordinates'], new_column_name='bbox', dtype=dict)
csv_sf['label'] = labels

# Combine bounding boxes of the same 'name' into lists
sf_annotations = csv_sf.groupby('name',
                                 {'annotations': tc.aggregate.CONCAT('bbox')})

# Join annotations with the images. Note, some images do not have annotations,
# but we still want to keep them in the dataset. This is why it is important to
# a LEFT join.
sf = sf_images.join(sf_annotations, on='name', how='left')

# The LEFT join fills missing matches with None, so we replace these with empty
# lists instead using fillna.
sf['annotations'] = sf['annotations'].fillna([])

# Save SFrame
sf.save('images.sframe')

# Load the data and preview the data
data =  tc.SFrame('images.sframe')
data['image_with_ground_truth'] = \
    tc.object_detector.util.draw_bounding_boxes(data['image'], data['annotations'])
data.explore()
```

```csv
image,id,name,xMin,xMax,yMin,yMax
acne-excoriated-8.jpg,1,excorciated,194,271,80,144
acne-excoriated-8.jpg,2,excorciated,337,406,320,384
acne-excoriated-8.jpg,3,excorciated,545,626,295,377
acne-pustular-20.jpg,1,pustular,100,147,235,280
acne-pustular-20.jpg,2,pustular,225,260,120,146
acne-pustular-20.jpg,3,pustular,243,282,169,199
acne-pustular-20.jpg,4,pustular,344,368,262,288
acne-pustular-20.jpg,5,pustular,345,369,294,316
acne-pustular-20.jpg,6,pustular,261,289,304,342
acne-pustular-20.jpg,7,pustular,214,246,305,334
acne-pustular-20.jpg,8,pustular,164,203,271,306
acne-pustular-20.jpg,9,pustular,160,177,229,247
acne-pustular-20.jpg,10,pustular,190,276,237,269
acne-pustular-18.jpg,1,pustular,364,379,123,137
acne-pustular-18.jpg,2,pustular,108,124,22,38
acne-pustular-18.jpg,3,pustular,89,100,168,192
acne-pustular-18.jpg,4,pustular,153,180,215,233
acne-pustular-18.jpg,5,pustular,316,338,345,363
acne-pustular-18.jpg,6,pustular,542,582,279,312
acne-pustular-18.jpg,7,pustular,477,506,261,284
acne-pustular-18.jpg,8,pustular,579,596,322,346
acne-pustular-18.jpg,9,pustular,545,569,145,161
acne-pustular-18.jpg,10,pustular,76,97,48,66
acne-pustular-18.jpg,11,pustular,367,389,272,289
acne-pustular-18.jpg,12,pustular,219,233,262,276
...
```

**Comment by Xutzgard** [comment]
use your snippets i got error of File "classifier.py", line 32, in <module>
    info = info.unpack().rename({'X.0': 'name'})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/turicreate/data_structures/sarray.py", line 3422, in unpack
    raise TypeError("Only SArray of dict/list/array type supports unpack")
