### ISSUE TITLE
Activity classifier data prep computes majority, not mode

### ISSUE THREAD

**Issue by nickjong** [apple/turicreate#986]
The activity classifier downsamples the raw data, so that *k* consecutive rows are assigned the same target classification. To compute the chunk's label from the *k* raw labels, it performs the [Boyer-Moore majority vote algorithm](https://en.wikipedia.org/wiki/Boyer–Moore_majority_vote_algorithm). However, this algorithm only guarantees that if the data has a majority value (occurs at least *k/2* times), then it outputs that value. Otherwise, it outputs an arbitrary element.

In particular, suppose *k* = 9 and the raw labels are `ABABABABC`. Then the Boyer-Moore algorithm outputs `C`, instead of one of the two modes.

Since we convert the labels into integers in 0..(num classes - 1), we should just generate a histogram. Computing the mode in this fashion is *O(n+k)* time and *O(k)* space, which for small *k* is just as good as Boyer-Moore's *O(n)* time and *O(1)* space.

**Comment by znation** [comment]
@nickjong This sounds like it would affect the accuracy of the resulting model - do you have a sense for how much effect it would have?

**Comment by nickjong** [comment]
It depends on the data. Honestly, I suspect that this is fine for most datasets most of the time. If the window only has two unique labels, then the algorithm is correct. So it's only wrong if the window has three or more labels, and none are in the majority.

For example, the HAPT dataset in the user's guide has a prediction window of one second's worth of samples. Then the algorithm _could_ do the wrong thing if the window contains an interval of less than half a second labeled with A, preceded and followed by two distinct labels B and C. You would think that for most domains, you would choose a prediction window whose granularity matches the data labeling granularity to some degree.

But while I think this may not be a critical bug to fix (AFAICT, we've had it for a while), it should not be hard to implement a fix. The histogram may even be faster than Boyer-Moore, since it involves fewer branch instructions.

**Comment by igiloh** [comment]
@nickjong nice catch! I wasn't aware of this disadvantage of Boyre-Moore algorithm.

@znation - As Nick has mentioned, this shouldn't really affect the correctness too much (if at all). Most prediction windows are expected to contain a single label, besides transition windows that may have two.  
In the HATP example Nick mentioned - it's not likely that a user has done 3 completely different activities (e.g. walking, running and swimming) within a single second. This is probably indicates either wrong data labeling or selecting an inappropriate window size - both of which are errors of a much larger magnitude.

I would even say that if the histogram solution (which I've noticed @abhishekpratapa has already [implemented](https://github.com/apple/turicreate/pull/1005/)) is a bit slower - it might even not be worth it.
